orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt
Presently any exceptions that occur during stage planning are not captured
and therefore will not show up in the execution JSON/UI for end-user to
see. This can be very confusing as there is no explanation for why a pipeline
stage fails.
=> fix(execution): Ensure exceptions in stage planning are captured

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/exceptions/OperationFailedException.java
If a user tries to start a pipeline manually from a jenkins trigger and the build is not found we fail super silently. Let's at least throw a new exception with the cause. 
This message will show up in a tiny tool tip in the UI. Not a great experience, but better than not showing the error at all.
=> fix(triggers): surface error if build not found

orca-web/orca-web.gradle, orca-web/src/test/groovy/com/netflix/spinnaker/orca/MainSpec.java, orca-web/src/test/groovy/com/netflix/spinnaker/orca/StartupTestConfiguration.java, orca-web/src/test/resources/orca-test.yml
Test that orca starts up with a very basic config, with just the baseUrl for each dependent service defined, and an in-memory execution queue.
=> test(core): Basic startup test

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandler.kt
This change should handle the case where notifications should not be null, but was in an existing template.
=> fix(templated-pipelines): handle a missing notifications field

orca-core/orca-core.gradle, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupport.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupportSpec.groovy
@duftler proof of concept for using a helper function to resolve label values to enable blue/green deployments in which labels are dynamically patched into Services:
Used in patch manifest stage...
...and resolved in pipeline execution:
Would you recommend creating some sort of helper class for a ReplicaSet/Deployment manifest spec rather than checking each step of spec --> template --> metadata -->labels? This seems pretty verbose.
=> feat(spel): add manifestLabelValue helper function

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTaskSpec.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy
The new method is used to fully resolve a bound artifact on a stage that can either select an expected artifact ID for an expected artifact defined in a prior stage or as a trigger constraint OR define an inline expression-evaluable default artifact.
=> feat(artifacts): Add stage artifact resolver

orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionFunctionProvider.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupport.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/DeployedServerGroupsExpressionFunctionProvider.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/ManifestLabelValueExpressionFunctionProvider.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextFunctionConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupportSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/DeployedServerGroupsExpressionFunctionProviderSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/ManifestLabelValueExpressionFunctionProviderSpec.groovy
Provides a strategy for extending Orca's SpEL expression language with new helper functions.
Additionally offers a more strongly typed and documented method of building these helpers, as
well as namespacing capabilities in case an organization wants to provide a canned group of
helper functions.
Moved `deployedServerGroups` and `manifestLabelValue` to use this new format.
Largely stolen from @ajordens prior art that was never merged.
=> refactor(core): Allow registering custom SpEL expression functions

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
the bound artifact should use the matched artifact account if it doesn’t have one
=> fix(artifacts): handle bound artifact account missing

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/ImageTagger.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/gce/GoogleImageTaggerSpec.groovy
`ImageTagger` already retries fetching images by id, but not when subsequently fetching by image name. This poses a race condition for `UpsertImageTagsStage` due to the fact that clouddriver's `ImageCachingAgent` stores image metadata and image -> name mappings as distinct objects which are not updated atomically, at least in the case of the AWS provider.
If `UpsertImageTagsStage` executes in the narrow window where a newly baked image's `image` object has been stored but `imageName` has not, it will go terminal without retries. This PR enables retries for the lookup by name when that name was derived from a successful lookup by id. When `ImageTagger.findImages()` is called with image names, the existing behavior is preserved and the first lookup failure remains terminal.
=> fix(imagetagging): retry for missing namedImages

orca-pipelinetemplate/orca-pipelinetemplate.gradle, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTag.java, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTagSpec.groovy
The ModuleTag class breaks with jinjava >= 2.2.8 because of a fix in failsOnUnknownTokens.  We need to catch this error in cases where we expect that a token may be unknown. The test also uses True as a literal which should be true (ie, lowercase) which worked before but breaks with the upgrade.
=> chore(jinja): Upgrade jinjava

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/ArtifactoryTrigger.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/TriggerSpec.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy
=> feat(core): Add support for an Artifactory Trigger

orca-pipelinetemplate/orca-pipelinetemplate.gradle
jinjava >= 2.2.9 breaks some v1 pipeline evaluation due to a change in
unknown token behavior that needs to be handled.
=> fix(mpt): temporarily pin back jinjava

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeployCloudFormationTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeployCloudFormationTaskSpec.groovy
adds support for YAML templates by attempting to deserialize using
snakeyaml instead of object mapper. since YAML is a superset of JSON
snakeyaml can process either format properly.
=> feat(cloudformation): support YAML templates

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DeleteSecurityGroupStage.groovy
Background:
Currently it failed to delete firewall and throw timeout exception at force cache stage while deleting firewall. After investigated, delete firewall task and force cache refresh task would be processed concurrently. If delete firewall task doesn't get the response from azure within 20 seconds, then force cache refresh task would throw timeout exception.
Fix:
So update the execution order for deleting firewall. After updated, force cache refresh task will be processed when monitor delete task is completed. After tested, now it can delete firewall successfully.
=> fix(provider/azure): Failed to delete firewall

orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/DryRunStageDefinitionBuilderFactory.kt
Variables are hard to get right, hence the EvaluateVariables stage, but
if it doesn't run in `dryRun` it makes quickly iterating on it harder.
=> fix(evaluateVariables): enable EvaluateVariables stage to run in dryRun

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTaskSpec.groovy
This handles a situation where we appear to be getting an occasional
stale min/max/desired when an asg id is re-used across deployments.
ie. app-v000 was deleted and re-created
Also reaching out to AWS for clarification as to whether this is
expected or not.
=> feat(clouddriver): Favor target capacity when current desired == 0

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
Now that echo handles augmenting triggers with build info, and that manual triggers default to go through echo, all triggers should be arriving in Orca with their build information already populated. We
should gate the logic in Orca to only run if it's not there.
We can't completely remove this logic yet because while manual triggering via echo defaults to enabled, there's still a flag to turn it off. Once that flag is deprecated, and we're confident that all manual triggers (including any via the API) go through echo, we can completely remove this block of code.
This commit also completely removes the populating of taggedImages, which has not been used since spinnaker/orca#837.
=> refactor(triggers): Gate calls to igor from orca

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/pipeline/GetPipelinesFromArtifactTask.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java
Orca no longer starts up without front50 because a dependency on front50 was added to a task bean. Halyard needs an orca without front50 to bootstrap deploy to kubernetes.
=> fix(core): Fix startup

orca-web/src/test/groovy/com/netflix/spinnaker/orca/MainSpec.java, orca-web/src/test/resources/orca-test.yml
When deploying to Kubernetes, halyard uses a bootstrap orca that doesn't have front50 enabled. This means that we need to keep orca starting without front50 around; set it to false in the test and remove the mock bean.
=> test(core): Remove front50 bean from startup test

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTask.java, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTaskSpec.groovy
Copying pipelines currently fails when managed service accounts are enabled. This commit fixes that by generating a pipeline id (UUID) in Orca before generating the managed service account.
=> fix(authz): Fix copying pipelines with managed service accounts

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/pipeline/SavePipelinesCompleteTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/pipeline/SavePipelinesData.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTaskSpec.groovy
This is a minor change to SavePipelineTask. By default it will still fail with a TERMINAL status exactly as before. I’ve added a unit test for this original behavior. But if it detects that multiple pipelines are being saved, then the failure status will be FAILED_CONTINUE instead. This allows the SavePipelinesFromArtifactStage to attempt to save all the pipelines from the artifact and then give a summary of the results.
=> feat(pipelines): if saving multiple pipelines, continue on failure

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineExpressionFunctionProvider.java
Added #pipeline function for usage in SpEL expressions.
It returns the ID of the pipeline given the name of the pipeline
(within the same app only)
=> feat(expressions): adding #pipeline function

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AppEngineBranchFinderSpec.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/ReturnTypeRestrictor.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/BuildInfo.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/ConcourseTrigger.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/SourceControl.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/BuildDetailExtractor.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy
Reopening this after having messed up the source branch on this prior PR: https://github.com/spinnaker/orca/pull/2758.
This should have been merged last week and is needed for 1.13 as it collaborates with Concourse features in other Spinnaker services.
=> feat(core): Add support for Concourse triggers

orca-clouddriver/orca-clouddriver.gradle, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/PollerSupport.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPoller.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/SpinnakerMetadataServerGroupTagGenerator.java
It's not clear to me why Spock's selection of JDK dynamic proxies for tests like `SpinnakerMetadataServerGroupTagGeneratorSpec` and `RestorePinnedServerGroupsPollerSpec` used to work without the correct visibility modifiers, but they seem to be necessary now?
=> fix(tests): Use JUnit vintage engine so Spock tests still run

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/CIStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/CIStage.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildArtifactsTask.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildPropertiesTask.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/RetryableIgorTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/pipeline/JenkinsStageSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/pipeline/ScriptStageSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/RetryableIgorTaskSpec.groovy
Improve some things around the Jenkins code that broke last week.
* test(ci): Add tests to JenkinsStage and ScriptStage 
There are no tests that waitForCompletion is properly read when starting a Jenkins stage; this functionality recently broke, so add some tests to it.  Also add some tests to verify that binding of artifacts works correctly.
The ScriptStage has no tests at all; add a simple test that it fetches the properties after the script finishes.
* refactor(ci): Move CIJobRequest and rename it CIStageDefinition 
This definition was originally only used one specific task, but it really represents the full stage definition of a CIStage, so rename it and move it to a more appropriate location.
* refactor(ci): Remove explicit casting from CIStage 
In order to quickly fix a bug, I …
=>  test(ci): Add tests to JenkinsStage and ScriptStage

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AppEngineBranchFinderSpec.groovy, orca-core/orca-core.gradle, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/ReturnTypeRestrictor.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/BuildInfo.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/JenkinsTrigger.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/BuildDetailExtractor.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/BuildDetailExtractorSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/model/JenkinsTriggerTest.java
* `BuildInfo<A>` needs to be reified to `JenkinsBuildInfo extends BuildInfo<JenkinsArtifact>` for deserialization to correctly deserialize into `JenkinsArtifact`. Otherwise, Jackson leaves the artifact as a `Map` and fails type checking that map against the `JenkinsArtifact` type on serialization.
* Made `JenkinsBuildInfo#name` optional, which I'm not sure if it really is, but was causing `BuildDetailExtractor` to silently swallow exceptions in tests.
* Made it clear that the deprecated method in `BuildDetailExtractor` was only intended for Jenkins build details.
=> fix(jenkins): Fix Jenkins trigger serialization

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/artifacts/FindArtifactFromExecutionTask.java
When filtering to only include successful executions, the front-end sets the flag 'successful' in the stage config. Orca is incorrectly looking for a value 'succeeded', and thus ignores the value that was set on the front-end.
While 'succeeded' is slightly better named as it matches the execution status, changing this on the backend means that existing pipelines will work automatically.  (Whereas changing it on the front-end would require either a pipeline migrator or for anyone affected to re-configure the stage.)
=> fix(artifacts): Fix successful filter for find artifacts

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/JarDiffsTask.groovy
This handles situations where a security group may prevent ingress
and otherwise timeout after the default (10s).
We automatically retry 5 times so our deployments are taking _at least_
50s longer than they need to.
This isn't perfect but that 50s will be lowered to 10s.
=> fix(clouddriver): Reduce jardiff connect/read timeouts

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt
This addresses a situation where the `DeployCanaryStage` failed to
plan after stages that involved a lookup against a restricted account.
=> fix(queue): Ensure that after stages run with an authenticated context

orca-igor/orca-igor.gradle, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/GoogleCloudBuildStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/GoogleCloudBuildStage.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/pipeline/GoogleCloudBuildStageSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTaskSpec.groovy
Add a stage that triggers a build using Google Cloud Build. At this point, the stage only accepts a build definition directly in the stage, and does not wait for the build to complete.
=> feat(gcb): Add Google Cloud Build stage

halconfig/orca.yml
Set `integrations.gremlin.enabled` from the Halyard feature named `--gremlin`.
This will work once spinnaker/halyard#1261 is merged.
=> feat(gremlin): Add Halyard config for Gremlin

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/StageData.groovy
There is the logic of “allowDeleteActive” in orca but seems it’s hardcoded to false. Azure has this specific scenario of deleting active instances in the ShrinkClusterTask in the Red/Black strategy, so enable this parameter. Assume other cloud providers that have been worked without interacting with this parameter won’t be impacted since this change makes its value as “false” as what it is used to be if this parameter is not set explicitly anywhere else.
=> fix(clouddriver): Enable the parameter of allowDeleteActive

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CloneServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/Manifest.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/clone/BakeryImageAccessDescriptionDecorator.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/clone/CloneDescriptionDecorator.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/clone/CloneServerGroupTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/clone/CloudFoundryManifestArtifactDecorator.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CloneServerGroupTaskSpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreatorTest.java
There was some AWS-specific logic in `CloneServerGroupTask` that adds launch descriptions to the task list for a clone. Separately, there was a need for us to bind an expected artifact for a manifest that is an input to the CF clone operation. I took this opportunity to extract the cloud provider specific modifications to this task to a `CloneDescriptionDecorator`.
=> fix(provider/cf): Bind clone manifest artifacts

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesTask.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesTaskSpec.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Some places uses `ContextParameterProcessor.buildExecutionContext` which (correctly) converts the
`trigger` in the pipeline to an object (instead of keeping it as `Trigger` class).
However, when tasks run, they use `.withMergedContext` which opts to build it's own SpEL
executionContext (in `.augmentContext`). This is needed so that fancy look up in ancestor stages works.
Fix `.augmentContext` to convert the trigger to an object/map.
This addresses issues evaluating expressions like
`${trigger.buildNumber ?: #stage('s1').context.buildNumber}`` when no `buildNumber` is present on the `trigger`
=> fix(expressions): make sure trigger is a map

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy
Many templatedPipelines don't have a `.schema` set and the code treats them as `v2` but they should
stay as `v1` and not be processed.
We saw a bunch of pipelines going through to `V2Util.planPipeline` increasing traffic to `front50`
about 200x and many calls would fail (presumably due to `v1` being treated as `v2`?)
=> fix(MPTv2): Fix for #2803

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CloneServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CloneServerGroupTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CloneServerGroupTaskSpec.groovy
This change undoes the move of CloneServerGroupTask to a different package
(this was introduced in #2815).
Today, tasks can not be moved once they have been created because Orca will
be unable to deserialize the tasks already in the queue created under a
different package.
=> fix(cloneservergrouptask): undo the move of CloneServerGroupTask

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/DeployedServerGroupsExpressionFunctionProvider.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/DeployedServerGroupsExpressionFunctionProviderSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
The deployment result is the place that cloud providers can put info about their deployments, but it is deeply nested on the context and hard to find. That can be eased by appending it to the info returned from the existing deployedServerGroups property/function.
=> feat(exp): deployedServerGroups now grabs deployments from deploy result

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestContext.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTaskSpec.groovy
* refactor(provider/kubernetes): Use constructor injection 
Refactor DeployManifestTask to use constructor injection, and change impelentation-specific fields to be private and final.
* feat(provider/kubernetes): Add traffic options to deploy manifest 
Add functionality to the deploy manifest task to handle the fields in the new trafficManagement section. In particular, pass along any specified service as well as whether to send traffic to new workloads.
=>  feat(provider/kubernetes): Add traffic options to deploy manifest

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestContext.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java
In 1.13, the K8S deploy manifest stage displays the new artifacts UI when the feature flag is enabled. The JSON structure it produces for the stage is not digestable by Orca. As a refresher on the structural changes done such that this is backwards compatible:
1. `manifestArtifact` can (optionally) have an `artifactAccount` now. With the new artifacts UI, you _must_ specify an artifact account up front in the expected artifact definition, so any artifacts created with the new UI will have it. `manifestArtifactAccount` is now a backwards compatible fallback for existing pipelines.
2. `requiredArtifacts` contains a list of bind artifacts that contain either an `expectedArtifactId` or a fully-defined `artifact`. The UI presents any artifacts defined in the old model (still present in …
=> fix(k8s): Deploy manifest now accepts stage-inlined artifacts

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/KubernetesPreconfiguredJobProperties.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/PreconfiguredJobStageProperties.java, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
allow preconfigured jobs to produce artifact. kubernetes jobs default to
true. can be overridden.
=> feat(preconfiguredJobs): produces artifacts

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepositorySpec.groovy, orca-sql/src/test/java/com/netflix/spinnaker/orca/sql/SqlTestUtil.java
When performing a search with a pipeline name that doesn't exist
sqlrepository will generate a query with an empty IN clause:
```
SELECT * FROM ... WHERE IN ()
```
this change short circuits this evaluation.
Additionally, set H2 into `MODE=MYSQL` so that we can actually catch
this invalid SQL in unit tests
=> fix(repository): don't generate invalid grammar

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy
When calling `pipelines/{id}/evaluateExpression`
we don't populate the eval context in the same way as we do for regular pipeline execution.
This means expressions that work during regular execution don't work when using this EP.
Most notably, nothing in `triggers` (or, more importantly, `trigger.parameters`) is accessible via
`${parameters["myParam"]}` instead one must modify the expression to be
`${execution.trigger.parameters["myParam"]}`
=> fix(expressions): populate context for evaluateExpression endpoint

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/SpringLiquibaseProxy.kt
Currently, any non-standard migrations are defined in the orca.yml as a list.
Sometimes, it's nice to be able to run without those migrations
(e.g. when developing both in OSS and private land). However, due to an issue in
spring (which, I believe, should be fixed in boot2.0.3) it's impossible to
override a list with an empty list, but you can override a list with a new list.
Hence this change to not run empty entries
=> chore(migrations): ignore empty migrations

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestContext.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestHighlanderStrategy.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestNoneStrategy.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestRedBlackStrategy.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestStrategy.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestStrategyHandler.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestStrategyStagesAdder.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestStrategyType.java
Adds support for red/black and highlander rollout strategies to the Kubernetes V2 provider:
- Adds synthetic stages to Deploy Manifest `afterStages` by delegating to strategy-specific `composeFlow` methods, which append a series of Disable and Delete stages for each previous version of the ReplicaSet.
- Adds a Kubernetes-specific `ManifestStrategy` interface (existing VM interface is coupled to deprecated `aroundStages` method, with `composeFlow` returning a list of stages rather than directly mutating to the stage graph).
=> feat(kubernetes): support redblack and highlander strategies

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/ResizeServerGroupStage.groovy
Reverts spinnaker/orca#2848
The description provided in the PR doesn't indicate that this is the appropriate fix.
=> Revert "fix(provider/azure): Failed to disable azure server group when rollback"

orca-igor/orca-igor.gradle, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/GoogleCloudBuildStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/pipeline/GoogleCloudBuildStageSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTaskSpec.groovy
Orca currently deserializes the build configuration in the stage to a Build object only to send it immediately over to igor (which re-serializes it). As orca doesn't actually need to know any of the details about the Build object it's sending over, just use a generic Map.
This addresses an issue where some fields are not correctly deserializing using the default objectMapper; I'll need to work around this in igor, but this reduces the scope of where that workaround needs to live.  (This also allows us to better encapsulate which microservices actually need to know about GCB objects.)
=> refactor(gcb): Use generic maps for GCB objects

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java
- feat(kubernetes): pass DeployManifestTask strategy to Clouddriver to enable downstream validation
- fix(kubernetes): remove unused imports from DeployManifestStage
=> feat(kubernetes): pass DeployManifestTask strategy to Clouddriver to enable downstream validation

orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionStatus.java
This will enable cleanup of old `CANCELED` tasks
=> fix(orca-core): Add CANCELED to list of COMPLETED statuses

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/CIStage.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/GetPropertiesStage.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildPropertiesTask.java
This fixes a "regression" that was introduced with the ci stage refactor. Previously we would try and get the properties file if the jenkins job failed. This pr adds a failure stage so that if a property file is defined, and the ci stage fails, we will try and get the property file. This failure stage may fail, but that seems fine because the stage itself already failed.
A user of ours is asking for this behavior.
=> fix(orca): if build stage fails and prop file exists, try and fetch

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/ConditionAwareDeployStagePreprocessor.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/conditions/Condition.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/conditions/ConditionConfigurationProperties.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/conditions/ConditionSupplier.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/conditions/ConfigurationBackedConditionSupplier.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/conditions/WaitForConditionStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/conditions/EvaluateConditionTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/conditions/ConfigurationBackedConditionSupplierSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/conditions/EvaluateConditionTaskSpec.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
- Updated interface to specify cluster, region and account
- Make injecting the stage optional on if there are active conditions
=> refactor(conditions): Do not inject waitForCondition on no conditions

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTaskSpec.groovy
* test(provider/kubernetes): Add tests to ManifestForceCacheRefresh 
Most of the functionality in ManifestForceCacheRefreshTask is not tested. Add significant test coverage to this class to prepare for a bug fix/refactor.
* refactor(provider/kubernetes): Replace nested maps with an object 
The ManifestForceCacheRefreshTask currently keeps track of its manifests as a Map<String, List<String>> which leads to a lot of complex iteration over this structure. Create a new class ScopedManifest and flatten this structure into a List<ScopedManifest> so that it's much easier to follow the processing that the class is doing.
* refactor(provider/kubernetes): Add account to ScopedManifest 
Rather than thread account through multiple calls in this class, add it to the ScopedManifest class and set the …
=>  refactor(provider/kubernetes): Add tests and simplify cache refresh

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTaskSpec.groovy
* test(provider/kubernetes): Re-order statements in tests 
This commit has no functional effect, it is just going to make the tests much easier to read in the next commit, where I change the order between checking on pending cache refresh requests and sending new ones.
* refactor(provider/kubernetes): Change control flow in refresh 
Instead of having refreshManifests and checkPendingRefreshes contain logic for determinig if the task is done, have them focus on mutating refreshedManifests and deployedManifests as they take actions.
Then add allManifestsProcessed to check whether we're done; which is just checking if all deployed manifests have been processed. This removes the need to track the state of all manifests in the mutating functions and allows us to consolidate the return value of …
=> fix(provider/kubernetes): Don't poll immediately after cache refresh

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
fixes this exception:
```
No such property: inferredRegions for class: com.netflix.spinnaker.orca.clouddriver.tasks.cluster.FindImageFromClusterTask
```
=> fix(clouddriver): Hoist inferredRegions var to parent scope so it is accessible to groovy code down below

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/GoogleCloudBuild.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/GoogleCloudBuildStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorGoogleCloudBuildTask.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorGoogleCloudBuildTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTaskSpec.groovy
* refactor(gcb): Use a GoogleCloudBuild type as return from igor 
To make the task logic simpler, create a class GoogleCloudBuild that has the build fields that Orca cares about and have retrofit deserialize the result from igor. Also, add the resulting field to the stage context so it can be used by downstream tasks.
* feat(gcb): Monitor GCB build status after starting a build 
Instead of immediatly returning success once the new GCB build is accepted, wait until the build completes and set the status of the stage based on the result of the build.
=>  feat(gcb): Monitor GCB build status after starting a build

orca-core/src/main/java/com/netflix/spinnaker/orca/StageResolver.java, orca-core/src/main/java/com/netflix/spinnaker/orca/Task.java, orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResolver.java, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/DefaultStageDefinitionBuilderFactory.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionRunner.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilderFactory.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/StageResolverSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/TaskResolverSpec.groovy, orca-dry-run/src/main/kotlin/com/netflix/spinnaker/config/DryRunConfiguration.kt, orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/DryRunStageDefinitionBuilderFactory.kt, orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisOrcaQueueConfiguration.kt, orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/migration/TaskTypeDeserializer.kt, orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/migration/TaskTypeDeserializerTest.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/admin/HydrateQueueCommand.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RescheduleExecutionHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeTaskHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/admin/HydrateQueueCommandTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RescheduleExecutionHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeTaskHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandlerTest.kt
The `*Resolver` implementations will be able to look at both raw
implementation classes _as well as_ any specified aliases.
This supports (currently unsupported!) use cases that would be made
easier if a `Task` or `StageDefinitionBuilder` could be renamed.
=> feat(core): Delegate task/stage lookup to `TaskResolver` and `StageResolver` respectively

orca-core/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/V2Util.java, orca-core/src/main/java/com/netflix/spinnaker/orca/preprocessors/DefaultApplicationExecutionPreprocessor.kt, orca-extensionpoint/src/main/java/com/netflix/spinnaker/orca/extensionpoint/pipeline/ExecutionPreprocessor.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePreprocessor.kt, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
This supports existing use cases around pipeline-centric preprocessors.
=> feat(core): Allow `ExecutionPreprocessor` to discriminate on type

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/CIStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/RetryableStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildArtifactsTask.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildPropertiesTask.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/RetryableIgorTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/RetryableIgorTaskSpec.groovy
* refactor(ci): Generify RetryableIgorTask 
I'd like to re-use the logic in RetryableIgorTask for some GCB tasks, but it requires that the stage map to a CIStageDefinition. Make the stage definition a parameter to the class so it can be re-used.
At some point it might make sense to make this even more general than just for igor tasks, but at least this makes it a bit more general than it is now.
=> refactor(ci): Generify RetryableIgorTask

halconfig/orca.yml
Related Halyard PR: https://github.com/spinnaker/halyard/pull/1293
I previously had the wrong idea about how Halyard was propagating config. This should put all of the burden onto Halyard to do it programatically.
=> fix(gremlin): Remove Gremlin config template and let Halyard do it from scratch

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/GoogleCloudBuildStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/GoogleCloudBuildStage.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetGoogleCloudBuildArtifactsTask.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorGoogleCloudBuildTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetGoogleCloudBuildArtifactsTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorGoogleCloudBuildTaskSpec.groovy
* refactor(gcb): Refactor monitor task to use generic retry logic
Now that RetryableIgorTask is generic, MonitorGoogleCloudBuildTask can extend it instead of having its own retry logic.                  
* feat(gcb): Fetch artifacts produced by a GCB build
* fix(gcb): Add longer timeout to GCB polling stage
We're currently using the default timeout of 1 minute, which will likely be too short.  As a starting point, use the timeout and backoff period we use for other CI jobs, though we can change these in the future if needed.
=> feat(gcb): Fetch artifacts produced by a GCB build

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorGoogleCloudBuildTask.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorGoogleCloudBuildTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTaskSpec.groovy
The refactor of TaskResult dropped setting the context in StartGoogleCloudBuildTask; restore it. We also should update the context each time we run MonitorGoogleCloudBuildTask so the context has an up-to-date status; add this.
=> fix(gcb): Properly set buildInfo in the context

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/conditions/ConditionConfigurationProperties.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/conditions/EvaluateConditionTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/conditions/EvaluateConditionTaskSpec.groovy
- added config property tasks.evaluateCondition.skipWait
- when skipWait=true, all paused deployments will proceed
=> chore(conditions): Adding a flag to skip wait

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractWaitForClusterWideClouddriverTask.groovy
This gets the proper class/logger name instead of using the parent `AbstractWaitForClusterWideClouddriverTask`
fixup for: https://github.com/spinnaker/orca/pull/2888
=> fix(logging): use logger.GetFactory over @slf4j

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/GoogleCloudBuildStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTaskSpec.groovy
* feat(gcb): Allow the build definition to come from an artifact 
As an alternative to having the build definition inline in the stage, allow it to come from an artifact.
* chore(gcb): nest gcb artifact properties under one key
=>  feat(gcb): Allow the build definition to come from an artifact 

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePreprocessor.kt
If a pipeline fails to start due to a validation error (thrown by the MPT parsers), add the error information to the reason message displayed in Deck. Depends on https://github.com/spinnaker/echo/pull/546 to work.
Examples:
=> feat(pipelines): Add validation errors to failure message

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.java
using an explicit artifact source makes it easier to define the stage
such that we don't have to guess what the source type is.
=> fix(runJob): use explicit artifact source

gradle/groovy.gradle, orca-web/orca-web.gradle, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/CorrelatedTasksController.java, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/CorrelatedTasksControllerTest.java
I want to avoid writing redundant resource history in Keel so rather than blindly submitting tasks and relying on Orca to de-dupe using the correlation id I'd like to first see if there are any in-flight tasks and if so do nothing in Keel.
=> New endpoint to list correlated executions

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/AccountCache.java
- polling to cache basic account dets
- disabled by default
=> feat(clouddriver): Adding a poller to cache basic account details

orca-pipelinetemplate/orca-pipelinetemplate.gradle, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
With kork-bom, we have picked up a new version of jinjava (despite the force=true
directive to gradle which doesn't work in bom scenarios where first one wins)
Anyway, old jinjava would handle missing variables by evaluating the expression to false;
new jinjava throws.
When a stage has a `{when}` condition that uses a variable that was part of the stage config
that variable doesn't get added to the context until we process the stage the second time!
Add those variables to the context on the first time round to make template expansion happy
=> fix(MPTv1): Fix template expansion

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/conditions/ConditionConfigurationProperties.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java, orca-core/src/main/java/com/netflix/spinnaker/orca/locks/LockingConfigurationProperties.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilderSpec.groovy, orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionBufferActuator.kt, orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/bufferpolicy/NaiveBufferPolicy.kt, orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/bufferstate/ActiveExecutionsBufferStateSupplier.kt, orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/bufferstate/KillSwitchBufferStateSupplier.kt, orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/promotionpolicy/NaivePromotionPolicy.kt, orca-qos/src/test/kotlin/com/netflix/spinnaker/orca/qos/ExecutionBufferActuatorTest.kt
Looks like boot2 is not happy with the dynamic spring properties being camel case. Switching to kebab.
=> fix(boot2): camel to kebab for fast properties

build.gradle, orca-core/orca-core.gradle, orca-pipelinetemplate/orca-pipelinetemplate.gradle, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/Front50SchemeLoader.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTag.java, orca-queue/orca-queue.gradle, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
Also, making some related calls anonymous to not be noisy
Also, had to pull specific version of guava since kork doesn't specify it
=> fix(mptv1): revert back Jinjava to 2.2.3 

orca-core/src/main/java/com/netflix/spinnaker/orca/preprocessors/DefaultApplicationExecutionPreprocessor.kt, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePreprocessor.kt, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
This allows an execution processor to specify order of invocation.
This is useful (/ needed) when an preprocessor needs to operate on a
fully instantiated pipeline. If the pipeline is templated it won't be
fully instantiated till the templatepreprocessor runs.
=> fix(executionprocessor): add @Order to execution processors

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForCapacityMatchTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForCapacityMatchTaskSpec.groovy
- We generally calculate targetDesired for resize operations by trusting
that clouddriver's cache accurately reflects the new desired size when
waiting for a capacity match. This is often provided via an onDemand
cache object (force cache refresh). When the new configured capacity
doesn't allow for autoscaling, we can derive targetDesired directly from
the stage context. This assists the TitusStreamingUpdateAgent which
doesn't currently implement onDemand caching.
=> feat(clouddriver): favor configured capacity for certain operations

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.java
This will be used to provide a link from the server group back to a pipeline that created it, and allow an alternate way to provide build info in some cases.
=> feature(cf): pass execution ID and trigger to server group creation

orca-web/config/orca.yml
rosco service listens port 8087, 8089 is listened by echo instead
=> fix(config): fix bakery port in orca-web/config

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
Same fix as #2524, but for the case where multiple artifacts matches. Without this, Echo will try to trigger the pipeline five times and it will appear five times in the execution list.
PTAL @ezimanyi
=> fix(artifacts): Use client error code for multiple matching artifacts

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/LambdaFunctionStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/lambda/LambdaFunctionTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/lambda/lambdaFunctionTask.java
The `updateLambdaFunction` stage that was added before only supported updating lambda function config. It didn't allow users to update the lambda function code, create or delete a lambda. This modification will allow users to forward arbitrary operations to Clouddriver.
The instructions [here](https://github.com/spinnaker/clouddriver/tree/master/clouddriver-lambda) describe how to enable lambda and available operations. Then you can hit Orca with something like:
```curl -X POST \
http://localhost:8083/orchestrate \
-H 'Content-Type: application/json' \
-d '
{
"application": "andrewtest",
"description": "lambda Test",
"stages": [
{
"type": "lambdaFunction",
"operation": "updateLambdaFunctionCode",
"region": "us-east-1",
"functionName": "andrew-lambda-handler",
"credentials": "aws-dev", …
```
=> feat(aws/lambda): Lambda stage can handle arbitrary ops

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.java
The V2 trigger pipeline endpoint is currently broken (it doesn't return a valid ref for people to lookup progress). This is one of 3 changes (other two in echo, gate), allowing clients to pass an execution ID (in addition to or in substitution of) a correlation ID. This will allow Gate to generate a pipeline execution ID and return it to the client without blocking on Orca to actually process the request.
echo: https://github.com/spinnaker/echo/pull/563
gate: https://github.com/spinnaker/gate/pull/811
=> feat(core): Support client-provided execution IDs

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DeploymentDetailsAware.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/jackson/OrcaObjectMapper.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/BuildDetailExtractor.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-integrations-cloudfoundry/src/main/java/com/netflix/spinnaker/orca/cf/pipeline/expressions/functions/ServiceKeyExpressionFunctionProvider.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplateService.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt, orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java, orca-web/src/main/groovy/com/netflix/spinnaker/orca/web/config/WebConfiguration.groovy
creating a new ObjectMapper instance for each Stage or other per-request
contexts can be wasteful; ObjectMapper is safe to reuse across threads
(after it is configured). See https://github.com/spinnaker/spinnaker/issues/4367 for more details.
=> perf(orca): reuse ObjectMapper instances

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-sql/src/main/resources/db/changelog-master.yml, orca-sql/src/main/resources/db/changelog/20190530-pipeline-config-index.yml
This PR fixes an issue where calls to `/applications/{application}/pipelines` can result in a full `pipelines` table scan per each of the applications pipeline configuration ids if they have more than N executions, where N is determined by the sql query optimizer at runtime.
=> fix(sql): optimize reading executions by pipeline id

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java
When save pipelines task is used multiple times in a stage, it now reuses the pipeline ID. This is problematic because if new pipelines are created they will reuse a previous pipeline ID and overwrite it rather than creating a new pipeline. I think the real problem here is the use of “pipeline.id” in the stage context for multiple purposes (both of which make sense independently).
1) SaveServiceAccountTask generates a new pipeline.id if one doesn’t exist for use with regenerateCronTriggerIds. It effectively changes the contract from a new pipeline not having an id, to it being generated beforehand.
2) Later in this class, after a pipeline is updated or created, its id is stored in “pipeline.id” to aid with refresh logic.
But the two of these together keeps the context “pipeline.id” from …
=> fix(pipelines): save pipelines task shouldn’t reuse pipeline id

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestAware.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PromoteManifestKatoOutputsTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTaskSpec.groovy
Addresses: https://github.com/spinnaker/spinnaker/issues/4422
Related PR: https://github.com/spinnaker/clouddriver/pull/3711
When using Kubernetes V2 Rollout Strategies with the `max-version-history` annotation, Clouddriver sometimes tries to disable a previously-deleted ReplicaSet because we are not refreshing the cache after the Deploy Manifest stage's `CleanupArtifactsTask`. Adds `MonitorKatoTask`, `PromoteManifestKatoOutputsTask`, and `ManifestForceCacheRefreshTask` in order to prevent this.
Previously, each stage had at most one `PromoteManifestKatoOutputsTask`, which composes the outputs of each kato task's outputs by taking the *first* non-null output value at each relevant key. In this case, our cleanup task's `outputs.manifestNamesByNamespace` was never being surfaced because …
=> fix(kubernetes): force cache refresh after deploy stage artifact cleanup

orca-core/orca-core.gradle, orca-core/src/test/groovy/com/netflix/spinnaker/orca/locks/LockContextSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/ExecutionSpec.groovy
Two problems were introduced by a1de32d0345446e240885b6a792a60b4ff13c2eb:
1. LockContextSpec throws a java.lang.VerifyError when the class is loaded by junit-vintage's TestEngine, which leads it to incorrectly think that there are no tests to run (of the type that it supports)
2. ExecutionSpec was broken in the change from using `org.apache.log4j.MDC` to `org.slf4j.MDC` because orca-core has `slf4j-simple` at `testRuntime` scope, which loads a no-op version of the MDC class which silently discards all values passed to `MDC.put(key, value)`.
Closes https://github.com/spinnaker/spinnaker/issues/4469
The fix for 1 above comes from something @ezimanyi mentioned on Slack - that the use of `type` seems to be confusing the Groovy compiler.
=> fix issue 4469: orca-core skipping most tests in build

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy
This is a smaller-scoped attempt at
https://github.com/spinnaker/orca/pull/2938, which relates to
https://github.com/spinnaker/spinnaker/issues/4367.
`ArtifactResolver.resolveArtifacts(Map)` currently attempts to load
_all_ executions for a pipeline in order to find the most recent
execution in the course of resolving expected artifacts. This causes a
lot of unnecessary data to be loaded from Redis/SQL, only to be
discarded a few operations later.
This change makes use of the fact that the ExecutionRepository
implementations will respect the `executionCriteria.pageSize` argument
when retrieving Execitions for a pipelineId.
In the Redis-based implementation, the executions are stored in a sorted
set scored on `buildTime` (or `currentTimeMillis()` if `buildTime` is
null), so retrieving all …
=> perf(artifacts): use pageSize=1 when resolving prior artifacts

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitorTest.kt
Remove check for all activators being up before running a zombie check.
It doesn't really buy us anything other than confusion.
E.g. if there is a dedicated instance that runs zombie checks but has
queue disabled the zombie check will not run.
Even if down instances run a zombie check that should be ok since their
view of the queue should still be accurate
=> fix(zombie-check): make zombie check run regardless of instance status

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/AwsDeployStagePreProcessor.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/PinServerGroupStage.groovy
For RRB we start by pinning the source SG so that it doesn't scale down during deploy (and end with unpinning it).
However, if for whatever reason some of the instances are taken out of discovery/targetgroup we will timeout waiting for the capacity match on this operation.
Since this pin/unpin operations are purely "cautionary" and don't require us to actually match the capacity, don't wait for the capacity match so we don't fail for this non-critical reason
=> fix(RRB): Add dedicated pin stage

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/GoogleCloudBuildStage.java
Fixes spinnaker/spinnaker#4503
* fix(spel): Fix NPE in SpEL evaluation 
Evaluating SpEL on a null object throws an NPE; if the input object is null, just return null as the evaluated expression.
* fix(gcb): Bind artifacts produced from GCB stage 
Because we didn't include the BindProducedArtifacts task in the GCB stage, produced artifacts were not matched to expected artifacts, which prevented correctly using them downstream.
=> fix(gcb): Bind artifacts produced from GCB stage

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/V2SchemaExecutionGenerator.java
Marks inherited items (triggers, notifications, parameters) as "inherited" so that the UI can distinguish between what is on the pipeline config and editable versus what is read only from the template.
https://github.com/spinnaker/spinnaker/issues/4451
=> fix(core): Mark mptv2 items as inherited

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java
When using SpEL functions like `*FromUrl` when the request requires auth and causes
a redirect response, we get a confusing "Not retrying" error message.
Make it a more descriptive error message that indicated where we are redirecting to (e.g. `login.asp`)
and state that it's not supported
=> fix(fromUrl): Better error message for redirects

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStageContext.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/model/CompletionDetails.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/model/JobStatus.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/DestroyJobTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy
Currently, when you cancel a run job stage it just leaves the underlying job running. That's unexpected behavior. 
This PR adds support for canceling the underlying job when you cancel the stage.
@ezimanyi @ethanfrogers I'm looking for some help verifying that this data structure also works for kubernetes (specifically that `jobStatus.name` is the name of the kubernetes job and the same name used in this [destroyJob](https://github.com/spinnaker/clouddriver/blob/29c5c1435ab0c750c4b491208f600647a3e98901/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/ops/job/DestroyKubernetesJobAtomicOperation.groovy) atomic operation).
This PR uses https://github.com/spinnaker/clouddriver/pull/3762 for Titus support.
=> fix(runJob): cancel underlying job on cancel stage

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java, orca-pipelinetemplate/src/test/resources/integration/v1schema/loops-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/loops-template.yml
Small enhancement for v1 MPT from an internal team.
They want to be able to be able to have like a `regions` (or in their case, `stacks`) var that they can iterate over to generate multiple deploy stages and be able to reference them by name later on.
=> feat(mptv1): Support templated stage IDs in looped stages

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy
fixes a case where parameter overrides would override the base job
configuration as well as the job in the context. this is because the
previous implementation would assign a reference to `context[it]`
instead of a copy. when the parameter overriding was done it would not
only modify the fields in context but also the base configuration. this
presented itself when running > 1 job in parallel. by focing a new copy
(via `converValue` for simplicity) we get a fresh object reference we
can assign.
fixes spinnaker/spinnaker#4487
=> fix(jobs): fix race condition in override

orca-bakery/orca-bakery.gradle, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/BakerySelector.java, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/config/BakeryConfiguration.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/config/BakeryConfigurationProperties.java, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTask.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/BakerySelectorSpec.groovy, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryServiceSpec.groovy, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTaskSpec.groovy, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy
- Using kork v2 selector to shard the bakery based on parameters
=> feat(bakery): Making bakery service selectable by parameters

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy
This is a smaller-scoped attempt at
https://github.com/spinnaker/orca/pull/2938, which relates to
https://github.com/spinnaker/spinnaker/issues/4367.
`ArtifactResolver.resolveArtifacts(Map)` currently attempts to load
_all_ executions for a pipeline in order to find the most recent
execution in the course of resolving expected artifacts. This causes a
lot of unnecessary data to be loaded from Redis/SQL, only to be
discarded a few operations later.
This change makes use of the fact that the ExecutionRepository
implementations will respect the `executionCriteria.pageSize` argument
when retrieving Execitions for a pipelineId.
In the Redis-based implementation, the executions are stored in a sorted
set scored on `buildTime` (or `currentTimeMillis()` if `buildTime` is
null), so retrieving all …
=> perf(artifacts): use pageSize=1 when resolving prior artifacts (#2955)

orca-front50/orca-front50.gradle, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
Pipeline triggers and pipeline stages were broken for templated pipelines that use a dynamic source that references an artifact. Resolved by resolving the artifacts a bit earlier (before the preprocessors).
=> fix(pipelines): Fix pipeline triggers for some templated pipelines

orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgent.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgentSpec.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/4467
OldPipelineCleanupPollingNotificationAgent is checking the age of the
pipeline execution twice before removing it:
1. the `Observable<Execution>` returned from
`executionRepository.retrievePipelinesForApplication(app)` is filtered
to only executions that have a completed status and where startTime (or
buildTime, if startTime is not set) is before `now - thresholdDays days`
2. After converting the `Observable<Execution>` to a `List`, sorting it,
and retaining `minimumPipelineExecutions` elements, each execution is
only deleted if `days between startTime and now > thresholdDays`.
The first check is true for executions as soon as they are a moment
older than `executionDays` days, but the second requires executions to be
older than …
=> fix(cleanup): remove 2nd check on thresholdDays in old pipeline cleanup

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/EnabledPipelineValidator.java, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/pipeline/EnabledPipelineValidatorSpec.groovy
Fetching a single pipeline config _should_ be more efficient than
fetching all pipelines (for an application) and filtering in
`orca`.
This is somewhat nuanced as the "all pipelines for application" is
likely being served out of the in-memory cache.
We have seen what looks like serialization-related load and this PR
aims to offer some relief.
=> feat(perf): Favor a single pipeline config lookup

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/FindImageFromTagsTask.java
When `tags` aren't provided by the user, treat it as if the user set them to an empty map
instead of failing with `NullPointerException`
=> fix(findImageFromTags): don't fail on missing tags

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy, orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStage.groovy, orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStageSpec.groovy, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTaskSpec.groovy
Add additional parameters to the monitored webhook to allow:
1. waiting some number of seconds before polling starts
2. retrying on specific HTTP status codes
Still needs deck counterpart
see [3450](https://github.com/spinnaker/spinnaker/issues/3450)
=> fix(webhooks): addresses issue 3450 - introduce a delay before polling webhook

Dockerfile, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/artifacts/FindArtifactFromExecutionTask.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy
Background
Currently the FindArtifactFromExecution stage resolves all artifacts for a pipeline and searches back to front for a matching artifact. This is undesirable when resolving from the same pipeline as the resolver will always resolve the same artifact produced from the previous FindArtifactFromExecution stage.
Change
Add new method getArtifactsForPipelineIdStageRef, which resolves artifacts for a given stage ref. This method is used to remove matched artifacts from the pipeline artifact resolver. By removing the artifacts found from the previous stage execution the task will not match artifacts produced by this stage.
Test
Added unit test for ArtifactResolver. Ran test suite. Writing UT for the task proved difficult with all the dependencies, since it currently has no UT i left it …
=> fix(task): FindArtifactFromExecutionTask no longer matches its own artifacts

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestContext.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestContextSpec.groovy
* test(kubernetes): Add tests to manifest context deserialization 
* fix(kubernetes): Fix NPE when traffic management not specified 
The refactor of the deploy manifest context broke the defaulting of TrafficManagement which prior to this could not be null. Fix that, and add a @Nonnull annotation.
Also, change the inner classes to be immutable as they were before the refactor.
=> fix(kubernetes): Fix NPE when traffic management not specified

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerTest.kt
When:
- you have a pipeline with `isKeepWaitingPipelines: true` 
- there are multiple `NOT_STARTED` queued up
- you cancel one of the pipelines in the middle
then orca would stop doing work on that pipeline.
This change tells orca to check for additional waiting executions after ignoring a StartExecution for a cancelled execution.
=> fix(queue): After trying to start a queued execution that is CANCELED check the pipeline queue for additional waiting executions

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsServerGroupCreator.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DeploymentDetailsAware.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy
Imagine following setup:
```
Pipeline A
-> Jenkins job (produces foo.*.deb)
-> Run Pipeline B
-> Jenkins job (produces bar.*.deb)
-> Bake package foo
```
In this case, the package lookup for bake stage will fail to lookup artifact
details for `foo.deb` to pass to the bakery. Thus the bakery is free to pick the
latest artifact matching the name which can be the wrong artifact.
This change allows package look up to traverse up parent pipeline stages, similar
to `FindImage` tasks
=> fix(bake): Lookup artifact details from all upstream stages

orca-core/src/main/java/com/netflix/spinnaker/orca/exceptions/ExceptionHandler.java
`errors` should be a meaningful message since that's what UI will show.
some parts of the code (`RetrofitExceptionHandler`) already ensure that the
message can't be null, but the default handler does not.
Adding it to the lowest level so callers don't have to worry about it
=> fix(exceptions): don't let `null` strings leak into errors field

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/EnabledPipelineValidator.java
Also adds support for using `initialConfig.enabled` as a short circuit
of the `EnabledPipelineValidator` check.
This seems reasonable as a user can already submit pipeline json against
an arbitrary pipeline config id (that may or may not exist).
Providing an ability to explicitly override the enabled check seems
harmless.
=> feat(core): Support deserializing `Execution.initialConfig`

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsServerGroupCreator.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsServerGroupCreatorSpec.groovy
Add support for deploying an ECS Task Definition as an artifact.
* Implements https://github.com/spinnaker/spinnaker/issues/4070
* Fixes https://github.com/spinnaker/spinnaker/issues/3341
This feature allows Task Definition attributes, including multiple containers, to be defined in an artifact (JSON file) and used in conjunction with pipeline images and other server group settings to deploy to ECS.
=> feat(ecs): Add support for task definition artifacts

build.gradle, orca-bom/orca-bom.gradle
compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
see related commit: nebula-plugins/nebula-publishing-plugin@a5432aa
Currently all published `pom.xml` contain:
```
<dependency>
<groupId>org.projectlombok</groupId>
<artifactId>lombok</artifactId>
<version/>
<scope>provided</scope>
</dependency>
```
which is considered invalid by Maven and thus all transitive dependencies of such artifacts are omitted.
=> Fix generated pom.xml to omit invalid lombok declaration

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
After cadence 1.14, kork introduce json-path 2.4.0 as dependency and the JsonContext().parse method is deprecated.
As a result, webhook stage fails to bind expected artifacts. 
Issue: https://github.com/spinnaker/spinnaker/issues/4599
This PR is for replacing the method with a static parse method which works for both json-path 2.4.0 and 2.2.0
reference:
https://static.javadoc.io/com.jayway.jsonpath/json-path/2.4.0/com/jayway/jsonpath/internal/JsonContext.html
https://static.javadoc.io/com.jayway.jsonpath/json-path/2.2.0/com/jayway/jsonpath/internal/JsonContext.html
=> fix(webhook-task): replace deprecated method for json parsing

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandlerTest.kt
This fixes https://github.com/spinnaker/spinnaker/issues/4596
Authentication is not propagated in Cancellable stages such as `CIStage`, so cancellation will fail if using Fiat permissions in build masters.
The fix is to propagate authentication context to the cancellation handler.
=> fix(queue): Propagate auth context on CancelStageHandler

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ResizeStrategySupport.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleExactResizeStrategy.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategySpec.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
Currently, if there are two ASGs:
(1) Newer one but disabled
(2) Older one but enabled
The RRB strategy will pick ASG (1) as the "source" which is incorrect for the deploy process.
This change takes advantage of the `determineSourceServerGroup` task and uses the ASG from it.
=> fix(RRB): Correctly determine source ASG

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategySpec.groovy
Make sure RRB disable step disabled the same number of instances as it brought online,
and only in the source server group.
Imagine there are multiple active server groups for RRB:
- v001 (capacity: 6, active)
- v002 (capacity: 10, active)
we are deploying v003, with the following steps: 50%, 100%
Currently, RRB will do the following:
1. Spin up 5 instances in v003 (50% of the source which is v002)
2. Disable 3 instances in v001 and 5 in v002 for a total of 8!
3. Spin up another 5 in v003 (100%)
4. Disable 3 and 5 respectively
Effectively we went from capacity 16 to 10 and are now under provisioned.
This is an edge case, but we want it to have predictable behavior that doesn't leave the cluster under provisioned
=> fix(RRB): disable traffic on the source server group only 

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/service/DefaultRestTemplateProvider.java, orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/service/RestTemplateProvider.java, orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookService.groovy
This supports the use-case of needing a specific `RestTemplate`
per url.
=> fix(webhook): Supply additional context when fetching `RestTemplate`

gradle.properties, orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisOrcaQueueConfiguration.kt, orca-redis/orca-redis.gradle, orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/locks/AbstractRedisLockManager.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/locks/RedisClusterLockManager.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/locks/RedisLockManager.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/notifications/RedisClusterNotificationClusterLock.java
- Enables use of Redis Cluster for Orca's queue and distributed lock
service, when SQL is used for the execution repository. Running Orca
entirely on Redis Cluster or with a mix of Redis and Redis Cluster
remains unsupported.
=> feat(redis): redis cluster support for queue and locking

orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfiguration.java, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookServiceSpec.groovy
```
public boolean isRedirect() {
switch (code) {
case HTTP_PERM_REDIRECT:
case HTTP_TEMP_REDIRECT:
case HTTP_MULT_CHOICE:
case HTTP_MOVED_PERM:
case HTTP_MOVED_TEMP:
case HTTP_SEE_OTHER:
return true;
default:
return false;
}
}
```
In the event that a redirect is detected, the value of the `Location`
header will be checked against `UserConfiguredUrlRestrictions`.
Can be disabled by setting `webhook.verifyRedirects: false`
=> fix(webhook): Support verification of redirected urls

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategySpec.groovy
When there is no source server group and a validation pipeline has been specified
RRB flow composition will fail (erroneously) trying to construct parameters to be
passed into the validation pipeline (even though the source isn't even necessary!).
This fix does two things:
1. Correctly calculate parameters passed into the validation pipeline
2. Don't even bother composing the flow if we are being called during the `beforeStages`
since all these stages will be discared anyway (none of the stages have `STAGE_BEFORE` synthetic)
Medium term: all of this should just go away - we shouldn't be using `aroundStages` which is a
source of lots of confusion. I will be refactoring this code to take advantage of newer
`beforeStages` and `afterStages`
=> fix(RRB): fix NPE introduced in https://github.com/spinnaker/orca/pull/3031

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/DisableServerGroupTask.groovy
As a result of https://github.com/spinnaker/orca/pull/3037, the RRB flow now no longer bypasses traffic guards
(it used to do that before, here: https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy#L145 `shouldSkipTrafficGuards`.)
Instead, now when we run the first disable step in RRB (e.g. disable 5% of source), the traffic guards think
the whole ASG is going away as it is unaware of the percentage disable flag and thus it terminates the operation
since "disabling entire ASG while new is still not fully up" is most certainly unsafe.
For now, add back the logic we had in the `AbstractClusterWideTask` to `DisableServerGroupTask` to skip check on RRB deploys.
In the …
=> fix(RRB): Do not consider traffic guards during RRB deploy

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/KayentaService.kt, orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/model/KayentaCanaryContext.kt, orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/model/RunCanaryContext.kt, orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/pipeline/RunCanaryIntervalsStage.kt, orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/RunKayentaCanaryTask.kt
This a temporary "hack" until https://github.com/spinnaker/kayenta/issues/600 is addressed.
This changes passes through the `siteLocal` stage context to the kayenta so that it can send
report emails. The `siteLocal` params are currently used at Netflix only but they exist in
OSS `deck`. Medium term, we will remove this from deck and orca
=> fix(kayenta): plumb through siteLocal for kayenta email support

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequest.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGeneratorSpec.groovy, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaIntegrationSpec.groovy, orca-pipelinetemplate/src/test/resources/integration/v1schema/conditionalStage-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/dependsOn-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/example-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/exampleCombined-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/expectedArtifactsInheritance-config.yml, orca-pipelinetemplate/src/test/resources/integration/v1schema/expectedArtifactsInheritance-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/expectedArtifactsInheritance-template.yml, orca-pipelinetemplate/src/test/resources/integration/v1schema/inheritance-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/loops-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/modularStageConfig-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/modules-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/nestedConditionalStage-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/parameterInheritance-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/partials-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/partialsAndModules-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/simple-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/stageInjection-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/stageReplacement-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/triggerInheritance-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/variableParameters-expected.json
When expected artifacts are defined in a template that is sourced dynamically,
expected artifacts are not added to the execution.
Expected artifacts can be defined in `TemplatedPipelineRequest`,
`TemplateConfiguration` and `PipelineTemplate` objects, so a merge strategy
is required. Given expected artifacts have a unique `id`, artifacts with
same `id` in these object will be overridden. The artifacts with higher
priority are the ones in `TemplatedPipelineRequest`, then `TemplateConfiguration`
and finally `PipelineTemplate`.
=> fix(pipelines): expectedArtifacts inheritance from dynamic parent templates

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/model/V2PipelineTemplate.java
hyphenated variable names are invalid, update validation used by the the save pipeline template task.
https://github.com/spinnaker/spinnaker/issues/4694
=> fix(core): update validaton to exclude hyphenated variable names

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStage.groovy, orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStage.groovy, orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy, orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStageSpec.groovy, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy
for webhooks that have `waitForCompletion=true` (i.e. monitored webhook) it is
desirable to have an indication of cancellation (either user cancels execution
or the execution is terminated due to some failure)
NOTE: this also deleted fields marked deprecated from webhook response. These have been marked deprecated 1yr ago so it's time to let them go
=> feat(webhooks): add support for cancellation to webhooks

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CloneServerGroupTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CloneServerGroupTaskSpec.groovy
CreateServerGroupTask does the right thing, and CloneServerGroupTask
also used to have allow-before-clone but it regressed at some point.
This means that if the first time we try to deploy an ami in an account
is via a clone operation, it is going to fail.
=> fix(clone): make sure we run allowLaunch before cloneServerGroup

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
If a pipeline that triggers a downstream pipeline is canceled, and that downstream pipeline doesn't limit concurrent pipelines, you can get two duplicate downstream pipeline executions.
This PR adds the `parent execution id` as a `correlationId` so that the downstream pipeline only run once.
=> fix(pipelines): an execution only starts one dep pipeline once

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
- Adding the pipeline description to `PIPELINE-DESCRIPTION` header , this will be consumed and set in `clouddriver` Eg  `X-Titus-CallReason` while making calls to titus.
=> fix(logging context header): add pipeline description details to MDC

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
People often try to fix expresions or test how they would evaluate by using the expressions testing endpoint. This runs in a different way than if you were to use an expression in a stage.
This PR adds a new endpoint that takes an execution id and a stage id from that execution. It evaluates the expression as if it was evaluated as that stage.
=> feat(expressions): entpoint to eval an expression from a stage

orca-web/config/orca.yml
Currently, we are testing features in debug mode, but aws server
group creation always failed because: "Missing security groups:
nf-datacenter,nf-infrastructure". This caused by default config
file in orca-web/config/orca.yml doesn't have default security
group settings, hence when we create alb in deck, orca always
adds two nonexistent security group name into security groups,
and failure happens because clouddriver cannot find them.
We do not want others cost valuable time in resolving such issue
when they are fresh or unfamiliar with aws provider code logic.
cc @zqfan
=> fix(aws): add default config for security groups

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy, orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTaskSpec.groovy
It appears as though we can get `UnknownHostException` in several different ways.
Making the exception handler for webhook stages a bit more robust and less constrained
when looking for `UnknownHostException` in the cause to make sure we retry these failures
=> fix(webhooks): correctly detect DNS failures

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/RunJobManifestContext.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesJobRunner.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesJobRunnerSpec.groovy
adds support for artifacts in the v2 kubernetes run job implementation.
follows the same patterns as deploy manifest. the KubernetesJobRunner
class is responsible for fetching artifacts and setting up the operation
description.
=> feat(runJob): support artifacts in k8s run job

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy
if the job is for kubernetes v2 (denoted by either `source` or
`manifest` keys), inject a couple of manifest refresh stages to prevent
cache misses when `WaitForJobCompletion` runs. this isn't the most ideal
way to implement this, however. we should eventually abstract this out
into the provider specific job runner classes.
=> fix(runJob): inject manifest fcr for k8s runjob

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy
if the job is for kubernetes v2 (denoted by either `source` or
`manifest` keys), inject a couple of manifest refresh stages to prevent
cache misses when `WaitForJobCompletion` runs. this isn't the most ideal
way to implement this, however. we should eventually abstract this out
into the provider specific job runner classes.
=> fix(runJob): inject manifest fcr for k8s runjob (#3090) (#3094)

gradle.properties, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/BakerySelector.java, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/config/BakeryConfigurationProperties.java
Prior to this PR, bakery selection had to be enabled on a per-pipeline basis via setting `"selectBakery": true` in a bake stage's context. This does not enable bakery service selection by default, but allows it to be enabled universally for a running orca instance via setting `bakery.selectorEnabled` to true. Both of these configuration methods are temporary, while bakery selection is in development.
=> chore(bakery): config to enable multi-bakery selection without stage context magic

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
Several classes were missed during the kork-expression migration
https://github.com/spinnaker/orca/pull/3071/files#diff-32563145a925ce8860f9464194446db8L60
this caused expressions such as ${execution.trigger.buildinfo} to fail for jenkins triggers
=> fix(expressions): add missed allowed classes back in

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepositorySpec.groovy
This attempts to fix https://github.com/spinnaker/spinnaker/issues/4762
Due to `ContextParameterProcessor` ultimately accepting `Stage` as return value, it is possible for a `Stage` whose `context` has been replaced with the one with all expressions evaluated (using `Stage.withMergedContext` extension in `ExpressionAware`) to contain cyclic reference to itself. 
This can be reproduced by having the `${#currentStage()}` inside the stage context. We found the bug above from a mistake when writing customised stage notification message (engineer write `${#currentStage()}` instead of `${#currentStage()['name'])}`.
The circular reference causes Orca to throw StackOverflowException in `StartStageHandler` during the `repository.storeStage(stage)` step. As a result, the stage will never be …
=> fix(core) Handle circular reference in Stage class

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
When a task fails due to an exception in the `execute` and the stage is marked
as 'failPipeline=false' the `RunTaskHandler` incorrectly set the task status to
FAIL_CONTINUE.
This causes subsequent tasks in the stage to run even if after a failure. This
also causes the original exception to be hidden by failures in subsequent tasks
This change corrects this behavior and treats task exceptions same as if the task
returned `TERMINAL`
=> fix(orchestration): mark tasks failed if the stage is marked ignore failure

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/StageStatusPreconditionTask.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/StageStatusPreconditionTaskSpec.groovy
Closes: https://github.com/spinnaker/spinnaker/issues/4768
Corresponding Deck PR: https://github.com/spinnaker/deck/pull/7348
Thoughts on surfacing useful error messages in Deck:
- Based on Deck's [expectations](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/orchestratedItem/orchestratedItem.transformer.ts#L171), non-thrown error messages should be set on a task's outputs `exception.details.error` or `exception.details.errors` to be surfaced in the `StageFailureMessage` component. I haven't encountered a standard way to do this in Orca but if you get this message and you know The Right Way please help me out :love_letter: 
- I'm also unsure of any conventions around when to throw an error vs. attach an error to the task context. I went with 1) throw an error …
=> feat(pipeline): add stage status precondition task

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
When an execution fails in to start (e.g. before the execution is persisted) in `orca`,
`orca` will mark and store the execution as failed.
Since the artifact resolution is being moved to `echo`, `echo` needs the same ability
to mark executions as failed - otherwise any failures during artifact resolution in
`echo` will turn into silent failures for the user (if no execution is persisted then
the UI can't show any failures associated with that execution).
This change adds an endpoint that `echo` can call to mark the execution failed
=> fix(error handling): add endpoint to mark executions failed

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/ArtifactExpressionFunctionProvider.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/ArtifactExpressionFunctionProviderSpec.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/4783
This MR  adds the following helper functions to Spinnaker Pipeline Expressions
`#triggerResolvedArtifact(name)` gets *one* resolved expected artifact that matches the provided `name`. I used `name` instead of `type` here to make it consistent with `#stage(..)`.
`#triggerResolvedArtifactByType(type)` is similar to `#triggerResolvedArtifact` but uses `type` of the artifact.
=> feat(core): Add SpEL Function Helpers for Resolved Trigger Artifacts

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/CapabilitiesController.java, orca-web/src/main/groovy/com/netflix/spinnaker/orca/model/DeploymentMonitorDefinition.java, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/CapabilitiesControllerSpec.groovy
Returns the names and ids of registered deployment monitors.
This will be used in `deck` to let the user pick a monitor (also need to plumb through `gate`)
=> feat(monitored deploy): add endpoint to get a list of deployment monitors

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/NotifyDeployCompletedTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/NotifyDeployStartingTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/EvaluateDeploymentHealthTaskSpec.groovy, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/DeploymentMonitorService.java
left over cleanup from the previous PR
=> chore(monitored deploy): clean up naming broadcast -> notify

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/ConditionAwareDeployStagePreprocessor.java
- Pausing deployments should only apply to pipelines
- Orchestrations should be ignored
=> fix(conditions): Only pause pipeline deploys

orca-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/SqlHealthIndicator.kt
- SqlHealthActivator is designed to halt queue processing when sql
persistence is in use and the connected database is in a read-only
mode. This is desired behavior when running in a single writer
environment, where write availability is impacted by a failover.
This PR adds a dynamic configuration property,
`sql.overrideSpringHealthCheck` that prevents Spring's Health
Indicator going unhealthy when connected to a read-only database,
allowing Orca to continue serving read-requests for task and pipeline
executions.
=> feat(sql): ability to override SqlHealthIndicator by dynamic config

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/MonitorJobTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/RunJobTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/RetryableTask.java, orca-core/src/main/java/com/netflix/spinnaker/orca/Task.java, orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Currently, task timeouts can't take anything about the execution environment into account (they are essentially a static method).
This change adds the ability for tasks to consider the current `stage` (`execution`) when evaluating timeout.
Additionally, the `onTimeout` method on the task can now return a `TaskResult`.
This allows the tasks to decide if they should be `TERMINAL` or `FAILED_CONTINUE` on timeout and return data to be added to the stage in a standard way
Both are needed for monitored deploy - as the timeout and what action to take depend on the monitor configuration.
This will also become useful for `clouddriver` tasks that are retryable (e.g. backed by sagas)
=> feat(orcestration): add support for dynamic task timeout

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/SourceResolver.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/SourceResolverSpec.groovy
If there are multiple possible server groups to choose as the source,
and all are of the same size, prefer the older server group.
This supports a use case where multiple simultaneous clone operations
are performed against a single source (the intention is to have
multiple active server groups in the region). Because a server group
can have its capacity manipulated during the deploy lifecycle, we
don't want the second deploy to choose the first deploy as its source
and result in snapshotting a capacity that may have had the min
size pinned high
=> fix(source resolver): prefer older servergroup when copying capacity

orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandler.kt
When `fillExecutorEachCycle` is enabled, keiko attempts to completely fill the `messageHandlerPool` executor which is configured to rejects executions when full instead of queue. `CancelStageHandler` attempted to fire and forget cancel methods by running on the same executor despite the fact that keiko attempts to keep it full. Running cancel methods on a dedicated threadpool resolves this race condition while preserving the fire-and-forget semantics that allow cancel methods to run beyond keiko's `ackTimeout`.
=> fix(core): run CancellableStage cancel method on dedicated thread pool

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollbackSpec.groovy
Does not entirely address this issue but makes it less likely to happen:
https://github.com/spinnaker/spinnaker/issues/4895
The "danger zone" is when a resize of the source server group happens
between the start of the rollback and the moment we take the capacity
snapshot. This change should reduce that "danger zone" from minutes to
seconds.
=> fix(rollback): capture the source capacity before anything else

gradle.properties, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestService.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoService.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/Task.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/MonitorJobTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTaskSpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryMonitorKatoServicesTaskTest.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/SystemNotification.kt, orca-web/config/orca.yml
Depends on https://github.com/spinnaker/kork/pull/383
=> feat(clouddriver): Basic support for retryable kato tasks

orca-sql/orca-sql.gradle
for some reason, the latest intellij doesn't copy the sql migration (changelog-master) file.
this change fixes that so we don't have to `gradlew build` to copy the file over
=> chore(intellij): fixing first time builds in intellij

orca-clouddriver/orca-clouddriver.gradle
bump to use the same version as cloud driver, the version used before was a beta version
=> chore(kubernetes): upgrade kubernetes client-java from beta to 5.0.0

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/gce/GceDeployStagePreProcessor.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategy.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategySpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/gce/GceDeployStagePreProcessorTest.java
Closes https://github.com/spinnaker/spinnaker/issues/4270
As a Spinnaker user deploying my first server group into a new cluster, I expect it to succeed if I have selected the red/black strategy.
Since Netflix has already added support for this user story in the AWS rolling red/black strategy, this PR takes the same approach: the GCE deploy stage pre-processor now short-circuits when attempting to add stages to pin and unpin the source server group's capacity if there is no source server group ([AWS code](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/AwsDeployStagePreProcessor.groovy#L173), for reference), and the red/black strategy `composeFlow` method now also short-circuits instead of adding …
=> fix(google): fix deploying with red/black into an empty cluster

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ScaleDownClusterTask.groovy
Closes https://github.com/spinnaker/spinnaker/issues/4810
In response to the deprecation of GCE autoscaler's `ONLY_DOWN` mode, we set the mode to `OFF` in the `ScaleDownClusterTask` in this [PR](https://github.com/spinnaker/orca/pull/3087/files). However, when we scale down a server group with an autoscaler, we are actually enacting the scale-down by updating the capacity of the autoscaler, so if we set its mode to OFF, the scale-down will hang until the task times out. Since we are setting `min`, `max`, and `desired` capacity to 0, I don't think it will matter whether the mode is ONLY_DOWN or ON, since it will have to scale down in order to actuate the new capacity.
<details><summary>Before</summary>
<p>
</p>
</details>
<details><summary>After</summary>
<p>
</p>
</details>
=> fix(google): fix scale down cluster task in gce red/black

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/gce/GceDeployStagePreProcessor.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/gce/GceDeployStagePreProcessorTest.java
Closes https://github.com/spinnaker/spinnaker/issues/4812
- When deploying to AWS, only the rolling red/black strategy pins the source server group's min capacity to its desired capacity (see [AwsDeployStagePreProcessor](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/AwsDeployStagePreProcessor.groovy#L155) and this [conversation](https://github.com/spinnaker/orca/pull/3173#discussion_r325905128) for details on how/why).
- This change brings the GCE implementation of red/black to parity with the AWS implementation: we will no longer pin the source server group's min capacity to its desired capacity. The potential drawback to this is that during the period when both the source and target server …
=> fix(google): do not pin source server group capacity in red/black

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/EvaluateDeploymentHealthTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/MonitoredDeployBaseTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/NotifyDeployStartingTask.java, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/config/DeploymentMonitorConfiguration.java, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/config/DeploymentMonitorDefinition.java, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/config/DeploymentMonitorServiceProvider.java, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/models/StatusExplanation.java
This change cleans up and significantly improves logging for deployment monitors.
Additionally, it take advantage of the dynamic task timeout mechanism newly minted in orca (see #3159)
The following will be added to context for `deck` to parse and present to user:
* The current status the deployment monitor has provided (e.g. wait/continue/abort)
* In case of failures to communicate with the deployment monitor
* A better high level summary of response from deployment monitor
The following simple logging is improved:
* retrofit errors
=> fix(monitored deploy): log everything better

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategySpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategySpec.groovy
The main issue being resolved here is how we determine if a source ASG is present during R/B deploy.
In some cases, the `.asgName` property is used while others `.serverGroupName` is used. If we don't check both, some UI (tasks) operations don't work correctly,
e.g. clone with red/black and leave max 2 remaining ASGs will fail to disable the old ASG as well skip the shrink step.
While here, I am also making similar change to RRB and MD strategies.
Additionally, cleaning up the `composeFlow` -> `composeBefore/AfterFlow` for strategies as a follow up from PR #3133
=> fix(redblack): fix red/black deploy

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/EvaluateDeploymentHealthTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/MonitoredDeployBaseTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/NotifyDeployCompletedTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/NotifyDeployStartingTask.java
Somehow... I forgot that tasks are singletons and shouldn't have any state stored...
Simple refactor to pass along the vars that are needed all the time
=> fix(monitored deploy): don't store any context in the task

orca-core/src/main/java/com/netflix/spinnaker/orca/TaskExecutionInterceptor.java
- The `maxTaskBackoff` for `RetryableTask` `RunTask` messages was previously limited via `LockExtendingTaskExecutionInterceptor` which was removed by https://github.com/spinnaker/orca/pull/3136. This makes the prior backoff constraint the default as it assists with patching and cancellation of in-flight executions.
=> fix(tasks): limit task maxBackoff time to 2min

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/AwsDeployStagePreProcessor.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/titus/TitusDeployStagePreProcessor.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/PinServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/MonitoredDeployBaseTask.java
* add monitored deploy to checks where we check for RRB (since, semantically, they are same)
* make some better summary messages
=> fix(monitored deploy): add monitored deploy to same checks as RRB

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/MonitoredDeployBaseTask.java, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/models/EvaluateHealthResponse.java, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/models/StatusExplanation.java
there is no point having an array of reasons from deployment monitor, making it a single object
=> fix(monitored deploy): make reason singular

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/AwsDeployStagePreProcessor.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategySpec.groovy
During rolling redblack (or monitored deploy), use the determined source server group to pin/unpin.
This used to live in the deploy preprocessor, but the deploy preprocessor runs too early to be useful (it runs before we run determineSourceServerGroup task).
This means it can pick the wrong ASG to pin! in the following scenario:
```
ASG v2 - being deployed
ASG v1 - Disabled
ASG v0 - Enabled
```
before this change, we would pin/unpin `v1` which is clearly wrong ASG to pin.
NOTE: currently the code is duplicated in RRB and MD strategies. I will do another PR with a refactor to make them share code (it's proving harder than anticipated to make this refactor actually nice)
=> fix(RRB & MD): pin and unpin the correct server group

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy
When deploy fails we need to sent completion notification to the deployment monitor
=> fix(monitored deploy): send complete notification on failure

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/CloudFormationForceCacheRefreshTask.java
For cache refreshing the CloudFormation cache can fail for
some reason (e.g. read timeout), but should generally succeed.
This patch makes this task more reliable by retrying if there was
a failure for up to 5 minutes.
=> fix(cfn): Add retries when force cache refreshing

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java
A previous refactor (#3011) reversed the order of stages returned from parent executions, which in turn caused a bug in the lookup of image id's.
If you have several image producing stages in a parent pipeline, for instance a "Find image by tag" stage followed by a bake stage, Spinnaker would now use the output of the "Find image by tag" stage instead of the bake stage. This PR changes it back to the former behaviour, so that the image closest to the current executing stage will be used.
=> fix(deploy): Correctly detect images in parent executions

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java
Why should pipelines get all the fun? If task triggers contain notifications, let's attach them to the execution. 
This is needed for https://github.com/spinnaker/echo/pull/668
=> feat(tasks): attach notifications to execution

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStage.groovy, orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
An assumption was made that body is a can be jackon parsed into a JSON object.
But that's not always the case, in fact, we actually account for it in the original parse:
https://github.com/spinnaker/orca/blob/master/orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy#L71
But then disregard it in StageContext mapping
This change removes those fields from being parsed since we don't actually need them for anything
inside the stage (they were added in the attempt to be fully typed)
=> fix(webhook): Don't try to deserialize fields we don't really need

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollbackSpec.groovy
This avoids a potentially dangerous scenario where we roll back to a server
group of size 0 and fail to look it up for some reason, e.g. if it is in
a restricted account and we fail to pass the credentials along to clouddriver.
=> fix(rollback): pass authentication context and consider errors fatal

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/CFRollingRedBlackStrategy.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/CFRollingRedBlackStrategyTest.java
After some investigating it looks like the problem is that when attempting to restore the old number of instances for the old server group, the following task waits on the wrong number of server groups to be up. The old server group remains disabled (in cf terms - stopped) but the task waits for the old number of up instances.
fix for spinnaker/spinnaker#4786
=> fix(cf): cf rolling red black did not resize old SG correctly

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/CloudFormationForceCacheRefreshTask.java
Force cache refreshing was a retryable task. However, it didn't return
RUNNING whenever the cache refresh failed, and thus the task failed
immediately. This patch makes the task return RUNNING whenever there's
an exception refreshing the cache so it actually retries.
=> fix(cfn): Return RUNNING if an error occurred

orca-sql-mysql/mysql-setup.sql
Just added this for convenience so it's easy to reset orca DB - this is only run manually
=> chore(mysql): add drop database to init script for convenience

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTask.java
Today, when determining health providers on Titus, we look at the labels on the source server group.
For AWS, we look at front50 if the app has the platform only override set.
Make Titus work similarly but allow the labels to be used as override (if they exist)
(change courtesy of @dreynaud)
=> fix(titus): use labels as override only for titus health providers

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestEvaluator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupport.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/ExpressionPreconditionTask.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt
Closes https://github.com/spinnaker/spinnaker/issues/4932
- chore(pipeline): add buildExecutionContext test to ContextParameterProcessorSpec
Adds test to demonstrate that currently, the context returned by `ContextParameterProcessor.buildExecutionContext`, when used as the context for `ContextParameterProcessor.process`, does not allow for the evaluation of variables that refer to the outputs of a prior stage.
- fix(pipeline): allow mid-task SpEL evaluation to reference prior stage outputs
Changes `ContextParameterProcessor.buildExecutionContext` to return `StageContext`, which extends a `ForwardingMap` in order to override `get` to search the stage's ancestors' outputs if a given key does not exist on the delegate object. Uses the `Map` previously returned by this method as the delegate. …
=> fix(pipeline): allow mid-task spel evaluation to reference prior stage outputs

orca-web/config/orca.yml, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/config/PreconfiguredWebhookSpec.groovy, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStageSpec.groovy
This fixes  https://github.com/spinnaker/spinnaker/issues/5009
Added `failFastStatus` property to `WebhookProperties.java` since there is no way to preconfigure this value when creating a **Custom webhook Stage**. Refer to the above mentioned issue for more details.
Also updated tests.
This PR contains the backend changes. Front end changes are made in `deck` here https://github.com/spinnaker/deck/pull/7512.
=> fix(webhook): Add fail fast status to webhook properties

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/manifests/helm/HelmBakeManifestRequest.java, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/BakeManifestContext.java
adds an option to bake manifest for rawOverrides. this will be passed
onto rosco to enable the --set option in helm.
=> fix(bakeManifest): add option for rawOverrides

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/RunKayentaCanaryTask.kt
Adding the config id and execution id to the outputs so that stage notifications can more easily construct a link to the canary report
=> chore(kayenta): add config id and execution to outputs

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/clouddriver/utils/CloudProviderAware.java, orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/RunKayentaCanaryTask.kt, orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/Tasks.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Task backoff can be configured globally, or drilled down to the cloudProvider and account level.  The relevant max backoff time always wins - if you desire no change of behavior simply do not create a dynamic config entry for a back off.  Note that the max back off time of 2 minutes can not be overridden.
=> feat(dynamicBackoff): Dynamically configurable task backoff

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ScaleDownClusterStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/monitoreddeploy/EvaluateDeploymentHealthStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/monitoreddeploy/NotifyDeployCompletedStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/monitoreddeploy/NotifyDeployStartingStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategySpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/EvaluateDeploymentHealthTaskSpec.groovy
Add rollback support to monitored deploy strategy.
It's slightly different from the default you get with CreateServerGroup, hence it is removed from there for this strategy
=> feat(monitored deploy): Support rollback on failure

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/EvaluateVariablesStage.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesTask.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesTaskSpec.groovy
You can create an adhoc spel expression that resolves to a complex object...
... and we will happily expand the entire object.
However, if you try to do the same thing in Evaluate Variables stage, you get an error:
```
java.lang.IllegalArgumentException: Unable to map context to class com.netflix.spinnaker.orca.pipeline.EvaluateVariablesStage$EvaluateVariablesStageContext
...
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.netflix.spinnaker.orca.pipeline.EvaluateVariablesStage$EvaluateVariablesStageContext[\"variables\"]
```
This PR changes `Variable` type from `[ key: string, value: string ]` to `[key: string, value: …
=> feat(EvaluateVariables): Support complex objects in EvaluateVariables stage

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/RollingRestartManifestStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/RollingRestartManifestTask.java
Closes spinnaker/spinnaker#4757
As the many comments/emojis on this [Kubernetes feature request](https://github.com/kubernetes/kubernetes/issues/13488) indicate, there are several valid user stories around issuing a rolling restart of a Deployment. The `kubectl rollout restart` command was released with kubectl version 1.15, and we currently use kubectl version 1.16 in Clouddriver. Like the other kubectl rollout commands, it is valid for Deployments, StatefulSets, and DaemonSets. We currently only expose the ad-hoc rollout commands for Deployments in Deck, but could at a later date expose them for StatefulSets and DaemonSets if there is evidence from users that it would be useful.
Related PRs:
Clouddriver: https://github.com/spinnaker/clouddriver/pull/4100
Deck: …
=> feat(kubernetes): support rolling restart operation for deployments

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStageSpec.groovy
This complements #3219 by ensuring that we only look at the image names for parallel bake stages associated with the top-level bake stage that the `CompleteParallelBakeTest` cares about when trying to decide whether to fail a parallel bake on inconsistent image names. This avoids failing the stage if there are unrelated bake stages in the pipeline (which would obviously generate different image names).
While troubleshooting this, I found that this task includes context information from the parallel bake stages of unrelated top-level bake stages in the pipeline, which is clearly visible in the execution JSON of such pipelines. I don't know if that is itself a bug or is by design, so I just left a note in a comment for now, but would be happy to correct that if it's not expected behavior.
=> fix(bake): Fix the fix for inconsistent names in parallel bakes

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategySpec.groovy
This is an addendum for #3224, which was causing Rolling Red/Black deployments with a "before cleanup" pipeline to fail as `StartPipelineTask` was looking for `stage.context.pipeline` but the pipeline ID was stored in `stage.context.pipelineId` here.
@marchello2000 and I search for other similar uses of `pipelineId` in the context and it looks like it's safe to make this change here.
=> fix(rrb): Store RRB before-cleanup pipeline ID in the right context field

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/BakeManifestContext.java, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/BakerySelectorSpec.groovy
Related to https://github.com/spinnaker/spinnaker/issues/4752
While investigating Retrofit errors in the Bake Manifest stage, found a few small code improvements:
- Move conversion of singular `inputArtifact` (Kustomize only) to list from `CreateBakeManifestTask.execute` into `BakeManifestContext` constructor. Also handle defaulting of `inputArtifacts` to empty list so that it doesn't need to be `@Nullable`. I think this lets the task be a little dumber about the Kubernetes vs. Helm inputs.
- In `CreateBakeManifestTask`, replace field injection with constructor injection. Because the `BakeryService` bean is not required, make it `Optional` per Stack Overflow [advice](https://stackoverflow.com/questions/42135102/how-to-set-autowired-constructor-params-as-required-false-individually) …
=> refactor(kubernetes): clean up bake manifest error messaging

gradle.properties, orca-core/orca-core.gradle, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluatorSpec.groovy
Depends on https://github.com/spinnaker/kork/pull/398
=> feat(plugins): Add kork-plugins, wire up initial spel function extension point

orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/models/RequestBase.java
Monitors need an ability to correlate calls to their API.
This adds a `deploymentId` parameter to all requests (which is really the `stageId` for the `createServerGroup` stage)
This allows the monitor to correlate e.g. `evaluateHealth @ 20%` and `evaluateHealth @ 50%` to the same cluster
Especially if multiple shards are deployed in the same pipeline
=> fix(monitored deploy): add deploymentId parameter

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListenerSpec.groovy
Failure in planning a, say, a single v2 templated pipeline will cause no dependent pipelines to start.
This is due to exception not being localized to each individual pipeline
=> fix(dependent pipelines): failure to trigger a dependend pipeline shouldn't affect others

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/StageContext.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/StageSpec.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt
Normally, if a synthetic child stage fails with `FAILED_CONTINUE` the `CompleteStageHandler`
will propagate the `FAILED_CONTINUE` status to the parent. This will prevent all subsequent
sibling stages from executing.
This change allows for an option (similar to Tasks) to continue execution even when a
child stage has a `status=FAILED_CONTINUE`
This option can only be set on a stage that is a synthetic child.
This is needed for Monitored Deploy where we want to allow the deploy to proceed even if the
monitoring fails
=> feat(orchestration): Allow sibling stages to continue on FAILED_CONTINUE

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/pipeline/CleanupCanaryClustersStage.kt, orca-kotlin/src/main/kotlin/com/netflix/spinnaker/orca/ext/Stage.kt
This change depends on https://github.com/spinnaker/orca/pull/3252
Sometimes, `DisableClusterStage` can fail. We don't want failures in `DisableClusterStage`
preventing the subsequent `ShrinkCluster` from trying to run and clean up the canary+baseline clusters
=> fix(kayenta): Make sure we destroy canary clusters

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/BakeManifestContext.java
This my fault, as [my comment](https://github.com/spinnaker/orca/pull/3244#discussion_r337703561) explicitly suggested using `Optional.of`.
The usages of Optional.of should be Optional.ofNullable.
=> fix(kubernetes): Fix Optional ofNullable

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeployCloudFormationTask.java
Something has changed between Spinnaker 1.15.6 and 1.16.0 with regard to how Cloudformation templates entered into the inline editor in Deck are parsed. Updating Orca to account for this change.
=> fix(cloudformation): Support Cloudformation templates as lists

gradle.properties, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AppEngineBranchFinderSpec.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/GitTrigger.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/TriggerSpec.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy
When dealing with webhook git triggers the event of the webhook does not reach the pipeline contexts. This PR makes this event available in the contexts of the pipeline execution.
This should no affect the current conditional for matching pipelines (source, project, slug, branch), it is just informative like the hash field.
For example: allow only github events where someone open/close a pull request using check preconditions, or if there is github push event follow a different branch in the pipeline, instead of one for pull request events.
For bitbucket server I used the header [ X-Event-Key ](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html)
For bitbucket cloud I used the header [X-Event-Key](https://confluence.atlassian.com/bitbucket/event-payloads-740262817 …
=> feat(triggers): add action field to git triggers context

orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/AbstractCloudFoundryWaitForServiceOperationTaskTest.java, orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionStatus.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/StageExpressionFunctionProvider.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluatorSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
* Let `#currentStage` be used in `stageEnabled` conditions
This requires `.withAuth` on the the entire StartStageHander::handle because the `currentStage` function relies on the execution to be present in the threadlocal (which is placed there by ``.withAuth`)
* Allow users to compare `ExecutionStatus` to string, e.g. this is now valid and works `${#stage('bake').status == 'SUCCEEDED'}`
in the past one would have to `${#stage('bake').status.toString() == 'SUCCEEDED'}` which is annoying
* Furthermore, added `hasSucceeded` and `hasFailed` to stage
This further simplifies above conditionals to `${#stage('bake').hasSucceeded}` & `${#stage('bake').hasFailed}`
=> fix(expressions): various quality of life improvements for SpEL

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/MonitoredDeployBaseTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/EvaluateDeploymentHealthTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/NotifyDeployCompletedTaskSpec.groovy, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/config/DeploymentMonitorDefinition.java, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/models/DeploymentMonitorStageConfig.java, orca-deploymentmonitor/src/main/java/com/netflix/spinnaker/orca/deploymentmonitor/models/RequestBase.java
Allow overriding `maxAnalysisMinutes` and `failOnError` values from within the stage
(defaults come from monitor config in orca.yml)
=> feat(monitoreddeploy): allow overriding maxAnalysisMinutes and failOnError

orca-api/orca-api.gradle, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/SimpleTask.java
* I bashed my head against the wall a little too much on the `SimpleStage` implementation: There's a lot of assumptions made that certain properties are non-null or off a certain type, but the generic type constraints do not enforce anything. I added `Optional` around the use of the problem properties, but didn't bother to harden the generic types or the handling of them - I'm not yet sure what I want to do with this.
* Removed unnecessary creation of `ObjectMapper` in `SimpleTask`.
* Removed `PluginManager` from the `StageResolver`.
=> fix(plugins): Remove unnecessary code

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy, orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListenerSpec.groovy
If a pipeline notification uses a SpEL expression which can't be evaluated at pipeline submission time (e.g. `${authentication.user}`)
that expression will not be evaluated prior to sending a notification. And the notification will have the raw expression present.
Ironically, app-level notifications don't suffer from this illness - they are properly evaluated and resolved prior to sending the notification.
This change adds explicit eval of notifications on the current execution
=> fix(notifications): Evaluate SpEL expressions in pipeline notifications

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
https://github.com/spinnaker/orca/pull/3280 introduced a regression where if there are multiple notifications
and the execution has SCM info (e.g. jenkins trigger) the pipeline notifications won't get sent out.
Why you ask? Side-effects, my friends!
`contextParameterProcessor.process` actually MUTATES the context that is passed in (it extracts the scm info which starts out as a list and then replaces it with an actual `SourceControl` object :mindblown:)
see https://github.com/spinnaker/orca/blob/master/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java#L170
I wanted to not jackson map the whole execution every single notification we eval so I cached and there-in lay my mistake...
This change does not reuse the executionContext map avoiding this …
=> fix(notifications): Fix regression from #3280

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PatchManifestContext.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PatchManifestTask.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestContextTest.java
Closes https://github.com/spinnaker/spinnaker/issues/5093
Corresponding Deck PR: https://github.com/spinnaker/deck/pull/7600
Clouddriver's patch operation expects Orca to send it a `patchBody` that is a list when the merge strategy is of type `json`, and a map otherwise. Prior to Spinnaker 1.15, Deck also saved the `patchBody` as either a list or map depending on merge strategy. In Spinnaker 1.15, the artifacts rewrite introduced a bug that caused the `patchBody` to be saved as a `Map` regardless of merge strategy, which broke the JSON merge strategy and Deck's YAML editor. This change:
1. Deserializes `patchBody` as an `Object`, and coerces it to a `List` to conform to the shared `ManifestContext` interface.
2. Validates that the list of patches is non-empty and that only JSON-strategy …
=> fix(kubernetes): fix patchBody typing depending on strategy type

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/GoogleCloudBuildRepoSource.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/GoogleCloudBuildStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTaskSpec.groovy
Added ability to call existing GCB triggers.
This is part of: spinnaker/spinnaker#5076
1. Enhanced `GoogleCloudBuildStageDefinition.java` to include the necessary fields for `igor` cloud build trigger endpoint:
- triggerId
- repoSource
2. Modified `StartGoogleCloudBuildTask.java` to check for the new build definition source and call the corresponding methods in `igorService`
=> feat(gcb): Ability to invoke existing GCB triggers

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.kt, orca-queue-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlPendingExecutionConfiguration.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/telemetry/SqlActiveExecutionsMonitor.kt
This makes it possible to conditionally create a secondary SqlExecutionRepository,
pointing at a specific named connection pool.
This also makes it possible to look up beans in DualExecutionRepository by name,
not just by class, which comes in handy when we want 2 SqlExecutionRepository beans.
=> feat(sql): add support for a secondary sql execution repo

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
When calling the following endpoint: `v2/applications/{}/pipelines` with `expand=false`
the `TaskController` will try "unexpand" the pipelines by removing "context" from all the stages.
However, there is a wrinkle: during removal of the context we want to preserve the `group` key (if it exists).
In order to check if the key is there, we make a call to `context.group`. The problem is that the `context` is actually a
`StageContext` and the `.group` is actually a `StageContext::get("group")`.
This particular call traverses the entire execution graph to see if `group` exists not only in the current stage context
but also in the outputs of any of it's parent stages. Well, if the stage graph is large this is a O(n^2) operation.
The kicker is that the `group` should never occur in the outputs …
=> fix(perf): Unexpanding pipeline without StageContext

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTask.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java
The nightly stats are showing both the `bake` and `bakeManifest` stages do not detect any `cloudProvider`s. This adds it in at least for GCE - the next nightly run will confirm it for AMIs and the hardcoded `bakeManifest`, which @ethanfrogers confirmed for me is always used for kubernetes (famous last words ;-)
=> fix(bakery): Include cloudProvider in CompleteBakeTask output results

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestEvaluator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/capabilities/models/ExpressionSpelEvaluatorDefinition.java, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/EvaluateVariablesStage.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/V2Util.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/capabilities/CapabilitiesServiceSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesStageSpec.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandlerTest.kt, orca-web/orca-web.gradle, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/util/ExpressionUtils.java, orca-web/src/main/groovy/com/netflix/spinnaker/orca/web/config/WebConfiguration.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/util/ExpressionUtilsSpec.groovy
Today, expressions are evaluated indiscriminately.
This change allows for a few useful changes:
1. Only evaluate SpEL expressions in a stage when that stage runs.
This allows for the SpEL expressions to such as `Instant.now()` to be used and produce correct value during stage execution
2. Allow evaluating SpEL expressions in the `EvaluateVariables` stage in order.
This allows for defining variables that depend on ones defined earlier.
3. We can now capture expressions before they are evaluated during stage execution and perform useful actions.
For example, prior to this change, it was impossible to know what was the "source" expression in the `CheckPrecondition` stage (this is especially annoying when the expression evaluates to `false`)
Now, it is possible to capture the expression and …
=> feat(expressions): Enhance expression evaluation order

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/AdminController.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/AdminControllerSpec.groovy
Adding new Admin endpoint to import execution from another spinnaker instance.
Useful to get a execution into other envs for troubleshooting.
Only imports executions with TERMINAL, SUCCEEDED or CANCELLED states.
=> feat(executions): Adding new ADMIN endpoint to import execution

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
This change makes the app notifications consistent with pipeline notifications in terms of how they are processed with SpEL
Related change: https://github.com/spinnaker/orca/pull/3311
The context wasn't being constructed properly so expression like `{execution.id}` would work in notification defined on a pipeline but not on the app.
This was because the context was `{execution: {id: ...,}}` vs. `{id: ...,}`.
This change makes the two consistent (and also consisten with all other places we use spel where context = `{execution: ..., trigger: ...,}`
=> fix(notifications+spel): follow up to #3311

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
With SpEL v4 Eval Vars calls process once for each variable, that doesn't work because .process has sideeffects and mutates context in a way that prevents it from running twice (bad, bad).
The culprit is `precomputeValues` which expands and does naughty things with the trigger. Making a copy of the context is a simple way to prevent the sideeffects
Also, as part of this i noticed that if `StartStageHandler` fails the error handling is not great and we are stuck with a zombie pipeline
=> fix(spel): make contextParameterProcess.process side-effect free

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTaskSpec.groovy, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/FindImageFromTagsTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/CFRollingRedBlackStrategyTest.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ConsumeArtifactTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/pipeline/GetPipelinesFromArtifactTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeployCloudFormationTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsServerGroupCreatorSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/gce/GoogleServerGroupCreatorSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesJobRunnerSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/tasks/artifacts/FindArtifactFromExecutionTaskSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/ArtifactExpressionFunctionProviderSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
The all-arg and no-arg constructors for Artifact and ExpectedArtifact were deprecated in spinnaker/kork#429. Replace their usages with a builder.
=> refactor(artifacts): Use builder to create artifacts

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeleteCloudFormationChangeSetTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeleteCloudFormationChangeSetTaskSpec.groovy
Clouddriver expects the credentials to be on the kato task context we
sent from Orca. That was not the case for the DeleteCloudFormationTask
so it was failing in Clouddriver.
This patch adds the credentials field so clouddriver can do the
task conversion properly.
=> fix(cfn): include credentials on the task sent to clouddriver

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/MonitoredDeployBaseTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategySpec.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java, orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/pipeline/CleanupCanaryClustersStage.kt, orca-kotlin/src/main/kotlin/com/netflix/spinnaker/orca/ext/Stage.kt
During a rolling deploy, if `scaleDown`, `notifyDeployCompleted`, or `shrinkCluster` fail and auto rollback was requested, a rollback will be performed.
This is suboptimal because you can easily argue that these operations are non-critical. In fact at this point the deploy is completed (and the old ASG is disabled).
So these are purely cleanup actions and having a perfectly good deploy fail and rollback due to a cleanup action failing is silly.
This change makes the three stages return `FAILED_CONTINUE` instead `TERMINAL` on failure thus not triggering a rollback.
The pipeline will still be marked as `FAILED_CONTINUE`
=> fix(monitored deploy): Give more leniency to scale down operations

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/EvaluateVariablesStage.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesStageSpec.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/util/ExpressionUtilsSpec.groovy
* Fix MPTv2 with SpEL v4.
The issue here was that `templateVariables.*` would need to be expanded in stages at pipeline creation.
Since this is not possible anymore, `templateVariables.*` are now added to the execution and used in the evaluation context during stage execution.
Thus the template variables are evaluated at runtime instead of creation time.
* Made SpEL v3 not deprecated (in the capabilities)
* Added description to variable in the eval vars stage
=> fix(expression): various fixes related to SpEL v4

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStageSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTaskSpec.groovy
We observed that, when a `RollbackClusterStage` was executed to rollback a failed deployment, the `DetermineRollbackCandidatesTask` was including disabled server groups when determining the target server group to rollback to, despite explicit class comments to the contrary. It did filter out disabled server groups when determining the newest server group, but not when actually determining the one to rollback to.
This was easily reproducible by creating 2 server groups `v000` and `v001` in a cluster, then disabling `v001`, then using a pipeline to deploy a new server group `v002` to the cluster. When this deployment failed, instead of rolling back to `v000`, we would rollback to the disabled group `v001`.
The fix should be self-explanatory given the context above.
Update: upon further …
=> fix(rollback): Ignore disabled server groups in automatic rollbacks

gradle.properties, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Trigger.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutator.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/model/V2PipelineTemplate.java, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutatorSpec.groovy, orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisOrcaQueueConfiguration.kt, orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueShovelConfiguration.kt, orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/pending/RedisPendingExecutionService.kt, orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueIntegrationTest.kt, orca-redis/orca-redis.gradle, orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConnectionInfo.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/notifications/RedisClusterNotificationClusterLock.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/notifications/RedisNotificationClusterLock.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/telemetry/RedisPoolMetricsPostProcessor.java, orca-redis/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepositorySpec.groovy, orca-test-redis/src/main/java/com/netflix/spinnaker/orca/test/redis/EmbeddedRedisConfiguration.java
Adjusting code for Jedis 3, Jackson 2.10 upgrades.
See spinnaker/spinnaker#5134
Dependent on spinnaker/kork#419 and spinnaker/keiko#72 for a Spring Boot dependency upgrade
=> chore(dependencies): Upgrade Spring Boot to 2.2.1

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/EnabledPipelineValidator.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorFront50Task.java, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/pipeline/EnabledPipelineValidatorSpec.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy
All calls from orca to the front50 /pipelines/id/history endpoint pass limit=1. Replace these with the new endpoint /pipelines/id/get that gets the current state of the pipeline config and does so more performantly than the history endpoint.
Requires front50 >= 2.11.0, which is when this new endpoint was added.
=> perf(pipelines): Use new endpoint to fetch pipeline config

orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/pipeline/ImportDeliveryConfigStage.kt, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt, orca-keel/src/test/kotlin/com/netflix/spinnaker/orca/keel/ImportDeliveryConfigTaskTests.kt
As discussed in https://github.com/spinnaker/deck/pull/7733, this renames the `publishDeliveryConfig` stage and associated classes to `importDeliveryConfig` for clarity, since this concept is exposed to users and from their perspective we're not publishing the delivery config anywhere, but rather pulling (i.e. importing) it into Spinnaker.
=> refactor(managed-delivery): Rename publishDeliveryConfig to importDeliveryConfig

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/GitTrigger.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/SourceCodeTrigger.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt
This adds support for other types of source code triggers to the delivery config import stage, beyond just git, by introducing a common interface for those types of triggers.
Note: while testing this, I actually found out that, because for some reason we deserialize, then re-serialize, then deserialize the trigger and/or pipeline JSON when triggering pipelines, during that second deserialization pass my new code trigger type, which is private to Netflix and looks almost the same as a `GitTrigger`, ends up getting converted to a `GitTrigger` by `TriggerDeserializer`. This doesn't have any undesired side-effects, but I thought I'd mention it because I wasn't sure this was intended behavior (the back-and-forth serialization, that is).
=> feat(managed-delivery): Add support for other types of code triggers

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/GitTrigger.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/SourceCodeTrigger.kt
I missed this in #3357 -- my bad. This is not required, but makes things cleaner.
=> refactor(trigger): Clean-up from adding SourceCodeTrigger

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/V2Util.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy, orca-pipelinetemplate/src/test/resources/integration/v1schema/dependsOn-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/example-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/exampleCombined-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/inheritance-expected.json, orca-pipelinetemplate/src/test/resources/integration/v1schema/stageReplacement-expected.json
Part of https://github.com/spinnaker/spinnaker/issues/5302
Goes in tandem with https://github.com/spinnaker/echo/pull/740
MPT V1 pipelines have a `source` field that can point to a remote resource. This PR adds to that field the version, and then uses that new version field in the V2 impl as well. This allows us to know when a pipeline execution came from either MPT V1 or V2 when collecting usage stats.
=> fix(stats): mpt tracking

Dockerfile.java8, Dockerfile.slim, Dockerfile.ubuntu, Dockerfile.ubuntu-java8
Reverts spinnaker/orca#3367
Java 11 has issues with kork's `PluginLoader`.
=> Revert "chore(java11): Switch the default containers to use Java 11."

orca-core/src/main/java/com/netflix/spinnaker/orca/NamedThreadFactory.java, orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/AbstractPollingNotificationAgent.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/config/OrcaQueueConfiguration.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/NoopQueue.kt
There must've been a regression where the queue can no longer really be disabled. If it is,
orca will fail to start due to missing bean.
Adding a `NoopQueue` that is created when the queue bean is missing.
Also, removing Rx from `PollingNotificationAgent` and making it so that the first invocation starts
without a delay and all subsequent invocations are delayed from the prior run's completion time
=> fix(queue): Allow execution without a queue + polling agent cleanup

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.kt
Fix dual exec repository to dedupe results it returns since completed executions can/will live in both old and new repos during migration
=> fix(execution repo): dedupe in DualExecutionRepo

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/admin/web/QueueAdminController.kt
Adds two endpoints:
1. Generic endpoint to post any message into the queue
2. A simplified EP to specifically post `StartWaitingExecutions` into the queue
=> feat(admin): Add queue admin EPs

orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/ExecutionLatch.kt
The test are starting to fail quite frequently with an assertion failure "Pipeline did not complete".  This is because we assert that an execution has started within 5 seconds of requesting it, which appears to fail frequently when running in constrained CPU environments.
Double the timeout to 10 seconds to alleviate the issue, though a better fix would probably be to avoid having an arbitrary timeout at all.  (Perhaps the test function would wait until the queue is quiescent before proceeding?)
=> fix(test): Fix flaky queue integration test

orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/AbstractPollingNotificationAgent.java
[`ThreadFactoryBuilder`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/util/concurrent/ThreadFactoryBuilder.html) supports named threads, but also has additional options that we may want to use in the future. I think guiding people towards that is preferred...
=> chore(kork): use Guava's ThreadFactoryBuilder instead of NamedThreadFactory

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtils.java
* refactor(artifacts): Simplify error handling of incorrect StageContext 
Two functions log a warning and return a default value if the input StageContext is not of the correct type. Instead of putting the entire (or bulk of the) function in an if/else block, just check the desired condition and return early if it fails, pulling the rest of the function out of the if/else block.
In the case of getBoundArtifactForId, just return null early rather than process an empty list that will eventually return null when nothing matches.
* refactor(artifacts): Clean up stream code in ArtifactUtils 
A lot of stream code is overly nested, primarily because it mixes Optional.map() with Stream.map() and needs to reach into the Optional. Instead use the simpler null-safe stream pattern: …
=> refactor(artifacts): Some minor cleanup of artifact handling

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTest.java
* test(execution): Add tests to START_TIME_OR_ID 
The next commit will fix a bug in the START_TIME_OR_ID comparator; add tests to document the current behavior and ensure that the bug fix only affects the intended case.
* fix(execution): Fix START_TIME_OR_ID comparator 
I noticed that the START_TIME_OR_ID comparator violates the general contract of Comparator in the case where one of hte executions has a null start time. I haven't noticed this causing actual bugs, but I think the failure mode would be intermittent cases of
"Comparison method violates its general contract" being thrown when trying to sort based on this comparator, which would be annoying and hard to debug, so fixing this now.
=> fix(execution): Fix START_TIME_OR_ID comparator

orca-web/config/orca.yml, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/config/PreconfiguredWebhookSpec.groovy, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStageSpec.groovy
This fixes spinnaker/spinnaker#5220.
The frontend already contains the changes needed to support "Signal on cancellation" but the PreconfiguredWebhook was missing the properties.
=> fix(webhook): Add cancel to PreconfiguredWebhook

.editorconfig, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoService.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/MonitorJobTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryMonitorKatoServicesTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTaskSpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryMonitorKatoServicesTaskTest.java
In the past, we would retry the `MonitorKatoTask` with fairly complicated logic of checking if it was a replica or a master we got the 404 from.
This change simplifies that by retrying a whole bunch (always from read replica).
Other than basic resilience, this is needed if/when one performs a clouddriver database migration.
The situation is as follows:
- the old clouddriver cluster is pointing to the old db
- the new clouddriver cluster is pointing to the new and old db so it can serve getTask requests in either DB
- during the deploy (with 0 downtime) both old and new will be in the load balancer taking traffic from orca.
- if an orca request creates a task in new clouddriver but then hits monitor on the old clouddriver it will fail with a 404
Instead of making the old cluster aware of …
=> fix(monitor kato): Retry MonitorKatoTask more aggressively

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/WaitStage.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/WaitTask.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/WaitTaskSpec.groovy
Noticed that when I restarted a WaitStage it didn't actually wait.
That's because it caches the stage `startTime`.
Not sure why it does since the stage should have actual start time the time the task runs, so making the wait task use that instead of caching it's own time.
=> fix(wait stage): Make wait stage restartable

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/PatchManifestStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestEvaluator.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PatchManifestTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolvePatchSourceManifestTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesJobRunnerSpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestEvaluatorTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryDeployServiceTaskTest.java
The goal of this refactor is to make Orca's input manifest resolution easier to reason about so that we can enhance it with [label filtration](https://github.com/spinnaker/spinnaker/issues/3695).
- **refactor(kubernetes): add tests for ManifestEvaluator**
Adds tests documenting the functionality of `ManifestEvaluator.evaluate` to ensure we don't break anything in the next commit.
- **refactor(kubernetes): clean up ManifestEvaluator**
Divides the functionality of `ManifestEvaluator.evaluate` into private methods responsible for a single bit of work. Adds immutability and cleans up streams where possible.
- **refactor(kubernetes): move task-specific ManifestEvaluator logic to tasks**
Removes `ManifestEvaluator.buildTaskResult`, which makes a call to Clouddriver to initiate a task and …
=> refactor(kubernetes): clean up source manifest resolution

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AddServerGroupEntityTagsTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AddServerGroupEntityTagsTaskSpec.groovy
We don't actually handle returning `SKIPPED` for status here. It makes it so the stage always fails because `SKIPPED` isn't a valid status. I choose to return `SUCCEEDED` because there were 0 tags, so it's a success. I don't think that tags are required for all spinnakers so i don't think it's correct to fail the stage if there are no tags.
=> fix(stage): entity tags task succeeds

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/AwsCodeBuildExecution.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/AwsCodeBuildStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/AwsCodeBuildStage.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorAwsCodeBuildTask.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartAwsCodeBuildTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/pipeline/AwsCodeBuildStageSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorAwsCodeBuildTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartAwsCodeBuildTaskSpec.groovy
Add a new stage to trigger AWS CodeBuild builds. For now, it only accepts project name as input and triggers build based on the project name. Support for source and artifact overriding will come later.
Related Issue: spinnaker/spinnaker#5292
=> feat(codebuild): Add AWS CodeBuild stage

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/CIStageDefinition.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildArtifactsTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildArtifactsTaskSpec.groovy
The presence of a property file should not affect whether or not artifacts should be added to the output. The Travis and Wercker integrations in Igor don't even care about this property, and the Jenkins integration also works even if the property file is null or blank.
This will also copy artifacts already present in the `buildInfo` to the stage context, to be more in line with CI triggers (where this already happens).
This fix makes it possible to use the "Find Artifacts from Execution" stage with Travis and Wercker, as well as increasing the usability for use with Jenkins.
=> fix(ci): Properly set artifacts on CI stage output

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/AwsCodeBuildStage.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetAwsCodeBuildArtifactsTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetAwsCodeBuildArtifactsTaskSpec.groovy
AWS CodeBuild is able to produce multiple artifacts to S3 location
as defined by users in their project configuration. However, these
artifacts are not visible to downstream stages, since they are not
Spinnaker artifacts. The two tasks added in this PR will fetch S3
location from CodeBuild and then bind it to the stage output, which
allows downstream stages to consume it as needed.
=> feat(codebuild): Bind artifacts produced by CodeBuild

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/ExecuteCloudFormationChangeSetTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/WaitForCloudFormationCompletionTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/ExecuteCloudFormationChangeSetTaskSpec.groovy
By default empty cloud formation changeSets are deleted to keep things tidy. 
There is an unexpected behavior when the user has the executionChangeSet flag enabled and uploads an empty changeSet, the changeset gets deleted and then tries to be executed, causing the stage to fail as the changeSet cannot be found anymore.
This change skips the execution when s a previous changeSet deletion (empty changeSet) is found.
It covers the most used case as we allow to apply empty cloud formation changesets from git and if there are no infra changes proceed with the application deployment without any failure.
=> fix(aws/cloudformation): Stage won't try to execute deleted change sets.

Dockerfile.slim, Dockerfile.ubuntu
This creates the default plugins directory so plugins can be downloaded and placed locally. I needed to add the spring.application.name in gradle.properties as well, otherwise plugins would fail to start when running in a container.
=> chore(plugins): adding plugins dir and application name

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTaskSpec.groovy
Changing the calculation for determent the number of healthy clusters from ceiling to round.
=> fix(clusterCalc): changing ceiling calculation to round for healthyDeployPercentage

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTaskSpec.groovy
This is a regression from #3441.
It prevents waiting for 0 instances which is a valid scenario in rolling style deploys.
This should've been caught by a unittest, but the unit tests had a bug which hid this issue (fixed now)
=> fix(wait for up): Fix to allow waiting for 0 instances

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java
Parts of https://github.com/spinnaker/spinnaker/issues/5474
This add `HELM3` as valid template renderer type.
=> feat(rosco): Add HELM3 Template Renderer

orca-peering/README.md, orca-peering/src/main/kotlin/com/netflix/spinnaker/config/PeeringAgentConfigurationProperties.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt, orca-peering/src/test/groovy/com/netflix/spinnaker/orca/peering/PeeringAgentSpec.groovy, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgent.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/TopApplicationExecutionCleanupPollingNotificationAgent.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-sql/src/main/resources/db/changelog-master.yml, orca-sql/src/main/resources/db/changelog/20200221-partition-name-table.yml, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgentSpec.groovy, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepositorySpec.groovy
This change adds three fixes for peering:
* Once a partition is set on the cluster/db it should never be changed (this is likely a misconfiguration issue)
* Added `where` clause to the pipeline/execution cleanup agents to only clean up executions in it's own partition (if one is set)
* Added prevention to not accidentally delete ALL executions during peering
=> fix(peering): disallow changing partition name and fix cleanup agents

orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionRunner.java, orca-interlink/src/main/java/com/netflix/spinnaker/config/InterlinkConfiguration.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/aws/InterlinkAmazonMessageHandler.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/CancelInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/DeleteInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/InterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/PauseInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/ResumeInterlinkEvent.java, orca-interlink/src/test/groovy/com/netflix/spinnaker/orca/interlink/InterlinkSpec.groovy, orca-interlink/src/test/groovy/com/netflix/spinnaker/orca/interlink/aws/InterlinkAmazonMessageHandlerSpec.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy
For some actions (like cancel, resume, pause), it is not sufficient to invoke the correspond execution repository call, we also need to create some events on the message queue (e.g. to actually cancel running tasks).
The task controller already has the logic to update both the queue and the execution repo, so I'm lifting some of it in a common but somewhat awkwardly named CompoundExecutionOperator. As a result, the same logic will be executed by the task controller and interlink events.
=> fix(interlink): apply events to a queue+repo operator

orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/MySqlRawAccess.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/SqlRawAccess.kt, orca-peering/src/test/groovy/com/netflix/spinnaker/orca/peering/PeeringAgentSpec.groovy
For historical reasons, `partition=null` is set on all current executions (since sqlrepo runs without a partition).
So when checking if an execution is local we need to check if `parition == MY_PARTITION` OR `partition is null`.
However, this check is not correct when copying from the peer. From the peer we need to get `partition == peerId or partition is null`,
but locally it must always be `partition == peerId` because we force set the partition during copy.
Without that we would think that we need to delete all our local executions since they would not show up in the peer query
This change fixes this issue
=> fix(peering): Don't use `null` partition on local db during peering

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java
This change unrolls the recursion of the `getAncestorImpl` call into an imperative call.
getAncestors is actually called A TON! (especially since all `context.get` evaluations depend on it).
If the execution depth is large (e.g. canary with many stages) this call can take a while and, in some cases, throw a StackOverflow excetion.
Additionally, I added some logic to cache the `getAncesors` calls in the expression evaluation as it can't change
For context: `getAncestors` is executed 64 times for a simple wait stage execution
Results:
Time for `getAncestors` was reduced by a factor of 7x (1000 executions on 100 stage pipeline went from 7.2s to 0.9s)
Furthermore, due to caching the number of calls to `getAncestors` is reduces by ~3 (from 64 to 19)
So a total improvement time about 21x
As …
=> fix(perf): Make `getAncestors` call faster

orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy
This is causing a compilation failure in the kork bump since this class
was deleted.
=> chore(plugins): remove an unused import

orca-keel/orca-keel.gradle, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/KeelService.kt, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt, orca-keel/src/test/kotlin/com/netflix/spinnaker/orca/keel/ImportDeliveryConfigTaskTests.kt
Include detailed error information added to keel in https://github.com/spinnaker/keel/pull/821 so it can be displayed in the UI.
Another piece to https://github.com/spinnaker/keel/issues/818
=> feat(managed-delivery): Include detailed error info in ImportDeliveryConfig

Dockerfile.java8, Dockerfile.ubuntu-java8
This was waiting on the removal of a `kork` `PluginLoader` class that
wasn't compatible. It was removed in spinnaker/kork#528 and #3476
=> chore(java11): Switch orca to use the Java 11 JRE

orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt, orca-peering/src/test/groovy/com/netflix/spinnaker/orca/peering/PeeringAgentSpec.groovy
If there are no "newly" completed executions to peer the peering agent would never peer active executions.
The reason was that that the "lastUpdated" timestamp wouldn't be updated if there was nothing completed to peer so it would sit at 0 indicating it's always first run
This change fixes that (and also fixes the tests)
=> fix(peering): Peer if there are no (newly) completed executions to peer

orca-validation/orca-validation.gradle
This also changes the organization from [fge](https://github.com/fge) to [java-json-tools](https://github.com/java-json-tools), as the former is retired. Avoids v2.2.6's references to Guava versions with known CVEs. Addresses https://github.com/spinnaker/spinnaker/issues/5523
=> fix(orca-validation): Update json-schema-validator to 2.2.12.

halconfig/README.md, halconfig/orca-bootstrap.yml, halconfig/orca.yml, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/config/BakeryConfigurationProperties.java, orca-web/config/orca.yml
See spinnaker/clouddriver#4368 for more details; this is making the same changes to orca.  I'll hold off on doing more services until everyone has weighed in on these two PRs, but if all looks good I'll make the same changes to all other services.
* config(core): Push halyard config defaults down to base 
This change pushes a number of config settings that were in the Halyard-specific config file down to the base config so they apply to all uesrs.
The one potentially breaking change is that echo used to default to disabled but now defaults to enabled. Given that most users use Halyard and netflix uses echo, I suspect that nobody was relying on this to default to off. We can document this as a change in the release notes (as it's easy to override if desired).
* config(core): Update bakery …
=> config(core): Push halyard config defaults down to base

orca-api/src/main/java/com/netflix/spinnaker/orca/api/preconfigured/jobs/PreconfiguredJobStageProperties.java, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
`basic` will cause Deck to register the default preconfigured job stage config UI (which renders inputs for each parameter).
=> feat(preconfiguredjob): Add 'ui' field to PreconfiguredJobStageProperties

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperator.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperatorSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/ExecutionSpec.groovy, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/aws/InterlinkAmazonMessageHandler.java
When manually cancelling an execution handled by a different orca cluster, we want to let the execution repo handle it. Also pushing messages on the queue for that foreign execution was an oversight, and it led to duplicate interlink messages getting published.
=> fix(queue): avoid pushing message for foreign execution

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/OrcaMessageHandler.kt
To aid debugging further an issue where the stage that should've been there was not
=> fix(logging): add logging for when we can't find the stage

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/gce/GoogleServerGroupCreator.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CreateServerGroupTaskSpec.groovy
* fix(google): Fix race condition in wait for up instances task 
There was a failure in the google_regional_server_group test this morning where the WaitForUpInstancesTask unexpectedly returned a status of TERMINAL.
After digging into this, it appears that what happenned is the following:
* The MonitorKatoTask earlier in the pipeline is supposed to wait for the deploy to finish, and the record certain details about the deployment in the stage context. In this case, the important field is the "deploy.server.groups" field, which should contain a list of server groups deployed.
* In this particular case, the MonitorKatoTask found that the clouddriver task had completed, but looking in the stage context it was missing two entries from the task history (including the final "Orchestration …
=> fix(google): Fix race condition in wait for up instances task

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/config/BakeryConfigurationProperties.java
The commit to clean up the config file by pushing some config down to code accidentally changed the default value of roscoApisEnabled. This was set as true in orca.yml, but I forgot to flip the default to true in code when removing the value in orca.yml, which ended up being a breaking change.
This change flips the default value of the boolean to true in code, restoring the deafult to what it was prior to the earlier change.
=> fix(config): Fix accidentally changed bakery config

.github/workflows/build.yml
Master build is failing and I noticed this was disabled previously (in TravisCI), so let's give it a shot.
=> fix(build): skip test in master build

orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/MySqlRawAccess.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/SqlRawAccess.kt
using `in` instead of `not in` is more performant and should shave ~15% of our running execution peering time
(ad hoc profiling showed the query going from 4s to about 1s)
=> fix(peering): minor perf improvement for peering

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/StageExecution.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/StageExecutionImpl.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperatorSpec.groovy, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/aws/InterlinkAmazonMessageHandler.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/InterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/PatchStageInterlinkEvent.java, orca-interlink/src/test/groovy/com/netflix/spinnaker/orca/interlink/InterlinkSpec.groovy, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlPipelineExecutionRepositorySpec.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy
Some operations like skip wait or manual approvals result in calls to
PATCH /pipelines/pipelineId/stages/stageId
with a context map values used to augment the designated stage context. The TaskController also updates the stage's `lastModified` field with user and account information, so that manual approval stages can be used to propagate auth info. This is all great as long as we operate on local executions, but for foreign executions (owned by a different orca cluster), we can't just patch read-only stages.
To support this, we:
- make `ExecutionRepository::storeStage` foreign-aware
- for foreign executions, we create a `PatchStageInterlinkEvent` (if supported) that contains the body of the stage
- the stage body includes the updated context map values and `lastModified` information
- we …
=> feat(interlink): patch stage support for foreign executions

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgent.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/TopApplicationExecutionCleanupPollingNotificationAgent.kt
resolves https://github.com/spinnaker/spinnaker/issues/5583 which is a regression of https://github.com/spinnaker/orca/pull/3461/files
don't require partition names in cleanup agents
=> fix(cleanupagents): fix for issue #5583

orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
When using Redis as the execution repository, the spelEvaluator field of
the Execution object was not serialized or deserialized.
This change adds the field to the object stored in Redis, and reads it
back out when deserializing an Execution object.
=> fix(execution): Persist `Execution.spelEvaluator` in Redis

gradle.properties
The bump dependencies workflow failed, so this one is being done manually.
=> chore(kork): Bump kork version

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionRunner.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/CancelInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/DeleteInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/InterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/PauseInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/ResumeInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/StartPendingInterlinkEvent.java, orca-queue/orca-queue.gradle, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueExecutionRunner.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandlerTest.kt
Imagine this scenario with peering:
* orca `peer A` is running execution `E1`
* a request (from `deck`) comes into orca `peer B` to start execution `E2`
since an execution (`E1`) is already running, `peer B` queues `E2`
* `peer A` completes `E1` and checks if there are any pending executions
* since the pending table is not peered (that would be basically impossible to get right) `peer A` doesn't see any pending executions
* and so `E2` stays forever in a "pending" state
There were a few thoughts on how to fix this:
1. Pending execution agent
2. Use dual pending execution service
3. Peering pending executions table
4. Handle this in the peering agent when it peers completed executions
5. Use interlink
Basically, all of these approaches are flawed and interlink seems least problematic: …
=> fix(peering): Trigger pending executions across orca peers

orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/MessageFlagger.kt
Follow up to my incorrect fix https://github.com/spinnaker/orca/pull/3537.
Since multiple threads run the `MessageFlagger::process` we need to make sure all `queue` is inside a lock of some sort.
=> fix(messageflagger): better thread safety

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesJobRunner.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesJobRunnerSpec.groovy
Fixes spinnaker/spinnaker#5562
The Kubernetes V2 Run Job stage doesn't bind artifacts if the manifest source is text. This is because we only populate artifacts if the source is an artifact; luckily the logic to populate artifacts is independent of the aritfact source, so we can run it in either case by just removing the if condition.
=> fix(kubernetes): Fix artifact binding for run job

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineExpressionFunctionProvider.java
I don't think it's a good idea to throw an exception when a pipeline does not exist, because exceptions cannot be handled in Spinnaker Expressions.
We should just return `null`, and let the user decide what to do with that
=> feature(Pipeline Expressions): add pipelineIdOrNull SpEl helper function

orca-api/api.md, orca-api/orca-api.gradle, orca-api/src/sample/java/preconfiguredjob/PreconfiguredJobStageSample.java, orca-api/src/sample/java/simplestage/SimpleStageSample.java, orca-api/src/sample/resources/preconfiguredjob/treasure.yml
Working through getting docs and examples in place. Nice thing about this strategy of putting samples in the service repos themselves is that we'll be able to ensure they continue to compile and (eventually) continue to pass unit tests. My intention is that these samples will function as both examples of basic usage as well as functional contract tests for every extension point exposed.
The docs are generated through Dokka. I'll be working on emitting the Jekyll format so we can export these artifacts into the spinnaker.io website every release.
=> docs(api): Initial samples and some more api docs

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesTask.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesTaskSpec.groovy
it's possible to consruct a pipeline with bad eval vars stage context as follows (both in UI and by hand):
```
"type": "evaluateVariables",
"variables": [
{
"key": "a",
"value": 1
},
{
"key": null,
"value": null
}
]
```
This causes an exception inside the exception handler of `RunTaskHandler`.
This fix strips out invalid variable keys
=> fix(evaluate variables): handle null/empty variable keys

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperator.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/CancelInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/DeleteInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/InterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/PatchStageInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/PauseInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/ResumeInterlinkEvent.java, orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/pending/RedisPendingExecutionService.kt, orca-queue-sql/src/main/kotlin/com/netflix/spinnaker/orca/q/sql/pending/SqlPendingExecutionService.kt, orca-queue/orca-queue.gradle, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/pending/DualPendingExecutionService.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/pending/InMemoryPendingExecutionService.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/pending/PendingExecutionAgent.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/pending/PendingExecutionService.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/pending/DualPendingExecutionServiceTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/pending/PendingExecutionAgentTest.kt
Introduces a pending execution agent which kicks off executions in the pending state.
Normally, such executions will be started by the act of completing a pipeline.
However, when there is a waiting execution in a different orca DB from where the current pipeline completed
it doesn't work.
With this change there is an agent that runs every ~15s (configurable) to see if there are any pending executions
which need to be kicked off and if so, kicks them off.
This is a continuation of failed attempt at implementing such functionality here:
https://github.com/spinnaker/orca/pull/3544
=> feat(peering): Pending Executions Agent

orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/ExecutionCopier.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/MySqlRawAccess.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/SqlRawAccess.kt
A big chunk of time was spent storing all stages of running executions.
This is not necessary because most of those stages don't change (only about 8% change with ~30s agent interval)
Only store stages that have a different `updated_at` timestamp (or those that don't exist).
This improves peering performance by about 25%
=> perf(peering): improve peering perf

gradle.properties
This causes a weird NPE in Gradle that manifests like this:
```
$ ./gradlew :orca-api-test:dependencies --configuration runtimeClasspath
Execution failed for task ':orca-api-test:dependencies'.
> Could not resolve all dependencies for configuration ':orca-api-test:runtimeClasspath'.
> Problems reading data from Binary store in /tmp/gradle731362267057772455.bin (exist: true)
```
Regular builds pass, so the PR GHA build suceeds, but turning on `-PenablePublishing=true` causes a failure, so the Debian builds and the post-merge GHA builds fail.
@robfletcher is working on a fix, but I'll rollback in the meantime.
=> chore(dependencies): roll back the most recent kork bump

build.gradle, orca-clouddriver/orca-clouddriver.gradle, orca-front50/orca-front50.gradle, orca-integrations-cloudfoundry/orca-integrations-cloudfoundry.gradle, orca-test-groovy/orca-test-groovy.gradle
@rpalcolea
Kotlin version was bumped here -- https://github.com/robfletcher/strikt/compare/v0.24.0...master
Which also added a new module.  Current theory is that this new module comes in and tries to add kotlin `1.3.71` which results in a dependency conflict resolution error when the following task runs:
```
./gradlew -PenablePublishing=true :orca-api-test:generatePomFileForNebulaPublication
```
Anyways, this will resolve the branch build failure and also resolve the composite build failure we see in our `-nflx` builds.
=> fix(build): Bump kotlin version to 1.3.71

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java
Closes https://github.com/spinnaker/spinnaker/issues/4737, https://github.com/spinnaker/spinnaker/issues/5533
Helm `inputArtifacts` have unfortunately never worked with `artifactsRewrite` enabled: we are unconditionally overwriting the resolved artifact's account with the unresolved input artifact's account (which will always be empty if configured with `artifactsRewrite`). Let's only overwrite the resolved artifact's account when there is a non-empty account defined on the input artifact (in other words, when it was configured with `artifactsRewrite` disabled).
I think we should cherry-pick this back into each supported release given the number of users who have commented on the first issue linked above.
=> fix(bakery): only conditionally override input artifact account in CreateBakeManifestTask

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/InMemoryExecutionRepository.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/MySqlRawAccess.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringMetrics.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/SqlRawAccess.kt, orca-peering/src/test/groovy/com/netflix/spinnaker/orca/peering/PeeringAgentSpec.groovy, orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/telemetry/RedisInstrumentedExecutionRepository.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/AbstractCleanupPollingAgent.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgent.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/TopApplicationExecutionCleanupPollingNotificationAgent.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-sql/src/main/resources/db/changelog-master.yml, orca-sql/src/main/resources/db/changelog/20200327-deleted-executions-table.yml, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgentSpec.groovy
Currently, in order to detect deletes, we need to perform a period FULL diff of the DB. This is EXTREMELY expensive and causes peering delay to be inconsistent.
This change adds what is essentially a log of all "recent" deletes into the new `deleted_executions` table.
The peering agent can then scan that table (remembering the last known "deletion" id) and delete all executions listed in the table.
Deletes older than some time (e.g. 2days) are cleaned up from the table during a delete.
Because execution deletes are now more complicated (need to add a row into the `deleted_executions` table) I had to change how cleanup agents work (in order not to duplicate the deletion code).
While there, I refactored them a little to extract [some] of the common functionality.
=> fix(peering): Improve peering of deletes

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/graph/TaskNode.java, orca-api/src/main/java/com/netflix/spinnaker/orca/api/simplestage/SimpleTaskDefinition.java, orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResolver.java, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/SimpleStageDefinitionBuilder.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/SimpleTask.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Multiple SimpleStages keeps Orca from starting because SimpleTask had a Component annotation and took a SimpleStage in its constructor. Orca would try to construct all the Tasks for taskResolver and when it got to SimpleTask it wouldn't know which SimpleStage to inject. So SimpleTask obviously shouldn't be a Component. But once the Component annotation was removed SimpleStages would not execute.
The TaskResolver now needs to load all the SimpleStages and wrap each one in a SimpleTask. They need to be keyed by the SimpleStage impl class name, they can't all be keyed as a SimpleTask. But you could only use classes of type Task to refer to them in the task graph, even though it ultimately just gets turned into a String. I made some modification to stick the SimpleStage impl name in the task …
=> fix(plugins): allow more than one SimpleStage impl

orca-core/src/main/java/com/netflix/spinnaker/orca/DefaultStageResolver.java, orca-core/src/main/java/com/netflix/spinnaker/orca/DynamicStageResolver.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/StageResolver.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/StageNavigator.java
Stage resolver requires alias to be passed in if present on the stage context to resolve the builders.
=> Fix stage resolver

orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt, orca-peering/src/test/groovy/com/netflix/spinnaker/orca/peering/PeeringAgentSpec.groovy
This fixes an issue where when there are no [new] completed executions to copy to the peer the peer would reset its "lastUpdated" timestamp causing a full diff on the DB next peering cycle.
Instead, we should just leave the "lastUpdated" timestamp unchanged. Also, fixed the test that didn't but should've exposed this issue (the test was incorrect)
=> fix(peering): don't reset lastUpdated time if there is nothing to copy

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java
The default error message here is confusing.  This is purely a clarification to the error message.
=> chore(bakeManifest): Update BakeManifest error when missing expectedArtifact

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy, orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListenerSpec.groovy
Simple PR to add `stage.id` to Echo event payload so that user can trace back which stage the event is coming from.
Closes https://github.com/spinnaker/spinnaker/issues/5660
=> feat(echo): Add stageId to Stage Event Details

orca-core/orca-core.gradle, orca-front50/orca-front50.gradle, orca-integrations-gremlin/orca-integrations-gremlin.gradle, orca-retrofit/orca-retrofit.gradle
An upcoming kork bump will remove some things that were api dependencies and make them implementation; update places that were relying on these to explicitly include them.
The places where groovy is added as an API dependency is because there are classes that due to groovy magic subclass a groovy type, so consumers need core groovy on the classpath.
=> refactor(core): Clean up dependencies

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PatchManifestTask.java
Prior to [this refactor](https://github.com/spinnaker/orca/pull/3402), PatchManifestTask read patchBody directly from the ManifestEvaluator's result. Now, we are attempting to read it off the stage's context, but we deserialized the context with the same model, PatchManifestContext, that we used to deserialize the initial stage inputs, which tries to read manifests from patchBody (at this point, we should be reading manifests from the manifests key instead). This is intended to be a cherry-pickable fix, but a better more invasive fix would define different models for the inputs and outputs of each task and assert that the context had required values before beginning the task.
=> fix(kubernetes): correctly write Patch Manifest patchBody (#3602)

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolvePatchSourceManifestTask.java
The patch manifest stage was incorrectly setting allArtifacts to just the required artifacts, which was breaking artifact resolution in clouddriver. Set this to all of the artifacts (both required and optional).
=> fix(kubernetes): Fix artifact binding in patch manifest stage

orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy
Aligning usage of `@SpringBootApplication` with how I've been doing it in Echo and Gate.  Also, removes the deleted package `com.netflix.spinnaker.plugin`.
=> chore(*): Cleanup Main Spring configuration

orca-sql/src/main/kotlin/com/netflix/spinnaker/config/OldPipelineCleanupAgentConfigurationProperties.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/config/TopApplicationExecutionCleanupAgentConfigurationProperties.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgent.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/TopApplicationExecutionCleanupPollingNotificationAgent.kt, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgentSpec.groovy
No functional change here, just move `@Value`s on the two cleanup agents to `ConfigurationProperties`
=> chore(pollers): add configuration properties

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-sql/src/main/resources/db/changelog-master.yml, orca-sql/src/main/resources/db/changelog/20200424-index-deleted-executions-table.yml
In my prior change (https://github.com/spinnaker/orca/pull/3569) I introduced a concept of a `deleted_executions` table to keep track of ~1day worth of deletes so that peering has much easier time to peer deletes.
This change causes the deletion of executions to fail sometimes because of a SQL deadlock.
To fix it:
1. Add an index on `deleted_at` - this column is used to delete executions older than `x` time
2. Take the truncation of the `deleted_executions` table out of the big delete transaction
=> fix(delete): Add index and chunk deletes of old executions

orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationExecutionCleanupPollingNotificationAgent.java, orca-keel/src/test/kotlin/com/netflix/spinnaker/orca/keel/ImportDeliveryConfigTaskTests.kt
A few standard things I've seen other places:
1) Java 11 is stricter about type constraints
2) Java 11 returns `Instants` with nanoseconds when using `Instant.now()` and friends.
=> fix(java11): Fix some issues that occur when running under Java 11

.github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/release.yml, Dockerfile.compile, orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/graph/StageDefinitionBuilder.java, orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/Stages.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/AbortStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
* chore(java11): Compile with Java 11 (but targeting Java 8)
release.yml looks scary in the GitHub diff view, but it's mostly indentation changes, and one other unrelated changes (removing two redundant If conditions) that already exist in every other repository. It's just copied from clouddriver.
* fix(java11): don't compare times with nanoseconds to those with millis
* fix(java11): Define getType for all anonymous StageDefinitionBuilders
Under Java 11, Class#getSimpleName() returns the empty string for an anonymous object literal. I verified that these are the only places in the entire codebase where we have an anonymous definition of StageDefinitionBuilder that doesn't override getType().
=> chore(java11): Compile with Java 11 (but targeting Java 8)

orca-integrations-gremlin/src/main/java/com/netflix/spinnaker/orca/config/GremlinConfiguration.kt, orca-web/config/orca.yml
The feature flag for gremlin was removed from deck (along with a number of other feature flags) in 1.20 but we missed that this flag was also checked in orca. This change removes checking the flag in orca (and removes setting the flag in orca.yml).
As orca.yml already sets the base url, we don't need to default the Value using it (though in the future maybe it's better to push the defaulting to there rather than have it in the default config).
=> fix(gremlin): Fix gremlin config

.github/workflows/release.yml
Release build has been failing with connection timeouts to bintray, let's see if this resolves that.
=> fix(build): 2 minute Gradle HTTP client socket and connection timeout

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java
Simplifies save pipeline behavior.
Gate sends the pipeline as base64, but when doing local development, it's annoying to take pipeline JSON and feed it into base64 before sending it into the API. This change will allow both base64-encoded pipelines, as well as raw JSON-defined.
It also optimizes the base64 path, which was decoding the full pipeline twice.
=> refactor(front50): Allow non-base64 encoded pipelines

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/SetPreferredPluginReleaseStage.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SetPreferredPluginReleaseTask.java, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SetPreferredPluginReleaseTaskSpec.groovy
We have a way to trigger pipelines when plugins are published into Spinnaker. This will allow us to set the preferred version of a plugin as part of that pipeline. Workflow kinda like:
```
Trigger(new plugin, preferred=false) 
-> Manual Judgement 
-> SetPreferredPluginVersion 
-> Trigger service redblack (for each required service)
```
This will allow teams to develop plugins and publish them as they see fit, and Delivery Engineering will get notifications of the newly published plugins, we can review them, and optionally approve them. When approved, the preferred version (the one that will actually get installed by services) will be updated to the newly published plugin and then service deployments will be triggered.
=> feat(plugins): Add stage to set preferred plugin version

halconfig/README.md, halconfig/orca.yml, orca-web/config/orca.yml
In #3482, I pushed some Halyard configs down to the base to prepare for kleat, which will not use the halconfig values.
As work on kleat has continued, I realize that we reading the port and bind address from spinnaker.yml is not a great idea and not something that I want to encourage in kleat. The decision of what port to listen on and what address to bind to is a decision that should be internal to that service and make in its config file; its externally visible URL is something external that other services should care about (and that should be in a common config file).
So let's revert the part of this that sets the port/address based on what's in the spinnaker.yml file; there is no real use case for overriding this in kleat so let's not over-complicate the base config without a clear …
=> fix(config): Clean up base config

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt
During, say a failover, we need to be able to take over ownership of an execution previously owned by a different orca cluster.
This fix allows us to actually do that
=> fix(sqlrepo): Update execution partition

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/AwsCodeBuildExecution.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorAwsCodeBuildTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartAwsCodeBuildTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StopAwsCodeBuildTaskSpec.groovy
Adding exported environment variables in the stage context would allow end users to consume the environment variables exported from CodeBuild build stage by specifying a pipeline expression like `${#stage('AWS CodeBuild')['context']['buildInfo']['exportedEnvironmentVariables']}`.
This PR addressed feature request https://github.com/spinnaker/spinnaker/issues/5686
=> feat(codebuild): Add exported environment variables in the stage context

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoService.groovy
We see a few operations per day seemingly fail for network reasons but actually be submitted and executed successfully.
This change adds a retry around the operation submission - if a duplicate operation is submitted, clouddriver will just return the prior one so this is safe.
=> fix(clouddriver): Retry submitting clouddriver operations

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/artifacts/ConsumeArtifactTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestEvaluator.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AppEngineServerGroupCreator.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeployCloudFormationTask.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtils.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtilsTest.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTask.java
Artifacts will soon become immutable to eliminate the confusion about whether mutating an artifact is actually updating the artifact on the pipeline. This is confusing because we very often use objectMapper.convertValue() on artifacts to convert back and forth between maps. It is thus far from clear whether a mutation at any given point is acting on a copy of the pipeline artifact or the artifact itself.
This commit updates places that mutated artifacts to instead return a copy. In all cases this is setting the account for legacy workflows that have this specified separately from the artifact itself. We should not be adding more of these, and ideally these would at some point be migrated to use the new workflow of having the account specified on the artifact.
In all cases updated here …
=> refactor(artifacts): Update places that mutate artifacts

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/EvaluateVariablesStage.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExpressionAwareStageDefinitionBuilder.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesStageSpec.groovy
When I implemented SPeLv4 (#3286) I introduced an issue where context keys that weren't part of `EvaluateVariableStage` didn't get processed.
This means that, for example, expressions in stage `notifications` wheren't processed an one could no longer specify an email as, say, `${parameters.email}`.
This change fixes the issue by introducing a helper method that runs all context values through the `ContextParameterProcessor` which aren't specially processed by the stage it self
This change correctly addresses https://github.com/spinnaker/spinnaker/issues/5697 and we will be able to revert https://github.com/spinnaker/echo/pull/869 which introduced a regression in RestEventListener
=> fix(spel): Process all entries for evaluate variables with SPeLv4

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartAwsCodeBuildTask.java
I'm working on better encapuslating artifacts, and one change is removing direct access to the map of metadata via .getMetadata() in favor of having clients specifically ask for keys via getMetadata(String key). In addition to hiding the implementation from clients, this usually also simplifies client code as generally client code first checks that the metadata map is not null then checks a specific key.
This updates the one place in orca where we were fetching the full metadata map to instead look up the desired key.
=> refactor(artifacts): Update call to getMetadata

orca-peering/orca-peering.gradle, orca-peering/src/main/kotlin/com/netflix/spinnaker/config/PeeringAgentConfiguration.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/CustomPeerer.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/MySqlRawAccess.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringMetrics.kt, orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/SqlRawAccess.kt, orca-peering/src/test/groovy/com/netflix/spinnaker/orca/peering/PeeringAgentSpec.groovy
This change adds an extension point (in the form of beans injected into the `PeeringAgent`) to allow peering of custom data in the `orca` [SQL] DB.
Currently, the custom peering agents are called without much context as to what the main peering agent is doing (they are simply called at the end of every agent tick, after all main peering agent logic completes).
This can be changed later if needed but for now I wanted to keep the two as independant and simple as possible.
=> feat(peering): add ability to author custom peering agents

orca-sql/src/main/resources/db/changelog-master.yml, orca-sql/src/main/resources/db/changelog/20200424-index-deleted-executions-table.yml, orca-sql/src/main/resources/db/changelog/20200603-deleted-executions-table-not-mysql.yml
Fixes https://github.com/spinnaker/spinnaker/issues/5788
I had to change `20200424-index-deleted-executions-table.yml` which I thought would break MySQL users due to checksum issues, but running locally I didn't encounter any problems. Maybe it's fine?
Anyway, this change will get non-MySQL users a working Orca, and MySQL users will be unaffected:
```
2020-06-03 15:37:11.999  INFO 99068 --- [           main] liquibase.changelog.ChangeSet            : [] Marking ChangeSet: classpath:db/changelog/20200603-deleted-executions-table-not-mysql.yml::create-deleted-executions-table-for-not-mysql::robzienert ran despite precondition failure due to onFail='MARK_RAN': 
classpath:db/changelog-master.yml : Not precondition failed
2020-06-03 15:37:12.000  INFO 99068 --- [           main] …
```
=> fix(sql): Fix migrations for users who do not run MySQL

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/PollerConfigurationProperties.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/EphemeralServerGroupsPoller.java
Will attempt to use the application owner of a server group as the user, or else fallback to the original behavior of a static `spinnaker` user if an application owner cannot be found.
=> fix(clouddriver): Use application owner as user in EphemeralServerGroupsPoller cleanup executions

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy
If a user specified 'do not use source capacity' and has several deploy stages in a row (and at least one of the first stages does not have 'do not use source capacity' set)
When we restore capacity (which we shouldn't even need to do anyway) for one of the `do not use source capacity` ASGs we will look up the wrong ASG causing an erroneous error message to be logged.
This change only considers stages that are part of this deploy chain (as opposed to including all stages which are requisite to the current one).
Also, make the warn a info since it's expected when there is no snapshot capacity captured
=> fix(aws): correctly find ancestor for restoring min capacity

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/AbstractLoadBalancerRegistrationTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryJobRunner.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.java
In the future we will be using Moniker to support non-frigga based naming conventions. This change ensures that the cloudfoundry tasks which use application name are sending the moniker object, as well as the old. The old will be removed once all clouddriver operations have been changed as well.
=> fix(provider/cf): use moniker objects for task operations to support future non-frigga names

orca-web/orca-web.gradle
This protects us from the scenario wherein the Implementation-Version set for a test actually ends up being the version used in a final JAR artifact (since Gradle does not re-compile the JAR after it has been compiled for a test task).
=> fix(build): Do not set Implementation-Version in test JAR if already set to a valid version

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
Timeouts are pretty expected and are handled well in the UI, no need to throw an error into logs
This makes integration with, say, sentry, more sane as these timeouts won't show up as "issues"
=> fix(errors): don't log out an error on timeout

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestService.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoService.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/OperationContext.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/OperationLifecycle.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/SubmitOperationResult.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/CloudOperationStage.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorCloudOperationTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/SubmitCloudOperationTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/ClouddriverOperationStageSpec.groovy
This is the first draft of a generic cloud operation stage. The goal of this
stage, and the surrounding work, is to migrate all cloud provider logic from
orca into Clouddriver. The "vision" of this would be that to add a cloud
provider, or new operations for a cloud provider, would no longer require
modification to Orca; only requiring changes to Clouddriver.
This PR is submitting an incomplete stage, but I don't want to drop a mega-huge PR once everything is buttoned up. I'm not really concerned about it being incomplete since nothing will be using it.
=> feat(clouddriver): Add generic cloud operation stage

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.java
Originally, when doing a CloudFoundry form-based manifest deployment, the form-based manifest would be set in the context under "manifest". This manifest object contains the actual details that are presented in the form. When this was passed to the resolveManifest method, it would try to map it to a StageContextArtifactView which contains an artifactId and an Artifact. This is then passed to artifactUtils.getBoundArtifactForStage(*) so that we can correctly resolve the manifest if its from a prior stage, statically typed in the stage, etc, etc. The problem was that when we tried to map a direct manifest (form-based) to the StageContextArtifactView, it would result in all its field being null, hence breaking. 
The fix is to use the pre-existing DeploymentManifest object and map the direct …
=> fix(provider/cf): fix form based manifest resolution in deploy stage

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AppEngineServerGroupCreator.groovy
groovy.lang.MissingMethodException when referencing github config artifact for GAE deploy. The config artifacts  were of instance of HashMap not an Artifact object. Added logic to translate HashMap to Artifact.
=> fix(provider/appengine): Fix for issue https://github.com/spinnaker/spinnaker/issues/5836 (Master branch)

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AppEngineServerGroupCreator.groovy
**Bug description:**
groovy.lang.MissingMethodException thrown when referencing github config artifact for GAE deploy. (see spinnaker/spinnaker#5836 for more details)
**Fix:**
The config artifacts  were of instance of HashMap not an Artifact object. Added logic to translate HashMap to Artifact.
=> fix(provider/appengine): groovy.lang.MissingMethodException when referencing github config artifact for GAE deploy - spinnaker/spinnaker#5836

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PluginTrigger.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt
It will be useful to have this data on the plugin trigger.
Related to:
https://github.com/spinnaker/igor/pull/793
https://github.com/spinnaker/echo/pull/949
=> feat(plugins): Add plugin description and provider to PluginTrigger

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryDestroyClusterStage.groovy, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryDisableClusterStage.groovy, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/MonitorCanaryStage.groovy, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/DisableCanaryTask.groovy, orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryDestroyClusterStageSpec.groovy, orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryDisableClusterStageSpec.groovy
This is to address RSLNC-365 and, in particular, mine canaries failing to wait after disabling the baseline and canary cluster. Ideally this would use the disableCluster stage. However it looked like that might require a larger refactor since Mine doesn't deploy things in a normal fashion and the disableCluster stage was silently filtering out the cluster I gave it.
=> Fixing mine canaries not waiting after disabling the canary clusters

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy
Every execution of preconfigured job would run groovy.eval which in turn generates a script whose Klass stuffs is never released from metaspace
(similar issues: https://github.com/elastic/elasticsearch/issues/18572 and https://hoangx281283.wordpress.com/2014/07/24/unload-groovy-classes/)
Unclear why there is a need to run `eval` here anyway, so removing it all-together
=> fix(leak): fix metaspace leak form preconfigured jobs

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy
We were failing to rollback because Capacity also has an "isPinned" field ([here](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/Capacity.java#L20)). This fixes the casting so that it won't fail.
=> fix(rollback): fix capacity casting

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryDeployServerGroupTaskTest.java
Please see https://github.com/spinnaker/orca/pull/3752. 
Here is the breaking [commit](https://github.com/spinnaker/orca/commit/98152c833631a84203f700099149c955e4e4cbb1#diff-9c8b0013a03ef69b40307d50445a4acd)
The object mapping on line 50 was expecting an Artifact or/and an ArtifactId. The original was an actual manifest so it didn't map correctly. This would work fine with any deployments that weren't form based but all form based broke after this change. The new change uses the original working mapper wrapped in a method to add some error handling and more specific throwables. 
Co-authored-by: Zach Smith
Co-authored-by: Zach Smith
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
=> fix(provider/cf): fix form based manifest resolution in deploy stage (#3752)

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePreprocessor.kt, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/PipelineMissingTemplateVariabledException.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/v2/transform/V2DefaultVariableAssignmentTransform.java
Currently, if there are any templated pipelines that are not fully specified (which is very common as users are iterating on pipeline design) planning those pipelines will generate lots of noise logs.
This is especially annoying when this is done as part of dependentpipeline starter and so it looks like an exception occurred during an execution when in fact it had nothing to do with this particular execution.
This change silences those logs for dependent pipeline starter, there will be a part 2 of this change where better logic is applied to `/v2/pipelineTemplates/plan` to not log exceptions for similar cases (this EP is called by echo alot)
=> fix(log noise - mptv2): denoise some MPTv2 errors

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.java
If there is no `jobStatus` object there was no job and we will NPE
=> fix(runjob): Only cancel runjob if one was started successfully

orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java
Similarly to the change in Fiat (spinnaker/fiat#309) this switches us
over to using JedisPoolConfig. This, among other things, lowers the
minEvictableIdleTimeMillis to 60 sec from 30 min.
=> fix(redis): New a JedisPoolConfig instead of GenericObjectPoolConfig

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStageSpec.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/ToggleablePauseTask.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/ToggleablePauseTaskSpec.groovy
Introduces the ability to "pause" bakes through a feature toggle.
Pausing is achieved by the insertion of a simple task at the top of the list which waits until the feature toggle has been cleared. Note that turning on the feature flag will not affect currently running bakes, only those that start after it's been set.
The immediate need for this is to support our migration of the Bakery to ElasticSearch 6.x. It will require temporary "downtime" as we finish migrating the data, deploy the new server groups, and verify everything is OK. During that period, the plan is to use this toggle to pause all new bakes, then allow running bakes to complete, before the deployment. Once the migration is completed, we will "unpause".
=> feat(bake): Toggleable pausing for bake stage

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy
On verifyInstanceTermination, short circuit checks for
server group instance state if there are no enabled
traffic guards for the server group
=> fix(traffic guards): avoid server group lookup

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/graph/StageDefinitionBuilder.java
Small fix while fixing other things.
=> fix(api): getType should use getExtensionClass to avoid getting type info from proxy

orca-web/orca-web.gradle, orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy
cleans up some configuration imports in Main that get discovered via auto configuration or
component scanning as well
=> chore(dependencies): replace kork dependencies with kork-runtime

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/MonitorCanaryStage.groovy, orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/MonitorCanaryStageSpec.groovy
Groovy... Canceling during [mine] canary deploys would cause an unhandled exception (`MissingMethod`) in the cancellation thread.
Because it's in a separate thread and uncaught we don't actually propagate the error in any way, but the side-effect is that if,
in a complex pipeline, some other stage fails and causes pipeline termination during a canary deploy, those deployed [canary and baseline]
clusters won't be cleaned up and still, potentially, taking traffic!
This fixes the cancelation code to correctly look up the top-level canary stage and cancel it.
=> fix(mine): Fix canary stage cancellation

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
This hoists up the `.withAuth` and `.withLoggingContext` calls such that all logging (specifically those for thrown exceptions)
contains the execution/stage/task ids
=> fix(logging): Wrap all of RunTaskHandler in a `withAuth` for context

orca-core-tck/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/PipelineExecutionRepositoryTck.groovy, orca-redis/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisPipelineExecutionRepositorySpec.groovy, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgentSpec.groovy, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlPipelineExecutionRepositorySpec.groovy
Reduces the time to run `:orca-sql:test` from ~2m30s to ~1m40s.
* perf(test): Speed up PgSQL tests
When overriding setupSpec, Spock runs both the parent (super.setupSpec) and the subclass setupSpec (in that order). This means that for the PgSQL tests, we're creating a MySQL database then immediately discarding it to replace it with a PgSQL database.
As creating the database spins up a container and is resonably slow, lightly refactor this so that we don't do this extra work.
* refactor(test): Push some logic down from execution repository tests
There's a lot of coupling between PipelineExecutionRepositoryTck and its subclasses that causes initialization order dependencies. In order to make it easier to make changes (such as changing what fields are updated in setup vs setupSpec), refactor …
=> perf(test): Speed up orca-sql tests

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/exception/PreconfiguredJobNotFoundException.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ClusterSizePreconditionTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ClusterSizePreconditionTaskSpec.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/exceptions/PipelineTemplateValidationException.java, orca-core/src/main/java/com/netflix/spinnaker/orca/exceptions/PreconditionFailureException.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/StageStatusPreconditionTask.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/V2Util.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/StageStatusPreconditionTaskSpec.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTask.groovy, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/IllegalTemplateConfigurationException.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/TemplateRenderException.java, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/graph/transform/V2ConfigStageInjectionTransformSpec.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy
In an effor to clean up logs to improve signal to noise ratio of bug vs non-essential/expected failures:
* clean up what exceptions are thrown from a bunch of places
* anything deriving from UserException won't get logged as a failure
* for now, change capacity short circuit to warn instead of error because it is mostly noise. I will work on making it provide accurate signal separately
=> chore(exceptions): Fix up what exceptions are thrown

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTaskSpec.groovy
Let's simplify the logic in WaitForClusterDisableTask:
1. first make sure that the server group disabled flag is set
2. then delegate to waitForRequiredInstancesDownTask to check the various healths and the more subtle points like whether interestingHealthProviderNames are set or not
Motivation: it was possible to get out of WaitForClusterDisableTask with a server group that had Down instances but `disabled: false`, therefore it would still count as an active server group and would be filtered out by downstream stages like scaleDownServerGroup.
=> fix(disable): enforce serverGroup.disabled is true

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy
I made changes in my previous PR (https://github.com/spinnaker/orca/pull/3835) to throw a new exception, but didn't update the catch so this is not again generating noise
=> fix(exceptions): fix pipeline template exception

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt
This PR is to fix https://github.com/spinnaker/spinnaker/issues/5936.
Before this PR, `CompleteStageHandler` treats `SKIPPED` tasks/synthetics as "unhandled condition".
As a result, `SKIPPED` tasks and synthetic stages will mark the (parent) stage as `TERMINAL`.
This is not desirable because:
- `SKIPPED` is benign
- a `SKIPPED` stage won't fail a pipeline and the behaviour is inconsistent
- `SKIPPED` has valid use cases, for example synthetic stages conditional on parent stage output
After this PR, `SKIPPED` task or synthetic stage won't fail (parent) stage.
A special case is where **all** the tasks are skipped. The stage status will be `SUCCEEDED` instead of `SKIPPED`, to differentiate from the case where the stage itself is conditional and skipped.
=> fix(stage): Handle SKIPPED tasks and synthetic stages

orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionPromoter.kt
This way, if an orca cluster is not running the queue we don't enable the promoter
=> fix(execution promoter): Only enable execution promoter if enabled

orca-core/src/main/java/com/netflix/spinnaker/orca/clouddriver/utils/CloudProviderAware.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
It's possible for trackResult metrics call to fail and we don't want that failure to leak out and fail orca tasks
=> fix(exceptions): Don't let errors in `trackResult` leak out

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildPropertiesTask.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/RetryableIgorTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildPropertiesTaskSpec.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/V2PipelineTemplateController.java, orca-web/src/main/groovy/com/netflix/spinnaker/orca/exceptions/OperationFailedException.java
When a user submits a bad pipeline e.g.
* with jenkins trigger that has an invalid properties file or job that doesn't exist)
* with a broken pipeline template
we don't want to 500 because:
a) the calling service (echo in most cases here) will keep retrying which makes no sense
b) it's an erroneous HTTP 500 metric that is noise
=> fix(exceptions): add exception handler for exceptional situations

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForAllInstancesNotUpTask.groovy
Let's add it as a beforeStage instead of duplicating the tasks in the disable stage.
In particular, the task graph of DestroyServerGroupStage was missing a determineHealthProviderTask
and using the now-deprecated WaitForAllInstancesNotUpTask.
=> fix(destroy): add disable stage to destroy server group stage

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy
Add an experimental flag `forceSkipDisable` to the `DestroyServerGroupStage` so that applications that don't participate in discovery can skip disable step which should speed up their destruction operation.
=> feat(destroy): Add a flag to be able to skip the disable of destroy stage

orca-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/telemetry/SqlActiveExecutionsMonitor.kt
When this bean is created via `@Component` it fails to find the qualifier bean sqlExecutionRepository when qos is disabled.  I can not say I really understand why.  Now, the qualifier bean sqlExecutionRepository is found regardless of qos enabled/disabled.
=> fix(sql): Create SqlActiveExecutionsMonitor via autoconfiguration instead of @Component

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStageTest.java
Groundwork for: https://github.com/spinnaker/spinnaker/issues/5906
Requires: https://github.com/spinnaker/clouddriver/pull/4841
* feat(kubernetes): DeployManifestStage makes live calls to determine cluster members for rollout strategies 
In order to make the `liveManifestCalls` behavior the default for all users, we must change all pipeline operations that rely on cache consistency to instead call Clouddriver endpoints that make live queries against the Kubernetes cluster.
This commit replaces the existing `getClusters` call in the DeployManifestStage, used to hydrate the context of any Disable and Delete stages necessary in order to enact a Red/Black or Highlander rollout strategy, with a new `getClusterManifests` call, which returns a list of ManifestCoordinates for members of a given …
=> feat(kubernetes): DeployManifestStage makes live calls to determine cluster members for rollout strategies 

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategy.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/MonitoredDeployStrategySpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTaskSpec.groovy
In some cases, when a stage in a monitored deploy pipeline execution fails and attempts to automatically
roll back, the rollback stage fails. The associated error reported by the rollback stage is that Spinnaker cannot find a valid server group to roll back to. However, the original server group still exists.
If the original server group still exists, a rollback triggered by a monitored deployment should roll back to the original server group.
The *MonitoredDeployStrategy* class has been modified to add the name of the original server group to the context of the *RollbackClusterStage* in the pipeline.
The *DetermineRollbackCandidatesTask* class, which executes inside of a *RollbackClusterStage*, now determines which server group to roll back to by retrieving the original server group from …
=> fix(monitored-deploy): roll back to original server group

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/service/JobService.java, orca-core/src/main/java/com/netflix/spinnaker/orca/DefaultStageResolver.java, orca-core/src/main/java/com/netflix/spinnaker/orca/DynamicStageResolver.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResolver.java, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/DefaultStageResolverSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/DynamicStageResolverSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/StageDefinitionBuildersProvider.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/TaskResolverSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/StageNavigatorSpec.groovy, orca-plugins-test/src/main/kotlin/com/netflix/spinnaker/orca/plugins/PreconfiguredJobConfigurationProviderExtension.kt, orca-plugins-test/src/test/resources/orca-plugins-test.yml, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/admin/HydrateQueueCommandTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RescheduleExecutionHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeTaskHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/migration/TaskTypeDeserializerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/util.kt
Use of `Task`, `StafeDefinitionBuilder`, and `PreconfiguredJobConfigurationProvider` (so all `SpinnakerExtensionPoint` implementations) must be called from an `ObjectProvider` since the v2 framework does not make guarantees about when beans are instantiated.  Additionally, we need to support loading these extensions at anytime so there are some tweaks here to re-compute caches if necessary.
=> feat(plugins): Orca v2 framework compatibility

orca-core/src/main/java/com/netflix/spinnaker/orca/DefaultStageResolver.java
My change in https://github.com/spinnaker/orca/pull/3889/files#diff-0b2f668fb285224a316a086cb5d08604R116 didn't sit well with me because it will fail to find the `StageDefinitionBuilder` if the type alias is non-null but there is no alias lookup.
We don't use the `DefaultStageResolver` at NFLX but I don't want to break this for anyone - no tests were failing, but ya never know?
=> fix(core): More accurate stage defintion builder lookup in DefaultStageResolver

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineExecutionImpl.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandler.kt
Imagine the following pipeline topology:
```
Pipeline A
Pipeline B (triggers of SUCCESS of A)
\
\-Pipeline C (Triggered by a stage in B)
```
Now, imagine you restart a failed stage in `Pipeline C`. This stage will attempt to (correctly) restart `Pipeline B` at the appropriate stage.
This works unless `Pipeline B` was started as a result of dependent pipeline starter. In this case, restarting `Pipeline B` will fail because we will fail to restart `Pipeline A`.
This happens because while `A` is technically a parent of `B` no `parentExecutionStageId` exists so we fail to look up the stage and there fore `Pipeline B` will never actually restart as a result of restart of `C`
This change skips restarting parent if no `parentExecutionStageId` is specified
=> fix(restart): Fix parent pipeline restart for dependent pipelines

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/scalingprocess/AbstractAwsScalingProcessTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/scalingprocess/ResumeAwsScalingProcessTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/scalingprocess/SuspendAwsScalingProcessTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/scalingprocess/AbstractAwsScalingProcessTaskSpec.groovy
- not filtering means we might issue a task that says "resume Launch/Terminate", when in fact they already are enabled. Which in the spirit of idempotency should be quick and error free anyway (a noop)
- filtering means we occasionally think we don't need to reenable, when in fact we should, leading to a pipeline not behaving correctly and leaving things in a bad state
=> fix(aws): do not filter scaling processes to resume/suspend

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/BuildService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartJenkinsJobTask.groovy, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartScriptTask.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartJenkinsJobTaskSpec.groovy, orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandler.groovy
This a companion PR to https://github.com/spinnaker/igor/pull/863
The issue here is that when kicking off a build takes a long time (e.g. when jenkins has a lot of job configs) orca might kick off a lot of builds instead of just one (and might still fail!)
Igor now adds support for "pending" operation so if the same request is received twice it will return 202. This change adds the corresponding support to orca, on 202, we just need to retry, because eventually igor will give us the build number
=> fix(igor): Handle timeouts kicking off builds

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
This change adds logging for when a tasks `execute` method takes a long time to run (over 30s).
Since tasks have a pretty sensitive ack timeout, having a long running taks might be indicative of a problem to come.
We have metrics for task invocation times as well, but once an operator knows that some task takes a long time, it's useful to find it in logs to see what it was doing for further investigation
=> chore(tasks): Add logging for when tasks take a long time to run

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/StageExecution.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/StageExecutionImpl.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/MonitorPipelineStage.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStage.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStageSpec.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTaskSpec.groovy
This change adds a `MonitorPipelineStage` stage that allows one to monitor a given set of executions, similar to how `PipelineStage` starts and monitors that pipelins.
The difference is that this stage doesn't start any pipelines, it simply performs the monitoring.
Ideally, I would use the `MonitorPipelineStage` as a synthetic child of `PipelineStage` but that requires a bit more finesse and refactor that I don't think is worth it right now.
I will also be making corresponding `deck` changes to visualize the stage execution
=> feat(stages): Add stage to monitor specific execution(s)

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTaskSpec.groovy
This allows us to monitor webhook responses while allowing the recipient
server to hold the entire logic for determining status. This is possible
today with CreateWebhookTask, but CreateWebhookTask has a fixed timeout,
whereas MonitorWebhookTask has an overrideable timeout. Another option
would be to make CreateWebhookTask into an
OverrideableTimeoutRetryableTask.
=> feat(webhooks): Allow for webhook monitor tasks without JSON processing

orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResolver.java, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
I overlooked calls to `getTaskClass` when doing the initial pass through of Orca for v2 plugin framework compatibility.  Turns out we call `getTaskClass` in a number of places and it's possible the task cache needs to be rebuilt.
=> fix(plugins): Rebuild task cache on call to get task by type identifier

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/graph/TaskNode.java, orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResolver.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Removes most of what was introduced here: https://github.com/spinnaker/orca/pull/3574
This is mostly a performance improvement so that we don't needlessly rebuild the task cache.
=> fix(tasks): Only lookup task by type in RunTaskHandler; remove code introduced to support one-off case for now obsolete SimpleTask

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/graph/TaskNode.java, orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResolver.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Reverts spinnaker/orca#3939
Didn't work as I hoped.
=> Revert "fix(tasks): Only lookup task by type in RunTaskHandler; remove code introduced to support one-off case for now obsolete SimpleTask"

orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResolver.java, orca-plugins-test/src/test/kotlin/com/netflix/spinnaker/orca/plugins/test/OrcaPluginsTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Previous implementation was naive - it turns out we have a number of codepaths that will trigger that rebuild and I don't want to rebuild that cache over and over again as it is wasteful and could potentially have very negative performance consequences.  This is much simpler and cleaner and what I should've done from the get go.
=> fix(tasks): Fetch missing tasks from task provider on cache miss and add to cache

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.java
Instead of manually building `app-stack-detail` string to get a moniker, let's use the one already provided in the source asg or just use the Moniker builder instead.
=> fix(cf): Use moniker/frigga utils to build moniker

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy
Similar to the bake stage, `skipRegionDetection` can be used to determine
whether or not additional regions are inferred from downstream deploy stages.
The default value is `false` which preserves the existing behavior.
```
{
...
"skipRegionDetection": true
}
```
=> feat(clouddriver): Look ahead region detection for "aws" can be disabled

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy
We encountered an issue wherein the `amiSuffix` sent in the bake request was different than the `amiSuffix` value set in the stage context.  I have not found a logical reason for how this could happen, but if it does happen let's just set it to what is in the stage context and log it out.
=> fix(bake): Log when bake request amiSuffix and stage context amiSuffix values are different and resolve the difference

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
This is part 1 of essentially a three part change (one more PR to clouddriver and then another internal change).  This will allow us to fallback properly when looking up docker images from clusters wherein the cluster doesn't exist but we still want to gracefully find an image.
CloudDriver OSS change: https://github.com/spinnaker/clouddriver/pull/5019
=> fix(docker): Support finding image from a docker registry

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTaskSpec.groovy
We have received user reports that the Google cloud provider does not set the `disabled` flag, so the task can't succeed in this case. Let's make enforcement configurable as a workaround for this issue.
fixes spinnaker/issues/6038
=> feat(disable): put the disabled flag enforcement behind a feature toggle

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/KayentaService.kt, orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/pipeline/RunCanaryIntervalsStage.kt, orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/MonitorKayentaCanaryTask.kt
This was causing an issue for Kayenta for cases where there were multiple scopes sent as part of the stage. If the stage ended up with slightly different start/end times for each scope, Kayenta would return a null for the duration. This was happening due to each start/end being calculated for each scope which was causing them to be off by a ms or two. The stage would then explode when Kayenta returned null for the duration.
This fixes the different times issue and the nullable field causing the stage to explode.
=> fix(kayenta): Fixing nullable duration

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/UrlExpressionFunctionProvider.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/UrlExpressionFunctionProviderSpec.groovy
Added a Spel Helper function `#readYamlAll` with the ability to read multi-document YAML strings.
Previously if you tried to do so with `#readYaml` you got a `SpelHelperFunctionException`:
=> feat(SpelHelpers): Support parsing multi-document yaml strings

orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/config/KeelConfiguration.kt
This is to make it compatible with igor and other services
that have dependencies on keel
This is most likely a breaking change for Netflix
@luispollo @robfletcher
=> fix(keel): read configuration for keel from services

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/Capacity.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy
It was meant as a helper function, but actually becomes a field in serialized server groups. It can make its way to deck and be confusing to users.
=> fix(json): remove `pinned` from serialized Capacity objects

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTaskSpec.groovy
There are situations where we capture the snapshot capacity that is wrong. For example, if we resize a cluster `1->10`, then we do a force cache refresh and if that doesn't actually get the new state of `10`,
`WaitForUp` will wait for `1` instead of `10` instances (we defer to `WaitForUp` from `WaitForCapacityMatch`).
The other situation is when we do a rollback to a `0` size ASG, the first step of resizing it will resize it to correct rollback number, but since `WaitForUp` will succeed immediately we will tear down the old ASG and thus leave a rollback with no ASG ready to take traffic.
This is mostly an issue on Titus because `ForceRefresh` is a no-op on Titus.
It appears there already was an attempt to "fixing" this issue in https://github.com/spinnaker/orca/pull/2923, however it …
=> fix(waitforup): Don't use the min of snapshot capacity

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/HealthState.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/HealthHelper.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/HealthHelperSpec.groovy
Clouddriver is now exposing that state in https://github.com/spinnaker/clouddriver/pull/5060
This models `draining` as:
- up-negative, i.e. it will prevent wait-for-up checks from succeeding (to prevent issues like https://github.com/spinnaker/spinnaker/issues/5867)
- down-negative, i.e. it will prevent wait-for-down checks from succeeding. If it did, we would end up terminating instances in the draining state even though they are still potentially doing work. This could lead to errors or data loss.
=> Add draining health state

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/admin/web/QueueAdminController.kt
Previous PR introduced an ambiguous endpoint, this cleans that up. 
Previous change: https://github.com/spinnaker/orca/commit/c0a94d275eae2718be27e442f3ddcc3c140872aa
=> fix(zombies): Avoid ambiguous REST method overload by adding specific applications endpoint

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForDisabledServerGroupTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForDisabledServerGroupTaskSpec.groovy
Rolling red black and monitored deployments create disable server group stages with a desiredPercentage, which only disables some instances and not the whole server group. In that case, we need to skip the check that the server group is disabled.
=> fix(disable): skip disabled check for partially disabled server groups

orca-applications/orca-applications.gradle, orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/DeleteApplicationTask.groovy, orca-applications/src/test/groovy/com/netflix/spinnaker/orca/applications/tasks/DeleteApplicationTaskSpec.groovy, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/KeelService.kt
Adds a call from the `DeleteApplicationTask` to Keel to delete any associated records for Managed Delivery.
Closes https://github.com/spinnaker/keel/issues/1567
=> feat(managed-delivery): Delete Managed Delivery data upon application deletion

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/StageExecutionImpl.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTaskSpec.groovy
This should help provide users better hints at what went wrong when Jenkins jobs fail in child pipeline hierarchies.
=> chore(jenkins): Include breadcrumb error message when jenkins job fails

keiko-core/src/main/kotlin/com/netflix/spinnaker/q/QueueContextHolder.kt, keiko-core/src/main/kotlin/com/netflix/spinnaker/q/QueueProcessor.kt
Exposes the originating queue message to the worker thread executing on the message.
This intended for observability purposes.
=> feat(queue): Add QueueContextHolder

orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/KeelService.kt, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/config/KeelConfiguration.kt, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt, orca-keel/src/test/kotlin/com/netflix/spinnaker/orca/keel/ImportDeliveryConfigTaskTests.kt
While testing deletion of a managed app, I ran into an authorization error in keel as the call was being made without the `X-SPINNAKER-USER` header and so was treated as anonymous. This PR fixes the configuration of the keel service object so that the `SpinnakerRequestInterceptor` is used (which automatically adds that and other useful headers).
=> fix(application): Fix deletion of Managed Delivery data from keel

orca-echo/orca-echo.gradle, orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStage.groovy, orca-echo/src/main/java/com/netflix/spinnaker/orca/echo/util/ManualJudgmentAuthorization.java, orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStageSpec.groovy, orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/util/ManualJudgmentAuthorizationSpec.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/web/config/WebConfiguration.groovy
This PR verifies the current user roles against `context.selectedStageRoles`.
The operation is _only_ allowed if there is at least one overlapping role.
This is a rewrite of what originally went in as https://github.com/spinnaker/orca/pull/3988.
=> feat(echo): Support for restricting who can perform a manual judgment

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTask.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTaskTest.java
**Issue Summary**
The way an array of manifests passed into a pipeline as YAML using `Spel` is getting mapped changed from v1.21.5 to v1.22.0.  In v1.21, the manifests resolved by a `Spel` function are flattened to have a list of manifests. In v1.22, the manifest are not flattened so it throws a `java.lang.IllegalArgumentException` exception.
The behavior changed because this fix: https://github.com/spinnaker/kork/pull/720
**Steps to reproduce**
switch spinnaker to 1.22 or higher, execute the following stage:
```json
{
"account": "kubernetes",
"cloudProvider": "kubernetes",
"manifests": [
"${#yamlFromUrl(\"https://raw.githubusercontent.com/dmrogers7/spinnaker-issues/main/manifests/array-of-manifests.yaml\")}"
],
"moniker": {
"app": "bugs-reproduced"
},
"name": "Deploy (Manifest)", …
```
=> Fix(manifest): Fix manifests resolved by Spel

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTask.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTaskTest.java, orca-clouddriver/src/test/kotlin/com/netflix/spinnaker/orca/clouddriver/pipeline/KubernetesPreconfiguredJobSpec.kt
This PR is related with backport #4037 into 1.23.x.  The automated PR generated by mergify #4040 is failing because the timeout defined in an integration test is not enough for a successful execution. so I increased the timeout in this PR.
=> fix(manifest): Fix manifests resolved by Spel #4037 backport 1.23.x

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTask.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTaskTest.java
When using an artifact only pipeline (such as Kustomize -> Deploy Manifest), the changes added in #4037 causes a NPE as the manifests object is null. This ensures that the manifests are only flattened when they exist.
=> fix(manifest): Fix deployment of artifact only stages

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/BuildService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorQueuedJenkinsJobTask.groovy
Requires that `spinnaker.wwwHost` be set in your `orca` configuration.
```
spinnaker:
wwwHost: https://www.spinnaker.net
```
=> feat(jenkins): Automatically set a build description that links back to Spinnaker

orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt, orca-keel/src/test/kotlin/com/netflix/spinnaker/orca/keel/ImportDeliveryConfigTaskTests.kt
If a user enters a value in the manifest field in Deck, then blanks it out again, the stage config will contain `"manifest": ""` resulting in a failure to look up the delivery config object. This PR makes it so that we handle a blank string in that field the same way we handle a `null` -- i.e. we default to `spinnaker.yml`.
=> handle empty string manifest path when importing delivery config

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorQueuedJenkinsJobTask.groovy
Fixes spinnaker/spinnaker#6332
=> fix(jenkins): Addresses startup issue when `spinnaker.base-url.www` is not set

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/InterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/PatchStageInterlinkEvent.java, orca-interlink/src/main/java/com/netflix/spinnaker/orca/interlink/events/RestartStageInterlinkEvent.java, orca-interlink/src/test/groovy/com/netflix/spinnaker/orca/interlink/InterlinkSpec.groovy, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
Without this PR, calling the restart endpoint causes orca to push a RestartStage message on the queue. But for foreign executions, this doesn't do anything.
With this PR, we follow the model of delegating to a CompoundExecutionOperator instead, which handles local vs foreign executions and queue vs execution repository routing. If the execution is foreign, it will rely on the execution repository to emit the appropriate interlink message.
=> feat(interlink): support for restarting stages of foreign executions

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/Bake.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTask.groovy
I want to consume the base ami id in `keel` for managed delivery. At netflix we have it in the bakery response, so this PR adds it to the outputs if it's present.
=> chore(bake): add base ami if present in bake response

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
turns out you need to specify the fields that go in outputs. cool.
=> fix(bake): add baseAmiId to the outputs

orca-core/src/main/java/com/netflix/spinnaker/orca/events/ExecutionComplete.java, orca-core/src/main/java/com/netflix/spinnaker/orca/events/ExecutionListenerAdapter.java, orca-core/src/main/java/com/netflix/spinnaker/orca/events/ExecutionStarted.java, orca-core/src/main/java/com/netflix/spinnaker/orca/events/StageComplete.java, orca-core/src/main/java/com/netflix/spinnaker/orca/events/StageListenerAdapter.java, orca-core/src/main/java/com/netflix/spinnaker/orca/events/StageStarted.java, orca-core/src/main/java/com/netflix/spinnaker/orca/events/TaskComplete.java, orca-core/src/main/java/com/netflix/spinnaker/orca/events/TaskStarted.java, orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/ExecutionCleanupListener.java, orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/StageListener.java, orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/config/EchoConfiguration.groovy, orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy, orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListenerSpec.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/TaskResultMonitor.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/AbortStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandlerTest.kt
This avoid loading things for the repository twice, e.g.:
- on a StartTask message, the handler loads the entire execution
- it then emits a TaskStarted event, which will load the entire execution again
- ... and so on for TaskComplete, StageStarted, StageComplete, etc.
On simple executions, it decreases the amount of executions fetched by 40%, which should translate to less load on the database and lower memory pressure on orca.
=> perf(events): create execution events with a ref to the execution

orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStage.java, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/tasks/WebhookResponseProcessor.java, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStageSpec.groovy
Mapping a webhook config with no `waitForCompletion` in its context results in `stageData.waitForCompletion` being null
Let's default to `false` if the value is absent, which is probably how it was before translating from Groovy to Java.
=> fix(webhook): fix NPE in webhook config

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt
The `validateHandledPartitionOrThrow` call in `updateStatus` will load the entire execution to check the partition, but the subsequent call to storeExecutionInternal will do it more efficiently (using the execution reference).
=> perf(sql): avoid unnecessary work in updateStatus

orca-api-tck/src/main/kotlin/com/netflix/spinnaker/orca/api/test/PipelineBuilder.kt, orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/PipelineExecution.java, orca-core-tck/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/PipelineExecutionRepositoryTck.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/DefaultPersister.java, orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/Persister.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineExecutionImpl.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java, orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionPromoter.kt, orca-qos/src/test/kotlin/com/netflix/spinnaker/orca/qos/DefaultExecutionPromoterTest.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandler.kt, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerTest.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt
This fixes a regression introduced in f04f16ceac67580b4d0629c08361f885867ace4d, which caused e.g. trigger.parentExecution.endTime to be missing from child pipelines.
Before:
- a handler invoked executionRepository.updateStatus(type, id, status)
- `executionRepository` would add fields like `endTime`, `canceled` and persist them
- (before f04f16ceac67580b4d0629c08361f885867ace4d) the application events would load the execution from the db and fire the echo event
- (after f04f16ceac67580b4d0629c08361f885867ace4d) the application events would fire the echo event based on the in-memory execution, which was not updated with fields like `endTime` or `canceled`
After this change:
- handlers have to invoke execution.updateStatus(newStatus) to update the in-memory execution
- handlers then invoke …
=> fix(events): update in-memory execution before firing events

orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt, orca-keel/src/test/kotlin/com/netflix/spinnaker/orca/keel/ImportDeliveryConfigTaskTests.kt
This works nicely, promoting it to be the default behavior.
=> chore(md): make sending git metadata the default behavior

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/PipelineExecution.java, orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/StageExecution.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPoller.java, orca-core/src/main/java/com/netflix/spinnaker/orca/AuthenticatedStage.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/StageExpressionFunctionProvider.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineExecutionImpl.java, orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStage.groovy, orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy, orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStageSpec.groovy, orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingPipelineExecutionListenerSpec.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTask.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListenerSpec.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTaskSpec.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/AuthenticationAware.kt
Cleans up a bunch of deprecations to enable some further refactors in
kork around auth:
* explicitly use runAs (rather than deprecated propagate with a principal
object) when invoking as a specific user
* refactors away from deprecated kork-security object in favor of
Pipeline.AuthenticationDetails for passing auth
* adds a #currentUser() SpEL expression that will retrieve the user in the
current execution context (for example downstream of a manual judgment
with auth propagation it will return the new user)
=> refactor(auth): refactor auth propagation for pipelines

orca-api/src/main/java/com/netflix/spinnaker/orca/api/operations/OperationsContext.java, orca-api/src/main/java/com/netflix/spinnaker/orca/api/operations/OperationsInput.java, orca-api/src/main/java/com/netflix/spinnaker/orca/api/operations/OperationsRunner.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/scalingpolicy/DeleteScalingPolicyTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/scalingpolicy/UpsertScalingPolicyTask.groovy, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/KatoOperationsRunner.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/model/KatoOperationsContext.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/model/TaskId.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/KatoOperationsRunnerSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/scalingpolicy/UpsertScalingPolicyTaskSpec.groovy
Implementations of OperationsRunner can be used to fork operations to different services (besides CloudDriver, for example).
Implemented in `DeleteScalingPolicyStage` and `UpsertScalingPolicyStage` stages, though we'll probably eventually sweep through and replace all instances of `katoService` in these stages with `operationsRunner`.
=> feat(api): Add OperationsRunner interface with KatoOperationsRunner implementation

orca-core/src/main/java/com/netflix/spinnaker/orca/TaskExecutionInterceptor.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
feat(run-task-handler): added hook in finally block that will be run regardless of whether the task completed without exception.
The existing hook doesn't execute when a task execution throws an exception.
This hook allows for an extension project to clear the security context that is set in the before task hook.
=> feat(run-task-handler): added hook in finally block that will be ran regardless of whether the task completed without exception.

orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/tasks/GetBuildPropertiesTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildPropertiesTaskSpec.groovy
Continuation of https://github.com/spinnaker/orca/pull/4089 - it should've been part of that PR really.
Orca will now always check for properties from Travis, so it shouldn't fail if none are found.
=> fix(travis): Should not fail stage if Travis properties are not returned

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/ExecutionPreprocessor.java, orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/TaskExecutionInterceptor.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/V2Util.java, orca-core/src/main/java/com/netflix/spinnaker/orca/preprocessors/DefaultApplicationExecutionPreprocessor.kt, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTask.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTaskSpec.groovy, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePreprocessor.kt, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/tasks/PlanTemplateDependentsTask.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy, orca-web/src/main/java/com/netflix/spinnaker/orca/controllers/V2PipelineTemplateController.java
Moving two existing interfaces from `orca-core` into `orca-api`. The purpose is to communicate that these interfaces are safe to use for extending orca functionality.
- `ExecutionPreprocessor`
- `TaskExecutionInterceptor`
=> refactor(orca-api): move ExecutionPreprocessor and TaskExecutionInterceptor into orca-api

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/CloudFormationForceCacheRefreshTask.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/WaitForCloudFormationCompletionTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/CloudFormationForceCacheRefreshTaskSpec.groovy
Add onDemand cache polling logic for cloud formation stacks.
Right now orca asks for the cache refresh and finishes the task.
This is most likely the cause of this issue:
https://github.com/spinnaker/spinnaker/issues/6125
This enables orca to start polling for the status of the force cache refresh
when the status received from clouddriver indicates that the force cache
the operation did not finish and has been queued.
This PR is complemented with https://github.com/spinnaker/clouddriver/pull/5276 
which add the OnDemand cache logic on the clouddriver side
=> fix(aws/cloudformation): Add onDemandCache refresh logic

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/Task.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
Plugin authors would like a way to add metadata to the stages when canceling a task.
=> feat(core): Support returning TaskResult from Task.onCancel

orca-clouddriver/orca-clouddriver.gradle, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java, orca-clouddriver/src/test/kotlin/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestExpressionEvaluationTest.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExpressionAwareStageDefinitionBuilder.java
Addresses parts of https://github.com/spinnaker/spinnaker/issues/5910
=> fix(manifest): fixes deploy manifest SpEL evaluation toggle

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/job/JobUtils.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletionTest.java
The WaitOnJobCompletion task make http calls to clouddriver to get the job status for a Kubernetes PreconfiguredJob. By default, when the stage.context does not have a moniker or application field defined the name of the object is used but it is parsed to Frigga Names object.
When an end user execute a pipeline and the WaitOnJobCompletion task is executed, if the stage's context does not have the moniker or application field defined, the Application name will be null or the job's name.
Clouddriver uses the account & pipeline name to determinate permissions, when sending the job name as the application name we can get an Access Denied error.
Instead of use the job name as default, I changed it to use the Application name in the PipelineExecution. This prevent to search permission in …
=> fix(jobs): use stage.execution.application as default when looking job status

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/ServiceManifest.java
adds versioned flag to the manifest in order to convert correctly for clouddriver. for more details, see the clouddriver PR
=> feat(cloudfoundry): add versioning to cf services

gradle/ktlint-root.gradle, gradle/spek.gradle, keiko-tck/keiko-tck.gradle, orca-deploymentmonitor/orca-deploymentmonitor.gradle, orca-dry-run/orca-dry-run.gradle, orca-queue-redis/orca-queue-redis.gradle, settings.gradle
now that it's been sunset (https://status.bintray.com/).
=> chore(build): remove references to jcenter/bintray

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy
Refer spinnaker/spinnaker#6537
During verification of Orca by upgrading spring boot, build failed with below error:
```
Task :orca-echo:compileGroovy
/home/opsmxbuild/spinnaker-comp/orca/orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy: 126: [Static type checking] - Cannot assign value of type java.lang.String to variable of type ?
@ line 126, column 34.
event.content.taskName = "${stage.type}.${task.name}".toString()
^
/home/opsmxbuild/spinnaker-comp/orca/orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy: 130: [Static type checking] - Cannot assign value of type com.netflix.spinnaker.orca.api.pipeline.models.PipelineExecution to variable of type ?
@ line 130, column 35. …
```
=> chore(dependencies): Upgrade Spring Boot to 2.2.13

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStage.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStageTest.java
Note: this is only applicable when the user has set 'allowDeleteActive: true' in the ShrinkCluster stage manifest
When `allowDeleteActive: true`, then in the ShrinkCluster stage, `disableCluster` step is performed before shrinking the cluster.
We have some users who do not want the disable cluster step to be executed in this scenario. They use the Shrink Cluster stage to destroy the old server groups. Because of this disable cluster step, no incoming requests are accepted and this creates downtime for their services. They prefer to shrink the cluster without disabling it at all.
This PR introduces a change to make disabling the cluster optional in such scenarios.
By setting `"runDisableClusterStep": false` in their stage context, this step will be skipped. By default, it is enabled to …
=> feat(clouddriver): provide a configurable option for the user to bypass the disableCluster step in the ShrinkCluster stage

build.gradle, orca-api/orca-api.gradle
`org.jetrbrains.dokka@1.4.10` is not present in maven central. This updates to a version that is present in maven central and is known to have all of it's dependencies there as well. https://github.com/Kotlin/dokka/issues/41#issuecomment-826700552
=> chore(dependencies): Update dokka version to version in maven central

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy
Nuget packages files names are written in the following format `MyPackage.1.3.3.7.nupkg` and the version separator is the `.` which is the same character used in the version Major/Minor/Patch separator (has opposed to `deb` and `rpm` which have distinct version separators).
Given this, we do not need to "further strip" in case the "version separator" is found in the version itself (since it will always happen).
=> fix(artifacts): Do not further strip version for nuget packages

build.gradle, gradle.properties, orca-applications/orca-applications.gradle, orca-bakery/orca-bakery.gradle, orca-bom/orca-bom.gradle, orca-clouddriver/orca-clouddriver.gradle, orca-echo/orca-echo.gradle, orca-front50/orca-front50.gradle, orca-igor/orca-igor.gradle, orca-pipelinetemplate/orca-pipelinetemplate.gradle, orca-web/orca-web.gradle, orca-webhook/orca-webhook.gradle
There is an issue in the Plugins Framework that was solved in this PR: spinnaker/kork#866
but this fix was released in kork 7.110.0
I bumped the version of kork to include the fix in VersionManager in the plugins framework but this involved changing the groupId of kork because now it's been published under "io.spinnaker" and this release branch is pretty old.
I had to bump the version of Fiat as well because it has issues when trying to download the kork version in fiat due to the groupId change.
=> fix(build): bump kork to 7.110.0 & change groupid for dependencies

orca-web/src/test/kotlin/com/netflix/spinnaker/orca/controllers/AdminControllerTest.kt
Fixes com.netflix.spinnaker.orca.controllers.AdminControllerTest intermittent failures. The failure seems to be caused by a start up issue. The DiscoveryActivator is not initialized when the test is checking for its initial status. This fix adds wait/sleep, so DiscoveryActivator can be fully initialized.
Here is the test log showing failure: 
[TEST-com.netflix.spinnaker.orca.controllers.AdminControllerTest.xml.log](https://github.com/spinnaker/orca/files/7685484/TEST-com.netflix.spinnaker.orca.controllers.AdminControllerTest.xml.log)
>
Here is the partial output of test when it encounters issue, and successful:
>2021-12-09T04:09:24.5943329Z 2021-12-09 04:08:58.103  INFO 7552 --- [    Test worker] o.s.t.web.servlet.TestDispatcherServlet  : Completed initialization in 239 ms …
=> test(discovery): fixes admin controller test intermittent failures

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pollers/EphemeralServerGroupsPoller.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPoller.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPollerSpec.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/PipelineExecutionLauncherSpec.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy
At a high level, all this does is that it replaces
ExecutionLauncher.start(ExecutionType type, String configJson)
with
ExecutionLauncher.start(ExecutionType type, Map<String, Object> config)
In general, the lifecycle of an execution is that it can live as:
- a json string, e.g. when it is submitted to the API
- a Map<String, Object> "config" that needs to be munged and massaged (with things like a user, origin, trigger...)
- a PipelineExecution model when it is fully formed
With this PR, we try to only move "up the chain" (string -> map -> model) and never back down (string -> map -> string -> map -> model).
In practice this means avoiding calls to objectMapper.writeValueAsString() followed by objectMapper.readValue(), which in turns simplifies some tests quite a bit.
=> perf(executions): remove ability to launch executions from a json string

orca-plugins-test/src/test/kotlin/com/netflix/spinnaker/orca/plugins/test/OrcaPluginsFixture.kt, orca-web/src/test/groovy/com/netflix/spinnaker/orca/StartupTestConfiguration.java
Fixes UnsatisfiedDependencyException seen in the tests when running  `./gradle build` (See: https://github.com/spinnaker/orca/runs/5069995846?check_suite_focus=true)
```
Caused by:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zombieExecutionService' defined in URL [jar:file:/home/runner/work/orca/orca/orca-queue/build/libs/orca-queue.jar!/com/netflix/spinnaker/orca/q/ZombieExecutionService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.spinnaker.q.metrics.MonitorableQueue' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
at …
```
=> fix(web/test): create MonitorableQueue bean to fix web test

gradle.properties, orca-plugins-test/src/test/kotlin/com/netflix/spinnaker/orca/plugins/test/OrcaPluginsFixture.kt, orca-web/src/test/groovy/com/netflix/spinnaker/orca/StartupTestConfiguration.java
We bumped korkVersion to 7.115.2 but there were issues in the integration test due to bean not created.
https://github.com/spinnaker/orca/pull/4217
After taking a look I found the zombieExecutionService requires a MonitorableQueue and in our integration test we created a Queue bean. So this makes the tests to fail.
=> chore(build): Bump kork version & fix tests

keiko-redis-spring/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueConfiguration.kt, keiko-redis/src/main/kotlin/com/netflix/spinnaker/q/redis/RedisClusterDeadMessageHandler.kt, keiko-redis/src/main/kotlin/com/netflix/spinnaker/q/redis/RedisDeadMessageHandler.kt, keiko-redis/src/test/kotlin/com/netflix/spinnaker/q/redis/RedisQueueTest.kt, keiko-sql/src/test/kotlin/com/netflix/spinnaker/q/sql/SqlQueueTest.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/jackson/OrcaObjectMapper.java, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/config/KeelConfiguration.kt, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequestSpec.groovy, orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisOrcaQueueConfiguration.kt, orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/pending/RedisPendingExecutionServiceTest.kt, orca-queue-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlOrcaQueueConfiguration.kt, orca-queue-sql/src/test/kotlin/com/netflix/spinnaker/orca/q/sql/SqlQueueIntegrationTest.kt, orca-queue-sql/src/test/kotlin/com/netflix/spinnaker/orca/q/sql/pending/SqlPendingExecutionServiceTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/migration/TaskTypeDeserializerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/pending/DualPendingExecutionServiceTest.kt, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgentSpec.groovy, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/TopApplicationExecutionCleanupPollingNotificationAgentSpec.groovy, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlPipelineExecutionRepositorySpec.groovy
I found issues in Orca when starting up.
```
2022-02-14 05:08:43.009  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisOrcaQueueConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.module.kotlin.KotlinModule.<init>(int, boolean, boolean, boolean, com.fasterxml.jackson.module.kotlin.SingletonSupport, int, kotlin.jvm.internal.DefaultConstructorMarker)'
```
This issues is related to the `jackson-module-kotlin` used. It's hard to know what version of jackson will end in the service. So I changed how the KotlinModule …
=> fix(kotlin): create kotlinModule using Builder instead constructor

orca-core/orca-core.gradle, orca-core/src/main/java/com/netflix/spinnaker/orca/config/UserConfiguredUrlRestrictions.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/UrlExpressionFunctionProvider.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/config/UserConfiguredUrlRestrictionsSpec.groovy, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtilsTest.java, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookServiceSpec.groovy
To allow better customizations of CloseableHttpClient, adding HttpClientProperties as an additional property in UserConfiguredUrlRestrictions that we can use in HttpClientUtils. This will allow us to enable/disable retry options and configure other HttpClient options.
Now, you will be able to configure `httpClientProperties`
e.g
```yaml
user-configured-url-restrictions:
httpClientProperties:
enableRetry: true
maxRetryAttempts: 1
retryInterval: 1000
timeoutMillis: 10000
```
=> feat(expressions): add option to disable retry for fromUrl expression function

orca-core/src/main/java/com/netflix/spinnaker/orca/telemetry/TaskSchedulerMetricsPostProcessor.java, orca-core/src/main/java/com/netflix/spinnaker/orca/telemetry/ThreadPoolMetricsPostProcessor.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/telemetry/RedisPoolMetricsPostProcessor.java, orca-web/src/test/java/com/netflix/spinnaker/orca/MeterRegistryProcessorIntTest.java, orca-web/src/test/java/com/netflix/spinnaker/orca/MeterRegistryProcessorTestConfiguration.java
This PR fixes https://github.com/armory-plugins/armory-observability-plugin/issues/32#issuecomment-1036400066.
It allows other `BeanPostProcessor` (e.g. Spring `MeterRegistryBeanPostProcessor`) to process registry implementations, restoring the exported metrics and aligning the behavior to the other spinnaker services.
I've retrofitted a test showing the missed processing of a dummy BeanPostProcessor, but more details are available on the issue.
We noticed this issue extends to _Kayenta_ too, given it pulls in `orca-core` modules and the affected classes, preventing the Observability plugin to export standard metrics (due to the binders - e.g. JvmMetrics - not being bound ).
=> Fix meter registry processor causing incompatibility with Armory's Observability plugin

.github/workflows/bump_dependencies.yml
to avoid a hard-coded 10 minute timeout.  See
e.g. https://github.com/spinnaker/bumpdeps/blob/c5ca595ec6211aae4160c46a14a4f2fd04359638/src/main/kotlin/io/spinnaker/bumpdeps/Main.kt#L128
=> chore(build): specify an artifact for bumpdeps to look for

gradle.properties
The autobump PR didn't happen due to rate limit violations.  From https://github.com/spinnaker/spinnaker-gradle-project/runs/5426168051?check_suite_focus=true:
```
[main] ERROR io.spinnaker.bumpdeps.BumpDeps - Exception updating repository orca
org.kohsuke.github.HttpException: {"message":"You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#secondary-rate-limits"}
at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:483)
at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:407)
at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
at …
```
=> chore(dependencies): bump spinnakerGradleVersion to 8.22.0

.github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/release_info.sh
- collapse version info gathering steps into single `build_variables` step
- collapse version info parts into single string and use everywhere.
- use short git sha: `(git rev-parse --short HEAD)`
Note `build.yml` versioning is not compatible with Debian package
building as gradle plugin enforces `^[0-9]+`.
We don't publish master branch or release-* branches to GAR apt
repository though.
Prefixing the version with `<tag>-dev-` or something and publishing Debian
packages is possible but may pollute `apt-cache policy spinnaker-rosco` output
and overall be unnecessary with regular releases.
=> chore(ci): GHA - simplify build versioning

orca-clouddriver/orca-clouddriver.gradle, orca-core/orca-core.gradle, orca-interlink/orca-interlink.gradle
While upgrading spring cloud to Hoxton.SR12, we encountered below errors :
```
> Task :orca-core:compileJava
/home/ubuntu/spinnaker-comp/spring-cloud-upgrade-SR12/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/DependsOnExecutionTask.java:31: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
^
/home/ubuntu/spinnaker-comp/spring-cloud-upgrade-SR12/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/DependsOnExecutionTask.java:87: error: cannot find symbol
@NotNull public String executionType;
^
symbol:   class NotNull
location: class TaskContext
/home/ubuntu/spinnaker-comp/spring-cloud-upgrade-SR12/orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/DependsOnExecutionTask.java: …
```
=> fix(dependency): Issue of missing javax.validation and hibernate-validator dependencies while upgrading the spring cloud to Hoxton.SR12 in kork

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/WaitForCloudFormationCompletionTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/WaitForCloudFormationCompletionTaskSpec.groovy
It seems that the status message from AWS has changed or could potentially differ. Updating to check for what I'm getting as output.
=> fix(cfn): Fix detection of empty CloudFormation changesets

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTaskSpec.groovy
The way that the monitor pipeline task worked before was that it only
stored the _status_ of the child pipeline when the child was running
(see file before the commit
[here](https://github.com/spinnaker/orca/pull/3902/files#diff-4c694b67271c7d9436d5af695f160f0b60c7ad7753a0ba1eb9aea76d7ba4e851R128-R130)).
After the commit was merged, the MonitorPipelineTask was storing the
context of the child pipeline on every update regardless of the child
pipeline’s status ([see line in
commit](https://github.com/spinnaker/orca/blob/20e2b9ea61037e7fc8eb59c817dc5d33f4718af3/orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy#L96)).
This should address the issue seen where large nested pipelines
especially those child pipelines that generate a lot of outputs …
=> fix(tasks): Fix MonitorPipelineTask regression

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperator.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperatorTest.java, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
This PR includes the changes to fix the [issue #6675](https://github.com/spinnaker/spinnaker/issues/6675) 
**Root cause:** 
Expression is not considered during restart of pipeline instead it picks the expression result from the previous run
**Fix:** 
Updating `StageExecution` for stage type `checkPreconditions` with expression from `restartDetails` Map
and store the updated `stage` with expression in the `ExecutionRepository`, from where the restart data gets picked.
This PR changes are dependent on https://github.com/spinnaker/gate/pull/1560
=> fix(restart-pipeline) : CheckPrecondition doesn't evaluate expression correctly when upstream stages get restarted

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfigurationProperties.java
I have no idea why this is necessary, since `@Data` includes `@RequiredArgsConstructor`, which in this case is equivalent to `@NoArgsConstructor`. Regardless, it doesn't work using `@Data`. Must be some weird interaction between Lombok and nested classes.
Fixes https://github.com/spinnaker/spinnaker/issues/6704
=> fix(clouddriver): fix property binding for Clouddriver

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/config/BuildServiceConfiguration.groovy, orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/BuildService.java, orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/IgorFeatureFlagProperties.java, orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildServiceSpec.groovy
When defining a Jenkins job inside folders, the name contains slashes. Because of that instead of matching the request to the IGOR STOP endpoint (/masters/{name}/jobs/{jobName}/stop/{queuedBuild}/{buildNumber}), Spring is matching the request to the BUILD one  (/masters/{name}/jobs/**)
The stop request is failing because it is trying to start a job that does not exist.
Feature flag added to call the existing endpoint (which accepts the job name as path variable) or the new one (which accepts  the job name as a query parameter)
Related Igor PR https://github.com/spinnaker/igor/pull/1038
=> feat(igor): Stop Jenkins job when job name has slashes in the job name

keiko-sql/src/main/resources/db/changelog/20190822-initial-schema.yml, orca-sql/src/main/resources/db/changelog/20200221-partition-name-table.yml, orca-sql/src/main/resources/db/changelog/20200327-deleted-executions-table.yml, orca-sql/src/main/resources/db/changelog/20200424-index-deleted-executions-table.yml, orca-sql/src/main/resources/db/changelog/20200603-deleted-executions-table-not-mysql.yml
Indentations for rollback are wrong in some files of database changeLog, which raises the following exception:
```log
liquibase.exception.ChangeLogParseException: Error parsing db/changelog/20200221-partition-name-table.yml
at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:89)
at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:587)
at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:363)
... 113 common frames omitted
Caused by: liquibase.parser.core.ParsedNodeException: Unexpected node found under databaseChangeLog: rollback
at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:483)
at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:318)
at …
```
=> fix wrong indentation for rollback in database changeLog

orca-core/orca-core.gradle, orca-core/src/main/java/com/netflix/spinnaker/orca/config/ExecutionConfigurationProperties.java, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/PipelineExecutionLauncherSpec.groovy, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncherTest.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/YamlFileApplicationContextInitializer.java, orca-core/src/test/resources/com/netflix/spinnaker/orca/pipeline/ad-hoc/deploy-manifest.json, orca-core/src/test/resources/com/netflix/spinnaker/orca/pipeline/ad-hoc/save-pipeline-blocked-user.json, orca-core/src/test/resources/com/netflix/spinnaker/orca/pipeline/ad-hoc/save-pipeline-permitted-user.json, orca-core/src/test/resources/com/netflix/spinnaker/orca/pipeline/ad-hoc/save-pipeline.json, orca-core/src/test/resources/com/netflix/spinnaker/orca/pipeline/ad-hoc/update-application.json, orca-core/src/test/resources/execution-launcher-properties.yml
There are two types of tasks - pipeline initiated tasks, and ad-hoc orchestration tasks. Some of the ad-hoc tasks can be done through the UI - such as update application, delete pipeline, update pipeline etc. For security reasons, we want the capability to disable ad-hoc tasks for all users (except the few that are permitted to execute them) in production environments. 
This PR introduces a few config knobs that provide a more fine-grained control over who can perform the above actions. By default, everyone can perform all actions (which equates to the current behavior). Users can opt-in to this capability by configuring the ad-hoc tasks in the manner presented below:
```
executions:
blockOrchestrationExecutions: true
allowedOrchestrationExecutions: # only applicable when …
```
=> feat(orchestration): provide a way to allow only certain configured ad-hoc operations to be performed

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/EvaluateVariablesStage.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesStageSpec.groovy
Issue: Expression evaluates the previous data when upstream stage(Manual Judgement) is restarted (or other restar case).
Steps to reproduce:
1. Execute the pipeline and choose Continue at the Manual Judgement stage. Upon completion note that the status variable inside "Evaluate Variables" was evaluated to 'success'; this is correct. 
2. Execute the pipeline again and when it reaches the Manual Judgment, wait 1 min for it to timeout or stop manually the judgment. Upon timeout, note that the status variable inside "Evaluate Variables" was evaluated to 'failed'; again this is correct. 
3. Click on the failed Manual Judgment stage and choose Actions -> Restart Manual Judgement from the drop down.  
The pipeline will execute. Choose Continue for the Manual Judgement. Upon completion note that …
=> fix(stageExecution): In evaluable variable stage restart scenario variables are not cleaned properly (#16)

orca-clouddriver/orca-clouddriver.gradle
since spring 2.4.13 brings it in (transitively).  The version from spring boot takes precedence, so the value we specify here is ignored.
Another approach would be to make the version here match what spring boot brings in (currently 11.0.3), but then future changes could again invalidate what's here.  If some future version of spring boot stops bringing in io.kubernetes:client-java, builds will fail with unspecified version, at which point we can specify the version once again.
Snippets of ./gradlew orca-web:dependencies
before:
```
+--- project :orca-applications
|    +--- project :orca-core
|    |    +--- io.kubernetes:client-java:11.0.2 -> 11.0.3
```
after:
```
+--- project :orca-applications
|    +--- project :orca-core
|    |    +--- io.kubernetes:client-java -> 11.0.3
```
Related …
=> chore(kubernetes): stop specifying the version of io.kubernetes:client-java

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfigurationProperties.java
when this class was refactored from groovy into java, the visibility of these two methods was (inadvertently?) changed, causing downstream plugins to break with illegal access.
https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/issues/125
=> fix(config): restore prior visibility of methods on CloudDriverConfigurationProperties class

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtils.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtilsSpec.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
When setting up multiple triggers with different expected artifacts, triggering the pipeline fails if _any_ defined expected artifact is missing, even if it is defined on another trigger. This fix filters the list of expected artifacts to make sure only the artifacts that are relevant for the current trigger is evaluated.
Example:
If you create two triggers like this, with different artifact constraints:
This would result in a pipeline config like this:
```json
{
"expectedArtifacts": [
{
"defaultArtifact": {
"customKind": true,
"id": "3c55a698-aa57-4f38-9326-a99511b8e7b0"
},
"displayName": "my-artifact",
"id": "89709fb4-4ad1-4267-ba14-77befa93b58d",
"matchArtifact": {
"artifactAccount": "custom-artifact",
"customKind": true,
"id": "dfa2e113-eb4f-4d20-adec-db0756ec4f44",
"name": …
```
=> fix(artifacts): Expected Artifacts should be trigger specific

orca-bakery/src/main/java/com/netflix/spinnaker/orca/bakery/api/manifests/helm/HelmBakeManifestRequest.java, orca-bakery/src/main/java/com/netflix/spinnaker/orca/bakery/tasks/manifests/BakeManifestContext.java
This is part of https://github.com/spinnaker/spinnaker/issues/6518
Add new field `includeCRDs` in request to rosco in order to include custom resource definitions manifests in templated output.
=> feat(bakery): add includeCRDs in Helm Bake request

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryService.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/DeleteBakesRequest.java, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeryPipelineDependencyCleanupOperator.java, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/BakerySelectorSpec.groovy, orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgent.java, orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/PipelineDependencyCleanupOperator.java, orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationExecutionCleanupPollingNotificationAgent.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgentSpec.groovy, orca-core/src/test/groovy/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationPipelineExecutionCleanupPollingNotificationAgentSpec.groovy, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgent.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/TopApplicationExecutionCleanupPollingNotificationAgent.kt, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgentSpec.groovy, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/TopApplicationExecutionCleanupPollingNotificationAgentSpec.groovy
**Description**
Rosco service uses Redis for caching purposes. The records created in Redis can be up to 50MB size and will never be removed. As a result, Redis can become quite expensive. This pull request changes solve this issue.
=> feat(bakery): Clean up cached data created by Rosco.

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/MonitorKayentaCanaryTask.kt, orca-kayenta/src/test/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/MonitorKayentaCanaryTaskTest.kt
Issue: Stage execution fails for Canary Analysis pulling metrics. Object Mapper used not support directly Instant datatype
Solution applied:
Orca handle the json response with different object mappers, the desired is use OrcaObjectMapper class, but override the default object mapper for entire pipelines TaskResult could affect other kind of stages/task results, so only data type Instant unsupported was changed before being returned.
=> fix(tasks): Fix MonitorKayentaCanaryTask on results data map

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/MonitorBakeTask.groovy, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy
Add support for handling the bake of managed and custom images for Azure.
Tested the feature manually.
To be pushed after the rosco packer templates have been validated and the entire workflow was tested.
=> feat(Azure): Update createBakeTask for managed and custom images.

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java
Get the rollback timeout value from stage data. The value is now configurable from the UI. If the value is not set in the UI the hardcoded value is used.
Testing:
The rollback failed after 20 min and 8 sec with a timeout of 20min.
=> feat(AWS): Get the rollback timeout value from stage data.

orca-web/orca-web.gradle
The property spring.config.additional-location is redundant in orca-web.gradle file. This property is set by class com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder in com.netflix.spinnaker.orca.Main. So removing it from gradle file.
=> refactor(web): Clean up redundant spring property in gradle file

gradle/groovy.gradle, orca-integrations-cloudfoundry/orca-integrations-cloudfoundry.gradle, orca-keel/orca-keel.gradle
with a specific goal to get `org.testng:testng:7.4.0` out of shipping code, since it's vulnerable to CVE-2022-4065.
=> chore(dependencies): remove dependency on groovy-all where straightforward

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/MonitorBakeTask.groovy
for MonitorBakeTask timeout
The default value is unchanged -- 3600000 milliseconds, or 1 hour.
See https://github.com/spinnaker/orca/pull/4347 which does a similar thing for MonitorPipelineTask.
=> feat(bakery): add tasks.monitor-bake.timeout-millis configuration property

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy
Closes: https://github.com/spinnaker/spinnaker/issues/6739
=> chore(front50): Make Monitor Pipeline Task timeout overridable

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStage.groovy, orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStageSpec.groovy, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/AuthenticationAware.kt
When Manual Judgment without propagate authentication enabled appear in a pipeline, next stages ignore the last user interaction in propagated stages, and is retrieving the executor user by default when the expected case is consider the last MJ with propagate authentication enabled.
Similar fix was applied in https://github.com/spinnaker/orca/pull/4289 but only considering skipped stages, now we extend the logic for sub cases
Requirements:
-AuthZ system enabled
-Roles properly configured to restrict and allow desired users
Ex:
Roles used:
-----------
permissions:
CREATE:
- "admin" # group members that CAN create applications if enabled
READ:
- "admin"
- "restricted"
WRITE:
- "admin"
EXECUTE:
- "admin"
- "restricted"
Users:
OscarMichelH as `admin`
oscar4armory as `restricted`
The wrong …
=> fix(stageExecution): Extend MJ auth propagate logic for exhaustive cases

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/model/Task.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTaskSpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryMonitorKatoServicesTaskTest.java
This adds context.kato.tasks[].outputs to the pipeline execution context for each stage that uses MonitorKatoTask.  It's empty unless clouddriver provides it via its GET /task/{id} endpoint.
Depends on https://github.com/spinnaker/clouddriver/pull/5846.
=> feat(tasks): Capture task output data from clouddriver

orca-web/orca-web.gradle, orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy
Using `com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder` class to setup spring and other related properties required for the spring boot application to start.
=> chore(web): clean up for spring property setup

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtils.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtilsSpec.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
It is currently hard/impossible to resolve artifacts in pipelines that doesn't have any triggers defined by themselves, and are triggered by a pipeline stage in another pipeline. Previously it was possible to get it to work by editing the json of the pipeline or in the UI by adding artifacts in a temp trigger and then removing it (this would keep the expected artifacts around). When I introduced trigger specific artifact constraints in #4322, I made it a lot harder (if not impossible) to do this because no triggers are used and thus all expected artifacts are filtered out.
This PR will fix this by copying expected artifacts from the parent execution (only if triggered by a pipeline stage), thus avoiding the whole situation altogether. It will also not filter away any expected artifacts …
=> fix(artifacts): Be more lenient when filtering expected artifacts

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
This commit partially reverts #4397. It broke some pipelines for a team that had a CI stage that created more artifacts with the same name as the expected artifact from the original trigger, and then had a pipeline stage. The result was that the child pipeline was triggered with multiple artifacts with the same name (but different version numbers), and then failed to start because the artifact resolver matched multiple artifacts instead of exactly one. Turns out the changes in DependentPipelineStarter wasn't really needed to fix the issue that #4397 tried to solve, so I'm reverting them.
=> fix(artifacts): Stop copying expectedArtifactIds to child pipelines

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50Configuration.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50ConfigurationProperties.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListenerSpec.groovy
in DependentPipelineExecutionListener when the front50.useTriggeredByEndpoint configuration property is true.  The default value is false.
The advantage of the new endpoint is that front50 only returns a (potentially very small) subset of pipelines over the wire to orca, in contrast to the current behavior where front50 returns all pipelines, and leaves it to orca to filter them.
Depends on https://github.com/spinnaker/front50/pull/1251 to add the new endpoint.
=> feat(front50): call front50's GET /pipelines/triggeredBy/{pipelineId}/{status} endpoint

orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplateService.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/FileTemplateSchemeLoader.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/Front50SchemeLoader.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/HttpTemplateSchemeLoader.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/ResourceSchemeLoader.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/TemplateLoader.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/TemplateSchemeLoader.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutator.java, orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandler.kt, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/loader/TemplateLoaderSpec.groovy, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutatorSpec.groovy, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaIntegrationSpec.groovy, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandlerSpec.groovy, orca-pipelinetemplate/src/test/resources/templates/dynamic-stages-001.yml
Adds support for using jinja expressions at the top level in the stages block. Because the template file had to be both well-formed YAML and adhering to the schema defined in `PipelineTemplate`, there was no way to use expressions at the top level here, as can be seen in the `dynamic-stages-001.yml` file. With this patch Orca will first load the yaml file as a `Map` instead of directly as a `PipelineTemplate`. Then it will parse any variables to create a context for the Jinja parser, and if the stages section is a single string, it will parse any Jinja expressions in the stages section. Finally it will load the result as `PipelineTemplate`, just as before, and proceed with processing the rest of the handler chain.
This lets you do stuff like this:
```yaml
schema: "1"
id: simpleTemplate …
```
=> feat(mpt-v1): Support for jinja expressions in stages

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/DeploymentManifest.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/ServiceManifest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestEvaluatorTest.java, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
This commit adds artifact storage to orca. The new artifact type
remote/base64 is completely compatible with SpEL and users can use the
same SpEL expressions. Meaning that this change should be completely
transparent to users
Signed-off-by: benjamin-j-powell <benjamin_j_powell@apple.com>
Co-authored-by: Nicolas Favre-Felix <nff@apple.com>
Signed-off-by: benjamin-j-powell <benjamin_j_powell@apple.com>
=> feat(artifacts): Add ArtifactStore to orca

orca-api-tck/orca-api-tck.gradle, orca-api/orca-api.gradle, orca-bakery/orca-bakery.gradle, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryServiceSpec.groovy, orca-bakery/src/test/java/com/netflix/spinnaker/orca/bakery/tasks/manifests/cf/BakeCloudFoundryManifestTaskTest.java, orca-clouddriver-provider-titus/orca-clouddriver-provider-titus.gradle, orca-clouddriver/orca-clouddriver.gradle, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestServiceSpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/model/ManifestTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStageTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletionTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTaskTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableTaskTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/DeployAppEngineConfigurationTaskTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/tasks/artifacts/FindArtifactFromPipelineExecutionTaskTest.java, orca-core/orca-core.gradle, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/CompoundExecutionOperatorTest.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/persistence/PipelineExecutionRepositoryTest.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverTest.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtilsTest.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtilsTest.java, orca-kayenta/src/test/java/com/netflix/spinnaker/orca/kayenta/pipeline/functions/KayentaConfigExpressionFunctionProviderTest.java, orca-plugins-test/orca-plugins-test.gradle, orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueIntegrationTest.kt, orca-queue-sql/src/test/kotlin/com/netflix/spinnaker/orca/q/sql/SqlQueueIntegrationTest.kt, orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt, orca-sql/orca-sql.gradle, orca-web/orca-web.gradle, orca-web/src/test/groovy/com/netflix/spinnaker/orca/MainSpec.java, orca-web/src/test/java/com/netflix/spinnaker/orca/MeterRegistryProcessorIntTest.java
Before refactor, total test cases executed were 4230. 
After refactor, total test cases executed are 4233.
=> refactor(tests): convert junit4 based test cases to junit5, clean up and unpin mockito in orca

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
fixes https://github.com/spinnaker/spinnaker/issues/6850
Expected artifacts can be used in automated triggers and stages,
as in the following example:
if we trigger the previous pipeline with a pipeline stage like the next image
you will get the following error even if the parent pipeline provides the artifact
in the example, I'm using a `Find Artifacts From Resource (Manifest)` stage 
and producing a docker image as an artifact, I believe this is a similar case for building
the docker image using Jenkins like is mentioned in https://github.com/spinnaker/spinnaker/issues/6850
Before the following PRs (i.e. in spinnaker < 1.30) `Deploy (Manifest)` stage was working
https://github.com/spinnaker/orca/pull/4322
https://github.com/spinnaker/orca/pull/4322 …
=> fix(artifacts): consider requiredArtifactIds in expected artifacts when trigger is pipeline type

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/ManifestLabelValueExpressionFunctionProvider.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/ManifestLabelValueExpressionFunctionProviderSpec.groovy
We have a use case where we want to make a stage conditional based on the value of the sequence label. This label isn't present in the `manifests` field of the context, because it's only applied during deployment by Clouddriver.
The `outputs.manfiests` field contains the full Kubernetes manifests that were deployed by Clouddriver, including labels added by Spinnaker during deployment. This should be a backwards compatible change, as the labels in the `manifests` field are obviously also included in the `outputs.manfiests` field.
I would have preferred to make this change optional using a default function argument of false, but it seems the `FunctionParameter` [class](https://github.com/spinnaker/kork/blob/1d5d80b2b9618bc801e012bf5bf29c97041ac8ec/kork-api/src/main/java/com/netflix/spinnaker …
=> fix(expressions): fetch labels from actually deployed manfiest

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolver.groovy, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/OortService.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolverSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/SourceResolverSpec.groovy
A bit of cleanup that makes it easier/possible to start using SpinnakerRetrofitErrorHandler in more places.
=> TargetServerGroupResolver cleanup

orca-queue/orca-queue.gradle, orca-queue/src/test/java/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerExceptionHandlerTest.java, orca-retrofit/orca-retrofit.gradle, orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy, orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/BaseRetrofitExceptionHandler.groovy, orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandler.groovy, orca-retrofit/src/main/java/com/netflix/spinnaker/orca/retrofit/exceptions/SpinnakerServerExceptionHandler.java, orca-retrofit/src/test/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/BaseRetrofitExceptionHandlerSpec.groovy, orca-retrofit/src/test/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/DummyRetrofitApi.java, orca-retrofit/src/test/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandlerSpec.groovy, orca-retrofit/src/test/java/com/netflix/spinnaker/orca/retrofit/RetrofitConfigurationTest.java, orca-retrofit/src/test/java/com/netflix/spinnaker/orca/retrofit/exceptions/SpinnakerServerExceptionHandlerTest.java
Not used yet, since orca doesn't use SpinnakerRetrofitErrorHandler, and doesn't explicitly throw SpinnakerServerException, nor its children.  Once we do use it, we'll get similar information present in the execution context if a SpinnakerServerException happens as we get today if a RetrofitError happens, and the same retry behavior.
=> feat(retrofit): add SpinnakerServerExceptionHandler

orca-bakery/orca-bakery.gradle, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryServiceSpec.groovy
A bit of cleanup inspired by some flaky tests.
=> refactor(bakery/test): wiremock cleanup

orca-bakery/orca-bakery.gradle, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/config/BakeryConfiguration.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy, orca-bakery/src/main/java/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryServiceSpec.groovy, orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy
- add SpinnakerRetrofitErrorHandler while creating BakeryService
- add retry support to createBake() method in CreateBakeTask
- add retry support to bakeManifest() method in CreateBakeManifestTask
=> refactor(retrofit): use SpinnakerRetrofitErrorHandler as a step towards simplifying exception handling

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtils.java, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtilsSpec.groovy
8df68b79cf1 broke custom triggers to Spinnaker integration. Prior to this commit if `getBoundArtifactForStage` failed to find a bound artifact, resolution would happen much later by utilizing the `triggers` field in stages.  However, `getBoundArtifactForStage` now throws an exception, which causes custom triggers to fail prematurely. Also if a custom trigger calls orchestrate directly and any pipeline contains `getBoundArtifactForStage`, this will throw an exception and prevent any resolution.
@jervi: please take a look at this as I noticed a couple of your PRs made some changes to artifact resolving, but I believe they only partially implemented the needed solution.
=> fix(artifacts): Resolving is broken in multiple places

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ClusterSizePreconditionTask.groovy
While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encountered the below error:
```
> Task :orca-clouddriver:compileGroovy FAILED
/orca/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ClusterSizePreconditionTask.groovy: 156: Illegal modifier for the enum constructor; only private is permitted.
@ line 156, column 5.
public Operator(String value, Closure<Boolean> closure) {
^
1 error
FAILURE: Build failed with an exception.
```
To fix this issue replaced the public modifier to private in ClusterSizePreconditionTask.groovy
For reference https://stackoverflow.com/questions/7113363/private-enum-constructor
=> refactor(cloudriver): fix enum constructor modifier as private during upgrade to groovy 3.x

orca-flex/src/test/groovy/com/netflix/spinnaker/orca/flex/tasks/AssociateElasticIpTaskSpec.groovy
While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encountered the following errors in groovy test compilation of orca-flex module:
```
> Task :orca-flex:compileTestGroovy FAILED
/orca/orca-flex/src/test/groovy/com/netflix/spinnaker/orca/flex/tasks/AssociateElasticIpTaskSpec.groovy: 30: The current scope already contains a variable of the name application
@ line 30, column 75.
count, cluster, region, _) >> { applicat
^
/orca/orca-flex/src/test/groovy/com/netflix/spinnaker/orca/flex/tasks/AssociateElasticIpTaskSpec.groovy: 30: The current scope already contains a variable of the name account
@ line 30, column 75.
count, cluster, region, _) >> { applicat
^
/orca/orca-flex/src/test/groovy/com/netflix/spinnaker/orca/flex/tasks/AssociateElasticIpTaskSpec.groovy: …
```
=> refactor(flex/test): fix conflict of variable scope by renaming local variables during upgrade of groovy 3.x

orca-web/orca-web.gradle, orca-webhook/orca-webhook.gradle
While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, groovy-json is not part of [spockframework](https://mvnrepository.com/artifact/org.spockframework/spock-core/2.0-groovy-3.0) and encounter below error during test compilation:
```
/orca/orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy: 45: unable to resolve class groovy.json.JsonSlurper
@ line 45, column 1.
import groovy.json.JsonSlurper
^
/orca/orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy: 32: unable to resolve class groovy.json.JsonSlurper
@ line 32, column 1.
import groovy.json.JsonSlurper
^
2 errors
> Task :orca-web:compileTestGroovy FAILED
```
```
> Task :orca-webhook:compileTestGroovy FAILED …
```
=> chore(dependency): add explicit dependency of groovy-json in orca-web and orca-webhook during upgrade of groovy 3.x

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/loadbalancer/UpsertLoadBalancerStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ModifyAwsScalingProcessStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/DetermineTargetServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/DetermineTargetReferenceStage.groovy
While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encountered the following errors in orca-clouddriver module:
```
> Task :orca-clouddriver:compileGroovy
/orca/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/loadbalancer/UpsertLoadBalancerStage.groovy: 35: [Static type checking] - Cannot find matching method com.netflix.spinnaker.orca.clouddriver.pipeline.loadbalancer.UpsertLoadBalancerStage#getType(java.lang.Class <com.netflix.spinnaker.orca.clouddriver.pipeline.loadbalancer.UpsertLoadBalancerStage>). Please check if the declared type is correct and if the method exists.
@ line 35, column 39.
final String PIPELINE_CONFIG_TYPE = getType(UpsertLoadBalancerStage)
^
1 error
> Task :orca-clouddriver:compileGroovy FAILED
```
```
> …
```
=> refactor(clouddriver): fix scope resolution of static method explictly calling by class name during upgrade to groovy 3.x

orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtilsSpec.groovy
While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encountered the following errors in groovy test orca-core module:
```
Stub 'executionRepository' matches the following required interaction:
0 * _   (0 invocations)
Remove the cardinality (e.g. '1 *'), or turn the stub into a mock.
org.spockframework.runtime.InvalidSpecException: Stub 'executionRepository' matches the following required interaction:
0 * _   (0 invocations)
Remove the cardinality (e.g. '1 *'), or turn the stub into a mock.
at app//org.spockframework.mock.constraint.TargetConstraint.setInteraction(TargetConstraint.java:57)
at app//org.spockframework.mock.runtime.MockInteraction.<init>(MockInteraction.java:53)
at app//org.spockframework.mock.runtime.InteractionBuilder.build(InteractionBuilder.java:187)
at …
```
=> refactor(core/test): fix cardinality issue by replacing Stub to Mock during upgrade to groovy 3.x

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStageSpec.groovy
While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encountered the following errors in groovy test orca-clouddriver module:
```
No signature of method: com.netflix.spinnaker.orca.clouddriver.pipeline.servergroup.strategies.AbstractDeployStrategyStage.getNoStrat() is applicable for argument types: () values: []
Possible solutions: getNoStrategy(), setNoStrategy(com.netflix.spinnaker.orca.clouddriver.pipeline.servergroup.strategies.NoStrategy)
groovy.lang.MissingMethodException: No signature of method: com.netflix.spinnaker.orca.clouddriver.pipeline.servergroup.strategies.AbstractDeployStrategyStage.getNoStrat() is applicable for argument types: () values: []
Possible solutions: getNoStrategy(), setNoStrategy(com.netflix.spinnaker.orca.clouddriver.pipeline.servergroup.strategie …
```
=> refactor(clouddriver/test): refactor Spy.with{} closure during upgrade to groovy 3.x

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTaskSpec.groovy
give the task terminal status in this case since that feels closer to the truth than succeeded even though the error is likely elsewhere (e.g. in a StartPipelineTask).
=> fix(front50): teach MonitorPipelineTask to handle missing/null execution ids

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
This fix allows us to revert https://github.com/spinnaker/orca/pull/4397
since that makes retrieving bound artifacts actually more strict for
most use cases. So this commit addresses the root cause that that PR was
trying to implement.
When a parent pipeline triggers a child pipeline, the child pipeline should be able to
resolve incoming artifacts properly. Right now that does not happen
because `expectedArtifactIds` is needed in the trigger section,
otherwise no resolution will occur.
This change fixes the parent payload to include `expectedArtifactIds` by
viewing the child pipeline's top level expected artifacts and finding
the intersection between expected artifacts and artifacts to be sent.
With that intersection we can grab the expected artifact ids and
properly set the the necessary …
=> fix(artifacts): Parent and child pipeline artifact resolution

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
While upgrading springboot 2.5.15, encounter below error in orca-bakery module:
```
/orca/orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy: 177: [Static type checking] - Incompatible generic argument types. Cannot assign java.util.List <java.lang.Object> to: java.util.List <String>
@ line 177, column 43.
<String> distinctImageNames = relatedBak
^
1 error
> Task :orca-bakery:compileGroovy FAILED
```
To fix this issue use explicit object reference of `List<StageExecution>` to hold and operate on the object stream, and `List` to capture the filtered generic objects.
=> refactor(bakery): fix incompatible generic type issue faced during upgrade to springboot 2.5.15

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/JarDiffsTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/AbstractQuipTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/InstanceHealthCheckTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/MonitorQuipTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/VerifyQuipTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/JarDiffsTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/InstanceHealthCheckTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/MonitorQuipTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTaskSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/VerifyQuipTaskSpec.groovy
As part of this PR , the target is to eliminate the usage of RetrofitError in InstanceService retrofit client under module orca-clouddriver. 
Replaced the exception handling logic with the handleError method under SpinnakerRetrofitErrorHandler class.
=> refactor(clouddriver) : InstanceService - Eliminated the usages of RetrofitError exception handling and replaced it with SpinnakerRetrofitErrorHandler

orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt
While upgrading Kotlin 1.5.32, encounter below error in orca-peering module:
```
> Task :orca-peering:compileKotlin FAILED
e: /orca/orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt: (197, 55): Using 'maxBy((T) -> R): T?' is an error. Use maxByOrNull instead.
e: /orca/orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt: (258, 52): Using 'max(): T?' is an error. Use maxOrNull instead.
```
To fix this error, replaced the deprecated method.
=> refactor(peering): replace deprecated method during upgrade to Kotlin 1.5.32

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandlerTest.kt
While upgrading Kotlin 1.5.32, encounter below error in orca-queue module:
```
> Task :orca-queue:compileKotlin FAILED
e: /orca/orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt: (355, 21): Using 'max(): T?' is an error. Use maxOrNull instead.
```
```
> Task :orca-queue:compileTestKotlin FAILED
e: /orca/orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandlerTest.kt: (136, 37): Using 'minBy((T) -> R): T?' is an error. Use minByOrNull instead.
e: /orca/orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandlerTest.kt: (137, 37): Using 'maxBy((T) -> R): T?' is an error. Use maxByOrNull instead.
```
To fix this error, replaced the deprecated method.
=> refactor(queue): replace deprecated method during upgrade to Kotlin 1.5.32

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestServiceSpec.groovy
While running complete test as `./gradlew --no-build-cache cleanTest test`, encountered below error in orca-clouddriver module with `KatoRestServiceSpec` intermittently:
```
java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8080
com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8080
at app//com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:146)
at app//com.netflix.spinnaker.orca.clouddriver.KatoRestServiceSpec.setup(KatoRestServiceSpec.groovy:61)
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8080
at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:137)
at …
```
=> fix(test): fix intermittent issue of port binding by using dynamic port for WireMockServer

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/cache/ClouddriverClearAltTablespaceTask.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/cache/ClouddriverClearAltTablespaceTaskTest.java
change exception handling in ClouddriverClearAltTablespaceTask to check for Spinnaker*Exception since, as of https://github.com/spinnaker/orca/pull/4528, CloudDriverCacheService uses SpinnakerRetrofitErrorHandler.
=> fix(clouddriver): change exception handling in ClouddriverClearAltTablespaceTask

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryServiceSpec.groovy
to reduce intermittent port conflict failures
similar to https://github.com/spinnaker/orca/pull/4600.
=> fix(bakery/test): use dynamic port in BakeryServiceSpec

keiko-core/src/test/kotlin/com/netflix/spinnaker/q/MessageHandlerTest.kt, keiko-core/src/test/kotlin/com/netflix/spinnaker/q/QueueProcessorTest.kt, keiko-tck/src/main/kotlin/com/netflix/spinnaker/q/QueueTest.kt, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/CFRollingRedBlackStrategyTest.java, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueShovelTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/admin/HydrateQueueCommandTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/AbortStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ConfigurationErrorHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/PauseStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/SkipStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandlerTest.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/metrics/ZombieExecutionCheckingAgentTest.kt
While upgrading spring boot 2.6.15, encounter similar errors as given below in multiple module of orca (keiko-core, keiko-tck, orca-clouddriver, orca-queue) during test compilation:
```
com.netflix.spinnaker.q.sql.SqlQueueTest > describe polling the queue > given there are no messages > com.netflix.spinnaker.q.sql.SqlQueueTest.it does not invoke the callback FAILED
java.lang.NoSuchMethodError: 'void org.mockito.Mockito.verifyZeroInteractions(java.lang.Object[])'
at com.nhaarman.mockito_kotlin.MockitoKt.verifyZeroInteractions(Mockito.kt:259)
at com.netflix.spinnaker.q.QueueTest$1$1$1$5.invoke(QueueTest.kt:75)
at com.netflix.spinnaker.q.QueueTest$1$1$1$5.invoke(QueueTest.kt:74)
```
Spring boot [2.6.15](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.15/sp …
=> refactor(test): replace deprecated mockito api verifyZeroInteractions() with verifyNoMoreInteractions() during upgrade to spring boot 2.6.x

orca-clouddriver/orca-clouddriver.gradle, orca-core/orca-core.gradle, orca-kayenta/orca-kayenta.gradle
with com.github.tomakehurst:wiremock-jre8-standalone
to get up to date, and to reduce the number of classes on the classpath.
before:
```
+--- com.github.tomakehurst:wiremock:2.15.0
|    +--- org.eclipse.jetty:jetty-server:9.2.22.v20170606 -> 9.4.51.v20230217
|    |    +--- javax.servlet:javax.servlet-api:3.1.0 -> 4.0.1
|    |    +--- org.eclipse.jetty:jetty-http:9.4.51.v20230217
|    |    |    +--- org.eclipse.jetty:jetty-util:9.4.51.v20230217
|    |    |    \--- org.eclipse.jetty:jetty-io:9.4.51.v20230217
|    |    |         \--- org.eclipse.jetty:jetty-util:9.4.51.v20230217
|    |    \--- org.eclipse.jetty:jetty-io:9.4.51.v20230217 (*)
|    +--- org.eclipse.jetty:jetty-servlet:9.2.22.v20170606 -> 9.4.51.v20230217
|    |    +--- org.eclipse.jetty:jetty-security:9.4.51.v20230217
|    | …
```
=> chore(dependencies): replace com.github.tomakehurst:wiremock

orca-queue-sql/src/test/kotlin/com/netflix/spinnaker/orca/q/sql/SqlQueueIntegrationTest.kt
While upgrading spring boot 2.6.15 and spring cloud 2021.0.8, encounter below errors in orca-queue-sql module during SqlQueueIntegrationTest execution and 19 tests fail with similar error:
```
./gradlew :orca-queue-sql:test --tests "com.netflix.spinnaker.orca.q.sql.SqlQueueIntegrationTest"
Failed to load ApplicationContext
java.lang.IllegalStateException: Failed to load ApplicationContext
at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:98)
at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
at …
```
=> refactor(sql/test): remove circular reference from SqlQueueIntegrationTest identified during upgrade to spring boot 2.6.x

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ResizeServerGroupProperties.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupProperties.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForCapacityMatchTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForCapacityMatchTaskSpec.groovy
Some of our users prefer to use the actual instance size list to verify if everything was scaled up or down accordingly instead of relying on the target percentage. They noticed this is causing instability on their end
=> feat(servergroup): Allow users to opt-out of the target desired size check when verifying if the instances scaled up or down successfully

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilderTest.java, orca-web/src/test/java/com/netflix/spinnaker/orca/controllers/OperationsControllerTest.java
so callers see 400 with a helpful mesage instead of 500.
There's also code here in PipelineBuilder.withStages to throw an IllegalArgumentException for null stages.  Due to [this change](https://github.com/spinnaker/orca/pull/4102/files#diff-88a2bb8f8eddf44a88866f3d27f096d67577c6c5f651acd88fdb3da32ed88d0aR211) in https://github.com/spinnaker/orca/pull/4102, PipelineBuilder.withStages isn't called with null even if stages is null in the incoming pipeline.  https://github.com/spinnaker/orca/pull/4182 (Nov 30, 2021, version 1.28.0) was a behavior change from a NullPointerException/500 to succeed (but do nothing) for a pipeline with null stages.  https://github.com/spinnaker/orca/pull/4102 (Jan 3, 2022) was also part of version 1.28.0.  Changing the behavior to explictly reject null stages / …
=> fix(core): handle null when invoking pipelines with stages that are missing a "type"

orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/BuildService.java, orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildServiceSpec.groovy
Fixes https://github.com/spinnaker/spinnaker/issues/6928
The implementation of: 
```
feature:
igor:
jobNameAsQueryParameter: true
```
did not include the support  for Jenkins artifacts and property files leading to failures on Manual triggers and rerun's of a Spinnaker pipeline retrieving BuildInfo from the sub-folder Jenkins job.
=> fix(jenkins): Enable properties and artifacts with job name as query parameter

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/DeleteApplicationTask.groovy, orca-keel/orca-keel.gradle, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/config/KeelConfiguration.kt, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt, orca-keel/src/test/java/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTaskTest.java, orca-keel/src/test/kotlin/com/netflix/spinnaker/orca/keel/ImportDeliveryConfigTaskTests.kt
This PR lays the foundational work for upgrading the retrofit version to 2.x, specifically focusing on refactoring the exception handling for KeelService.
Note, there's a behaviour change on the Task Results error message format when KeelService API throws any 4xx/5xx http errors with empty error body.
- On any 4xx http errors with empty error body:
before:
11:56:19.324 [Test worker] ERROR com.netflix.spinnaker.orca.keel.task.ImportDeliveryConfigTask - {message=Non-retryable HTTP response 400 received from downstream service: HTTP 400 http://localhost:62130/delivery-configs/: 400 Bad Request}
after:
12:00:02.018 [Test worker] ERROR com.netflix.spinnaker.orca.keel.task.ImportDeliveryConfigTask - {message=Non-retryable HTTP response 400 received from downstream service: HTTP 400 …
=> refactor(keel): use SpinnakerRetrofitErrorHandler with KeelService

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/config/IgorConfiguration.groovy, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorQueuedJenkinsJobTask.groovy, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorWerckerJobStartedTask.groovy, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartJenkinsJobTask.groovy, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartScriptTask.groovy, orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/tasks/RetryableIgorTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetAwsCodeBuildArtifactsTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildPropertiesTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetGoogleCloudBuildArtifactsTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorAwsCodeBuildTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorGoogleCloudBuildTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/RetryableIgorTaskSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartJenkinsJobTaskSpec.groovy, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt, orca-keel/src/test/kotlin/com/netflix/spinnaker/orca/keel/ImportDeliveryConfigTaskTests.kt, orca-web/orca-web.gradle, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
This PR lays the foundational work for upgrading the retrofit version to 2.x, specifically focusing on refactoring the exception handling for IgorService.
There are no behaviour changes detected with these code changes and hence no additional tests added to demonstrate the functionalities. Few existing tests are modified to align it with the new changes.
=> refactor(igor): use SpinnakerRetrofitErrorHandler with IgorService

orca-core/orca-core.gradle, orca-pipelinetemplate/orca-pipelinetemplate.gradle, orca-webhook/orca-webhook.gradle
because the version from kork-bom/spring boot takes precedence.
From `$ ./gradlew orca-core:dependencies`, `$./gradlew orca-webhook:dependencies` and `$ ./gradlew orca-pipelinetemplate:dependencies` before:
```
+--- com.jayway.jsonpath:json-path:2.2.0 -> 2.5.0
|    +--- net.minidev:json-smart:2.3 -> 2.4.10
|    |    \--- net.minidev:accessors-smart:2.4.9
|    |         \--- org.ow2.asm:asm:9.3
```
after:
```
+--- com.jayway.jsonpath:json-path -> 2.5.0
|    +--- net.minidev:json-smart:2.3 -> 2.4.10
|    |    \--- net.minidev:accessors-smart:2.4.9
|    |         \--- org.ow2.asm:asm:9.3
```
=> chore(dependencies): unpin com.jayway.jsonpath:json-path

orca-echo/orca-echo.gradle, orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/config/EchoConfiguration.groovy
This code change is to maintain the uniformity across all the retrofit client configurations in ORCA,  as part of upgrading the retrofit version to 2.x.
There are neither any changes to the exception handler logics nor any behaviour changes involved.
=> refactor(echo): use SpinnakerRetrofitErrorHandler with EchoService

keiko-sql/src/main/kotlin/com/netflix/spinnaker/q/sql/SqlQueue.kt, keiko-sql/src/test/kotlin/com/netflix/spinnaker/q/sql/SqlQueueTest.kt
`SqlQueue#doContainsMessage` doesn't process more than 1 batch because of an incorrect loop inside. When the last element in the batch is processed (`ResultSet#next` returns `false`), the following invocation of `ResultSet#getRow` will return 0. No matter how many rows were processed before.
Basically, this PR is just a copy of https://github.com/spinnaker/orca/pull/4184 with addressed comments. But https://github.com/spinnaker/orca/pull/4184 is abandoned so opened this one. Kudos to Ivor for the original PR
=> fix(queue): Fix `SqlQueue#doContainsMessage` to handle queues with more than 100 items

orca-flex/orca-flex.gradle, orca-flex/src/main/groovy/com/netflix/spinnaker/orca/flex/config/FlexConfiguration.groovy
This code change is to maintain the uniformity across all the retrofit client configurations in ORCA,  as part of upgrading the retrofit version to 2.x.
There are neither any changes to the exception handler logics nor any behaviour changes involved.
=> refactor(flex): use SpinnakerRetrofitErrorHandler with FlexService

orca-kayenta/orca-kayenta.gradle, orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/config/KayentaConfiguration.kt
As part of the upgradation process of retrofit version to 2.x, this PR aims at ensuring the uniformity across all the retrofit client configurations.
Since the use of RetrofitError are not detected, no changes in the exception handler and no behaviour changes as well.
=> refactor(kayenta): use SpinnakerRetrofitErrorHandler with KayentaService

orca-retrofit/orca-retrofit.gradle, orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/BaseRetrofitExceptionHandler.groovy, orca-retrofit/src/main/java/com/netflix/spinnaker/orca/retrofit/exceptions/SpinnakerServerExceptionHandler.java, orca-retrofit/src/test/java/com/netflix/spinnaker/orca/retrofit/exceptions/SpinnakerServerExceptionHandlerTest.java
`BaseRetrofitExceptionHandler`'s retry behavior uses a method called `findHttpMethodAnnotation` to retrieve an exception's HTTP method. For retrofit2 exceptions, this method no longer works due to things being annotated differently in retrofit2. However, Spinnaker*Exceptions can use `getHttpMethod()` to retrieve this value, so this PR updates the exception handler to default to using the getter and only use `findHttpMethodAnnotation` if the getter returns null.
=> fix(retrofit): use SpinnakerServerException.getHttpMethod() instead of reflection in SpinnakerServerExceptionHandler

orca-mine/orca-mine.gradle, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/config/MineConfiguration.groovy, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStage.groovy, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/DisableCanaryTask.groovy, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/MonitorAcaTaskTask.groovy, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/MonitorCanaryTask.groovy, orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/RegisterCanaryTask.groovy, orca-mine/src/test/java/com/netflix/spinnaker/orca/mine/tasks/RegisterCanaryTaskTest.java
This PR lays the foundational work for upgrading the retrofit version to 2.x, specifically focusing on refactoring the exception handling for MineService
There is no behaviour changes involved. Couple of tests added to verify the same for only RegisterCanaryTask in the previous commits.
=> refactor(mine): use SpinnakerRetrofitErrorHandler with MineService

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/RollbackConfigurationProperties.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollbackSpec.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTaskSpec.groovy
When a user performs an Ad-Hoc Rollback through Deck, Orca is expecting to receive a response from Clouddriver about the serverGroup details in a hardcoded 5 seconds timeout. 
Although in most cases this is enough, in higher scale environments with thousands of AWS/ECS accounts and especially in applications that have a large amount of serverGroups the 5 sec timeout is too strict resulting in error during the serverGroup lookup.
With this change we can configure the timeout (in seconds) through Orca config - while defaulting to the previous timeout of 5secs.
=> fix(explicitRollback): Add configurable timeout for serverGroup lookup from Clouddriver API

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt
Searching for the executions of the pipelines of an application by triggerType and eventId (Gate endpoint: applications/<app>/executions/search?triggerTypes=<triggerType>&eventId=<eventId>) query execution is not optimal and creates high response times as the execution history of the application increases and/or the application has a lot of pipelines. 
The retrievePipelinesForPipelineConfigIdsBetweenBuildTimeBoundary creates  SQL queries with LIMIT 20 and OFFSET that look like this:
```
select id, body, `partition`
from pipelines
where (config_id in (<List of PipelineConfigIds in App>) and build_time > 0 and build_time < 9223372036854775807)
order by build_time desc limit 20
offset X;
```
With this change the queries are optimised with a deferred join (see …
=> perf(sql): Optimise searchForPipelinesByTrigger LIMIT and OFFSET SQL query

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/DeleteApplicationTask.groovy, orca-applications/src/test/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTaskSpec.groovy, orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pollers/EphemeralServerGroupsPoller.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/job/JobUtils.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy, orca-front50/orca-front50.gradle, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50Configuration.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/AbstractFront50Task.groovy, orca-front50/src/main/java/com/netflix/spinnaker/orca/front50/pipeline/EnabledPipelineValidator.java, orca-front50/src/main/java/com/netflix/spinnaker/orca/front50/tasks/DeleteDeliveryConfigTask.java, orca-front50/src/main/java/com/netflix/spinnaker/orca/front50/tasks/MonitorFront50Task.java, orca-front50/src/main/java/com/netflix/spinnaker/orca/front50/tasks/UpsertDeliveryConfigTask.java, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/pipeline/EnabledPipelineValidatorSpec.groovy, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy, orca-pipelinetemplate/orca-pipelinetemplate.gradle, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/loader/Front50SchemeLoaderSpec.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/ProjectController.groovy, orca-web/src/main/java/com/netflix/spinnaker/orca/controllers/ExecutionsImportController.java, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/ExecutionsImportControllerSpec.groovy
This PR lays the foundational work for upgrading the retrofit version to 2.x, specifically focusing on refactoring the exception handling for Front50Service.
There are no behaviour changes detected with these code changes and hence no additional tests added to demonstrate the functionalities.
Few existing tests are modified to align it with the new changes.
=> refactor(front50): use SpinnakerRetrofitErrorHandler with Front50Service

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/PipelineExecution.java, orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/StageExecution.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineExecutionImpl.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/StageExecutionImpl.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/model/PipelineExecutionImplTest.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/ExecutionMapper.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-sql/src/test/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepositoryTest.kt
to make changes in size over time more observable.  This makes it easier to see the impact of features like the artifact store.
Not setting the size in RedisExecutionRepository because the extra objectMapper.writeValueAsString is potentially expensive and I'm not sure how many folks are using redis for this.
=> feat(sql): log the size of executions when they complete

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50ConfigurationProperties.java, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListenerSpec.groovy
so orca only queries for the pipelines it needs from front50 instead of all of them.
https://github.com/spinnaker/orca/pull/4448 introduced this feature on Apr 20, 2023, first released in version 1.31.0 of Spinnaker.  Enough time has passed to enable this by default.
=> feat(front50): set front50.useTriggeredByEndpoint to true by default

orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt, orca-keel/src/test/java/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTaskTest.java
This fix removes the javadoc link to the missing method: handleRetryableFailures(RetrofitError, ImportDeliveryConfigContext), which was cleaned up as part of the commit : 32e6571ad0578b9745a30fde75a85e8ac0d2b6b1.
=> fix(test/keel): Javadoc referring to missing method in ImportDeliveryConfigTaskTest

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTaskSpec.groovy
With the introduction of the commit: e63a661e215461bd10ff0af90d416e9ca7fcfa6c , the expected behaviour of all BakeryService APIs is to throw Spinnaker*Exception when any http error has occurred.
- CompletedBakeTask is invoking an API : lookupBake(region, bakeid) -https://github.com/spinnaker/orca/blob/d2f50242637207491ba9fdcc40eaf02c3255c447/orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTask.groovy#L43. This API error response is mocked up with RetrofitError in the test : https://github.com/spinnaker/orca/blob/d2f50242637207491ba9fdcc40eaf02c3255c447/orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTaskSpec.groovy#L84
- This test case seems to be invalid/irrelevant because it has to throw SpinnakerHttpException here.
This …
=> fix(test/bakery): Mock http error using SpinnakerHttpException in CompletedBakeTaskSpec

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryServiceSpec.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolver.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
As part of the foundational work paving the way towards migrating to retrofit 2.x, this PR aims at cleaning up unused occurrences of RetrofitError throughout ORCA service.
=> refactor(retrofit): Cleanup unused RetrofitError occurrences

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/WaitForCloudFormationCompletionTaskSpec.groovy
With the introduction of the commit: 84a7106c512ceada65d7799f527a956262d964d5 , the expected behaviour of all OortService APIs is to throw SpinnakerHttpException when any http error has occurred.
Here in this test the response of the API : https://github.com/spinnaker/orca/blob/a1b32d7398eb9b1ff610d7f3afd980b51f6cf7b1/orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/OortService.java#L182 is mocked up with RetrofitError which makes the test irrelvant.
Wrapping the RetrofitError in SpinnakerHttpException to make it in compliance with the retrofit configuration.
=> fix(test/clouddriver): Mock http error using SpinnakerHttpException in WaitForCloudFormationCompletionTaskSpec

orca-integration/src/test/java/com/netflix/spinnaker/orca/BaseContainerTest.java, orca-integration/src/test/java/com/netflix/spinnaker/orca/PostgresMigrationContainerTest.java, orca-sql/src/main/resources/db/changelog/20180510-add-legacy-id-fields.yml, orca-sql/src/main/resources/db/changelog/20180515-execution-canceled-column.yml, orca-sql/src/main/resources/db/changelog/20180521-status-enum.yml, orca-sql/src/main/resources/db/changelog/20180724-partitions.yml, orca-sql/src/main/resources/db/changelog/20181016-add-start-time.yml, orca-sql/src/main/resources/db/changelog/20200327-deleted-executions-table.yml
Added new integration test to validate the postgres migration scenario which uses latest 1.32.x image(us-docker.pkg.dev/spinnaker-community/docker/orca:8.36.3-dev-release-1.32.x-3f8965d03-202406101625-unvalidated) as base image. 
This PR fixes checkSum errors caused after liquibase upgrade(to 4.24.0) as the checksum calculations in liquibase underwent some changes causing this issue.
This PR fixes the checksum errors by adding validChecksum tags to the failing changesets.
Similar clouddriver PR for reference: https://github.com/spinnaker/clouddriver/pull/6217
=> fix(liquibase): fix checkSum errors occurring with spinnaker upgrade

build.gradle, gradle/dokka.gradle
to fix release builds (e.g. https://github.com/spinnaker/orca/actions/runs/9485164370/job/26140574935) that fail with:
```
2024-06-12T16:46:31.8095689Z java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
2024-06-12T16:46:31.8098205Z 	at org.jetbrains.org.objectweb.asm.ClassVisitor.visitPermittedSubclass(ClassVisitor.java:266)
2024-06-12T16:46:31.8100476Z 	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:684)
2024-06-12T16:46:31.8103055Z 	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:402)
2024-06-12T16:46:31.8105572Z 	at org.jetbrains.kotlin.load.kotlin.FileBasedKotlinClass.create(FileBasedKotlinClass.java:96)
2024-06-12T16:46:31.8108484Z 	at org.jetbrains.kotlin.load.kotlin.VirtualFileKotlinClass$Factory$create$1.invoke( …
```
=> fix(dokka): use version 1.9.20 of org.jetbrains.dokka

.github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/release.yml, Dockerfile.compile, build.gradle, gradle.properties, gradle/dokka.gradle, orca-api/orca-api.gradle
since it's not possible to release orca jars, which we need to do to finish adopting spring boot 2.7 everywhere (e.g. in kayenta).
This reverts https://github.com/spinnaker/orca/pull/4747 and https://github.com/spinnaker/orca/pull/4738.
=> fix(build): revert java17 changes

.github/workflows/build.yml, .github/workflows/pr.yml
so things fail earlier, as opposed to later during publishing as part of a release
See e.g. https://github.com/spinnaker/orca/actions/runs/9485164370/job/26140574935.
=> chore(build): exercise dokka in prs and branch builds

orca-integration/src/test/java/com/netflix/spinnaker/orca/BaseContainerTest.java, orca-integration/src/test/java/com/netflix/spinnaker/orca/PostgresMigrationContainerTest.java
to avoid failures like https://github.com/spinnaker/orca/actions/runs/9507661382/job/26207523266
```
PostgresMigrationContainerTest > testHealthCheckWithPostgres() FAILED
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image us-docker.pkg.dev/spinnaker-community/docker/orca:8.36.3-dev-release-1.32.x-3f8965d03-202406101625-unvalidated
```
also changing the timeout in BaseContainerTest to avoid failures testing locally.
=> fix(integration/test): increase container startup time

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionLengthTest.java, orca-core/src/test/resources/expression-properties.yml
Spring Expression Lanuage (SpEL) has a default limit of 10,000 characters. Springframework provides the feature to configure the limit. This feature allows to configure the limit of characters for SpEL expressions.
Approach:
In order to use an expression with characters more than the given default limit, require to follow either of the below approaches:
1. For Springframework >=5.3.28 and <6.1.3, by setting `maximumExpressionLength` field while instantiating the custom `SpelParserConfiguration` class. 
https://github.com/spring-projects/spring-framework/issues/30380 
https://github.com/spring-projects/spring-framework/issues/30446
2. For Springframework >=6.1.3, by setting a JVM system property or Spring property named `spring.context.expression.maxLength` to the maximum expression length …
=> feat(SpEL): implement to configure the limit of characters for SpEL expressions

build.gradle, orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluatorSpec.groovy
that uses a non-public constructor/method, and so requires special treatment under java 17.
=> test(core): demonstrate behavior of SpEL expression evaluation

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStageSpec.groovy
Related to https://github.com/spinnaker/orca/pull/4745; fixes the issue on the DestroyServerGroup stage
Failing tests before the fix:
=> fix(orca-clouddriver): replace getType() with StageDefinitionBuilder.getType() for DestroyServerGroup

keiko-mem-spring/keiko-mem-spring.gradle, keiko-mem-spring/src/test/kotlin/com/netflix/spinnaker/q/mem/spring/SpringStartupTests.kt, keiko-redis-spring/keiko-redis-spring.gradle, keiko-redis-spring/src/test/kotlin/com/netflix/spinnaker/q/redis/spring/SpringStartupTests.kt
Startup test under module keiko-mem-spring and keiko-redis-spring are not executing and throwing below error:
```
> Task :keiko-mem-spring:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':keiko-mem-spring:test'.
> No tests found for given includes: [com.netflix.spinnaker.q.mem.spring.SpringStartupTests](--tests filter)
```
```
> Task :keiko-redis-spring:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':keiko-redis-spring:test'.
> No tests found for given includes: [com.netflix.spinnaker.q.redis.spring.SpringStartupTests](--tests filter)
```
After fixing these issues by refactoring the junit platform as `junit-jupiter`, encountered below errors while execution:
```
Failed to load …
```
=> fix(tests): refactor tests and junit platform name to execute startup tests

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlPipelineExecutionRepositorySpec.groovy
When execution repository compression is enabled the generated query for retrieving the pipelines with configId was not returning the compressed columns from the left outer join. 
Orca was failing with: 
```
org.jooq.exception.DataAccessException: SQL [select id, body, compressed_body, compression_type, `partition` from pipelines join (select id from pipelines left outer join pipelines_compressed_executions using (id) where (config_id in (?, ?) and build_time > ? and build_time < ?) order by build_time asc limit ? offset ?) as `alias_79833741` using (id) order by build_time asc]; Unknown column 'compressed_body' in 'field list'
at app//org.jooq.impl.Tools.translate(Tools.java:2903)
at app//org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
at …
```
=> fix(sqlExecutionRepo): Return compressed columns when enabled for retrieve pipelines with configId

orca-core/orca-core.gradle, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncherTest.java, orca-core/src/test/resources/com/netflix/spinnaker/orca/pipeline/ad-hoc/pipeline-with-pipeline-trigger.json, orca-core/src/test/resources/com/netflix/spinnaker/orca/pipeline/ad-hoc/pipeline-with-pipelineRef-trigger.json, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/PipelineRefTriggerDeserializerSupplier.kt
I added more tests in executionLaucherTest regarding PipelineRef feature include as part of https://github.com/spinnaker/orca/pull/4749
=> test(sql): Add extra test  for pipelineRef feature flag

orca-pipelinetemplate/orca-pipelinetemplate.gradle, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy, orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaIntegrationSpec.groovy
While upgrading spockframework from 2.0-groovy-3.0 to 2.2-groovy-3.0, encountered below errors during test execution of orca-pipelinetemplate module:
```
> Task :orca-pipelinetemplate:compileTestGroovy FAILED
/orca/orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy: 40: unable to resolve class org.unitils.reflectionassert.ReflectionComparatorMode
@ line 40, column 1.
import org.unitils.reflectionassert.ReflectionComparatorMode
^
/orca/orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy: 45: unable to resolve class org.unitils.reflectionassert.ReflectionAssert
@ line 45, column 1.
import static …
```
=> refactor(test): replace assertion used from library unitils-core to assertj-core while spockframework upgrade to 2.2-groovy-3.0

orca-mine/orca-mine.gradle
While upgrading spockframework from 2.0-groovy-3.0 to 2.2-groovy-3.0, encountered below errors during test execution of orca-mine module:
```
/orca/orca-mine/src/test/java/com/netflix/spinnaker/orca/mine/tasks/RegisterCanaryTaskTest.java:22: error: package org.assertj.core.api does not exist
import static org.assertj.core.api.Assertions.assertThatThrownBy;
^
/orca/orca-mine/src/test/java/com/netflix/spinnaker/orca/mine/tasks/RegisterCanaryTaskTest.java:150: error: cannot find symbol
assertThatThrownBy(() -> registerCanaryTask.execute(deployCanaryStage))
^
symbol:   method assertThatThrownBy(()->regist[...]tage))
location: class RegisterCanaryTaskTest
```
To fix this issue added assertj-core dependency explicitly.
=> chore(dependency): add explicit assertj-core dependency while spockframework upgrade to 2.2-groovy-3.0

orca-applications/orca-applications.gradle, orca-clouddriver-provider-titus/orca-clouddriver-provider-titus.gradle, orca-echo/orca-echo.gradle, orca-front50/orca-front50.gradle, orca-igor/orca-igor.gradle, orca-interlink/orca-interlink.gradle, orca-mine/orca-mine.gradle, orca-peering/orca-peering.gradle, orca-pipelinetemplate/orca-pipelinetemplate.gradle, orca-webhook/orca-webhook.gradle
While upgrading spockframework from 2.0-groovy-3.0 to 2.2-groovy-3.0, encountered similar errors as mentioned below during test execution of orca-mine, orca-pipelinetemplate, orca-applications, orca-echo, orca-clouddriver-provider-titus, orca-front50, orca-igor, orca-peering, orca-interlink and orca-webhook module:
```
Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5f9b2141
at app//net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:464)
at …
```
=> chore(dependency): add explicit byte-buddy dependency while upgrading spockframework to 2.2-groovy-3.0

orca-front50/orca-front50.gradle, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50Configuration.groovy, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50ConfigurationProperties.java, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy, orca-front50/src/main/java/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java, orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTaskSpec.groovy, orca-web/config/orca.yml
Change is dependent on https://github.com/spinnaker/front50/pull/1483
Added code to save multiple pipelines at once to sql database.
This is part of: spinnaker/spinnaker#6147.
Enhanced SavePipelineTask.java to
Added code to ensure that the SavePipelineTask.java also accepts list of pipelines json.
This method will validate all the pipelines.
This method will call the front50 service to save the pipelines list.
Enhanced Front50Service.groovy to
Added new rest api which accepts list of pipelines json.
Also contains some changes to make the timeout values in the front50 client configurable.  They all default to 10000:
* front50.okhttp.readTimeoutMs
* front50.okhttp.writeTimeoutMs
* front50.okhttp.connectTimeoutMs
=> feat(batchUpdate): Pipeline config batch update

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStageTest.java
In the RunJob Stage when the annotation:
```
job.spinnaker.io/logs: "someExternalUrl"
```
is present the expectation is that the context will be amended with:
```
"execution": {
"logs": "someExternalUrl"
}
```
which is rendered by Deck to an external URL for the console logs.
This is working as expected when the source is text (inline manifest) but when the manifest is coming from an artifact store the process needs to happen afterStages because only then the manifest content is present in the context
This PR addresses this missing use case.
=> chore(runJobStage): Fix logs annotation processing on manifest artifact

orca-sql/src/main/resources/db/changelog-master.yml, orca-sql/src/main/resources/db/changelog/20240731-add-compression-type-column-mariadb.yaml
This contribution was discussed in this slack thread: 
https://spinnakerteam.slack.com/archives/C7J1CU4LA/p1722343931881969?thread_ts=1710447204.964799&cid=C7J1CU4LA
In summary: 
The migration in `20201214-create-compressed-executions-table.yaml` that is adding the column `compression_type` is not being ran for MariaDB because it contains `dbms: mysql`. This causes Orca to throw the following error on startup if using MariaDB:
```
liquibase.exception.DatabaseException: Unknown data type: 'COMPRESSION_TYPE_ENUM' [Failed SQL: (4161) ALTER TABLE spinnaker_orca.pipelines_compressed_executions ADD compression_type COMPRESSION_TYPE_ENUM DEFAULT 'ZLIB' NOT NULL
```
This happens because, since the column is not being created on that migration, the Postgres migration is ran because of this …
=> fix(orca-sql): Add migration for mariadb support

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/Task.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/TaskConfigurationProperties.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PromoteManifestKatoOutputsTask.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTask.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletionTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PromoteManifestKatoOutputsTaskTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveDeploySourceManifestTaskTest.java, orca-clouddriver/src/test/resources/com/netflix/spinnaker/orca/clouddriver/tasks/job/runjob-context-success.json, orca-clouddriver/src/test/resources/com/netflix/spinnaker/orca/clouddriver/tasks/job/successful-run-job-state.json, orca-clouddriver/src/test/resources/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/deploy-manifest-context.json, orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java, orca-core/src/main/java/com/netflix/spinnaker/orca/config/TaskConfigurationProperties.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/artifacts/BindProducedArtifactsTask.java, orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/tasks/artifacts/BindProducedArtifactsTaskTest.java, orca-core/src/test/resources/com/netflix/spinnaker/orca/pipeline/tasks/artifacts/bake-manifest-context.json, orca-core/src/test/resources/com/netflix/spinnaker/orca/pipeline/tasks/artifacts/deploy-manifest-context.json, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetBuildPropertiesTaskSpec.groovy
Introduced new config classes for the following Tasks:
- WaitOnJobCompletionTask
- BindProducedArtifactsTask
- PromoteManifestKatoOutputsTask
- ResolveDeploySourceManifestTask
Through these config classes, certain keys from the outputs in the stage context can be removed.
Added unit tests for these tasks. 
Here are the configuration properties to exclude the keys:
```yaml
tasks:
clouddriver:
promoteManifestKatoOutputsTask:
excludeKeysFromOutputs:
- outputs.createdArtifacts
- outputs.manifests
- outputs.boundArtifacts
waitOnJobCompletionTask:
excludeKeysFromOutputs:
- jobStatus
- completionDetails
resolveDeploySourceManifestTask:
excludeKeysFromOutputs:
- manifests
- requiredArtifacts
- optionalArtifacts
core:
bindProducedArtifactsTask:
excludeKeysFromOutputs:
- artifacts
```
=> feat(stageExecution): reduce execution context size

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/tasks/CheckIfApplicationExistsTaskConfig.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/tasks/RetryConfig.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CloneServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/ResizeServerGroupStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/AbstractCheckIfApplicationExistsTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractWaitForClusterWideClouddriverTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/CheckIfApplicationExistsForClusterTask.java, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CheckIfApplicationExistsForServerGroupTask.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/TaskConfigurationProperties.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/AbstractClusterWideClouddriverOperationStage.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/BulkDestroyServerGroupStage.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTask.java, orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/CheckIfApplicationExistsForManifestTask.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStageSpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/AbstractClusterWideClouddriverOperationStageTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStageTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStageTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletionTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CheckIfApplicationExistsForServerGroupTaskTest.java, orca-clouddriver/src/test/kotlin/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestExpressionEvaluationTest.kt, orca-clouddriver/src/test/resources/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/clouddriver-application.json
Introduces a new CheckIfApplicationExists task that is meant to be added to various pipeline stages. This task performs the following actions:
- checks if the application defined in the pipeline stage context is known to front50 and/or clouddriver. If it isn't, this stage throws an exception. Without this task, clouddriver ends up creating a new synthetic application that is not known to front50 and it causes a whole lot of problems for us, as this application does not have any permissions, doesn't have account rbac etc.
- There are three main types of pipeline stages where this task needs to be added:
- ServerGroup (aws)
- Cluster (aws)
- Manifests (kubernetes)
- Servergroup, cluster and manifests stages obtain an application name in different ways. Hence, a separate …
=> feat(clouddriver): add a new task that checks if the application specified in the moniker or cluster keys exists in front50 and/or clouddriver

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryServiceSpec.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/JarDiffsTask.groovy, orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/AbstractQuipTask.groovy, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestServiceSpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ClusterSizePreconditionTaskTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/monitoreddeploy/EvaluateDeploymentHealthTaskTest.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/kato/pipeline/strategy/DetermineSourceServerGroupTaskTest.java, orca-kayenta/src/test/kotlin/com/netflix/spinnaker/orca/kayenta/KayentaServiceTest.kt, orca-keel/src/test/java/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTaskTest.java, orca-mine/src/test/java/com/netflix/spinnaker/orca/mine/tasks/RegisterCanaryTaskTest.java, orca-retrofit/orca-retrofit.gradle, orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy
Moving away from `com.squareup.okhttp.OkHttpClient` to `okhttp3.OkHttpClient` to avoid any unwanted dependency conflicts. 
okhttp3.OkHttpClient for retrofit1 is provided by [Ok3Client](https://github.com/JakeWharton/retrofit1-okhttp3-client)
Ok3Client is already being used in Orca in many places and this PR makes sure no other code uses OkClient.
=> refactor(retrofit): replace OkClient with Ok3Client

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt
The duplicate repository.storeStage call was originally added in https://github.com/spinnaker/orca/commit/e872ce859e5e82ca9a4726bea596ae1513b0e765 to ensure that the start time for a stage is set even if the handler encounters an exception. 
However, even without the extra repository.storeStage, orca still sets the start time for a stage when it encounters an exception.
=> perf(repository): Remove duplicate storeStage call

orca-retrofit/src/main/java/com/netflix/spinnaker/orca/retrofit/RetrofitInterceptorProvider.java
All references to com.squareup.okhttp will be removed with this PR.
Refer https://github.com/spinnaker/kork/pull/1210 for kork PR which completes the removal of okhttp2 dependencies.
=> refactor(retrofit): remove all com.squareup.okhttp dependencies

orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionBufferActuator.kt
Depending on the load and configuration, the metric may be updated infrequently, and therefore the real value is deleted. As a result, instead of the value you see N/A. Replaced with PolledMeter to hold a strong reference
=> fix(qos): Use PolledMeter to prevent metric deletion by Garbage Collector

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/PipelineRefTriggerDeserializerSupplier.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/ExecutionMapper.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/PipelineRefTrigger.kt, orca-sql/src/test/kotlin/com/netflix/spinnaker/orca/sql/PipelineRefTriggerDeserializerSupplierTest.kt, orca-sql/src/test/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/ExecutionMapperTest.kt
Spel expressions with the function `#triggerResolvedArtifact` are throwing an evaluation error when pipelineRef feature is enabled in Orca. See: https://github.com/spinnaker/spinnaker/issues/6993
The error happens because when we transform a PipelineTrigger into a PipelineRefTrigger we are not populating the `resolvedExpectedArtifacts`. As the `resolvedExpectedArtifacts` is empty the Spel function `#triggerResolvedArtifact`  is not able to collect the artifact we want.
This small code change fix the issue.
=> fix(pipelineRef): add resolvedExpectedArtifacts from pipelineTrigger to PipelineRefTrigger

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/InMemoryExecutionRepository.kt, orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-web/orca-web.gradle, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy, orca-web/src/main/java/com/netflix/spinnaker/config/TaskControllerConfigurationProperties.java, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy, orca-web/src/test/kotlin/com/netflix/spinnaker/orca/controllers/TaskControllerTest.kt
This PR improves performance when using sql as the backend by optimizing the way the results are obtained for the api call `/applications/{application}/pipelines?expand=false&limit=2` frequently initiated by deck.
Deck makes that call to Gate. Gate further forwards that call to Orca, specifically to `/v2/applications/{application}/pipelines` endpoint.
Orca calls front50 to get the pipeline and strategy config ids and then merges them. Then for each id in the merged list, it queries its own db (SQL) to handle the query parameters, such as limit=2 and filter by statuses. It is observed that these db operations are taking longer times and this PR fixes the slowness by optimizing the queries to the db.
Refactored TaskController to support externalized config properties
Optimize …
=> feat(sql): Optimize executions

orca-queue-sql/src/test/kotlin/com/netflix/spinnaker/orca/q/sql/SqlQueueIntegrationTest.kt, orca-sql/orca-sql.gradle, orca-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgentSpec.groovy, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/TopApplicationExecutionCleanupPollingNotificationAgentSpec.groovy, orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlPipelineExecutionRepositorySpec.groovy, orca-sql/src/test/java/com/netflix/spinnaker/orca/testconfig/SqlConfigurationTest.java, orca-sql/src/test/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepositoryTest.kt, orca-web/src/test/kotlin/com/netflix/spinnaker/orca/controllers/TaskControllerTest.kt
Introduce a read pool for some read-only database queries in SqlExecutionRepository.  Enable this by configuring an additional connection pool named `"read"`, like this:
```
sql:
connectionPools:
default:
<...>
read:
jdbcUrl: jdbc:...
user: orca_service
password: 
connectionTimeoutMs: 
validationTimeoutMs: 
maxPoolSize:
minIdle:
maxLifetimeMs:
idleTimeoutMs:
```
Additional read-only database queries happen in places that expect to see "just-written" contents.  They're not safe to convert to use the read replica until there's logic in place to be aware of replication lag, and wait until the read replica is up-to-date.
=> feat(sql): use a connection pool named "read" for some read operations in SqlExecutionRepository

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy, orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListenerSpec.groovy
To reduce load on echo and the downstream consumers of echo events when task event information is not needed. Configurable by setting echo.events.ignoreTaskEvents=true.
=> perf(echo): don't send task events

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.kt, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/InMemoryExecutionRepository.kt, orca-front50/orca-front50.gradle, orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy, orca-front50/src/main/java/com/netflix/spinnaker/orca/front50/scheduling/UnusedPipelineDisablePollingNotificationAgent.java, orca-front50/src/test/java/com/netflix/spinnaker/orca/front50/scheduling/UnusedPipelineDisablePollingNotificationAgentTest.java, orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java, orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt, orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy, orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy, orca-web/src/test/kotlin/com/netflix/spinnaker/orca/controllers/TaskControllerTest.kt
Adding an opt-in feature to exclude Execution Retrieval for Disabled Front50 pipelines. This can be configured via: 
```
tasks:
controller:
excludeExecutionsOfDisabledPipelines: true #(defaults to false) 
```
When enabled Orca calls the Front50 with a query parameter `enabledPipelines=true`. Front50 responds only with the enabled pipelines of the application. 
This feature aims to ease the load on the execution retrieval for applications that have a lot of pipelines and for historical reasons users dont want to delete the obsolete pipelines that are disabled.
Additionally an agent is implemented to check for unused/unexecuted pipelines per application for the past X days and disable them in Front50. This is only applicable for SQL execution repository and can be configured via: 
``` …
```
=> feat(execution): Exclude execution retrieval for Disabled Front50 pipelines

orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/BuildService.java, orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/IgorService.java, orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/model/CIStageDefinition.java, orca-igor/src/main/java/com/netflix/spinnaker/orca/igor/tasks/WaitForConcourseJobCompletionTask.java, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildServiceSpec.groovy, orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildServiceSpecMock.groovy
This is in conjunction with the igor changes made.
=> fix(jenkins): Updated buildNumbers to be longs rather than an ints

orca-webhook/orca-webhook.gradle, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/service/WebhookService.java, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookServiceSpec.groovy, orca-webhook/src/test/java/com/netflix/spinnaker/orca/webhook/service/WebhookServiceTest.java
Configure with the following properties:
```
webhook.allowedRequestsEnabled (default: false)
webhook.allowedRequests: (default: empty list)
- httpMethods: list of strings, e.g. [ "GET" ]
urlPrefix: "https://my-url:port/path/starts/with"
```
Note, if allowRequestsEnabled is true, and allowedRequests is empty, no requests are allowed.
=> feat(webhook): add http method + url-based allow list to webhook stages

orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfiguration.java, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookServiceSpec.groovy, orca-webhook/src/test/java/com/netflix/spinnaker/orca/webhook/service/WebhookServiceTest.java
via new config properties webhook.maxRequestBytes and webhook.maxResponseBytes. The default value for both is 0.
When greater than 0, only requests/responses whose header + body size is less than or equal to the max are allowed.
=> feat(webhook): add request/response size limits

orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfiguration.java, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java, orca-webhook/src/test/java/com/netflix/spinnaker/orca/webhook/service/WebhookServiceTest.java
Default to true so there's no behavior change. When false, don't follow redirects in webhook stages.
=> feat(webhook): add new webhook.followRedirects property

orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfiguration.java, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java, orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookServiceSpec.groovy, orca-webhook/src/test/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfigurationTest.java, orca-webhook/src/test/java/com/netflix/spinnaker/orca/webhook/service/WebhookServiceTest.java
`webhook.readTimeoutMs` (default 20000) and `webhook.connectTimeoutMs` (default 15000).
If not present, fall back to `ok-http-client.readTimeoutMs` and `ok-http-client.connectTimeoutMs` (same defaults) to mantain behavior where those ok-http-client properties are set.
This way it's possible to configure webhook stages independently of the way spinnaker microservices communicate with each other.
=> feat(webhook): add webhook-specific configuration properties for read and connect timeout

orca-webhook/orca-webhook.gradle, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfiguration.java, orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java
which defaults to false. When true, log information about each webhook request and response.
with a small fix to a response-too-big error message as well.
=> feat(webhook): add webhook.auditLoggingEnabled config property

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/models/StageExecution.java, orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/StageExecutionImpl.java, orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt, orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
via a new backoffPeriodMs stage configuration property. Before this, pipeline authors had no control over the backoff period. It came from either spinnaker configuration properties or implementations of RetryableTask.getDynamicBackoffPeriod.
This makes it possible for pipeline authors to, for example, control the delay between attempts when webhook stages retry. The actual backoff used is the largest of:
- backoffPeriodMs in the stage
- tasks.global.backOffPeriod
- tasks.<cloud provider>.backOffPeriod
- tasks.<cloud provider>.<account name>.backOffPeriod
=> feat(queue): provide a way for pipeline stages to specify a backoff period

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStageTest.java
Fixes the mapping exception when trafficManagement is not defined in the Deploy stage definition. 
Exception: 
Resulted from changes in https://github.com/spinnaker/orca/pull/4823
=> fix(orca-clouddriver): Fix exception in mapping of trafficManagement when null

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.java, orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestServiceSpec.groovy, orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfigurationTest.java, orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/config/EchoConfiguration.groovy, orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/config/IgorConfiguration.groovy, orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/config/KeelConfiguration.kt
This PR, along with https://github.com/spinnaker/kork/pull/1233, fixes any issues arising due to the addition of Retrofit2EncodeCorrectionInterceptor to the OkHttpClient that is used for retrofit1 client.
=> fix(retrofit1): exclude Retrofit2EncodeCorrectionInterceptor from the retrofit1 clients
