spinnaker/orca

orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/ExecutionPropagationListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTasklet.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/ExecutionPropagationListenerSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTaskletSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/lifecycle/ExecutionCancellationSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/lifecycle/FailureRecoveryExecutionSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/parallel/ParallelCompletionSpec.groovy
orca-test/src/main/groovy/com/netflix/spinnaker/orca/test/JobCompletionListener.java

If a branch fails the other branch will now get cancelled which means any cancellation handling logic will kick in. It n longer sets the "terminate only" flag on the job as that will cause the inconsistency previously seen where the job execution listeners will fire immediately if the failing branch is the primary one and not until everything finishes if it's another branch. That meant if it was the "primary" branch that failed the pipeline status would immediately become TERMINAL even though things were still running.
I also had to make TERMINAL status override CANCELED as we don't want the pipeline to show as CANCELED due to the non-TERMINAL branches.

Stops inconsistent failures between parallel pipeline branches

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/strategies/AbstractDeployStrategyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/strategies/CustomStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/support/Location.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/support/TargetServerGroupLinearStageSupport.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/support/TargetServerGroupResolver.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelDeployStage.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTask.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTaskSpec.groovy

Propagates a few deployment properties through the pipeline starter and differentiates regions and zones in a few places.
Tested with a custom strategy in both AWS and GCE through both the UI clone button and findImage/deploy pipelines.
@duftler @tomaslin @cfieber PTAL
https://github.com/spinnaker/spinnaker/issues/585

Enables custom strategies for GCE pipelines and deploys

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/FindImageFromClusterTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/gce/GoogleServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/gce/GoogleServerGroupCreatorSpec.groovy

1.) Add more helpful error message when image is not found
2.) GCE is not limited to regional images, so we now fallback to non-matching zone iff 1 deploymentDetail entry is found (this allows cross-zonal "Clone" operations).
a.) Fail with helpful message if this is the case:
3.) Fail with graceful error message if no image is found. Previously, this bubbled up a cryptic Clouddriver error. 
@duftler, @spinnaker/google-reviewers PTAL

GCE-specific find image tweaks

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/titan/TitanServerGroupCreator.groovy

- Resulted in 'ServerGroupCreator not found for cloudProvider titan' otherwise

Override getCloudProvider() for TitanServerGroupCreator

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/config/BakeryConfiguration.groovy

bake requests are failing because we are passing empty values for base_ami, etc

should not pass empty values to bakery

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy

The goal is to surface this in the UI, letting users know that an actual bake did not occur and we are instead using a previously baked artifact.
When performing a bake (at least via the internal Netflix bakery), there are two signals that the requested bake already exists:
1. The response status code from the API call is 200 instead of 202
2. The status of the returned bake is `COMPLETED` instead of `RUNNING`
I do not see a clean way of getting at the status code on a successful bake call via Retrofit+OkClient, so am going with (2), which is probably more straightforward, anyway.
Not in love with the flag name (`bakeExists`) and am open to suggestions there.
@robfletcher @duftler please review

add bakeExists flag if createBake returns COMPLETED

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy

This will go with a corresponding change in Deck to allow users to explicitly request a rebake when starting a pipeline.
We have heard from a few users that they wanted to force a rebake without having to update the package artifacts explicitly. While they don't necessarily _always_ want the option, they do want an easy way to do so when dependent packages have changed.
Deck PR pending - will add a comment referencing it when it's ready...
@ajordens @duftler please review

allow rebake via trigger

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/ExpressionPreconditionTask.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/ExpressionPreconditionTaskSpec.groovy

- The ExpressionPreconditionTask will explicitly evaluate the expression at task execution time
- Any portions of the expression wrapped in ${ and } will be evaluated at both pipeline start and stage start

Precondition expressions no longer need to be wrapped in ${ and }

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/OortHelper.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/WaitForTerminatedInstancesTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/WaitForTerminatedInstancesTaskSpec.groovy

Updates WaitForTerminatedInstancesTask to a 10 second interval from a 1 second interval
If available, looks up instances from the serverGroup rather than an instance search
Updates AbstractInstancesCheckTask to a 10 second interval from a 5 second interval
@ajordens ptal

less agressive polling for instance stage changes

---

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/pipeline/util/PackageInfoSpec.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/BuildService.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorQueuedJenkinsJobTask.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartJenkinsJobTask.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartScriptTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildServiceSpec.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTaskSpec.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartJenkinsJobTaskSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

Fixes: https://github.com/spinnaker/spinnaker/issues/605
Depends on: https://github.com/spinnaker/igor/pull/42

Update Igor endpoints

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/ExecutionStatus.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/BatchStepStatus.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/adapters/RetryableTaskTasklet.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTasklet.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/adapters/RetryableTaskTaskletSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTaskletSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

- Works by having Retryable tasks enter a no-op loop when paused (no execution will occur)
- Non-Retryable tasks can not be paused (a theoretical drawback but in-practice unlikely to cause concern)

Support for pausing and resuming a Pipeline

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreatorSpec.groovy

We had all this code in the `CreateDeployTask`, but at some point Orca changed to use the `AmazonServerGroupCreator` to handle pipeline deployments, which bypassed all the work done to find the image to deploy from upstream stages.
The code in the `CreateDeployTask` seems to have been written in the same week as the code to use `AmazonServerGroupCreator`, but by different people ( @ttomsu , @robfletcher ), so it's probably just a miscommunication.
I tested this locally and it works as expected.
@robfletcher @ttomsu please review when you have a minute.

prefer AMIs from upstream stages on Amazon deploys

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/QuickPatchStage.groovy

Like the `ResizeAsgStage`, the `QuickPatchStage` itself just spawns a child stage, which does all the work.
Right now, it marks itself as `SUCCEEDED`, so it gets an `endTime` but no `startTime` when Orca persists it, which causes grief in the UI. Also, since the stage doesn't really show us anything useful (all its data is presented in the child stages it spawns), it just takes up space in the execution details.
@cfieber does this seem legit or are there bigger problems setting this flag on this stage?

mark quickPatchAsg stage as initializationStage

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy

Adds a #fromUrl helper method that will either return a list or map from the url that is sent in. 
This is intended to help in situations where you might want to check against a healthcheck or get more details from another pipeline. 
This is just a building block, we will add more helper functions that will make it easier to get things like a #hostname from a cluster, for example. 
Usage:
```#fromUrl( 'http://myserver/endpoint' )[0].instances```

add a #fromUrl helper method that will allow fetching content 

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/MonitorBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/MonitorBakeTaskSpec.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractWaitForInstanceHealthChangeTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/UpsertLoadBalancerResultObjectExtrapolationTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractWaitForInstanceHealthChangeTaskSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/ExecutionStatus.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/BatchStepStatus.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindow.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/ExecutionPropagationListenerSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTaskletSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/lifecycle/FailureRecoveryExecutionSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/lifecycle/ManualInterventionExecutionSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/restart/PipelineRecoveryListenerSpec.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoEventSpec.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTaskSpec.groovy
orca-rush/src/main/groovy/com/netflix/spinnaker/orca/rush/tasks/MonitorDockerTask.groovy

As much as it pains me to do this, I'm suggesting we remove the `FAILED` status value and just go with `TERMINAL` everywhere. We don't seem to be doing anything useful with `FAILED`, unless confusing our UI developers and other consumers of our APIs is considered useful.
This would leave us with "only" eight status values to consider in the UI. I should probably remove the quotes around "only" because we "literally" deal with "fifteen" different potential status values right now (https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/orchestratedItem/orchestratedItem.transformer.js#L139-L163). I frankly have no idea where those fifteen values come from. Looking at the history of that enum file, I don't see most of them, which makes me think we can get probably align those …

convert FAILED status to TERMINAL

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/MonitorCanaryStage.groovy

The current behavior of the monitor canary task is to timeout after two days, which is not great if the canary is scheduled to run for 48 hours or longer.
This sets a timeout to two hours _longer_ than the canary lifetime, which will avoid canaries crashing/burning/not getting cleaned up in the above scenario.
The downside is that timeouts apply at the _stage_ level, not the _task_ level, so now every task in the canary could potentially spin for a very long time without failing - registering the canary, cleaning up the canary, completing the canary. This isn't a terrible downside, I suppose.
@ajordens or @cfieber your review is appreciated

set sensible default for canary monitor stage

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/MonitorCanaryStage.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/MonitorCanaryStageSpec.groovy

Turns out the `lifetimeHours` field is usually a string, not a number.
If it's not present or non-numeric or zero for some reason, default to 48 hours; otherwise, set the stage timeout to the canary lifetime plus two hours.
@ajordens please review

handle string values for monitor canary timeouts

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy

On rare occasions the (Netflix internal) bakery will kick off two simultaneous
bakes in a region and end up producing two names for the results to resolve
uniqueness constraints, resulting in both
* `foo-120.2-h180.ffea4c7-x86_64-20160218235358-trusty-pv-ebs`
* `foo-120.2-h180.ffea4c7-x86_64-20160218235358-trusty-pv-ebs1`
In this case we accept either of those values and use the image find to search
against the base of `foo-120.2-h180.ffea4c7-x86_64-20160218235358-trusty-pv-ebs`. We
then iterate over any results that come back, and pull amis to match regions that were
requested but didn't exist in the search cluster.

Handles duplicate bakes in cross region image lookup

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTaskSpec.groovy

If a user tries to shrink a non-existent cluster to zero server groups, the operation will only succeed if the `allowDeleteActive` flag is set to `false`. When it's set to `true`, we inject a `DisableClusterStage`, which will fail if no cluster is found.
This change introduces a `continueIfClusterNotFound` flag to the stage, which will cause the task to succeed immediately if the cluster is not found.
Tested locally to verify it succeeds to placate the @ajordens , who should review this, or let @cfieber review it.

allow ShrinkClusterStage to succeed if shrinking to 0, none present

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTaskSpec.groovy

Follow-up to https://github.com/spinnaker/orca/pull/743
Sometimes Clouddriver returns an empty cluster with no server groups. In this scenario, the task should also succeed.
@cfieber or @ajordens or @robfletcher please review

allow shrink cluster to succeed when empty cluster exists somehow

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonSecurityGroupUpserter.groovy

This seems to be why ip ingress disappears when editing a security group. Everything in cloud driver is tested and works as advertised. The ipIngress field has been on the cloud driver upsert sg description since 2014 (not a new field), but it seems that it has never been wired in at this level.

Pass ipIngress to clouddriver

---

orca-core/orca-core.gradle

Version 3.2.1 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/
Also, do consider using Guava in the future.

Upgrade Apache Commons Collections to v3.2.2

---

orca-core/orca-core.gradle

It looks like we are not actually using commons-collections anywhere, just declaring the dependency. We probably _were_ using it at some point, but, according to gradle's dependency report, we aren't now.
You can see it getting pulled in by `spring-batch-test` in the `orca-test` project, but that shouldn't affect the runtime path of the application. 
To see `commons-collection` coming in, run `./gradlew orca-core:dependencies`:
```
\--- project :orca-test
...
+--- org.springframework.batch:spring-batch-test:3.0.4.RELEASE -> 3.0.3.RELEASE
|    +--- commons-collections:commons-collections:3.2.1
```
Then run `./gradlew orca-web:dependencies --configuration runtime` to see what should be on the classpath when the application actually runs.
Someone who's more familiar with gradle should sanity …

remove unused dependency on commons-collections

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesServerGroupCreator.groovy

Previously, it was possible to create a pipeline `FindImage -> ... -> Deploy`, go back and edit `FindImage` and have the pipeline fail, because the `Deploy` stage's pattern selector no longer matched that of the `FindImage` stage. Referring to the `RefId` of the `FindImage` stage in `Deploy` fixes that.
This only changes behavior for the Kubernetes provider, since it's the only one use a pattern to select images. Requires https://github.com/spinnaker/deck/pull/2056
@duftler

provider/kubernetes: Find image by stage id

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesServerGroupCreator.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

When a user leaves their image tag blank for a docker trigger, the tag is now resolved in the deploy phase.
@duftler

provider/kubernetes: Use image tag resolved at runtime (from trigger) if needed

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/scalingpolicy/DeleteScalingPolicyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/scalingpolicy/UpsertScalingPolicyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/scalingpolicy/DeleteScalingPolicyTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/scalingpolicy/UpsertScalingPolicyTask.groovy

These are simple pass-through tasks, with stages that do their jobs, refresh their server groups, and call it a day.
@ttomsu still cleaning up the Clouddriver and Deck bits (I have it all working locally, still need to write tests and clean up the contracts between them), but does this look good to you on the Orca side?

add scaling policy upsert/delete stages/tasks

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy

titus currently doesn't provide a good way to disable a server group. 
will remove this workaround once we've integrated service discovery properly.

skip disable steps for titus destroy operation

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy

@spinnaker/netflix-reviewers PTAL fixes SPIN-1607

when regexing image names to account for bakery dupe handling, if the image name doesn't match the regex, consider it as is

---

orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandler.groovy
orca-retrofit/src/test/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandlerSpec.groovy

This fixes an issue where we'll retry things like create server group on CloudDriver if we get a network error. We should only ever retry things that are known to be idempotent.

Don't retry network errors for non-idempotent requests

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy

Removed this in an earlier PR, but forgot it's needed to disambiguate between multiple images. 
@duftler

provider/kubernetes: Match against imageNamePattern

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolver.groovy

The check becomes relevant when there are two or more server groups with the same name but in different regions.

Minor fix; zone is not available for some of the cloud providers

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreatorSpec.groovy

Since CF doesn't bake, allow repository/artifact as well as images when creating new server groups.

Allow CF to have repositories

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/AwsDeployStagePreProcessor.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/CaptureSourceServerGroupCapacityTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/DeployStagePreProcessor.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/StageData.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ApplySourceServerGroupSnapshotTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CaptureSourceServerGroupCapacityTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/StageDataSpec.groovy

This avoids situations where AWS scaling policies manipulate the `desired` capacity of a newly deployed server group due to the cluster being double provisioned (old ASG is still active while new ASG is deploying)
- Only applies to AWS deploys that have `useSourceCapacity: true`
- The `min` will be restored after the deploy has completed (based on the source server group)

Server groups should be deployed with min = desired (initial)

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/JobForceCacheRefreshTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/JobRunner.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/RunJobTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesContainerFinder.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesJobRunner.groovy

Closely modeled after the deploy server group stage; however, the force cache refresh doesn't wait for the refresh to take place since the job could easily have completed by the time the refresh finishes.
@duftler

core: Run job task & stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy

It's possible there are other scenarios in which we'll need to apply something similar; this one fixes the issue where nothing happens on cluster-wide tasks, e.g. deployments with strategies.

fallback to region if regions not found

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/BuildService.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/IgorService.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildServiceSpec.groovy

newer retrofit version barfs on a PUT with no `@Body`

add empty body to @PUT requests to appease the bustigated retrofits

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/QuickPatchStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/AbstractQuipTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/InstanceHealthCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/MonitorQuipTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/VerifyQuipTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/InstanceHealthCheckTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/MonitorQuipTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/VerifyQuipTaskSpec.groovy
orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy

main goal of this change it just to expose some configuration around the okclient creation to experiment with addressing the EOFExceptions.  
* adds extra configuration for okclient connection pool and retry (defaults to the existing default values)
* updates a couple of classes that were not explicitly passing a retrofit client
* fixed a bug where the retrofit client user agent interceptor wasn't actually getting applied

updates retrofit okclient construction.

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/ExecutionContextManager.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/ExpressionPreconditionTask.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

Adds an allowUnknownKeys option when processing parameters - when transforming a pipeline before execution this is set to false to ensure any unresolved expressions do not get interpreted. This addresses the case of an expression as part of a larger string such as `${foo}-bar` getting resolved to `-bar`.
Transformation inside the execution of a stage allows for missing keys which enables the use of the SpEL elvis operator and preserves existing behavior.
@tomaslin PTAL

makes ContextParameterProcessor explicit about behavior of unknown attributes.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesContainerFinder.groovy

I realized that only a single trigger can start a pipeline at once, so there is no need to search through buildInfo to find a matching trigger.
@duftler

provider/kubernetes: simplify resolve tag

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy

Because of the `-` delimiter being nondeterministic, we have to have sophisticated parsing to extract the package name from rpm file names. We found this in our installation when a build produced two rpms, myapp and myapp-someotherpackage. When the bakery was told to install myapp, orca matched the myapp-someotherpackage and the bakery installed the wrong package.

Handle multiple rpm artifacts in random order

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupport.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupportSpec.groovy

- Aligns with a UI that now prompts for an expression that determines whether a stage should run (vs determining that a stage should not run)
- Any issue evaluating an expression will result in the stage being executed

Minor adjustment to how an <optional> expression is interpreted

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/QuickPatchStage.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/pipeline/util/PackageInfoSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy
orca-web/config/orca.yml

Please note the `allowMissingPackageInstallation` parameter is not used internally and never passed down to the bakery, in any case so it has been just removed from the BakeRequest

Expose allowMissingPackageInstallation as a configuration property

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreatorSpec.groovy

This is a legitimate case if issuing a cloneServerGroup wanting to inherit the AMI from the
source serverGroup

Don't inject an allowLaunch operation if there is no amiName

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/DeployStrategyStage.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategySpec.groovy

The existing implementation was an attempt to speed things up by not waiting on the disable step for instances we were about to terminate, but not doing the disable is disruptive to active clients and causes unnecessary errors / retries

Disable before scaling down old server groups in red/black

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy

This is to take care of a use case for Google to allow the build stage to have an empty package name, and not extract a package name from the trigger context or stage generated artifacts.
@duftler PTAL and let me know if this doesn't fix your issue.

Fix for build stage with empty package name.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreator.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CloneServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/DetermineSourceServerGroupTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreatorSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CloneServerGroupTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/DetermineSourceServerGroupTaskSpec.groovy

Should not fail, but should not inject an allowLaunch operation for a clone with no amiName
Uses DeploymentDetailsAware trait to resolve an image rather than looking only for a preceeding bake (allow clone in a pipeline)
Reverts a change to AmazonServerGroupCreator that was checking for null amiName - that path is only used during a createServerGroup

cloneServerGroupTask ami handling updates

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonSecurityGroupUpserter.groovy

The monitor task will never complete if performed from an API call, since it's looking for all the declared ingress rules. This takes care of that case.

(aws) watch for appended security groups in monitor task

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/BuildDetailExtractor.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/pipeline/util/PackageInfoSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/BuildDetailExtractorSpec.groovy

Part of a series of PR adding build info support for travis integration on AWS
by adding new build_info_url tag to the images in order to be able to full fill the build info correctly for travis.
This PR adds a build_info_url BakeRequest from Orca to Rosco
Rosco will add the build_infor_url as a ec2 tag.
This is the final result
Related PRs
https://github.com/spinnaker/rosco/pull/102
https://github.com/spinnaker/clouddriver/pull/652
https://github.com/spinnaker/deck/pull/2304

Travis support for orca

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy

Build info is not required without `defaultResolveMissingLocations` enabled, so it seems reasonable to not require it with `defaultResolveMissingLocations` enabled as well.

Allow missing build info when resolving missing locations.

---

orca-web/orca-web.gradle

This change will fix problems where logrotate ignores
/etc/logrotate.d/orca due to 'bad file mode.'
For Spinnaker issue [#904](https://github.com/spinnaker/spinnaker/issues/904)

Update logrotate file permissions

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/serialize/SerializeApplicationStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/serialize/SerializeApplicationTask.groovy

Created a stage and task for serializing an application. Modeled it closely after the stages and tasks in orca. I tested it by sending a curl command to gate and it properly forwards the request to clouddriver. @lwander @duftler PTAL.

core: Serialize application task & stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractWaitForInstanceHealthChangeTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForDownInstanceHealthTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstanceHealthTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForAllInstancesDownTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/HealthHelper.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractWaitForInstanceHealthChangeTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForDownInstanceHealthTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstanceHealthTaskSpec.groovy

The WaitForUpInstanceHealthTask & WaitForDownInstanceHealthTasks would never get into a success state when the Aamzon health state (which is always "Unknown") was used in determining health.
This would cause the "Reboot Instance Task" to hang on these tasks.  The reboot of the instance would complete but the task would appear hung, causing end user confusion.
This fix simply allows success of the tasks if the only health state is Unknown.
In the case of multiple health checks:
For "Up" health check it will accept combinations of "Up" and "Unknown" state for success
For "Down" a combination of "Down", "OutOfService", & "Unknown" state for success

SPIN-1840: Fix Instance Rebooting

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy

I'm really interested in this to present user feedback when performing migrations, since they are long-ish running tasks (up to 30 seconds), and it would be nice to let the user know something is happening.
This pumps the kato task history into the orca task history, updating it as the task progresses.
I asked for this almost two years ago and there were concerns about it, I think, but that was a long time ago.
@cfieber @robfletcher any concerns with this?

record kato task history while task is running

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

We have this functionality on pipelines, and we already propagate the `limit` parameter from Gate - we just ignore it.
@ajordens PTAL

(core) allow limit parameter when retrieving tasks

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/QuickPatchStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/ResolveQuipVersionTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/VerifyQuipTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/QuickPatchStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTaskSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/StageNavigator.groovy

the quick patch stage used to do work at stage evaluation time in order to determine how many synthetic stages to add for the rolling patch case
it still does some (it looks up all the instances in the cluster) which is not great, but with this change the resolution of which version to deploy happens in a task
this means that the `bulkQuickPatch` stage now has to handle the "skip if up to date" behaviour, and the retrieval of the version from the context has to traverse back up to the parent stage's context
this change enables a pipeline that has `[some random stages]-->[jenkins stage]-->[quick patch]`

move quip version determination into a task so it runs at stage execution time not stage evaluation time

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/RegisterAcaTaskTask.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/RegisterCanaryTask.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/tasks/RegisterCanaryTaskSpec.groovy

There is an edge case when a canary is with both a duration and warm-up periods are set the canary times out before completion.
Basically there was no padding built into the stage timeout time.
This add a 2 hour padding to the time out to allow for the canary to complete and report back before timeout.

Fix for Canaries Timing out

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/MigratePipelineStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MigrateTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/PipelineClusterExtractor.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/pipeline/MigratePipelineClustersTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/pipeline/UpdateMigratedPipelineTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelDeployClusterExtractor.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MigratePipelineClustersTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/UpdateMigratedPipelineTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelDeployClusterExtractorSpec.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryPipelineClusterExtractor.java
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryPipelineClusterExtractorSpec.groovy

Extractor components are responsible for plucking any clusters out of stages, then putting them back into the stages after Clouddriver completes the migration.
@cfieber PTAL

implement pipeline migration

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy

core/bake: Temporarily comment-out logic that strips extraneous attributes from bake requests sent to Netflix's internal bakery.

core/bake: Don't strip extraneous attributes from bake requests sent to Netflix's internal bakery.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/pipeline/MigratePipelineClustersTask.java

@cfieber This is why we're creating load balancers in EC2-Classic via pipeline migrations.

provider/netflix: send elbSubnetTypeMapping field to MigrateCluster op

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/CompleteCanaryTask.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/tasks/CompleteCanaryTaskSpec.groovy

If continueOnUnhelthy is checked and the ACA has a health status of UNKNOWN the stage
will be marked as FAILED_CONTINUE. Presently this will just throw an IlleagialStateException and cancel the pipeline.

Continues ACATask Stage if ACA health is UNKNOWN.

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/CompleteCanaryTask.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/tasks/CompleteCanaryTaskSpec.groovy

We were not handling the FAILURE case for canaries. This was causing an IllegialStateException to be thrown instead fo setting the stage to TERMINAL or FAILED_CONTINUE if 'continueOnUnhealthy'  is true

Handle canary failure case

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestServiceSpec.groovy
orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy

companion PR to https://github.com/spinnaker/clouddriver/pull/928
Sends a unique identifier to Clouddriver requests so that Clouddriver can dedupe requests in the scenario where Clouddriver successfully performs an operation but its response is dropped.

retry retrofit requests, include clientRequestId in kato/ops calls

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/securitygroup/SecurityGroupForceCacheRefreshTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/securitygroup/SecurityGroupForceCacheRefreshTaskSpec.groovy

The targets object in the security group stage has a securityGroupName,
region, and accountName which came from the MortService.SecurityGroup
object. When constructing the object being sent to clouddrive,
SecurityGroupForceCacheRefreshTask was trying to access
target.credentials which is always null.
Effectively, on demand caching for all providers was not working since
clouddriver got a null account name. Since security groups are
infrequently upserted, it was not noticed.

Fix account name in security group force cache update.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/OortHelper.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/JarDiffsTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/JarDiffsTaskSpec.groovy

- Prefer using privateIpAddress (over host name which may be public)
- Short-circuit after unsuccessfully checking 5 instances

Additional sanity checks around jar diffs

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy

Because we now use `@JsonAnySetter` we can send all kinds of garbage to the Bakery. Recently we've had problems where `status` gets sent and breaks the bake request.

Avoid sending fields to the bakery that we shouldn't

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy

The idea is to make it easier to render the completed job information in the executionDetails view in deck.
@danielpeach FYI @duftler PTAL

(core) Nest completion details for easy retrieval

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/serialize/RestoreSnapshotStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/serialize/RestoreSnapshotTask.groovy

Added a pipeline stage for restoring infrastructure. Named this deserialization for now to match the serialization pipeline stage, I will soon change them to restoreSnapshot and saveSnapshot to match front50. PTAL @lwander @duftler

core: Added a pipeline stage for restoring infrastructure

---

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/pipeline/DeploymentStrategiesExecutionSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/DefaultTaskResult.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/StageStatusPropagationListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSupport.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/TaskNode.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/NoOpTask.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/listeners/StageStatusPropagationListenerSpec.groovy
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/SpringBatchExecutionRunner.java
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/orca/batch/SpringBatchExecutionRunnerSpec.groovy
orca-test/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSpec.groovy

- inject a no-op task if there are no tasks before the parallel part of the stage
- fix handling of status propagation in v2

Propagate status correctly on parallel tasks

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy

It's possible to have the "wait for up instances to fail" task if a server group isn't caught in the "force cache refresh" preceding it. This is easy to verify by modifying deploy handler to deploy nothing (but report deployment details), causing the "force cache refresh" task to simply report that the server doesn't exist (and attempt to evict it from the cache), which succeeds happily. Finally "wait for up instances" tries to verify that the server group exists, which throws an exception.
This only happens when a no blocking action happens during a deploy stage, and takes around a minute after the deploy for the server group to even show up (ignoring instances).
@ajordens @duftler

(core) wait for server group during up instance check

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineStarter.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Pipeline.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

- Dependent pipelines should be launched with the executionEngine of their parent pipeline

Persist `executionEngine` as part of the Execution

---

orca-web/config/orca.yml

@ttomsu Going to push this through temporarily so Orca can start up.
Not sure how you intend to configure this, and guessing Clouddriver might need the same treatment.

Specify services.fiat.baseUrl.

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTasklet.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTaskletSpec.groovy

Handles the following situation:
`Jenkins` -> `Manual Judgment` -> `Deploy`
- `Manual Judgment` is conditional on `Jenkins` being FAILED_CONTINUE.
- `Manual Judgment` is set to not fail the pipeline on failure
A problem arises if `Jenkins` is FAILED_CONTINUE and `Manual Judgment` is STOPPED.
If `Jenkins` is restarted and passes, `Manual Judgment` should be skipped ... even if it
was STOPPED previously.

Only no-op a previously completed task if the stage is NOT optional

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/Bake.groovy
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTask.groovy

The Netflix bakery provides the `amiName` - we're just not capturing it as part of the `CompleteBakeTask`. It would be nice to supply that in the UI if it's present.
@duftler @spinnaker/netflix-reviewers PTAL

include amiName if present in bake results

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

We have an agent running hourly to cap the # of tasks at 2500 but
any tasks created after the agent run (> 2500) are non-deterministically
returned by the /applications/{application}/tasks endpoint.
This would be unnecessary if the backing set was sorted (future)

Increased the default limit for tasks from 2500 -> 3500

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/StageBuilder.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/adapters/RetryableTaskTasklet.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/StageBuilderSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy

Previously a pipeline that was paused for 12hrs would automatically go TERMINAL and
subsequent attempts to restart would fail.
- Adjusted max pause time upwards from 12hrs -> 72hrs to handle pausing over a weekend

Resume a previously paused pipeline when restarting

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStage.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStageSpec.groovy

Can't guarantee that there will be a canary id on the context when a call to cancel from the restart.

Add guard around canceling a canary for restart

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy

When we retrieve clusters from Clouddriver, we get their instances, which can have a lot of fields we'll never care about. If there are thousands of instances, we end up with a very bloated JSON representation of the pipeline. Further, on AWS clusters, the ASG itself has a collection of the instances, which we never look at.
As far as I can tell, we only ever care about four fields: name (for sorting), launch time (for sorting), health (for platform health checks), and health status (for active server group filtering). By retaining just those fields, we should be able to slim down the pipeline payload substantially.
@spinnaker/reviewers PTAL. It's frankly a little hard to track where all we use `TargetServerGroup`s and their fields.

retain minimal instance fields on TargetServerGroup

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/CompositeExecutionListener.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/ExecutionCleanupListener.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/ExecutionPropagationListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/OrchestrationJobBuilder.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/listeners/CompositeExecutionListenerSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/listeners/ExecutionCleanupListenerSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/listeners/ExecutionPropagationListenerSpec.groovy

- `targetReferences` contains complete asg/instance details and is no longer
necessary after an execution has completed

Remove `targetReferences` from any successful completed execution

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTaskSpec.groovy

@robfletcher @ajordens @duftler PTAL
Kubernetes uses different health providers for different tasks, so the health providers need to be pulled from the stage context. Is there a neater/more consistent way for Kubernetes to get its health providers?

(core) get health providers from stage context

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindow.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindowSpec.groovy

We're seeing an issue where execution window calculations go awry if they are scheduled for a day of the week in the future. The JSON in the execution context looks correct, so I'm really just guessing at the underlying issue here and hoping the log message sheds some light on things.

convert day of week strings to ints in execution windows

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/parallel/WaitForRequisiteCompletionTask.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/parallel/WaitForRequisiteCompletionTaskSpec.groovy

- Replaced explicitly exception throw with a STOPPED return result

STOPPED stage in a branch should not fail the pipeline if all requisite stages succeeded

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindow.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindowSpec.groovy

~~From the logs, I am seeing that somewhere, somehow, something is converting our nice, clean `Integer`s into `Float`s when performing execution window calculations. This started around 10/11/16, but I can't see anything that would have caused this. So I'm just hacking away at the symptom here.~~
EDIT: there are other places in this class that are coercing floats back to integers. Going to assume this is not a new issue and I'm just bad at testing.

handle decimal numbers in restrict execution window days

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy

`List<Map> amiDetails = oortService.getByAmiId("aws", account, region, ami)` needs an `amiId` so if you use an ami name it can not resolve the amiDetails.
PTAL @tomaslin @ttomsu @dzapata

GetCommitsTask : Use amiId instead of ami name

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy

Before this orca can extract artifacts from triggering pipelines of depth 1.
This code enables orca to extract artifacts from pipelines in infinite depth
and also extract the build details from the build that produced the artifact.
The objective of this PR is to populate buildInfo in amis created with artifacts
from parent pipelines.

Extract buildInfo from parent pipelines

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/StageStatusPropagationListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSupport.java
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListenerSpec.groovy

Echo expects `stageDetails` key to be present in context. Because it wasn't there at the time the echo listener fires before the stage the "stage starting" notification was never triggered.

Fix v2 stage notifications

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/WaitForUpsertedImageTagsTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTagger.java

- A multi-region bake will produce multiple images (with the same name)
- `WaitForUpsertImageTags` will run less frequently (every 30s)

AmazonImageTagger should only tag distinct images (not all images)

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/HighlanderStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategy.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/HighlanderStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategySpec.groovy

@duftler @ajordens please review. If 'consider only platform health' is enabled and 'show health override for each stage' is disabled, synthesized stages don't inherit `interestingHealthProviderNames` properly from the `determineHealthProvider` task if that key is present in the stage context.

Propagate 'interestingHealthProviderNames' in synthesized stages.

---

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTask.groovy
orca-applications/src/test/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTaskSpec.groovy

We currently ignore the accounts that are passed in when updating an application.
@robzienert or @jeyrschabu PTAL

prefer accounts passed in when updating applications

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStage.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStageSpec.groovy

Restarting an ACA Task stage will cancel the Canary and, in doing so will put the stage into a STOPED state, preventing the
restarted pipeline from continuing.
This fix just put the stage state back to the RUNNING state that the 'prepareStageForRestart' puts it in.

Fixing stage state when restarting a ACA Task.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForCapacityMatchTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/HealthHelper.groovy

We get a lot of confused users when instances are not coming up for some reason. It might be a problem with their code, or their server group configuration, or capacity constraints on AWS. When it happens, though, it's pretty opaque to the user - the deploy (or resize) stage just spins until it times after after two hours.
I'm not 100% sure what it will look like, but I would like to feed this info into the running execution UI to provide more context to users.
There's more work to be done, e.g. if there are issues with the launch configuration, that almost certainly won't be surfaced by this info. 
But this should at least get us started on adding that visibility.
@ajordens PTAL

provide status info in execution context on AbstractInstanceCheckTasks

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/entitytags/DeleteEntityTagsTask.java

- Clouddriver will short circuit if the entity tags do not exist

Avoid fetching EntityTags from `clouddriver` when deleting

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/QuickPatchStage.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/pipeline/util/PackageInfoSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy

fixes the case were the build info/artifacts in the QUIP stage has been overwritten by a parallel or parent Jenkins stage.  the fix navigates the ancestors looking for the first match that contains the correct build info/artifacts based on the QUIP stage's properties.

fix QUIP stage when build artifacts are missing

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/DeleteLoadBalancerTask.groovy

@lwander deleting a kubernetes load balancer causes an exception right here.

safe check for regions in delete lb task

---

build.gradle
orca-core/orca-core.gradle
orca-extensionpoint/README.md
orca-extensionpoint/orca-extensionpoint.gradle
orca-extensionpoint/src/main/java/com/netflix/spinnaker/orca/extensionpoint/pipeline/PipelinePreprocessor.java
orca-pipelinetemplate/README.md
orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplateModule.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-web/orca-web.gradle
orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
settings.gradle

Adds an orca-extensionpoint module as a no-dependency API for adding extensions to orca core functionality.
Defines PipelinePreprocessor extension point and wires it into OperationsController /orchestrate endpoint to transform supplied JSON object.
Adds orca-pipelinetemplate module as placeholder to start work on declarative continuous delivery efforts, with initial (no-op) PipelinePreprocessor implementation (also not enabled by default without `pipelineTemplate.enabled=true`
Some build updates to get rid of all subprojects having groovy as a compile time dependency.
@spinnaker/netflix-reviewers PTAL - does adding a separate module for extension interfaces seem like a dumb idea? (orca-core is a pretty heavy dependency to bring in currently, was trying to avoid that...)

Adds orca-extension module to define extension interfaces.

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplateMerge.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigModuleReplacementTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/Identifiable.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateModule.java

Small change to get stages & templates merging using their ids, rather than names. I know @cfieber is messing around with TemplateMerge, so I didn't want to do a whole ton of stuff.
@cfieber PTAL

Fixing module & stage merge functionality

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy

Allows for a boolean flag be set on the stage context to make a call to
delete one or more fast properties via a pipeline stage.
This will be primarily used for the new Global Fast Property work that is in flight.

Add the ability to delete a Fast Property via Pipeline Stage

---

orca-validation/orca-validation.gradle
orca-validation/src/main/java/com/netflix/spinnaker/config/ValidationConfiguration.java
orca-validation/src/main/java/com/netflix/spinnaker/orca/validation/StageValidator.java
orca-validation/src/main/java/com/netflix/spinnaker/orca/validation/ValidationModule.java
orca-validation/src/main/java/com/netflix/spinnaker/orca/validation/exception/StageValidationException.java
orca-validation/src/main/resources/schemas/aws.json
orca-validation/src/main/resources/schemas/bake.json
orca-validation/src/test/groovy/com/netflix/spinnaker/orca/validation/StageValidatorSpec.groovy
settings.gradle

Ideally we have a single json schema document per stage type describing
relevant properties with some additional metadata linking the property
to 0..* cloud providers.
`orca` will process these schema documents and generate a valid json
schema containing only the properties supported by the current cloud
provider.

Preliminary support for validating stages against json schemas

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy

The call to delete a Fast Property does not return a body, only a status code
This was causing a NPE when calling the mimeTime() method on the body.
@robfletcher @ajordens PTAL

Fixes NPE when deleting a Fast Property.

---

orca-web/orca-web.gradle

Wasn't allowing access to orca for Netflix deployment.

downgrading fiat back down to 0.11.0 from 0.21.0

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/GraphMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/StageInheritanceControlTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/StageInheritanceControlTransformSpec.groovy

Allows for finer-grained control over what gets inherited
or overridden by child templates or configurations in nested
data structures.
This is being run after the render stage, so inheritance controls
cannot use handlebar templates. We can change this later on, but
I wanted to limit the amount of side-effects as part of introducing
this level of modification.
Implements this guy: https://github.com/robzienert/dcd-spec#inheritance-control

Adding inheritance control support for template stages

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CloneServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupMetadataTagTask.groovy
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java

- requires that the 'upsertEntityTags' operation is available in clouddriver

Support tagging of server groups when created / cloned

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTask.groovy

we don't need 1 second granularity on these operations, and with very high task activity this can cause some thrashing on the clouddriver redis side

poll clouddriver for task status less often

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/PropertyAction.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/cleanup/FastPropertyCleanupListener.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/pipeline/CreatePropertyStage.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/PropertyChangeCleanupSpec.groovy

Actually adding code to make the FastPropertyCleanupListener rollback a Fast Properties to a last know good state when a
Execution TERMINALs or CANCELs.
- Creating a new FP will delete it on failure/cancel
- Updating a FP will upsert the original property on failure/cancel
- Deleting a FP will also upsert the original property on failure/cancel

Fast Property Rollback on TERMINAL, CANCEL

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/FeaturesRestService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/FeaturesService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CloneServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupMetadataTagTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupMetadataTagTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/pipeline/DeploymentStrategiesExecutionSpec.groovy

* enables metadata tagging if `upsertEntityTags` is available from Clouddriver's features endpoint
* adds some tests
@spinnaker/reviewers PTAL - Deck changes to surface this metadata will follow...

tag server groups with metadata if feature enabled

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/cleanup/FastPropertyCleanupListener.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/PropertyChangeCleanupSpec.groovy

This should fix the fast property rollback on pipeline TERMINAL and CANCEL status
There was also a bug introduce that caused the monitoring of FP Deletes to fail with a NPE that this addresses.

Fix Fast Property Rollback

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineLauncher.java

@anotherchrisberry this is what I was mentioning to you.
I can trigger this behavior by running a pipeline like:
````json
{
"keepWaitingPipelines": false,
"limitConcurrent": true,
"parallel": true,
"lastModifiedBy": "user@host.net",
"stages": [
{
"refId": "1",
"requisiteStageRefIds": [],
"type": "destroyServerGroup",
"name": "Destroy Server Group",
"cloudProviderType": "aws",
"regions": [
"us-east-1"
],
"cloudProvider": "aws",
"target": "ancestor_asg",
"credentials": "test",
"cluster": "spintest"
}
],
"triggers": [],
"executionEngine": "v2",
"updateTs": "1486499714000"
}
````

if a pipeline fails during the initial startup phase, put it in a TERMINAL state with a cancellation reason

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/HealthHelper.groovy

There is a fundamental problem with the way we are calculating the `lastCapacityCheck` value: it is not contextually sensitive to the task. 
The up/down counts need to be based on what the task itself is using to determine success. When waiting for up instances, the task is going to wait for all health checks to pass - but we're counting the instance as "up" if _any_ health checks pass.
The initial design of this was to make it generic, so we could show it across all the `AbstractInstancesCheckTask`s. It's a nice idea, but I don't think it's particularly useful. The problem we were originally trying to help with was Deploy stages, when instances aren't passing health checks. And, in the UI, we're _only_ surfacing this data on the Deploy stage. So let's make it work on Deploy stages, and …

(core) only render lastCapacityCheck on WaitForUpInstancesTask

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ModifyAwsScalingProcessStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupLinearStageSupport.groovy

Tactical fix for SPIN-2298
Because `aroundStages` is re-entrant but in the case of TargetServerGroupLinearStageSupport it also mutates the original stage context it was losing the additional regions. I would like to not have the method be re-entrant at all but this should fix things for now.

Ensure target server group after stages are added correctly

---

orca-web/src/main/resources/logback-defaults.xml

@ttomsu 
You changed this here https://github.com/spinnaker/orca/commit/7514e2ad115798aa9b44c97c742ea8876f398928#diff-8af87d1b446779657d406343bfb9c928L20
I assume it was an accident.

Remove '-' before level in logback format to be like rest of Spinnaker

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/CloudDriverCacheService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/CloudDriverCacheStatusService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/MortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfigurationProperties.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/ImageForceCacheRefreshTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/DestroyJobForceCacheRefreshTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/DeleteLoadBalancerForceRefreshTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/UpsertLoadBalancerForceRefreshTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/securitygroup/DeleteSecurityGroupForceRefreshTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/securitygroup/SecurityGroupForceCacheRefreshTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/MigrateForceRefreshDependenciesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestServiceSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/DeleteLoadBalancerForceRefreshTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/UpsertLoadBalancerForceRefreshTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/securitygroup/DeleteSecurityGroupForceRefreshTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/securitygroup/SecurityGroupForceCacheRefreshTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/MigrateForceRefreshDependenciesTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTaskSpec.groovy

This extracts the mutating bits out of `OortService` and `MortService` leaving those only performing `GET` operations against clouddriver. Adds a `ConfigurationProperties` object for clouddriver baseUrl configuration that supports providing `clouddriver.readonly.baseUrl` as a pointer to a clouddriver that should only receive read operations (this could be backed by a redis read replica).
Also prefers `clouddriver.baseUrl` as the configuration for the standard clouddriver endpoint but falls back to one of `kato.baseUrl`, `oort.baseUrl`, `mort.baseUrl` for backwards compatibility with existing configurations.
This moves:
* `forceCacheRefresh` from `MortService` and `OortService` into `CloudDriverCacheService` which will hit the writable clouddriver url
* `pendingForceCacheRefreshes` from …

support pointing clouddriver reads at a readonly replica.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/DestroyServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/DisableServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ResizeServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/OortHelper.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/DestroyServerGroupTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy

Rough cut of a proposed guarding mechanism to prevent disable/destroy operations from leaving a cluster in a state where it has no instances taking traffic.
Requires the entity tags feature to be enabled.
@spinnaker/netflix-reviewers PTAL - if this seems like a good approach, I'll start working on the UI

initial cut at cluster guards

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy

If the application can't be found, a 404 gets thrown via Front50Service.
If some other error occurs, we should still block the operation and throw the exception.

throw exception if Front50 application retrieval returns non-200/404

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy

The default error message is vague:
```
Deploy Canary failureRequest to resolve images for missing regions requires exactly one image. (Found [])
```
This just makes it more clear (IMO).

provide better error message when canary baseline lookup fails

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/config/EchoConfiguration.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoEventIntegrationSpec.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoEventSpec.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListenerSpec.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/model/ApplicationNotifications.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/model/ApplicationNotificationsSpec.groovy

We currently rely on Echo to determine any application-configured pipeline notifications and send them out on pipeline events.
In the following unlikely scenario (because who would do something like this):
* a full Spinnaker is running (spinnaker-a)
* a separate Spinnaker stack (spinnaker-b) is running, but sends its notifications via Echo on spinnaker-a
spinnaker-a's Echo will only know about spinnaker-a, so when it fetches application-level notifications for a pipeline sent from spinnaker-b, it won't get them, or it will get the wrong notifications if there's an application with the same name in spinnaker-a.
To get around this, we can read from Front50 when starting a pipeline, and adding any pipeline-level notifications to the pipeline config.
The `ApplicationNotifications` class is …

core/notifications: add notifications from Front50 to pipeline notifications

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/zombie/ZombiePipelineCleanupAgent.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/zombie/ZombiePipelineCleanupAgentSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

This option will make it possible to force cancel a pipeline (kill a Zombie process) before the default timeout has passed.
The intent is to make a feature in Deck that lets a user force cancel a zombie process before the default timeout interval of the pipeline has elapsed.

Add optional force flag to the cancel pipeline endpoint

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/ExecutionPropagationListener.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/listeners/ExecutionPropagationListenerSpec.groovy

Current options on stage failure are:
* fail branch and cancel other branches, pipeline = TERMINAL
* fail branch, finish other branches, pipeline = SUCCEEDED (unless other stuff fails)
* ignore failure (FAILED_CONTINUE status), pipeline = SUCCEEDED
This adds another option where the branch stops, other branches can complete but the pipeline itself will be TERMINAL at the end. This is for make benefit Cadmium folks.

allow branch failure to fail pipeline even if other branches finish

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/ActiveExecutionTracker.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/SpringBatchActiveExecutionTracker.java
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/orca/batch/SpringBatchActiveExecutionTrackerSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Also don't flush them when an instance goes stale so we can see zombie executions.

add details of running executions to execution tracker

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy

In order for properties to be lookup enabled, need to add the values generated by the monitor jobs task to the global context

fix(jobs): add output from jobs to global context for downstream jobs

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/UnknownIdentifierHelper.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGeneratorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRendererSpec.groovy
orca-pipelinetemplate/src/test/resources/templates/invalid-handlebars-001.yml
orca-pipelinetemplate/src/test/resources/templates/invalid-template-001.yml
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

A very rudimentary plan capability for pipeline templates. I have some ideas on how to improve (and increase) debug output if people get to using this and need more output. I'd prefer to see how people start to use this feature before diving deep into enhanced output.
Should we want more details, I think I'll do some refactoring to allow us to collect consumer-friendly errors and debug output as we compile the execution. Before tackling this, I'd like to see what the UI might want to display so we're providing the right context.

feat(pipelinetemplates): Adding basic plan capability

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/WithMapKeyHelper.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/WithMapKeyHelperSpec.groovy

I'm converting some spindemo pipelines into solidified examples to verify we've got all the helpers we need to get things done without the deployment model work.
Handlebars' compatibility with maps is quite unpleasant, so this PR adds a new block helper that allows template owners to dynamically register variables using a specific map's key without iterating over the whole map.
Example: The deploy stage targeting AWS takes a list of clusters which is pretty easily iterable, but needs to be given both a region, as well as availability zones within that region.
```yaml
variables:
- name: regions
description: A list of regions to bake in
type: list
defaultValue:
- us-east-1
- us-west-2
- name: regionAvailabilityZones
description: A map of regions to availability zones to deploy into
type: …
```

feat(pipelinetemplates): Adding withMapKey handlebars helper

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/ActiveExecutionTracker.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/zombie/ZombiePipelineCleanupAgent.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/zombie/ZombiePipelineCleanupAgentSpec.groovy
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/SpringBatchActiveExecutionTracker.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Instead of using a heuristic to determine if a pipeline is in a zombie state we now just look at the reported state of the instance running the pipeline.

feature(netflix): simplify zombie pipeline cleanup

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/MonitorCanaryTask.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/tasks/MonitorCanaryTaskSpec.groovy

passes cloud provider to canary cleanup operations and uses new operation names

fix(canary): add cloud provider to canary operations

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy

- Added a guard to return with a TERMINAL status when we dont have a buildNumber

fix(Jenkins): Ensuring there is a buildNumber present in the context before proceeding

---

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupLinearStageSupportSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineStarterListener.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/pipeline/PipelineStarterListenerSpec.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoEventSpec.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListenerSpec.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy

This will any "anonymous" pipelines submitted via the REST API will run on v2. That should mean everything is running v2.
We should ensure this is happy before merging #1214

any execution that does not specify a version will run v2

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy

Allows multiple application names to be added to a scope for a fast property.
Previously only the first one in the appIdList was used.

Fast Property multiple apps in scope

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateConfiguration.java

Pipeline templates will eventually have an associated pipeline config in front50 when the UI side of things are developed, just like any other pipeline. Until then, adding a config option to allow people to manually specify the pipelineConfigId that an execution should be associated with.

fix(pipelinetemplate): Allow associating to an existing pipelineConfigId

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/InvalidPipelineTemplateException.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1SchemaValidationHelper.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateSchemaValidator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/validator/Errors.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/validator/SchemaValidator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/validator/VersionedSchema.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1SchemaValidationHelperSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidatorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateSchemaValidatorSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

Working in a better interface for performing validation of templates and configurations. This doesn't include working in any of the `orca-validation` module stuff. My goal here is to emit more user-friendly errors than stacktraces that are surfaced in the UI or Halyard.

feat(pipelinetemplate): Basic template & config validation

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/GraphMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConditionalStanzaTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/DefaultVariableAssignmentTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/ModuleHelper.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/WithMapKeyHelper.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/DefaultVariableAssignmentTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRendererSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/ConditionHelperSpec.groovy
orca-pipelinetemplate/src/test/resources/templates/conditional-stages-001.yml

Continuing to test more advanced templates. Apologize this PR is a bit over the place.
* Adding default variable assignment from templates into the configuration. This implementation was overlooked previously.
* Unmarshaling handlebars templates from JSON was failing if the rendered string had extraneous leading whitespace. I'm now trimming this before passing it off to the object mapper.
* A few minor quality of life changes on handlebars error handling. I'm very unsatisfied by the errors returned by the handlebars library, so I'll be putting together another PR to help address debuggability of incorrect templates.
* Most importantly, Terminator-ing the spelling of `judgment`.

fix(pipelinetemplate): Handlebars rendering & variable inheritance issues

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/BulkDestroyServerGroupStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractBulkServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/BulkDestroyServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/BulkDisableServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/BulkWaitForDestroyedServerGroupTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/BulkDestroyServerGroupTaskSpec.groovy

- Added bulk server group destroy operation
- This is supported within the scope of one application, one account & within one region
- A bulk ASG destroy request body would look like:
```
{
"job":[
{
"type":"bulkDestroyServerGroup",
"serverGroupNames":[
"app-v001",
"app-v002",
],
"region":"us-east-1",
"credentials": "account",
"cloudProvider": "titus",
"user":"u@netflix.com"
}
],
"application":"app",
"description":"Bulk Destroy Server Group: [app-v001, app-v002]"
}
```

feat(aws & titus): Adding support for bulk server group operations

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/TerminateInstanceAndDecrementServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/TerminateInstancesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DisableInstancesTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy

Traffic guards are pretty limited right now, and don't verify remaining instances are "Up" - only that the other server groups in the cluster have some instances and that the other server group is not disabled.
This checks for actual "Up" instances, and adds guards on terminate/disable (and terminate and shrink) instance operations.
This is going to add a fair amount of overhead to instance-level operations, so I'd like some feedback on performance concerns.
Also clarifying exception ("traffic protection" is now "traffic guards") message to be more consistent with other references.

feat(trafficguards): check on terminate/disable instances

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JsonRenderedValueConverter.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderedValueConverter.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTag.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTagSpec.groovy
orca-pipelinetemplate/src/test/resources/templates/conditional-stages-001.yml
orca-pipelinetemplate/src/test/resources/templates/invalid-handlebars-001.yml
orca-pipelinetemplate/src/test/resources/templates/simple-001.yml

Refactoring pipeline templates codebase to use a Jinja rendering engine over Handlebars.
While converting our internal pipelines to use templates, I found that I was spending a lot of time fighting against Handlebars. Jinja is a lot more expressive, so it's easier to work with (especially around maps and mutating objects). As a bonus, the standard Jinja tags, filters and expression are fairly well-featured, which should allow us to maintain a smaller codebase (whereas Handlebars, I was already having to build a number of helpers for simple quality of life). I opted for doing this work now, rather than later so we don't need to support a migration effort.
I'm leaving the handlebars code in place (and also the default) for the time being while I convert our already existing pipelines over …

feat(pipelinetemplate): Adding a Jinja template renderer alternative

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

I was errantly relying on `pipeline.plan` existing after any PipelinePreprocessors run, which can mutate the pipeline object (and in this case, was removing the attribute before the time we actually needed to use it).
cc @danielpeach

fix(pipelinetemplate): Ensure plan flag doesnt get overwritten by preprocessors

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplateMerge.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateSchemaValidator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/validator/EmptyValidatorContext.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/validator/ValidatorContext.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplateMergeSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateSchemaValidatorSpec.groovy

* Adds `protect` flag to templates, allowing template creators to prevent configuration-level modification of the stage graph. Going for the simplest level to start with, we can get more granular down the road if necessary.
* Adds new (optional) metadata block to templates containing `name`, `description` and `owner` so we can surface this in the UI for additional context.
@spinnaker/netflix-reviewers @spinnaker/google-reviewers PTAL

feat(pipelinetemplate): Metadata for UI; template protection

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/YamlRenderedValueConverter.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy

Big quality of life improvement for pipeline templating. Makes templates like these:
```yaml
- id: bake
type: bake
config:
regions: |-
[
{% for region in bakeRegions %}
"{{ region }}"{% if not loop.last %},{% endif %}
{% endfor %}
]
```
Easier to read and write, like so:
```yaml
- id: bake
type: bake
config:
regions: |
{% for region in bakeRegions %}
- {{ region }}
{% endfor %}
```
Still supports JSON, of course, so there's no incompatibility with existing templates.

feat(pipelinetemplate): Support YAML output from templates

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTag.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTagSpec.groovy

The current implementation of module parameters is fairly naive of the handlebars context. This change will allow people to resolve nested values in the context and resolve other EL expressions.

fix(pipelinetemplate): Resolve EL expressions in module param arguments

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/filters/FriggaFilter.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/filters/FriggaFilterSpec.groovy

A common thing in many stages is working with cluster names (or parts of them). Quality of life filter that should cut down the number of variables required in some templates.
```yaml
variables:
- name: clusterName
defaultValue: myapp-test-dcd
stages:
- type: deploy
config:
clusters:
- account: test
application: "{{ application }}" # var comes for free, but could also do `clusterName|frigga('app')`
freeFormDetails: "{{ clusterName|frigga('detail') }}" # dcd
stack: "{{ clusterName|frigga('stack') }}" # test
```
@spinnaker/netflix-reviewers @spinnaker/google-reviewers PTAL

feat(pipelinetemplate): Frigga jinja filter

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java

Crashing the pipeline when front50 is disabled causes problems when running pipelines against a minimal (clouddriver + orca) Spinnaker

fix(core): Don't apply traffic checks w/o front50

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindow.groovy

The current timeout of 2 days doesn't work so well if a stage starts on a Friday afternoon but is only allowed to run M-F in the mornings.
@robfletcher or @ajordens any concerns here?

fix(execution windows): allow execution window to wait for 7 days

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageFinder.java
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy

* fix bug in orca-igor whereby the field searched for the ami needed for
performing a commit diff (amiId) was changed without falling back to the
original value (ami) if the `amiId` was `null`.

fix(orca): fix ami retrieval for diff commits

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy

Adds some additional context to find image from cluster to include the missing locations to help users self-service find image issues.

fix(clouddriver): Add missing locations to failed find image error message

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy

In the case of multiple template inheritance, templates are first merged together by `TemplateMerge`, which doesn't have knowledge of injection rules. Once getting to the stage injection mutations, the stages with injection rules will re-insert themselves, creating duplicates. This caused incorrect graphs, as well as concurrent modification exceptions to be raised while using the streaming API.
@spinnaker/netflix-reviewers @jeyrschabu PTAL

fix(pipelinetemplate): Correctly handle template inheritance with injection

---

orca-loadtest/README.md
orca-loadtest/orca-loadtest.gradle
orca-loadtest/src/main/resources/orca-simulation.conf
orca-loadtest/src/main/resources/request-bodies/wait.json
orca-loadtest/src/main/scala/com/netflix/spinnaker/orca/loadtest/OrcaSimulation.scala
orca-loadtest/src/main/scala/com/netflix/spinnaker/orca/loadtest/OrcaSimulationConfig.scala
orca-loadtest/src/main/scala/com/netflix/spinnaker/orca/loadtest/OrcaSimulationEngine.scala
orca-loadtest/src/main/scala/com/netflix/spinnaker/orca/loadtest/actions/OrcaActions.scala
orca-loadtest/src/main/scala/com/netflix/spinnaker/orca/loadtest/scenarios/OrcaScenarios.scala
settings.gradle

Sets up the bare minimum structure for load tests in orca. This will be progressively enhanced to help enable vetting of nu-orca's reliability characteristics.
The plan here is to get this skeleton in place to run local load to vet what metrics will and will not be valuable for nu-orca. From there, my goal is to start injecting more diversified orchestations, polling and what have you to uncover any issues, as well as vet more advanced features like rate limiting, execution logs and so-on.
It's laid out kinda strange for such a simple implementation, but the structure scales well as we introduce more complexity. Thanks @jonsie for the pointers & refreshers.
PTAL @robfletcher

feat(loadtest): Skeleton loadtest

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/IllegalTemplateConfigurationException.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/InvalidPipelineTemplateException.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/TemplateRenderException.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/StageInheritanceControlTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderUtil.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTag.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1SchemaValidationHelper.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateSchemaValidator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/validator/Errors.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/StageInheritanceControlTransformSpec.groovy

Refactoring error handling in pipeline templates to correctly propagate causes.
In some cases, especially around modules, context was not being provided for
what the actual error was:
```json
{
"message": "Pipeline template is invalid",
"status": "BAD_REQUEST",
"errors": [
{
"severity": "FATAL",
"location": "template:stages.wait",
"message": "Failed rendering stage"
}
]
}
```
With these changes, errors now include details as well as nested errors, which 
gives a clearer picture of what the problem is:
```json
{
"message": "Pipeline template is invalid",
"status": "BAD_REQUEST",
"errors": [
{
"severity": "FATAL",
"location": "template:stages.wait",
"message": "Failed rendering stage",
"nestedErrors": [
{
"severity": "FATAL",
"location": "template:stages.wait",
"details": {
"reason": …
```

fix(pipelinetemplate): Bubbling up root cause errors

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageFinder.java

* remove no longer used `amiId` property from `deploymentDetails` map on
the stage context for AWS.  this is cleanup as a result of the
discussion in #1264.

chore(aws): remove no longer used amiId

---

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/pipeline/DeploymentStrategiesExecutionSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupport.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/ExpressionPreconditionTask.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupportSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/ExpressionPreconditionTaskSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/restart/RollingRestartSpec.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/config/EchoConfiguration.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoEventIntegrationSpec.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListenerSpec.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/config/SpringBatchConfiguration.java
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/orca/batch/ExecutionContextManager.groovy
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/orca/batch/RetryableTaskTasklet.groovy
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/orca/batch/TaskTasklet.groovy
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/orca/batch/TaskTaskletAdapter.groovy
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/orca/batch/ExecutionContextManagerSpec.groovy
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/orca/batch/adapters/RetryableTaskTaskletSpec.groovy
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTaskletSpec.groovy
orca-test/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

- whitelist which classes and methods can be used in pipeline expressions
- inject configuration into ContextParameterProcessor to enable whitelisting allowed
URLs in the fromUrl function

fix(expressions) - restrict expressions

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/UserConfiguredUrlRestrictions.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/WebhookService.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/WebhookServiceSpec.groovy

breaking: this changes the configuration namespace for the recently introduced URL restriction configuration from `expressions` to `userConfiguredUrlRestrictions`

fix(url restriction) - includes url restriction on webhook stages

---

orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy

Adds a test case for the fix in efbc839ad4e48e3d6ad5325f22e0a8981d04f213 that highlights the danger of allowing unknown subtypes to be instantiated (rx.internal.util.RxThreadFactory extends AtomicLong extends Number)

fix(expressions) - test case highlighting why classes should be explicitly whitelisted

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSupport.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/orca/batch/SpringBatchExecutionRunner.java

This was partly masked by the fact that restarting on the same orca instance would use the same Spring Batch job so nothing got rebuilt at all. However, restarting on a new instance would duplicate all the synthetic and parallel stages.
SPIN-2505

make sure synthetic stages don't get re-generated on restart

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplateService.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/PipelineTemplateController.groovy

Endpoint resolves & merges a template inheritance tree by source. This will be used to help Deck render variable bindings while configuring a pipeline template.

feat(web): Adding resolve pipeline template endpoint

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSupport.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Task.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/restart/PipelineRestartingSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/restart/RollingRestartSpec.groovy
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/orca/batch/SpringBatchExecutionRunner.java

Previously deserializing old executions could blow up if someone renamed a Task implementation class. Now at least it will only prevent running a new execution. Still not ideal but having a bean name reference or whatever is just as prone to breakage and this solution doesn't require any data migration.

Task.implementing class becomes a String to avoid CNFE when deserializing

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/CaptureSourceServerGroupCapacityStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/RollbackServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToServerGroupResizeStrategy.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/RollbackServerGroupStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupSnapshotTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToServerGroupResizeStrategySpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java

This prevents the target server group from unnecessarily scaling down
and causing the rollback to timeout / take far longer than expected.
`min` capacity is restored when the rollback is complete.

Pin `min` capacity to `desired` capacity when rolling back

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/Front50SchemeLoader.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/pipeline/CreatePipelineTemplateStage.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/pipeline/UpdatePipelineTemplateStage.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/tasks/CreatePipelineTemplateTask.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/tasks/UpdatePipelineTemplateTask.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/loader/Front50SchemeLoaderSpec.groovy

Adds: 
* Added `spinnaker://myPipelineId` template loader
* Added create & update tasks for write operations into front50
* Added `scope` stanza list for templates, this will be used via the UI to filter what templates are available for people to create templates from. Will add enhancement in a followup PR to enforce within orca as well.
@spinnaker/netflix-reviewers PTAL for initial feedback

feat(pipelinetemplate): Support spinnaker-baked pipeline templates

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesContainerFinder.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesContainerFinderSpec.groovy

This aims to enable the deployment of baked docker containers by making two changes:
- The bake stages `refId` is added to the `deploymentDetails`
- The parsed docker image name is added to the `imageDetails`
This PR is a requirement for https://github.com/spinnaker/deck/pull/3588 to work and these two PRs should therefor be seen in unison. Like I mentioned in the Deck PR, I'm open to corrections on this approach, as I've merely made this work, and there might be a different preferred path.

feat(provider/kubernetes): Enable deployment of baked docker containers

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/WebhookService.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/WebhookServiceSpec.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy

This will add support for customizing request headers that will be sent to the service called by the webhook stage.
Depends on https://github.com/spinnaker/deck/pull/3589

feat(webhooks): allow custom headers on webhook call

---

orca-queue-redis/orca-queue-redis.gradle
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueue.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueSpec.kt
orca-queue-sqs/src/main/kotlin/com/netflix/spinnaker/config/SqsQueueConfiguration.kt
orca-queue-sqs/src/main/kotlin/com/netflix/spinnaker/orca/q/amazon/SqsQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/QueueConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Queue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/TrafficShapingQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/memory/InMemoryQueue.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/memory/InMemoryQueueSpec.kt

Once a failed message has been tried 10 times it gets passed to a handler that will terminate the associated pipeline

fix(queue): limit re-deliveries of failed messages

---

orca-core/orca-core.gradle
orca-loadtest/src/main/resources/request-bodies/wait.json
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisExecutionLogRepository.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/ExecutionLogListener.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/ExecutionLogRepository.kt
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Returns fun payloads like so:
```json
[
{
"executionId": "003d47e0-b079-445a-bcce-8fb42c6886f7",
"timestamp": "2017-04-27T23:16:05.571Z",
"eventType": "ExecutionStarted",
"details": {},
"currentInstanceId": "nfml-rzienert"
},
{
"executionId": "003d47e0-b079-445a-bcce-8fb42c6886f7",
"timestamp": "2017-04-27T23:16:05.621Z",
"eventType": "StageStarted",
"details": {},
"currentInstanceId": "nfml-rzienert"
},
{
"executionId": "003d47e0-b079-445a-bcce-8fb42c6886f7",
"timestamp": "2017-04-27T23:16:05.655Z",
"eventType": "TaskStarted",
"details": {},
"currentInstanceId": "nfml-rzienert"
},
{
"executionId": "003d47e0-b079-445a-bcce-8fb42c6886f7",
"timestamp": "2017-04-27T23:16:20.775Z",
"eventType": "TaskComplete",
"details": {
"status": "SUCCEEDED"
},
"currentInstanceId": "nfml-rzienert"
},
{ …
```

feat(nuorca): Add get execution logs endpoint

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Executions.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Message.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/MessageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/PauseTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerSpec.kt

Because of concurrency issues in `JedisExecutionRepository` it's pretty easy to end up with invalid task ids. Obviously, that needs fixing but it did expose that they weren't getting handled well.

fix(queue): don't just assume task ids are valid

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/azure/AzureServerGroupCreator.groovy

This was displaying as an empty string in Deck

fix(azure): Set imageName on server groups

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/WebhookService.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/WebhookServiceSpec.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTaskSpec.groovy

Add custom header support to monitor (getStatus) task  of webhook stage.
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](http://www.spinnaker.io/docs/contributing-to-spinnaker).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests …

feat(webhooks): allow custom headers on monitor task of webhook stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/oraclebmcs/OracleBMCSServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/oraclebmcs/OracleBMCSServerGroupCreatorSpec.groovy

This adds an Oracle BMCS server group creator pipeline task. This has been tested against latest clouddriver where we've recently finished integration of the Oracle BMCS provider.

feat(oraclebmcs): Add Oracle BMCS server group creator

---

gradle/spek.gradle
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Message.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ConfigurationErrorHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/discovery/DiscoveryActivatedSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/MessageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueProcessorSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/SpringIntegrationTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ConfigurationErrorHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/PauseStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/PauseTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/spek/should.kt

Instead of the `CompleteExecution` message carrying a status (that might get overridden), the handler now works out the status based on the pipeline state. That way it can ignore messages sent early when un-joined branches complete, can override status sensibly, etc.

handle completion of executions correctly

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/UpsertLoadBalancerTask.groovy

Prior to this PR, defaulting to `clusterName` without null-checking would cause the context name to default to 'null-frontend' in some cases when Orca asked Clouddriver for a cache refresh, which would cause failures that were subtle and hard to debug without `FULL` debug levels on Orca and Clouddriver. This way is safer and clearer in case of defaulting failures.

fix(upsert_lb_task): Fix up context name defaulting.

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Executions.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/time/time.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerSpec.kt

timeout should be based on start time of the task not the stage, also paused time should only be considered if the execution was paused _during_ the task.

fix(queue): handle task timeouts correctly

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueue.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueSpec.kt

Queue locks were trying to apply the lock to a set. It would kinda work but was spawning tons of unnecessary redis keys.
Execution windows could not be skipped because of an obscure snag in the execution repository. If a stage actually had data for all its fields (nothing `null`) we'd try to issue an `hdel` command with no fields which is invalid. Execution windows showed this up as they're one of the few things that sets the `lastModified` details field on stages.

fix queue locks and skipping execution windows

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueue.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueSpec.kt

This caused some unexpected behavior with re-delivering messages

Revert "fix(queue): instance lock logic was backward"

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/resources/templates/jinja-001.yml
orca-pipelinetemplate/src/test/resources/templates/jinja-002.yml

This enables us to use jinja to override what template source to use. This means you can upload a template in your ci build and use that one in the pipeline execution. This means we can have pipeline definitions following the same flow as other code and still be able to rollback easily.
```
{
"appConfig": {},
"config": {
"pipeline": {
"application": "gardtest",
"name": "My wait pipeline",
"pipelineConfigId": "eebaa78d-ecc2-4638-86aa-1afa9defebec",
"template": {
"source": "file:///opt/orca/templates/{{trigger.parameters.template}}"
},
"variables": {}
},
"schema": "1"
},
"executionEngine": "v2",
"keepWaitingPipelines": false,
"lastModifiedBy": "gard.rimestad@schibsted.com",
"limitConcurrent": true,
"parallel": true,
"parameterConfig": [
{
"default": "test.yml",
"name": "template"
}
], …
```

feat(dcd): support setting templates from trigger context using jinja

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java

We don't want userland code interacting with the filesystem.
Also, making test output less bad and noisy. @robfletcher FYI

fix(pipelinetemplate): Disable risky jinja tags

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Message.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueExecutionRunner.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/Stages.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerSpec.kt

- fixes propagation of user as handler doesn't have access to authenticated request
- clears `canceled` flag on restart so it's possible to restart canceled pipelines
- clears nested synthetic stages of stages being reset

Fixes to restart handling in v3

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/GraphMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigPartialReplacementTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PartialDefinition.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/DefaultRenderContext.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderContext.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy

Implements the common cases for [Template Partials](https://github.com/spinnaker/dcd-spec/blob/master/PIPELINE_TEMPLATES.md#partials). There's some cleanup necessary (some fairly rough code in here), as well as adding support for recursive partials before this can go in.
I also departed from the spec in some ways that I'll need to go back and update. Most notably, instead of adding a `ref` field into `StageDefinition`, I rolled it up into the `type`:
```yaml
stages:
- id: foo
type: partial:myPartial
partials:
- id: myPartial
```
@jeyrschabu PTAL

feat(pipelinetemplate): Pipeline Template Partials support

---

build.gradle
orca-core/src/main/groovy/com/netflix/spinnaker/orca/ExecutionStatus.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupportSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/ExecutionLatch.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerSpec.kt

the existing restrictions weren't being applied when the object graph was traversed using property notation
additionally this change removes all the types from the expression root object (it will just be a JSON object of Map<String, Object> where as before it was actually a reference to the execution object
finally this converts ExecutionStatus from groovy to java which had a minor ripple into some of the kotlin code (@robfletcher might have a suggestion on naming the property acccessor differently on ExecutionStatus?)

fix(expressions): further restrict object traversal in expression processing

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSupport.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StageBuilderAware.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/Stages.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerSpec.kt
orca-web/config/orca.yml
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/config/PreconfiguredWebhookProperties.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/config/WebhookConfiguration.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/exception/PreconfiguredWebhookNotFoundException.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStage.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStage.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookService.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/config/PreconfiguredWebhookSpec.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStageSpec.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookServiceSpec.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTaskSpec.groovy

Adds support for preconfigured webhook stages that appears as native stages in Deck. Please have a look, I'm sure there's a lot of room for improvement here 😃
Screenshots from Deck:
Example configuration in `orca.yml`:
```yaml
webhook:
preconfigured:
- label: Some Webhook
description: This is a webhook stage, but it appears as a native stage in Spinnaker
type: customWebhook # Should be unique
enabled: true # default true
url: https://my.webhook.com/event
headers:
Accept:
- application/json
AnotherHeader:
- valueOne
- valueTwo
method: POST
payload: |
{
"text": "Version ${trigger.buildInfo.artifacts[0].version} deployed"
}
waitForCompletion: true
statusUrlResolution: webhookResponse # getMethod, locationHeader, webhookResponse
statusUrlJsonPath: $.statusUrl # Only used if …
```

feat(webhooks): Support preconfigured webhook stages

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy

Allow access to authenticated user name and paused details

fix(expressions): Allow access to additional execution attributes.

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Executions.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Message.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueProcessor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/memory/InMemoryQueue.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerSpec.kt

This aims to prevent 2 scenarios:
1. two parallel stages complete essentially at the same time and CompleteStageHandler thinks the other one is still running so it no-ops.
2. two branches complete at the same time and CompleteExecutionHandler makes the same mistake.

Fix occasional stalled pipelines

---

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/VerifyApplicationHasNoDependenciesTask.groovy
orca-applications/src/test/groovy/com/netflix/spinnaker/orca/applications/tasks/VerifyApplicationHasNoDependenciesTaskSpec.groovy

Since we're no longer passing in account, we can greatly simplify dependency verification when deleting an application.

fix(application): simplify dependency verification on app delete

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Executions.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandlerSpec.kt

If any BEFORE stage failed this would just have kept retrying its message forever. The condition was if all BEFORE stages have passed (or skipped or whatever) then continue this stage otherwise retry later. If any BEFORE stage failed the condition would never be true.

don't retry ContinueParentStage if a BEFORE stage has failed

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageFinder.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageFinderSpec.groovy

When using Redis to cache AMIs it is possible to receive a NullPointerException such as this:
```
java.lang.NullPointerException
at com.netflix.spinnaker.orca.clouddriver.tasks.providers.aws.AmazonImageFinder$AmazonImage.toAmazonImageDetails(AmazonImageFinder.java:98)
at com.netflix.spinnaker.orca.clouddriver.tasks.providers.aws.AmazonImageFinder.lambda$null$2(AmazonImageFinder.java:59)
at java.util.Optional.map(Optional.java:215)
at com.netflix.spinnaker.orca.clouddriver.tasks.providers.aws.AmazonImageFinder.lambda$byTags$3(AmazonImageFinder.java:59)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.netflix.spinnaker.orca.clouddriver.tasks.providers.aws.AmazonImageFinder.byTags(AmazonImageFinder.java:56)
at com.netflix.spinnaker.orca.clouddriver.tasks.image.FindImageFromTagsTask. …
```

fix(provider/aws): Prevent NullPointerException when image id is not in the cache

---

gradle/buildViaTravis.sh
gradle/installViaTravis.sh
settings.gradle

This will include the loadtest project if the `-Pskip.loadtest=true` is not passed into gradle commands. Explicitly setting this flag in all Travis operations so we can speed up the build.
@cfieber @robfletcher PTAL

chore(build): Conditionally include loadtest project in build

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/YamlRenderedValueConverter.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy

When rendering a graph (we assume any root-level render is a graph), we pass the rendered value into a value converter to expand the value into additional renderable objects. When pipeline expressions are used, the YAML converter throws an error attempting to parse the output as a YAML document, which is incorrect.
I'm catching the generalized invalid token parser exception, rather than attempting to determine if the rendered value is a valid expression syntax, which I think should be sufficient.

fix(pipelinetemplate): Handle converting groovy expression syntax better

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.kt

Also made queue metric gathering less aggressive

fix(queue): ensure null queue state is never returned on new instances

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

calling toJson on an object with expressions in it (execution, stage, stage.context) returns
a String containing an expression which is then reevaluated. This string typically contains
the orignal toJson expression and the result is infinitely evaluating the expression and hanging
the execution
this rejects a toJson call that returns a String that still contains an expression

fix(expressions): fixes an issue with toJson on expressions.

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerSpec.kt
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/orca/batch/RetryableTaskTasklet.groovy
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/orca/batch/adapters/RetryableTaskTaskletSpec.groovy

There are cases where a manual judgment stage should be marked successful if no user input is ever provided and the stage times out.
@robfletcher PTAL - is the stage context the right place to declare this (seems like it to me)? Also, happy to make it a `const` somewhere instead of a string in the tasklet.

feat(task): add flag to let stage succeed on timeout

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/CleanUpTagsTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/CleanUpTagsTaskSpec.groovy

This PR changes two things:
- Fetch `imageId` from the server group launch config, because it's not available in the context
- Sends the fully qualified server group id to clouddriver, not just the name

fix(tagging): Fix cleaning of entity tags during rolling push

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisTrafficShapingConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisPriorityCapacityRepository.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisRateLimitBackend.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/QueueConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/TrafficShapingConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/TrafficShapingProperties.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/TrafficShapingQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/capacity/PrioritizationStrategy.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/capacity/PriorityCapacityListener.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/capacity/PriorityCapacityRepository.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/ApplicationRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/GlobalRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/PriorityCapacityQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/ratelimit/RateLimitBackend.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/TrafficShapingQueueSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/ApplicationRateLimitQueueInterceptorSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/GlobalRateLimitQueueInterceptorSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/PriorityCapacityQueueInterceptorSpec.kt

An interceptor designed to help maintain message processing SLAs by
assigning Priority to each individual message according to a custom
PrioritizationStrategy.
It can be configured with a ceiling of concurrent executions, which
once exceeded, will begin to throttle lower-priority messages to make
room for higher ones.
As of this PR, OSS Orca will only ship with a ConstantPrioritizationStrategy,
which assigns all messages MEDIUM Priority. It's expected that each
organization running Spinnaker would have varying opinions of what
types of messages have certain priorities, and how to determine them. At
Netflix, I'll be writing a strategy that will allow us to blanket assign
priority to certain applications & teams, and eventually, take into account
the cloud account that a pipeline is …

feat(queue): Prioritized message capacity guarantees support

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy

I really wish I could say I knew why this actually worked the way it was originally on v2...

fix(aws/deploy): before stage preprocessors were not working on v3

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/scalingpolicy/DeleteScalingPolicyStage.groovy

Not breaking anything, just a little surprising when you see it.

fix(aws): fix monitor task name on delete scaling policy stage

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/PipelineModelMutator.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/SavePipelineStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/UpdatePipelineStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTaskSpec.groovy
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderUtil.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutatorSpec.groovy

Merging this won't physically change any functionality. A followup PR in gate will move the save path from `gate -> front50` to `gate -> orca -> front50`.
This PR includes a mutator that will allow templated pipelines to correctly save params, triggers, etc to where the rest of spinnaker expects them to be when saved into front50.

feat(pipelines): Add support for task-backed pipeline config saves

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupport.groovy

There were changes to the order in which expressions get validated for the v3 engine. This makes sure that expressions both with ${} and without are evaluated correctly in the `conditional on expression` field for stages.

fix(core)- optional stage support cannot handle expressions with ${}

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisRateLimitBackend.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/TrafficShapingProperties.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/ApplicationRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/GlobalRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/PriorityCapacityQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/ratelimit/RateLimitBackend.kt

Allows static & dynamic configuration of queue traffic shaper rate limit durations.

feat(queue): Configurable rate limit durations

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutatorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGeneratorSpec.groovy

@danielpeach Sorta what I'm thinking to fix that TODO in roer. I think the mutator work is superfluous to the reordering in the JSON generator, though. I'd be interested to hear what version of orca they're running that they don't see the auto-mapping already working - maybe this reordering will do the trick alone.

fix(pipelinetemplate): Prefer pipeline ID over templated value; map on save

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueProperties.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisDeadMessageHandler.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisDeadMessageHandlerSpec.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueProcessor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandler.kt

I'm not handling unsupported message types at this point. There were no occurrences over the last 24 hours of unsupported message types; everything fell through the `DeadMessageHandler`. However, I did add more context around the QueueProcessor TODO for a DLQ that will output what the message contents actually are if something were to go that path.

feat(queue): Implement redis-backed dead message handler

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/RollingPushStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/WaitForNewUpInstancesLaunchTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/RollingPushStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/WaitForNewUpInstancesLaunchTaskSpec.groovy

The current rolling push code assumes every new instance that is started during a rolling push will eventually come up healthy. We've learned that is not a great assumption: instances sometimes never start, or never become healthy and are terminated, which leads the rolling push to enter a terminal state, as the WaitForUpInstanceHealthTask will get a 404 trying to fetch the instance.
This change consolidates the `waitForNewInstances` and `waitForUpInstances` tasks into a single task, which is resilient to these scenarios, as it only records instances once they've become healthy.

fix(rollingpush): handle new instance termination

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/config/QueueConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueProcessor.kt

The current messageHandler thread pool never expands its capacity because the queue never fills (default capacity is `Integer.MAX_VALUE`) so the new `QueueExecutor` will never stop polling the redis queue.
@cfieber @robfletcher PTAL

fix(queue): Sets boundary on thread pool work queue and aborts work when full

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/MessageHandler.kt

This was encountered when trying to destroy a server group in Deck via authentication and authorization enabled.
With this change the authentication information is propagated from either:
a) A previous AuthenticatedStage
b) AuthenticationDetails inside of the Execution (which can be set in OrchestrationLauncher, for example)
Here is an example log showing the issue:
```bash
2017-07-06 13:40:54.740 DEBUG 22241 --- [0.1-8083-exec-3] c.n.s.f.shared.FiatAuthenticationFilter  : [testuser] Set SecurityContext to user: testuser
2017-07-06 13:40:54.791  INFO 22241 --- [0.1-8083-exec-3] c.n.s.o.c.OperationsController           : [testuser] requested task:{
"application" : "test123",
"name" : "Destroy Server Group: test123-v002",
"appConfig" : null,
"stages" : [ {
"interestingHealthProviderNames" : …
```

fix(stage): Fixed an issue with authentication details propagation.

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/YamlRenderedValueConverter.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy

We had some more edge cases with ternary ops that break the YAML converter. This change will blanket treat anything that looks like a potential EL as the final rendered value.

fix(pipelinetemplate): Ignore rendering anything that might look like an EL

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/tasks/SavePipelineTemplateTask.java

@robzienert 
Changed my mind from this morning, since templates without scopes don't show up under `{front50}/pipelineTemplates`, which is pretty confusing. Also the dcd-spec says they're required.

fix(pipeline_templates): require scopes

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/TargetReferenceSupport.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/TargetReferenceSupportSpec.groovy

We want Orca to retry on 429s, which can happen frequently, but not on 404s, which indicate a cluster truly does not exist.

fix(targetReferenceSupport): retry non-404 errors getting cluster

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisPriorityCapacityRepository.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/capacity/PriorityCapacityListener.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/capacity/PriorityCapacityRepository.kt

The current strategy doesn't actually track executions very well (currently the MEDIUM index in prod shows 10000 running executions, which is obviously wrong). Storing by execution ID will allow us to do compensation jobs if things drift due to weirdness, etc.
@ajordens @robfletcher PTAL

fix(queue): Changing redis impl for priority capacity traffic shaper

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/OrchestrationLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionLauncherSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerSpec.kt

This field is meaningless and misleading with v3 in place. Executions are no longer pinned to an instance.

chore(model) remove executingInstance field from execution

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTaskSpec.groovy

When a child pipeline fails, we do not provide any error messaging to users, as it's buried in the child execution. If pipelines are chained together, e.g. pipeline A has a pipeline stage that kicks off pipeline B, which has a pipeline stage that kicks off pipeline C, and C fails, that error is really hard to track down.
This extracts any errors (we have similar logic in Deck) and adds the exception to the pipeline stage itself.
@robfletcher or @ajordens or @robzienert PTAL

fix(core): propagate exceptions from child pipelines

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutator.java

@robzienert please review.
An update fails if the pipeline config uses a template and has parameters/notifications/triggers.

fix(pipeline_templates): do type conversion during pipeline save

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy

This writes out the contents of a properties file to a map called propertiesFileContent. This will allow us to render it in the UI and potentially use it to reconstruct a global context for restarts.

fix(script, jenkins): put results of properties files in its own map

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy

This fixes a `StringIndexOutOfBoundsException` when calling the function `resolveInfoFromAmi` and the `appVersion` doesn't match the required pattern.
Added a regexp to check for the required pattern and a simple test.

fix(igor): Resolve index out of bound exception and added test for it

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy

Otherwise the new server group will be started with the original size of the other cluster

fix(core): set use source capacity to false in rolling red black

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Message.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/ApplicationRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/GlobalRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/PriorityCapacityQueueInterceptor.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/TotalThrottleTimeAttributeTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/ApplicationRateLimitQueueInterceptorTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/GlobalRateLimitQueueInterceptorTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/PriorityCapacityQueueInterceptorTest.kt

* add new message attribute for keeping track of the total amount of
time a message is throttled.
* modify the task handler to deduct the total throttled time in the
calculation of how long a task has been executing before timing out.

fix(queue): consider throttle time before timeout

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

Using a WWII-era library to make durations human readable, e.g. "5 minutes" instead of "PT5M"

fix(timeout): make timeout duration human readable

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStageSpec.groovy

If a canary stage is marked to continue on failure, we'll throw a bunch of NPEs on the canaryComplete task, assuming the deployments were successful, so we need to short-circuit that.

fix(canary): mark deployComplete terminal if any deploy stages failed

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

A handful of tasks explicitly return FAILED_CONTINUE, but we end up dropping those messages in the task handler.

fix(taskHandler): treat FAILED_CONTINUE as SUCCEEDED

---

orca-eureka/src/main/java/com/netflix/spinnaker/orca/eureka/NoDiscoveryApplicationStatusPublisher.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/AdminController.groovy

Note this only works when the instance is not managed by eureka.

feat(queue): Make instance status externally settable

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreatorSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CreateServerGroupTaskSpec.groovy

The current message is a rather cryptic `allowLaunchDescription.amiName.empty`, because we delegate the validation to Clouddriver.
We know this error is going to happen before we send the operation to Clouddriver, so we might as well give the user something more useful to work with.
@tomaslin I don't believe this should affect Titus (doesn't seem like Titus has any notion of AZs), but I added an additional guard to check the `cloudProvider` field before adding the `allowLaunchOperation`s just in case, so PTAL.

fix(provider/amazon): better error on failing allowLaunchOperation

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/RetryableTask.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/MetricsExecutionListener.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt

This PR also introduces a few new metrics:
- `executions.started`: A counter for all started pipelines/orchestrations
including application name.
- `task.invocations.duration`: A distribution summary for tasks grouped by
duration (lt5m, gt5m, gt15m, gt30m, gt60m).

feat(task): Tasks can specify a dynamic `backoffPeriod`

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/AdminController.groovy

Commit 09e2933c185871c4ac91168f6f816394da3ce84f fails on startup as there are > 1 `ApplicationListener` beans in play.

fix(orca) prevent bean override

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTaskSpec.groovy

Pipeline save operations via tasks incorrectly evaluate pipeline expressions. This PR changes the expected contract to use base64 encoded pipelines instead.
Also reduces the backoff time for the task so UI ops don't take so long.

fix(front50): Base64 decode pipeline save tasks

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/filters/Base64Filter.java

There was a bug in the previously used jinjava version that caused empty filters (e.g. `'hello'|base64`) to fail, but work when called as a function. Also a null-check fix.

fix(pipeline_template): Fix base64 filter via lib upgrade

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt

This commit https://github.com/spinnaker/orca/commit/03ebaf54ff9742a02b00b91f736a062d561e057d changed the behavior such that ${region} fails to evaluate properly when used in a bake stage (e.g. `aws_$region$.json` when specified for `varFileName` evaluates to `aws_.json`.
This PR uses a cloned stage when determining whether a stage can be skipped, to avoid the (too early) side-effects of swapping out the context of the real stage.

fix(core): Clone stage before evaluating optional condition.

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/filters/Base64Filter.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/filters/Base64FilterSpec.groovy

It was requested that the value being passed to base64 be rendered prior to encoding.

feat(pipeline_template): base64 var rendering support

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/YamlRenderedValueConverter.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy

@robzienert please review.
If your template had
```
keyA: yes
keyB: 'yes'
```
Orca was mapping it in the rendered pipeline to
```
{
"keyA": true,
"keyB": true
}
```
Should now map to 
```
{
"keyA": true,
"keyB": "yes"
}
```
Open to suggestions for a better approach.

fix(pipeline_templates) ignore yaml keywords in rendered value converter

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingCloudDriverCacheStatusService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingClouddriverService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingMortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/ByApplicationServiceSelector.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/ByExecutionTypeServiceSelector.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfigurationProperties.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/DefaultServiceSelector.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/SelectableService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/ServiceSelector.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfigurationPropertiesSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/config/SelectableServiceSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/ExecutionContext.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/AuthenticationAware.kt

Criteria can be applied to each clouddriver to filter the types of requests that will be sent to it.
This PR supports execution type and application (regex) criteria.
If no criteria is specified, all requests are eligible to be sent to the particular clouddriver.
Example Configuration:
```
clouddriver:
baseUrl: https://my-writeable-clouddriver.com
readonly:
baseUrls:
- baseUrl: https://clouddriver-for-orchestrations.com
priority: 5
config:
selectorClass: com.netflix.spinnaker.orca.clouddriver.config.ByExecutionTypeServiceSelector
executionTypes:
- orchestration
- baseUrl: https://clouddriver-for-spindemo.comm
priority: 10
config:
selectorClass: com.netflix.spinnaker.orca.clouddriver.config.ByApplicationServiceSelector
applicationPattern: .*spindemo.*|.*cdspindemo.*
- baseUrl: …
```

feat(clouddriver): Support multiple read-only clouddrivers

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingClouddriverService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/ByOriginServiceSelector.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/SelectableService.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/config/SelectableServiceSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/ExecutionContext.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/AuthenticationAware.kt

This allows you serve all pipeline/orchestrations generated by the UI
with a dedicated clouddriver read replica.

feat(clouddriver): Support sharding read-only requests by `origin`

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTag.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTagSpec.groovy

Must strip only leading & trailing (single or double) quotes. Some pipelines also have quotes (of both types) intermixed in the actual pipeline name.
@jeyrschabu FYI

fix(pipeline_template): Correctly unwrap quotes in pipelineId tag

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java

Someone in OSS hit an error caused by upgrading orca, but not gate, which caused a ClassCastException to be thrown. Adding an explicit check & prompt for upgrading gate.

fix(front50): Throw exception if using old gate version API

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/ByOriginServiceSelector.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/config/SelectableServiceSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt

```
clouddriver:
readonly:
baseUrls:
- baseUrl: https://clouddriver-deck-only.com
priority: 20
config:
selectorClass: com.netflix.spinnaker.orca.clouddriver.config.ByOriginServiceSelector
origin: deck
executionTypes:
- orchestration
```
Also adjusted logging around the `CompleteExecution` message.

feat(sharding): Support for execution type restriction in `ByOriginSelector`

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java

@robzienert 
Template rendering should fail if the template includes, e.g., `{{region}}` and `region` hasn't been defined.

fix(pipeline_templates): fail if template has undefined variable

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/PipelineTemplateController.groovy

Before the configuration stanza was defined in a singular form as `pipelineTemplate`.
To keep it consistent with the feature name it is now changed to plural form.

fix(pipeline_templates): change configuration stanza to pipelineTemplates

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTaskSpec.groovy

Outputs a sentinel value after successfully retrieving the task info from clouddriver so that a subsequent instance of MonitorKatoTask in the same stage doesn't inherit the state tracking from the original MonitorKatoTask.
Sentinal value because you can't delete things from the stage context via task results due to use of ImmutableMap.

fix(clouddriver): support retries from multiple MonitorKatoTasks in a stage.

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/HttpTemplateSchemeLoader.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy

Imagine the following managed pipeline that is triggered with:
```
shouldWait: true
regions: us-west-2,us-east-1
```
```
---
schema: "1"
id: waitChain
variables:
- name: shouldWait
defaultValue: "{{ trigger.parameters.shouldWait == true }}"
- name: regions
defaultValue: "{{ trigger.parameters.regions | split(',') }}"
stages:
- id: wait1
type: wait
config:
waitTime: 1
when:
- "{{ shouldWait == true }}"
- id: bake
type: bake
dependsOn: [wait1]
config:
...
regions: |
{% for region in regions %}
- "{{ region }}"
{% endfor %}
when:
- "{{ regions | length > 0 }}"
```

feat(pipeline_templates): Support jinja expressions in template variables

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.groovy

- Fix a regression in v2 to not prematurely flag an expression as failed

fix(expressions): allow unevaluated values in V2 evaluator

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisDeadMessageHandler.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueIntegrationTest.kt
orca-queue/orca-queue.gradle
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/log/ExecutionLogListener.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueExecutionRunner.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueProcessor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/ThreadPoolQueueExecutor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ConfigurationErrorHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/PauseStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/PauseTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/TaskResultMonitor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/TrafficShapingQueue.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt
orca-web/orca-web.gradle

- No longer need to use `open` and `@Autowired constructor` on most `@Component` classes.
- Trying to quiet some of the logging from the queue integration tests.

chore(orca): Kotlin enhancements for Spring 1.5

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTaskSpec.groovy

If spotPrice is set, there is no guarantee that the instances will come up immediately (especially if the price is too low). This is to stop the UI from hanging and say that the deployment is done when the launchConfig has been created.
Related to: https://github.com/spinnaker/deck/pull/4043 and https://github.com/spinnaker/clouddriver/pull/1833

fix(clouddriver): Stop deployment from hanging when spotPrice is set

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/EnabledPipelineValidator.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTask.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/pipeline/EnabledPipelineValidatorSpec.groovy
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTag.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTagSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

This should prevent orca from triggering a front50 refresh when fetching pipelines. This call can be slow, so we want to pull the cached version from front50 (no more than a minute old). 
@ajordens PTAL

feat(web) disabling front50 refresh when orca fetches pipeline

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequest.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/generator/ExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGeneratorSpec.groovy

When concurrency options are configured on a templated pipeline via the UI, they weren't being respected. This allows a pass-through, preferring any configuration that's been setup via the template configuration, then using the UI value if undefined.

fix(pipeline_template): Respect UI-configured concurrency options

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/GraphMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/TrimConditionalsTransform.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/resources/templates/conditional-partials.yml

When using partials and conditionals stages, the evaluation of the `when` tag and the removal of stages that evaluate to `false` must be done in the end - when we are sure that the partials have been expanded and added to the stage tree.

fix(pipeline_template): Build partials, execute conditionals after and trim conditions as the last step

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/pipeline/UpdatePipelineTemplateStage.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/tasks/PlanTemplateDependentsTask.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/tasks/PlanTemplateDependentsTaskSpec.groovy

This change will now perform best-effort plans against all resolvable
dependents of a template. Pipelines that resolve their templates
dynamically will not be checked for compatibility while performing a
template save operation.
On a failure, the stage outputs look sorta like this:
```
{
"outputs": {
"notification.type": "plantemplatedependents",
"pipelineTemplate.allDependentPipelines": [
"d8a7e9ad-93f2-4273-9873-6ea4674bafa1"
],
"pipelineTemplate.dependentErrors": {
"d8a7e9ad-93f2-4273-9873-6ea4674bafa1": [
{
"location": "configuration:stages.foo",
"message": "Stage is missing type",
"severity": "FATAL"
},
{
"location": "configuration:stages.foo",
"message": "Stage configuration is unset",
"severity": "FATAL"
},
{
"location": "configuration:stages.foo",
"message": "A …
```

feat(pipeline_template): Plan all dependent pipelines before updating a template

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/pipeline/UpdatePipelineTemplateStage.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/pipeline/UpdatePipelineTemplateStageSpec.groovy

Allows updates to templates that define triggers, params, notifications
or concurrency options to cascade changes to downstream pipelines.
We'll selectively re-save pipelines only if:
1. The template actually defines an inheritable config (triggers, params, notifications, concurrency options) **AND**
2. A pipeline explicitly defines that it wants to inherit any of these configs.
@danielpeach @ajordens @emjburns PTAL

feat(pipeline_template): Re-save dependent pipelines on template save

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/MonitorPropertiesTask.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy

Need the ability to declare one-off overrides of property stages when running a pipeline, rather than persisting those changes to the pipeline config.
I will move all of the Fast Property code into our internal repo this weekend.

feat(fastproperties): allow individual stage overrides via trigger

---

gradle.properties

The spring boot upgrade is forcing 2.9.0, which we don't want.

fix(gradle): Pin jedis version

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/MonitorPropertiesTask.groovy

context is just used to get the property list, which is populated by the previous task - not the override

fix(fastproperty): do not override context on monitor stage

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt

Previously overriding the stage timeout did not take into account the cumulative time the task were running/had run. This changes the stage timeout behavior so that when a user overrides the timeout, the stage times out after that value.
This change respects pausing the stage but NOT tasks getting throttled. If we want to take throttling time into account, we need to revisit the throttling strategy (as it's not easy to correctly calculate the stage throttle duration). Right now, we are assuming that users will enter pipeline timeout overrides have enough margin for throttling.
@ajordens @robfletcher @robzienert PTAL

fix(timeout): stage timeout overrides cumulative task durations

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueue.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueTest.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/MonitorableQueue.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt

This makes de-dupe easier (no more indexes for hash values) and means we'll be able to re-prioritize existing messages efficiently (PR to follow).

Use fingerprint of message instead of id

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisConfiguration.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/telemetry/ThreadPoolMetricsPostProcessor.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/migrations/MultiRedisOrchestrationMigrationNotificationAgent.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/QueueConfiguration.kt

I've teased out the stuff applying metrics to thread pools so it just uses spring to do so. This was causing me some pain in pulling the queue library out.

refactor(metrics): more configurable metrics wiring for thread pools

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidator.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidatorSpec.groovy
orca-pipelinetemplate/src/test/resources/integration/v1schema/stageReplacement-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/stageReplacement-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/stageReplacement-template.yml

Adding tests and fixing behavior for config level stage replacement.
@robzienert PTAL

fix(pipeline_template): config level stage replacement

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CloneServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AddServerGroupEntityTagsTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ContextBasedServerGroupEntityTagGenerator.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupEntityTagGenerator.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/SpinnakerMetadataServerGroupTagGenerator.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AddServerGroupEntityTagsTaskSpec.groovy

Allows a user to include an `entityTags` collection in the payload of a deploy operation, which will add those tags once the deploy completes.
**NOTE:** this is technically a breaking change - I have modified the `ServerGroupEntityTagGenerator` method signature to return a collection of tags instead of a single tag. Since this was just released a few weeks ago, and I don't know of anyone else using entity tags (much less writing their own custom generators), I'm reluctant to label it a breaking change. Will defer to the Orca owners on that.
@ajordens PTAL

feat(servergroup): allow ad-hoc entity tags on deployments

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy

This is my favorite clouddriver endpoint and I am upset it's not already available in OortService.

chore(oortService): expose /serverGroups endpoint

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/TerminateInstanceAndDecrementServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/TerminateInstancesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DisableInstancesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/WaitForNewUpInstancesLaunchTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/WaitForNewUpInstancesLaunchTaskSpec.groovy

If a `serverGroupName` or `asgName` is available on the stage context,
there is no need to lookup each instance id individually.
Also, `getServerGroup()` is more efficient than `getServerGroupFromCluster()`
when dealing with clusters containing multiple server groups.

perf(rollingpush): Avoid unnecessarily searching for instance ids

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplateMerge.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/NamedContent.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/NamedHashMap.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplateMergeSpec.groovy
orca-pipelinetemplate/src/test/resources/integration/v1schema/parameterInheritance-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/parameterInheritance-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/parameterInheritance-template.yml

Internal teams would like the ability to have some level of control over how params, triggers and notifications are inherited. Adds two new flags, `remove` and `merge`, which are booleans and will control whether or not the config option is either removed from the final pipeline, or its values are merged into with the template values.

feat(pipeline_template): Allow granular inheritance control on params, triggers, notifications

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePreprocessor.kt
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/handler/PipelineTemplateContext.kt
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/handler/PipelineTemplateErrorHandler.kt
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidator.java
orca-pipelinetemplate/src/test/resources/integration/v1schema/example-child.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/example-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/example-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/example-root.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/example-template.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/exampleCombined-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/exampleCombined-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/exampleCombined-template.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/protect-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/protect-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/protect-template.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/unsupportedVersion-expected.json

Removing `mptRequestId` in favor of defaulting to some structured logging that is being implemented.
Adding more complicated wait stage tests.
@robzienert PTAL

tests(pipeline_templates): integrations tests and removing unique ID

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandler.kt
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidator.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandlerSpec.groovy

Depends on #1621.
Adds support for creating pipelines with the same syntax as MPT, but without the template. This was spawned by the desire to express early concepts more simply in the new docs that are being written. As an added bonus, this should help enable people to onboard pipelines that simply don't need to have a parent template.

feat(pipeline_template): Support template-less configurations

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/MonitorBakeTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractWaitForClusterWideClouddriverTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractWaitForInstanceHealthChangeTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForTerminatedInstancesTask.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/OverridableTimeoutRetryableTask.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorQueuedJenkinsJobTask.groovy
orca-kayenta/src/main/groovy/com/netflix/spinnaker/orca/kayenta/tasks/MonitorCanaryTask.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/MonitorAcaTaskTask.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/MonitorCanaryTask.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt

Added a new type of task `OverridableTimeoutRetryableTask` to indicate tasks (like waiting and monitoring) that want to have the same timeout value as the stage. This came about because the bake stage with an overridden timeout of 2.5 hours failed, because the `monitorBakeTask` has a default timeout value of 1h. 
With this change, some waiting/monitoring stages will not use their default timeout when there is an overridden timeout. I think I grabbed all the `tasks` that make sense, but PTAL @robzienert @robfletcher.
@jrsquared this (should) fix the bake issue.

fix(timeouts): some tasks inherit stage timeout override

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/ProjectController.groovy

If we define a previous Redis connection, the task repository will get `n` executions from each redis. So, if you limit by 2, 4 results will be returned. This change will enforce that the limit is accurate on the way out, after sorting by start time.
cc @anotherchrisberry @emjburns

fix(web): Enforce limit of pipelines when using previous redis conn

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy

Decreasing the timeout in run job, allowing timeout to be overridden.
@lwander @tomaslin PTAL

feat(job): decrease job timout and make overridable

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Missed this endpoint on the PR from yesterday.

fix(web): Enforce limit on previous redis for app pipelines endpoint

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/StageContext.java

I was going to add the trigger output support first, but got stuck on a question about executions that I pinged you about.

feat(stage context): Lookup all stage outputs matching a key

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy

This used to be 1 second; it was bumped to 10s back in February when we were seeing some performance issues.
Not sure what the appetite is for bumping it back up, or if we feel like there's much to be gained in task throughput.
@cfieber or @ajordens thoughts?

refactor(clouddriver): monitor clouddriver tasks every 5 seconds

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/StageContext.java

spinnaker/spinnaker#1902
spinnaker/spinnaker#1915

feat(context): Adds trigger contents to stage context

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingClouddriverService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/ByAuthenticatedUserServiceSelector.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/SelectableService.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/config/SelectableServiceSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/ExecutionContext.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/AuthenticationAware.kt

This allows you to serve all pipelines/orchestrations generated by a
particular user (or set of users) with a dedicated clouddriver
read replica.

feat(clouddriver): Support sharding read-only requests by `user`

---

orca-clouddriver/orca-clouddriver.gradle
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractWaitForClusterWideClouddriverTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ClusterSizePreconditionTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ClusterSizePreconditionTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy

Deducing the application name of a cluster is handled in two ways:
1. For newer pipeline configs: a moniker will be used to determine a cluster's application.
2. Older pipeline configs: since there isn't a moniker we need to fall back on frigga.

feat(moniker): Use a cluster's moniker if available.

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionEvaluationSummary.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy

- Include execution id in log message
- Remove some noise with debug statements

chore(expressions): Cleanup some noisy logs

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy

The changes tab that displays SCM diff between deploys was not showing if the pipeline was triggered by another pipeline. Now it does.

feat(get_commits): Display SCM changes in pipeline-triggered pipelines

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/StageData.groovy

Orca casts stage json into StageData and TargetServerGroup throughout the process of running certain stages. This PR will allow the moniker to be maintained.
The corresponding Deck change is still in progress, but Deck will add a moniker to the necessary stages. Here is an example of a deploy stage:
```
{
"clusters": [
{
"account": "aws-dev",
"application": "nginx",
"associatePublicIpAddress": true,
"availabilityZones": {
"us-west-2": ["us-west-2a"]
},
"capacity": {
"desired": 1,
"max": 1,
"min": 1
},
"cloudProvider": "aws",
"cooldown": 10,
"copySourceCustomBlockDeviceMappings": true,
"freeFormDetails": "mydetail",
"healthCheckGracePeriod": 600,
"healthCheckType": "EC2",
"instanceMonitoring": false,
"instanceType": "t2.micro",
"moniker": {
"app": "nginx",
"stack": "mystack",
"detail": …
```

feat(moniker): Allow moniker field to pass through to StageData and TargetServerGroups

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToServerGroupResizeStrategy.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToServerGroupResizeStrategySpec.groovy

This PR introduces the ability to specify a `scalePct` when scaling
based on the capacity of another server group (scale_to_server_group).
Previously all RRB capacity adjustments on the target server group were
determined at build time.

fix(rrb): RRB should determine resize percentages at runtime

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTag.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTagSpec.groovy

feat(pipeline_template): PipelineIdTag checks context for variables defining application and name

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractWaitForClusterWideClouddriverTask.groovy

This was missed when removing frigga from the cluster based tasks in a prior PR.

Remove unused frigga import

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTask.java

When application name can't be found in the context, try to use the moniker before frigga.

feat(moniker): Use moniker in DetermineHealthProvidersTask

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunner.java
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Message.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Queue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueExecutionRunner.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RescheduleExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/memory/InMemoryQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/MonitorableQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/QueueEvent.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/TrafficShapingQueue.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RescheduleExecutionHandlerTest.kt
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Using this as a start to eliminating delays in polling tasks. 
When you pause an execution, this will update the delivery time on any runtask message to be now, so that it can be reevaluated, and have the pause take effect almost immediately.
This is done by adding a reschedule method to the queue, which updates the deliver time of an existing message on the queue. If the message doesn't exist, it doesn't update the delivery time (used to make sure that RunTask messages that aren't retryable don't get erroneously run more than once).
This requires redis 3.0.0 for zadd with xx flag. Waiting on https://github.com/kstyrc/embedded-redis/pull/87 to add more current support for testing with redis.
@robfletcher PTAL as I work to get the changes in embedded-redis into this project.

feat(queue): update delivery time on runtask

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindow.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/WaitTask.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStage.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

Removed polling for wait, manual judgment, and execution window stages.
Message sent to reevaluate the stage at the time it would complete or timeout.
A PATCH to /pipelines/{executionId}/stages/{stageId} triggers a reevaluation of the running tasks for the stage in question.
Dynamic backoffs also implemented in these tasks so that if the task is not finished at the expected time polling will resume on the old backoff schedule (in case of throttling or pausing, for example).
@robfletcher PTAL - specifically at how I'm using the messages and pushing to the queue.

feat(polling): remove polling for waiting stages

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolver.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/SpinnakerMetadataServerGroupTagGenerator.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolverSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AddServerGroupEntityTagsTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/SpinnakerMetadataServerGroupTagGeneratorSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/SourceResolverSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/RetrySupport.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/RetrySupportSpec.groovy

This will ultimately facilitate an orchestrated rollback even if the
previous server group no longer exists.
It relies on the entity tags feature being enabled (dependency on
elastic search and not enabled by default in `clouddriver` / `orca`).
This PR also introduces some common retry handling (see `RetrySupport`).

feat(entitytags): Include previous server group image details

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/NoopStage.java

Allows users to submit ad-hoc tasks to provide traceability (via the Tasks view in Deck) of operations occurring outside Spinnaker that affect infrastructure components.

feat(core): implement noop stage

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindow.groovy

Incorrectly set the value for message delivery (to timeout, not the next available time to run).
Reverting this behavior for now.
@anotherchrisberry PTAL

fix(executionWindow): revert to polling

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryStage.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/MonitorCanaryStage.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/DeployedClustersUtil.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/DisableCanaryTask.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/RegisterCanaryTask.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryStageSpec.groovy

When canaries finish successfully: disable canaryAsg + waitTask(2min) + disable baselineAsg + waitTask(2min) + cache refresh, then proceed with deletion of both canary and baseline as before.
This addresses issues resulting from both canary and baseline asg's getting force deleted (which deletes asg lifecycle hooks) with simultaneous instance terminations (which also bypasses lifecycle hooks) while still serving traffic.
When canaries are terminated early and CanaryStage.cancel() invoked, asg's are also disabled prior to deletion.

fix(canary): gentle canary cleanup

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollback.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollbackSpec.groovy

If `interestingHealthProviderNames` are specified on the parent stage
context, propagate them to the clone stage.

fix(rollback): Propagate `interestingHealthProviderNames`

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandlerTest.kt

Issue: if you cancel a pipeline during a wait stage/manual judgement stage the cancel won't propagate until the stage times out.
Fix: this adds a 'rescheduleExecution' message to the queue, which will make sure all running tasks are evaluated again right away, so that they cancel themselves.
@anotherchrisberry @robfletcher PTAL

fix(cancel): cancel during wait stage

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

Adding another field to log message to try and get more information about a bug that I can't reproduce locally.
Seeing manual judgment stage sometimes fail with a timeout error when you hit 'continue' as judgment status.

chore(logging): updating timeout message w/ timeout value

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/WaitTask.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStage.groovy

Adds polling back for wait stages.
Removes use of shared task state: there is only one instance of each task in spinnaker. Nothing should be stored in the task state. They are assumed to be stateless.

fix(tasks): stop using 'shared' task state

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AbstractWaitForAppEngineServerGroupStopStartTask.groovy

Similarly to the other PRs I've been doing, first try to use the moniker then fall back on frigga.

feat(moniker): Attempt to use moniker before frigga in appengine packages

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/CleanUpTagsTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/CleanUpTagsTaskSpec.groovy

Similarly to how I've done the previous PRs for monikers, first try to use the moniker then fallback on frigga.

feat(moniker): Use moniker for Rollingpush tasks.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/CustomStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/HighlanderStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategySpec.groovy

Right now Deck will generate something like this when a user creates a new deploy stage in a pipeline:
```
{
"clusters": [
{
"account": "aws-dev",
"application": "nginx",
"associatePublicIpAddress": true,
"availabilityZones": {
"us-west-2": [
"us-west-2a"
]
},
"cloudProvider": "aws",
"freeFormDetails": "",
"instanceType": "t2.micro",
"moniker": {
"app": "nginx",
"cluster": "nginx-cluster1",
"detail": "",
"stack": "cluster1"
},
"provider": "aws",
"stack": "cluster1",
"strategy": "redblack",
"subnetType": "external (spinnaker)",
"terminationPolicies": [
"Default"
]
}
],
"name": "Deploy",
"type": "deploy"
}
```
A deploy stage (redblack/highlander/rolling/etc) will generate several sub-stages. This PR will allow the cluster's moniker to be passed to the cleanup sub-stages …

feat(moniker): Pass moniker to cleanup stages.

---

orca-flex/orca-flex.gradle
orca-flex/src/main/groovy/com/netflix/spinnaker/orca/flex/tasks/AbstractElasticIpTask.groovy

Similar to the other PRs for monikers, first try to use the moniker from the stage (which is added by deck). Then fall back on frigga.

feat(moniker): Use moniker for app name over frigga in flex

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/MaheService.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/cleanup/FastPropertyCleanupListener.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/PropertyChangeCleanupSpec.groovy

The current rollback functionality makes some potentially dangerous assumptions:
* it relies on the producer of the pipeline config to supply the relevant information about which properties are being created/updated. If the pipeline is configured incorrectly, or has out-of-date information when it runs, it could delete a property entirely on rollback, when it should have restored it to its previous state.
* property stages from a pipeline do not include the `originalProperties` field, so a rollback of the pipeline will always delete the property, which is not great if the property change was an upsert.
(Note: this is internal Netflix functionality - it is not used in open source)

fix(mahe): do not clean up properties that have been updated

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookService.groovy

The webhook stage runs from Orca, so it has direct access to Clouddriver, Front50, etc. A user can create a request to, say, Clouddriver with a X-SPINNAKER-USER header of a user with sufficient permissions and effectively bypass all security checks.
This PR strips the X-SPINNAKER-USER and X-SPINNAKER-ACCOUNT headers before the request is created.
@ttomsu

fix(security): Prevent webhook users from spoofing authed user

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy

moniker objects are incorrect on canary deploy stages, this removes those objects for now pending a fix of the source problem

fix(moniker): hotfix canary deploy stages

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/cleanup/FastPropertyCleanupListener.groovy

(Netflix internal code)
Got a little excited about some refactoring I'm doing, forgot about backwards compatibility.

fix(mahe): check property structure on cleanup

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandlerTest.kt

Tested locally by ensuring cancelling pipeline A triggered pipeline B with an on cancel trigger.

fix(triggers): ensure canceling pipeline sends ExecutionComplete event

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStage.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/Front50SchemeLoader.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/pipeline/UpdatePipelineTemplateStage.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/loader/Front50SchemeLoaderSpec.groovy

As we're trying to get our nightlies to pass we found that front50 has become required for orca again, breaking some halyard flows.

fix(front50): Keep front50 optional

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/Bake.groovy
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTaskSpec.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/FindImageFromTagsTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/ImageFinder.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageFinder.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/gce/GoogleImageFinder.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/FindImageFromTagTaskSpec.groovy

The idea here is to place artifacts from rosco in the global context along with artifacts from `findImageFromTag` and `findImageFromCluster` so that it's in place when we want to start working on the feature toggle to enable deployment of artifacts. I was a bit unsure on the naming and placement of this object `Artifacts` so feel free to suggest alternative approaches.

feat(orca) Place produced artifacts in global context

---

build.gradle
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/FindImageFromTagsTask.java

Should fix the Artifact.metadata serialization issue.

chore(dependencies): Bump spinnaker-dependencies to 0.120.1

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/TerminateInstanceAndDecrementServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/TerminateInstancesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractBulkServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/BulkDestroyServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/BulkDisableServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/DestroyServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/DisableServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ResizeServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/ClusterMatcher.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/MonikerHelper.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DisableInstancesTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractServerGroupTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/ClusterMatcherSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy

This PR will remove the use of frigga from `TrafficGuard`.
First, `Map<String, Object> operation` is generated from a `Stage` object in `TargetServerGroup.toClouddriverOperationPayload()` and `AbstractServerGroupTask.convert()`. 
`Stage` object may or may not have a moniker. If it is an older pipeline config, then it will not have a moniker.
`operation` is used by `validateClusterStatus()` in 
- `TerminateInstanceAndDecrementServerGroupTask.groovy`
- `TerminateInstancesTask.groovy`
- `BulkDestroyServerGroupTask.java`
- `BulkDisableServerGroupTask.java`
- `DestroyServerGroupTask.groovy`
- `DisableServerGroupTask.groovy`
- `ResizeServerGroupTask.groovy`
When calling `TrafficGuard.verifyTrafficRemoval()` a moniker is generated (via MonikerHelper and frigga) if one can't be found in the …

feat(moniker): Use moniker in TrafficGuard.

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/RegisterCanaryTask.groovy

In at least one case of total canary stage failure, the deployedClusterPairs
context variable doesn't get set at all, resulting in a null value -- this
avoids the "Cannot invoke method getAt() on null object" error message
that results from trying to dereference the zero'th element in this case.

fix(orca/canary): Don't presume array present

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/OrchestrationLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Pipeline.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

Allows us to repeatedly send orchestrations with the same correlation id and only running a single one. Pre-req for keel.

feat(core): Add correlation ids to orchestrations

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTag.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTagSpec.groovy

fix(pipeline_template): Deal with whitespace in jinja module kv pairs

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStage.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStageSpec.groovy

When an ACA task stage is restarted it attempts to cancel the previous canary. However, if enough time has passed the canary will have ended already. This case wasn't being handled. Also `canaryDeployments` got removed from context which makes sense for "full" canaries as they'll do a fresh deploy but not for ACA tasks.

Fixes restarting ACA task stages

---

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CreateServerGroupTaskSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/AlertOnAccessMap.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/StageContext.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/v2/ContextParameterProcessorSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt
orca-test/src/main/groovy/com/netflix/spinnaker/orca/test/model/ExecutionBuilder.groovy

Restores commit f49653055f614cb38110e4e7924cedf923f0fdb5 and fixes the issue in parsing parent Pipeline from trigger that meant the `execution` back-ref was not set on stages.

Use StageContext consistently without breaking strategies

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStageSpec.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTaskSpec.groovy

This PR also propagates some details about the particular stage that
failed such that `deck` can render an appropriate link.

fix(front50): Avoid canceling an already canceled child pipeline

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTask.groovy

If deployment strategy == custom and the resulting strategy dropdown remains blank (as may happen if custom strategy was selected by accident) the resulting `Unable to located referenced pipeline null` error message doesn't make sense to users unfamiliar with custom strategy configuration.

fix(log): clarify null custom strategy error

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy

The instance termination task does not normally have a `serverGroupName`
explicitly specified.
Without such, the moniker used to check traffic guards is invalid.

fix(trafficguards): Fix Moniker usage in instance termination

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplateService.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequest.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandler.kt
orca-pipelinetemplate/src/test/resources/integration/v1schema/example-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/inheritance-expected.json
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/PipelineTemplateController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

When you try to edit a pipeline based on a template with dynamic source, you're greeted with the 
following message in Deck:
This commit makes Orca try to fetch ~the last~ any previously ran pipeline execution and use the context of that to render the source field, thus getting rid of the above error. If you press the "Configure Template" button, you're able to edit the variables. This commit also fix so that the graph renders correctly, going from this:
To this:

feat(pipeline_template): Render configuration for templated pipelines with dynamic source

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

Was causing 500 errors because the method couldn't be found in other places in the Controller. Thanks, Groovy.
@spinnaker/netflix-reviewers @jervi FYI

fix(web): Reverting needless method sig refactor from #1718

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

fix(*): fix startup failure if pipeline templates are not enabled

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListenerSpec.groovy

The class is always `Execution` now, so we need to use the `type`

fix(notifications): send correct notification type on pipeline events

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/MortService.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/MortServiceSpec.groovy

To support Keel's security group management, updates Orca to allow passing the VPC name, rather than ID.

feat(clouddriver/aws): Allow finding SG vpc IDs by name

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/tasks/PageApplicationOwnerTask.groovy

Related echo PR: https://github.com/spinnaker/echo/pull/195

feat(pagerduty): Support multiple applications and keys directly

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollbackSpec.groovy

`ApplySourceServerGroupCapacityTask` is expecting to have the `cloudProvider` field. If it doesn't, then it defaults to AWS. This is causing k8s rollbacks to fail.
This PR combined with https://github.com/spinnaker/orca/pull/1805 will fix k8s rollbacks (and I suspect some other providers as well.)

fix(kubernetes/rollback): Pass cloudProvider to downstream tasks.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy

`ApplySourceServerGroupCapacityTask` overrides `convert()`. `convertMoniker()` also needs to be overridden. The moniker used when verifying the cluster should be the same as the server group in the operation.
Everything seems to be working just fine for AWS, but the k8s rollback stage is currently failing. There is a bigger problem that @lwander is working as to why k8s is using this stage that is in the aws provider.
@ajordens - Would you mind taking a look at this for me? This task seems to work a lot differently than the others that extend `AbstractServerGroupTask` and based on the blame you have the most experience with it.

fix(moniker): Use the correct moniker when applying source server group

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollbackSpec.groovy

cherry-pick of https://github.com/spinnaker/orca/pull/1810 for 1.5.1

fix(kubernetes/rollback) Pass cloudProvider to tasks so it doesn't default to aws (#1810)

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy

cherry-pick of #1805 for 1.5.1

fix(moniker): Use the correct moniker when applying source server group (#1805)

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java

Occasionally seeing TrafficGuard prevent disabling the old servergroup during redblack and highlander deploys, when the new servergroup has UP instances. Adding additional logging to help troubleshoot.

fix(trafficguards): debug logging when no enabled asgs found

---

gradle.properties
gradle/kotlin.gradle
gradle/spek.gradle
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/cleanup/FastPropertyCleanupListener.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/MonitorPropertiesTask.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/MonitorPropertiesTaskSpec.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/PropertyChangeCleanupSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

The cleanup listener for fast properties would previously search for properties in global context (transitively because it checks each fast property stage) and could end up rolling back those it shouldn't. I've prevented any of the keys associated with fast properties from getting exported from stage outputs to global context. Also removed the duplication of the same data in context and outputs. This removes one of the main hits currently occurring on global context.

Keep fast property stuff out of global context

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy

In my use case, I find it using too much time on WaitForClusterDisableTask. So this PR will help us to configure minimum time cost on this task by orca-local.yml. 
----
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been …

Make WaitForClusterDisableTask configurable in yml

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy

The missing brace was causing:
```
```org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'queueProcessor' defined in URL [jar:file:/opt/orca/lib/orca-queue-4.7.0-SNAPSHOT.jar!/com/netflix/spinnaker/orca/q/QueueProcessor.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'runTaskHandler' defined in URL [jar:file:/opt/orca/lib/orca-queue-4.7.0-SNAPSHOT.jar!/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name …

fix(core): Missing closing brace

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/StrategyIdTag.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/StrategyIdSpec.groovy

Modeled off PipelineIdTag.  It's the least obtrusive, though I could refactor both this and PipelineIdTag if we want to - let me know.
@robzienert

feat(pipeline_template) Add strategyId tag to render ids by application and strategy name

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

Related to https://github.com/spinnaker/echo/pull/207
We noticed that pipelines that had triggers (like CRON or Jenkins triggers) were failing if they didn't also have parameters because of our change. This should fix that in a better way given that triggers are expected to have several null values.

fix(pipeline_parsing) Protect against NPEs with trigger params.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DeploymentDetailsAware.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreatorSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CreateServerGroupTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/CreateDeployTaskSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/ExecutionSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/StageContextSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/StageSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt

This ensures deployment details are retrieved from upstream stages, trigger or parent pipeline without using global context

Deployment details no longer accessed from global context

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy
orca-pipelinetemplate/src/test/resources/integration/v1schema/dependsOn-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/dependsOn-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/dependsOn-template.yml

I noticed that when I saved a pipeline configuration with `roer` the stage `dependsOn` data from the config was not being used to configure the pipeline.  Turns out `roer` will always send an empty `inject` object, which in-turn throws an `IllegalTemplateConfigurationException` from the `ConfigStageInjectionTransform` mutator.  This exception is thrown but the process of saving the pipeline continues - just without data from the pipeline config being applied to the pipeline.
This fix essentially continues with mutator processing if an empty `inject` object is present. 
I also added a dependsOn integration test to catch this issue in the future.
@robzienert

fix(pipeline_template) Do not throw IllegalTemplateConfigurationException if empty inject object is passed with pipeline stage configuration

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/RollbackClusterStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

This allows for interesting scenarios where a stage could have a `Task`
responsible for building the context that is subsequently used to build
a dynamic set of synthetic stages.
Currently this logic must reside entirely in `aroundStages()` and you
lose the ability to arbitrarily retry with backoff's, etc. that normal
`Task` execution provides.

feat(core): AFTER_STAGE stages can now be planned post task completion

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy

This means expressions that reference "context" will work.
I'd like to go further and make the whole trigger JSON parseable but this is a start.

fix(expressions): ensure parentExecution is an execution not a map

---

orca-queue/orca-queue.gradle
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerTest.kt

Looks like we were never canceling pipelines that were canceled while queued. This will not start a pipeline if it is in a canceled state.

fix(queue): really cancel queued pipelines that were canceled

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPoller.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/PinnedServerGroupTagGenerator.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPollerSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/PinnedServerGroupTagGeneratorSpec.groovy

Spinnaker currently pins the minimum capacity on newly deployed server
groups (`min` = `desired`).
When the deploy completes, this capacity is unpinned and the `min` is
set to the `min` of the source server group.
_If_ the deploy does not complete successfully, the newly created server
group is never unpinned.
This PR introduces a new entity tag `spinnaker:pinned_capacity` that
records both the pinned and unpinned capacities. A background agent
periodically looks for server groups that remain pinned despite the
originating execution having completed.
There is no impact if entity tags are not enabled.

feat(amazon): Ensure that server groups are unpinned when a deploy fails

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/WaitForUpsertedImageTagsTask.java

We have lots of amis indexed in our AWS account and sometimes it takes more than 10 minutes to fetch the status of the tag operation.
With this PR we want to mitigate the issue while we find a way to clean-up old amis.

feat(timeout) Add configurable timeout to wait for upserted image tag task

---

orca-kayenta/src/main/groovy/com/netflix/spinnaker/orca/kayenta/KayentaService.groovy
orca-kayenta/src/main/groovy/com/netflix/spinnaker/orca/kayenta/pipeline/KayentaCanaryStage.groovy
orca-kayenta/src/main/groovy/com/netflix/spinnaker/orca/kayenta/pipeline/RunCanaryPipelineStage.groovy
orca-kayenta/src/main/groovy/com/netflix/spinnaker/orca/kayenta/tasks/MonitorKayentaCanaryTask.groovy
orca-kayenta/src/main/groovy/com/netflix/spinnaker/orca/kayenta/tasks/RunKayentaCanaryTask.groovy

Also add support for scope name and improve handling of exceptions and cancelations.

fix(canary-v2): Use new /canary/{executionId} entry point.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractWaitForClusterWideClouddriverTask.groovy

Adds a configuration property to allow for longer timeouts for WaitForCluster tasks.   The default is 30 minutes.
Example of having a timeout of 60 minutes:
```
tasks:
waitForClusterTimeout: 3600000
```

feat(tasks) - adds configuration property to waitForCluster timeouts

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/config/PreconfiguredWebhookProperties.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStage.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStageSpec.groovy

adds support for configuring predefined parameters as part of a
preconfigured webhook stage. this will allows admins to add options for
users to fill out. the values set by users can then be used in the other
options via SPEL. this is a really basic implementation and only
supports string types options.
spinnaker/spinnaker#2224
@robzienert @robfletcher @ajordens could some of you guys take a look at this. it's my first orca PR and _seems_ like it was easier than it should have been. i'm open to having a deeper conversation around it if need be. thanks!

feat(webhooks): support preconfig params

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandlerTest.kt

Expressions were not being evaluated in dynamic stages/tasks added (e.g. expressions in synthesized regional deploys in a deploy stage).

fix(spel): Evaluate expressions in synthesized stages.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractWaitForClusterWideClouddriverTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/WaitForUpsertedImageTagsTask.java

We have a few situatations where task timeouts are overridable:
- tasks.waitForClusterTimeout (value is expected to be milliseconds)
- tasks.waitForUpsertedImageTagsTimeout (value is expected to be seconds)
- tasks.disableClusterMinTimeMillis (value is expected to be milliseconds)
The first two were added in the last 1-2 weeks, the latter was merged in
late November.
My preference would be to align around the suffix for these sort of
properties, even if it might mean a breaking change right now.

chore(core): Consistency around `Millis` suffix on `task.*` values

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/config/EchoConfiguration.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListenerSpec.groovy

SPEL expressions in notifications weren't being evaluated prior to stage execution.

fix(spel): Evaluate stage notifications before sending.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy

If there are no connections to drain, don't wait 90 seconds before proceeding.
This speeds up shrink cluster operations that are essentially no-ops.

perf(clouddriver): skip cooldown on disable if no server groups disabled

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStage.java
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/JenkinsStage.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/ScriptStage.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStage.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStageSpec.groovy

Resetting start/end time, status, and tasks is handled from the place `prepareStageForRestart` is called so there's no need for implementations of that method do such things.

chore(restarts): remove redundant logic from stage restart methods

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-dry-run/orca-dry-run.gradle
orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/DryRunStage.kt
orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/DryRunTask.kt
orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/stub/BakeOutputStub.kt
orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/stub/FindImageFromTagsOutputStub.kt
orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/stub/FindImageOutputStub.kt
orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/stub/OutputStub.kt
orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/stub/random.kt
orca-dry-run/src/test/kotlin/com/netflix/spinnaker/orca/dryrun/DryRunTaskTest.kt
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy

This allows pipelines with a `dry-run` trigger type to generate dummy data from certain stage types. The plan is to add a "dry run" checkbox to the manual trigger dialog to allow users to test out pipelines verifying expressions, optional stages, functionality based on parameters, etc.

More useful dry run

---

orca-core/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java

Groovy truth treats "" as falsy but I'd just used a null check when converting the config class to Java.

fix(redis): Fix bug starting Redis pool with no path on the connection

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTagger.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSpec.groovy

In a multi-region bake, we sometimes see a slight difference in the times the bakes start, which leads to different image names (usually off by a single digit on the timestamp).
The current implementation of the image tagger always gets all the regions from all the different AMIs, but does not consider which region each image comes from. This fixes that up.
I'm not sure if there are other repercussions or assumptions based on the `extraOutputs`, but this change should at least get us past this bug.

fix(amazon): derive image regions when tagging from Clouddriver data

---

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelDeployStageSpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/JenkinsTrigger.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/ManualTrigger.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/TravisTrigger.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/BuildDetailExtractor.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/PipelineSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/BuildDetailExtractorSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

- buildInfo and properties are looked up from the Jenkins master not sent with the trigger
- fixed tests broken in IntelliJ when non-null annotation checks compiled in
- any `@Nonnull` list or map accepts null on the constructor and defaults the value

fix(triggers): derived properties of Jenkins triggers

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

When a pipeline fails validation, due to its being disabled, having
an invalid template, or being missing an artifact, log a failed execution
to the execution history instead of only generating an error in the
logs.

fix(pipelines): Improve pipeline error reporting

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

In parsing the `Trigger` objects, we wind up unable to evaluate SPEL (which only works on maps lists & strings). To get around this, I defer parsing the trigger until after SPEL has been evaluated.
This should keep the behavior of https://github.com/spinnaker/orca/pull/1937 the same, since it requires the trigger to be parsed before the error message is reported (please confirm @ezimanyi).

fix(triggers): evaluate incoming triggers (& artifacts)

---

orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

Update the tests to enforce that failure to parse a pipeline
leads to an entry being added to the execution history.

test(pipelines): Improve failed pipeline tests

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStage.groovy

Manual Judgements were not respecting overridable timeouts in the UI.   implementing `OverridableTimeoutRetryableTask` allows the override condition to be met.
For reference: 
https://github.com/spinnaker/orca/blob/993d24d5a758801d015fec3875ac0078670838db/orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt#L180

fix(manualJudgment) - respect manual timeout override in the manual judgement stage

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTaskSpec.groovy

The webhook stage puts a lot of arbitrary information into buildInfo, that broke assumptions done other places in Orca (#1892).
This commit deprecates the use of buildInfo, and adds information about the deprecation and how to migrate, to the stage output. The webhook output is now added beneath the key `webhook`.
The deprecated stuff should be removed after some time.
Note: Most error messages have been fully migrated, meaning I did not leave a copy at the root of `context`. I did the assumption that only successful results are being used in later stages.
Discussion of this issue: #1947.

fix(webhook): Deprecate use of buildInfo

---

orca-web/etc/init/orca.conf

Changing to appending to the log file so logs will correctly rotate.  This prevents large amounts of null data at the start of a rotated log file.

fix(orca/log): Append to log instead of overwrite

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

This fixes a regression introduced in #1937. The preprocessors are not mutating `pipeline` inline, so we have to return the new, rendered pipeline back to caller.

fix(pipelines): Fix templated pipelines not being triggered

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/StageSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

```
def pipeline = pipeline {
stage {
id = "1"
stage {
id = "2"
stage {
id = "3"
}
}
}
}
```
This PR allows a synthetic stage (#2 in ^^ example) to override the
`stageTimeoutMs` that will be used by a child synthetic stage (#3).
The current behavior has a synthetic stage only looking at it's root
top-level stage for `stageTimeoutMs`.
Will be used by spinnaker/orca#1944

feat(core): Allow a synthetic stage to override `stageTimeoutMs`

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesContainerFinder.groovy

Due to the changes in moving orca triggers to classes vs maps it caused the exception below when deploying to Kubernetes and using a DockerTrigger or ManualTrigger when choosing a container to deploy
```
No such property: account for class: com.netflix.spinnaker.orca.pipeline.model.DockerTrigger\n\tat org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)\n\tat org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetPropertySafe(AbstractCallSite.java:410)\n\tat com.netflix.spinnaker.orca.clouddriver.tasks.providers.kubernetes.Kuber …
```

fix(provider/kubernetes) - fixes exception when deploying with manual or container based trigger

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/JenkinsTrigger.java

Some jenkins triggers seem to provide this, causing the pipeline to crash.

fix(jenkins): full display name in trigger

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/RollbackClusterStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollback.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/RollbackClusterStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollbackSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTaskSpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java
orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/Stages.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/Executions.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

This PR injects a `RollbackCluster` stage if a particular cluster
deployment has automatic rollback enabled.
Automatic rollback can be enabled by adding the following to a deploy
stage:
```
"rollback": {
"onFailure": true
}
```

feat(rollback): Support for automatic rollback when a deployment fails

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java

fix(core): use correct object mapper for context processing

fix(core): use correct object mapper for context processing (#1984)

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt

Currently any non-started synthetic stage is removed from the graph
even if there are no `onFailure` stages to replace them.

fix(queue): Only remove synthetic stages if there are replacements

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/ReturnTypeRestrictor.java

Make SpEL support the new strongly typed `Trigger`s and some other models. Gets rid of errors like this: `Failed to evaluate [expression] found getter for requested trigger but rejected due to return type interface com.netflix.spinnaker.orca.pipeline.model.Trigger`

fix(spel): Support new return types in SpEL expressions

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/AwsDeployStagePreProcessor.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/DeployStagePreProcessor.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ResizeServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ResizeStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ResizeStrategySupport.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleExactResizeStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleRelativeResizeStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToClusterResizeStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToServerGroupResizeStrategy.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleExactResizeStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleRelativeResizeStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToClusterResizeStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToServerGroupResizeStrategySpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/WaitTask.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

This PR attempts to avoid unnecessary and problematic autoscale events
that occur as the total # of instances increase when a deploy is
happening.
As instance count increases, there is natural downward pressure
on the cluster resulting in the source server group being scaled down.
It is particularly bad for rolling red/black where the old server group
is not immediately disabled.
The expectation is that the source group will be returned to its
original unpinned capacity when the deploy completes (or fails!).

feat(aws): Support for pinning min=desired capacity on source server group

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreator.groovy

Restores a block of code from https://github.com/spinnaker/orca/pull/1254 that was removed during a refactor.

fix(provider/amazon): restore finding imageId from trigger properties

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTaskSpec.groovy

- keeping track if we have tried master
- added fx to look up task from master directly (KatoRestService)

fix(clouddriver): Getting task from clouddriver master when timed out attempts to replicas

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/artifacts/BindProducedArtifactsTask.java

In order to use the artifact binding functionality in the image bakery,
we'll need this functionality to be available in orca-core so it can
be called from orca-bakery.

refactor(artifacts): Move artifact binding to orca-core

---

README.md
build.gradle

Starting orca with ./gradlew -DDEBUG=true now causes the JVM to
listen on port 8183 for a remote debugger.

chore(build): add debug flag to orca build

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/titus/TitusJobRunner.groovy

titus v3 api no longer sets default security groups. Replicating functionality for create server groups in run jobs

fix(titus): set default security groups for run job stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java

no change in behavior, the types are compared w/o case.

chore(provider/kubernetes): de-capitalize cache refresh type

---

build.gradle
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/dynomite/DynomiteExecutionRepository.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/AbstractRedisExecutionRepository.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy

- also fixes an issue where retrieveOrchestrationForCorrelationId may select the incorrect redis instance during a migration

fix(persistence): enable dynomite repository tests

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/Strategy.java
orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/Stages.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

This PR will correctly unpin the source server group when an RRB
deployment fails and is automatically rolled back.
The previous server group is guaranteed to exist so the automatic
rollback _only_ needs to disable the new server group.

fix(rollback): Better support for automatic rollbacks on RRB deploys

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy

Right now, if a stage is skipped, we still send a message to echo indicating it succeeded. This is really confusing if there are notifications configured.
I'm proposing we send a different, more accurate status, so we do not lose the ability to track the events, but also do not send inaccurate notifications.

fix(echo): send different phase in notification when stage is skipped

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy

Better than the NPE we throw 20 lines further down in a log statement.
We talked about making more artisanal error classes, but I don't know where we landed on that. Happy to make this special if someone has a good name for it.
Closes https://github.com/spinnaker/spinnaker/issues/2291

fix(trigger): better error message when triggering a disabled pipeline

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CompletedBakeTaskSpec.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/gce/GoogleServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/gce/GoogleServerGroupCreatorSpec.groovy

Update the Bake stage to emit the baked image as an artifact, and the Deploy stage to optionally deploy an specified artifact instead of searching upstream for the most recent Bake or Find Artifact stage.

feat(artifacts): Use artifacts for Bake->Deploy GCE stages

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/FeaturesService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CloneServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollback.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollbackSupport.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/RollingPushStage.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollbackSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollbackSupportSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTaskSpec.groovy

If entity tags are not enabled, the expectation is that the rollback
will fall back to looking at previous server groups and picking the
newest.

fix(rollback): Guard against entity tags not being enabled

---

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/MonitorKayentaCanaryTask.kt

Without this fix, `durationString` is serialized as a long in milliseconds. This causes the stage execution details to render like this:
With the fix, it's back to:

fix(canary-v2): Fix issue with serialization of duration string.

---

orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandler.kt

- ensures stages and tasks with long backoff times are promptly cancelled
after CancelExecution is called.

fix(queue): requeue running tasks from CancelStage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/NetflixAWSConfiguration.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/dynomite/DynomiteExecutionRepository.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/AbstractRedisExecutionRepository.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt
orca-test/src/main/java/com/netflix/spinnaker/orca/test/redis/EmbeddedRedisConfiguration.java

Depends on https://github.com/spinnaker/kork/pull/131 before anything will work.
Nothing particularly interesting going on here, but this is what it takes to update any of our services to kork Jedis / Dynomite.
I ran locally with the following config(-ish). `redis.connection` was wiring up the queue, and the execution repository writing into dynomite, reading previous executions from local.
```yaml
redis:
connection: redis://localhost:6379
clients:
executionRepository:
primary: 
driver: dynomite
config:
applicationName: orca
clusterName: dyno_spinnaker_staging
forceUseStaticHosts: true
connectionPool:
maxConnsPerHost: 5
hosts:
- hostname: ip-1.1.1.1.us-west-2.compute.internal
ipAddress: 1.1.1.1
previous:
driver: redis
config:
connection: redis://localhost:6379
```

chore(*): Wiring up kork redis/dynomite client factories

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/appengine/StartAppEngineServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/appengine/StopAppEngineServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ModifyAwsScalingProcessStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DisableServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/EnableServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/ResizeServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupLinearStageSupport.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupLinearStageSupportSpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

Spotted by @duftler.
This was caused by the new before / after stage mechanism defaulting to `aroundStages` twice. After the action has taken place it may not be able to resolve target server groups, though.

Fix failure when re-entering aroundStages method of TargetServerGroupLinearStageSupport

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/graph/StageGraphBuilder.java
orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt

This PR handles generating a `refId` for a synthetic stage that has
pre-existing siblings.
In such cases, the `refId` should be unique and offset by the number of
siblings.
All `onFailureStages()` should be run linearly otherwise you run the
risk of a parent stage being notified prematurely.

fix(rollback): Ensure that rollback stages are injected correctly

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutator.java

@rz FYI also. We had issues where more than one trigger of the same type wasn't resolved properly -- e.g. two crons wound up with incorrect `cronExpressions` after a `roer pipeline-template publish <...>`.

fix(pipeline-templates): Fix trigger merging when hydrating templates.

---

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/KayentaService.kt
orca-kayenta/src/test/kotlin/com/netflix/spinnaker/orca/kayenta/KayentaServiceTest.kt

This moves the canaryExecutionRequest, application, and config  to be top-level objects, to match a soon to be fixed Kayenta version.
BREAKING CHANGE:  This will require an upgrade of Kayenta after a pull request is merged there.

feat(orca-kayenta): move canaryExecutionRequest and application to top-level

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/stages.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

This is a bridge to the 6.19.x branch of Orca where after stages are _always_ planned just in time. During deployment this can be an issue if a 6.19.x instance starts a stage (and does not plan after stages) and a 6.18.x instance tries to complete the stage (finding no before stages or tasks and no planned after stages).

fix(after stages): Allow for just-in-time planning of after stages

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt

Allows users to define a specific execution-level and/or stage-level start time TTL. This will allow teams to guarantee an upper bounds SLA for pipeline / task executions. Especially handy for the likes of Chaos Monkey.

feat(execution): Adding start time TTLs to executions and stages

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/pipeline/WebhookStage.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy

as mentioned in spinnaker/spinnaker#2330, webhook stages now support
producing artifacts. this expects that there is a top-level `artifacts`
key in the response. these artifacts are then bound and available to
downstream stages.

feat(webhooks): support webhook artifacts

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/DetermineTerminationCandidatesTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/DetermineTerminationCandidatesTaskSpec.groovy

If the order of instances is specified in rolling push (using `"order" == "given"`), then let's terminate instances in that order.
Let's also test to make sure that the order we terminate in is the order we expect.

feat(rolling push): respect specified order of terminations

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandlerTest.kt

It turns out that we'd start the first waiting execution then cancel it as well. This is bad. Also the test is asserting that _doesn't_ happen, so is evidently not right. I've verified this fixes the behavior. Going to work on the test so it will catch any regression properly.

fix(core): don't cancel waiting pipelines as well as starting them

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/TriggerSpec.groovy

Handle the case where an execution JSON may not have a trigger at all.
This makes older pipelines made by an older Orca in Kayenta still retrievable.

bug(orca-core): handle missing trigger json

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerTest.kt

Reverting spinnaker/orca#2112 for now.
The `RunTaskHandler` is manipulating the task status and the
expectation of spinnaker/orca#2112 was that it was working on the raw
task status.

revert(queue): `FAILED_CONTINUE` tasks should halt stage execution

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/messages.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt

This PR improves upon spinnaker/orca#2112 by only executing subsequent
tasks when a task _explicitly_ completes with the `FAILED_CONTINUE`
status.
An execution being flagged `"continuePipeline": true` is not enough to
cause subsequent tasks to execute if an unsuccessful status is
merely overridden to `FAILED_CONTINUE`.

fix(queue): `FAILED_CONTINUE` tasks should not halt stage execution

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

Similar to `TERMINAL`, we should pass the original task completion
status in the `CompleteTask` message whenever it has been overridden.

fix(queue): Pass original task status along for `CANCELED`

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionEvaluator.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy

- broke out the main transform method into type specific ones
- small cosmetic changes: corrected inconsitency var names including allowUnknownKeys
- added a way to stringify certain types before returning

fix(expressions): Better handling for composite spel

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt

Changing up how `startTimeTtl` works a little bit, as well as fixing up some bugs.
* Property is now `startTimeExpiry`, which is more self-descriptive.
* I had a hell of a time getting `Instant` to serialize to a `long`, despite configuring the object mapper to do so, so I switched away to a `Long` for the internal type.
* Changed the `StartStageHandler` behavior to use `SkipStage` instead of `CancelStage`, since this seems more in line with current queue behavior
* I wasn't correctly slotting the request properties into the models, derp.

refactor(core): Alter startTimeTtl -> expiry, fix serialization

---

orca-core/src/main/java/com/netflix/spinnaker/orca/TaskResult.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/SavePipelineStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorFront50Task.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java

This offers a very small bandaid around situations wherein a Front50
backed by S3 does not always provide read-after-write consistency.

fix(front50): Wait for pipeline to be updated before completing stage

---

orca-core/src/main/java/com/netflix/spinnaker/orca/annotations/Sync.java
orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/DelegatingApplicationEventMulticaster.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/InspectableApplicationListenerMethodAdapter.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/InspectableEventListenerFactory.kt
orca-core/src/test/groovy/com/netflix/spinnaker/orca/listeners/DelegatingApplicationEventMulticasterSpec.groovy
orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/OrcaQueueConfiguration.kt

Some plumbing work in preparation for implementing the QoS management system, which will be an `extensionpoint` to Orca's core functionality. Orca is currently written so that all Spring events are asynchronous, but we'll be adding event extensions that will need to be synchronous. Spring's normal behavior is to opt into async listeners, with sync being the default; in our case we need the inverse which requires switching up some Spring plumbing. 
Supports both class-based event listeners, as well as method-level event listeners. You can opt a listener of either kind into synchronous execution via the new `@Sync` annotation.
I've also addressed a series of TODOs that move the event task executor pool stuff into `orca-core` from `orca-queue`, since I was already touching this system.
At …

feat(core): Support for both sync/async application event listeners

---

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleRelativeResizeStrategySpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java

Came across this while fixing something earlier today. I just re-generated the methods with IntelliJ.

chore(core): equals/hashCode don't need to reference super

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

With this, we should be able to see a breakdown of time taken for different task types (looking at you, `ServerGroupCacheForceRefreshTask`)

config(metrics): tag task duration metric with task type

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Without this, stages don't get collapsed on templated pipelines, and it is pretty difficult to work with from the UI.

fix(pipelines): retain group field in stage context if present

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/InstantiationTypeRestrictor.java

Java8 added java.time.LocalDate which allows for more advanced date manipulations. Very useful in pipeline parameters to calculate dates.
Works beautifully, for eg, to calculate the date 5 days from now: 
${ T(java.time.LocalDate).now().plusDays(5).toString() }

fix(spel): Whitelist java.time.LocalDate to allow for date manipulation

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTaskSpec.groovy

Per Slack discussion with @ezimanyi https://spinnakerteam.slack.com/archives/C091CCWRJ/p1523425204000140; my intended use case is to access artifacts emitted by the child pipeline, but there may be other utility as well.
This appears to be the easiest way to do this, but it relies on the deprecated `getContext()` on `Execution`. In order to avoid that, I could recreate the outputs by walking the stages in the child pipeline, or just create a non-deprecated `getOutputs()` on `Execution`. If someone can comment on _why_ the method is deprecated, that might help. It was deprecated in a89c57b7d35ac8370f1955b465750ef0748c7f7b by @robfletcher.
I did _not_ add support for declaring Expected Artifacts and emitting only expected artifacts in the pipeline stage, but I can do that as well. Perhaps …

feat(artifacts) Expose child pipeline outputs as outputs of a pipeline stage

---

gradle.properties
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueShovelConfiguration.kt
orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueIntegrationTest.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandlerTest.kt

Upgrading version of keiko.
Actually using our dead letter handler so that tasks/stages/executions are successfully canceled on error.

fix(q): actually using dead letter handler

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy

- including error msg if composite spel is not evaluated or is partially evaluated

fix(expressions): Include eval summary for unevaluated composite expressions

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

When a pipeline is initiated via manual execution and using the context of a previous build, the field `trigger.artifacts` is not populated. 
The artifacts information is in `trigger.buildinfo`, but when the execution happens via the build trigger, Echo puts the artifacts into `pipeline.receivedArtifacts` which will then end in `trigger.artifacts`. Such doesn't happen when it's a manual execution.
~~This PR will make the `ArtifactResolver` look into `trigger.buildinfo` to check if there are artifacts to be processed.~~

fix(core) Populate trigger.artifacts when it's a manual execution with the context of a previous build trigger

---

orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionStatus.java
orca-core/src/main/java/com/netflix/spinnaker/orca/events/BeforeInitialExecutionPersist.java
orca-core/src/main/java/com/netflix/spinnaker/orca/events/ExecutionEvent.java
orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/ExecutionListener.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionLauncherSpec.groovy
orca-qos/orca-qos.gradle
orca-qos/src/main/kotlin/com/netflix/spinnaker/config/QosConfiguration.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/BufferPolicy.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/BufferState.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/BufferStateSupplier.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionBufferActuator.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionPromoter.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/PromotionPolicy.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/bufferstate/ActiveExecutionsBufferStateSupplier.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/strategy/naive/NaiveBufferPolicy.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/strategy/naive/NaivePromotionPolicy.kt
orca-qos/src/test/kotlin/com/netflix/spinnaker/orca/qos/DefaultExecutionPromoterTest.kt
orca-qos/src/test/kotlin/com/netflix/spinnaker/orca/qos/ExecutionBufferActuatorTest.kt
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-web/orca-web.gradle
orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy
settings.gradle

We've been experiencing production pain in the form of higher bursty execution
load than what Orca's downstream services are able to take if offered in a
firehose fashion. This PR offers a framework (albeit simplistic first impl)
for enforcing QoS of executions.
The basic premise is that a new extension hook is added when executions are
initially saved into the system, they'll potentially be set with a BUFFERED
status, which will prevent StartExecutionHandler from seeing it, and thus
beginning any work.
A BufferStateSupplier is implemented (currently based off system-wide active
executions) that can flip the system from INACTIVE to ACTIVE. In the case of
this basic implementation, if a threshold of active execution is surpassed the
QoS system is set to ACTIVE.
Once ACTIVE, an …

feat(qos): Adding initial naive Quality of Service module

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/ServerGroupForceCacheRefreshStage.java

A new `ServerGroupForceCacheRefreshStage` that simply wraps the
`ServerGroupCacheForceRefreshTask.`
At some point will support renaming of tasks so I'm not too worried
about the slight inconsistency.

feat(clouddriver): Allow for external server group force cache refreshes

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/YamlRenderedValueConverter.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaIntegrationSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy

The snakeyaml processor is not thread-safe, and we are currently sharing
it across threads, leading to intermittent NPEs when concurrent uses put
it in an inconsistent state.

fix(pipeline_template): Don't share snakeyaml instance across threads

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy

With this change, bake stages now support a field packageArtifactIds
that contains an array artifacts representing packages to bake into
the produced image.  This field will not be visible in the UI until
the corresponding change is made to deck.

feat(artifacts): Orca passes artifacts to bake to rosco

---

orca-core/orca-core.gradle
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java

Switching from `java.util.UUID` to [ulid](https://github.com/ulid/spec) (via impl [sulky-ulid](https://github.com/huxi/sulky/tree/master/sulky-ulid)) to get us a time-sortable ID in executions and stages. This is internals work for SQL.

feat(core): Change Execution & Stage IDs to use ULIDs

---

orca-core-tck/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplateService.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/OrcaMessageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerTest.kt
orca-redis/src/main/java/com/netflix/spinnaker/orca/migrations/MultiRedisOrchestrationMigrationNotificationAgent.groovy
orca-redis/src/main/java/com/netflix/spinnaker/orca/migrations/MultiRedisPipelineMigrationNotificationAgent.groovy
orca-redis/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgent.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationExecutionCleanupPollingNotificationAgent.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-redis/src/test/groovy/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgentSpec.groovy
orca-redis/src/test/groovy/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationExecutionCleanupPollingNotificationAgentSpec.groovy
orca-redis/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepositorySpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/ProjectController.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

No functional changes. Not really prerequisite work for Squirrelly Quagmire Lounge, but will be a nice thing to have anyway. I didn't go about changing any internals of `RedisExecutionRepository` - I think using it inside is totally fine and probably makes a good deal of sense still.

refactor(core): Remove RxJava from ExecutionRepository interface

---

orca-web/src/main/groovy/com/netflix/spinnaker/config/EnhancedMonitoringConfiguration.java
orca-web/src/main/groovy/com/netflix/spinnaker/config/EnhancedMonitoringConfigurationProperties.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Calculating this metric for orchestrations can be a somewhat heavy
operation and has been left as an explicit opt-in.
```
pollers:
enhancedMonitoring:
enabled: true
intervalMs: 60000
applications:
- my_application_foo
- my_application_bar
```
In such a configuration, the # of `RUNNING` orchestrations will be
determined every 60s and emitted as the `executions.running` metric.

feat(monitoring): Allow for `executions.running` to be tracked for a specific set of applications

---

orca-retrofit/orca-retrofit.gradle
orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy

config(rpc): add an OkClient bean (in addition to Ok3Client)
This allows FiatAuthenticationConfig to find a client it expects, while
connections to echo, front50 and clouddriver go through the okhttp3 client
(as confirmed with breakpoints).
Other notable change: Ok3Client now has singleton scope, because that's
what the okhttp3 documentation recommends (because each client now has
its own connection pool instead of sharing a global singleton pool).

Okhttp3 oui oui

---

orca-core-tck/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/PollingAgentExecutionRepositoryTck.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgent.java
orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/PollingAgentExecutionRepository.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationExecutionCleanupPollingNotificationAgent.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgentSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationExecutionCleanupPollingNotificationAgentSpec.groovy
orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-redis/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisPollingAgentExecutionRepositorySpec.groovy

A few things changed here:
1. Switched `ExecutionCriteria` to be an interface. Ended up refactoring my current use for it out, but seemed handy enough to keep.
1. Added new `PollingAgentExecutionRepository` which has some additional poller-specific methods.
1. Moved the two polling agents back into `orca-core`

refactor(core): Polling agents to be persistence agnostic

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy

This is a kind of clunky fix, but needed(?) because the context parameter processor only handles a few types of objects: Maps, Lists, and Strings. Anything else doesn't get processed, and the current code converts the trigger from a Map to a Trigger, so...no good.

fix(front50): process expressions in dependent pipeline trigger

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy

Help us track down errors in monitoring a webhook stage: our fault or endpoint fault?

log(monitorWebhook): add status code from the url for debugging

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AddServerGroupEntityTagsTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/PinnedServerGroupTagGenerator.java

No sense preserving pre-existing entity tags when a new server group
is created.
This can happen if `clouddriver` fails to delete entity tags alongside
the previous server group.
spinnaker/clouddriver#2640 has improved the entity tag delete story in
`clodudriver.`

fix(clouddriver): overwrite entity tags when creating new server group

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java

`buildExecutionContext` is only called by stages trying to evaluate SPeL inside a stage on some input text. The issue is, at this point in the execution, the trigger has already been cast to something other than the generic `Trigger.class`, which some expressions depend on. This explains why typical SPeL evaluation doesn't run into this problem, and only the "ContitionalOnExpression" and "DeployManifest" stages see this.

fix(pipeline/expressions): reference trigger as map, not object

---

orca-kotlin/src/main/kotlin/com/netflix/spinnaker/orca/ext/Stage.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt

Prior to this change, a stage that threw an exception while planning `beforeStages` would still plan + execute its `afterStages` (and not its `onFailureStages`).

fix(queue): fail stage if `beforeStages` planning fails

---

orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionBufferActuator.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/bufferstate/ActiveExecutionsBufferStateSupplier.kt

Moving the metrics reporting of buffering state to the actuator, so we don't need to worry about implementing this metric in each `BufferStateSupplier` implementation.

refactor(qos): Move buffering metric to actuator

---

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/model/KayentaCanaryContext.kt
orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/pipeline/KayentaCanaryStage.kt
orca-kayenta/src/test/kotlin/com/netflix/spinnaker/orca/kayenta/pipeline/KayentaCanaryStageTest.kt
orca-kayenta/src/test/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/AggregateCanaryResultsTaskTest.kt

lifetimeHours continues to be supported for backwards compatibility.
lifetimeDuration can be passed as a string matching this format: https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-
https://github.com/spinnaker/kayenta/issues/283
Supporting UI: https://github.com/spinnaker/deck-kayenta/pull/311

feat(kayenta): support analysis lifetimes shorter than 1 hour

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/oracle/OracleServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/oracle/OracleServerGroupCreatorSpec.groovy

This is a duplicate PR of https://github.com/spinnaker/orca/pull/2280 but has the relevant commit cherry-picked on to master.  It appears #2280 is somehow missing commits.  I've confirmed that this branch includes the commit hash that #2280 is missing and so I hope Travis will successfully build this branch.
The original PR message follows:
The name oraclebmcs is no longer used in Oracle product offering. To avoid confusion, spinnaker provider "oracebmcs" is replaced with the name "oracle".
halyard has made this refactoring in spinnaker/halyard#959.

refactor(provider/oracle): oraclebmcs provider is renamed to oracle

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryUtil.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryUtilSpec.groovy
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-test-groovy/src/main/groovy/com/netflix/spinnaker/orca/test/model/ExecutionBuilder.groovy

Necessary for fixing up the SQL version. Better this way than copying around some non-trivial sorting logic.

refactor(core): Move stage sort logic to utility function

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50Configuration.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTask.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListenerSpec.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/StartPipelineTaskSpec.groovy

BREAKING CHANGE
This addresses a potential security vulnerability wherein a user could
configure a pipeline to be triggered by the completion of another
privileged pipeline.
Currently, the authentication details of the privileged pipeline would
be propagated to the triggered pipeline.
To enable service accounts for implicitly triggered pipelines, you must
enable `services.fiat.enabled`.

fix(auth): Avoid propagating auth to triggered pipelines

---

build.gradle
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50Configuration.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListenerSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

This allows for fiat to be selectively enabled at runtime via the
`DynamicConfigService` (environment-specific).

feat(fiat): Delegate whether fiat is enabled to `FiatStatus`

---

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/KayentaService.kt
orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/MonitorKayentaCanaryTask.kt

Adds a warning to canary stage response if # of data points was fewer than 50.
In support of https://github.com/spinnaker/deck-kayenta/pull/314

feat(kayenta): annotate canary run results with warnings

---

build.gradle
orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy

This PR also adds an `OkHttpMetricsInterceptor` to the `Ok3Client`
used for inter-service communication.
See the service-specific `okhttp.requests` metric.

chore(dependencies): bump `spinnaker-dependencies` to 0.161.1

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java

fix(provider/kubernetes): fail when an artifact couldn't be bound (#2301)

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

- fail stage on `failOnFailedExpressions==true` and failed expressions
- `failOnFailedExpressions` must be in the context and has to be `true`
- sample stage:
```
{
"name": "Wait",
"refId": "1",
"requisiteStageRefIds": [],
"type": "wait",
"waitTime": 120,
"failOnFailedExpressions": true,
"comments": "${failing spel missing closing parens"
}
```

feat(expressions): Adding support for failing stage on failed evaluations

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/JobRunner.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/RunJobTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/dcos/DcosJobRunner.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesJobRunner.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/titus/TitusJobRunner.groovy

This avoids doing a `Names.parse()` on the titus job name which happens
to be a UUID.
Also correct the spelling of `application`.

fix(titus): Include `application` in context of a job run

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/DelegatingExecutionRepository.kt
orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/telemetry/RedisInstrumentedExecutionRepository.kt

Pulling forward some interfaces from the -nflx SQL work and implementing a Redis-mirror of the SQL instrumented execution repository delegate.
This will allow us to get some better apples-to-apples comparisons of redis vs sql perf.

feat(redis): Adding instrumented redis execution repo

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AddServerGroupEntityTagsTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/SpinnakerMetadataServerGroupTagGenerator.java

SpinnakerMetadataServerGroupTagGenerator makes clouddriver calls with retry, which can eventually result in an exception/timeout.
AddServerGRoupEntityTagsTask now has an increased timeout to account for remote timeout from multiple server groups.
In addition, an exception from a single tagger is not fatal to the tagging operation - any successfully generated tags will get applied, and an error logged for a failed tagger

fix(entitytags): improved timeout handling for servergroup entity tagging.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesContainerFinder.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesJobRunner.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesServerGroupCreator.groovy

Kubernetes V1 stages now allow docker containers to be specified as artifacts. Orca will resolve the artifacts and pass the resulting containers to Clouddriver.

feat(kubernetes): Resolve docker containers passed as artifacts

---

build.gradle

BREAKING CHANGE: This change affects the way in which artifacts injected
into a pipeline are matched to expected artifacts. Prior to this change,
a match was successful if the regular expression in the expected artifact
matched any substring of the corresponding field in the incoming artifact;
after this change, the regular expression in the expected artifact must
match the entire corresponding field incoming artifact.
As an example, consider an incoming artifact with name 'artifact123'. Before
this change, it would match expected artifacts with names 'artifact' and
'artifact.*'.  After this change, the incoming artifact will no longer
match an expected artifact with name 'artifact' but will continue to match
'artifact*'; users will need to explicitly add a wildcard (or some more
complex …

feat(artifacts): Artifact matching should use entire string

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTaskSpec.groovy

`tasks.monitorKatoTask.taskNotFoundTimeoutMs: 120000`

feat(clouddriver): Allow `TASK_NOT_FOUND_TIMEOUT` to be overridden

---

orca-front50/orca-front50.gradle
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/SavePipelineStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/UpdatePipelineStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTaskSpec.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTaskSpec.groovy

Part of https://github.com/spinnaker/spinnaker/issues/3037
This adds an Orca task to generate/update service accounts if the pipeline spec contains a `roles` field.

feat(authz):  Generate spinnaker managed service accounts based on pipeline roles.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTaskSpec.groovy

Currently the ServerGroupForceRefreshTask will return SUCCEEDED if any cache refresh is applied immediately; it should only do this if all cache refreshes are applied immediately.

fix(caching): Poll for completion if any cache update is not immediate

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTaskSpec.groovy

Fiat service account names are always lower cased in Fiat/Front50.

fix(serviceAccounts): Ensure service account names are always lowercase

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/GraphMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy
orca-pipelinetemplate/src/test/resources/integration/v1schema/loops-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/loops-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/loops-template.yml

Adding basic looping ability for stages & partials (non-recursive).
Required by a couple infrastructure teams internally. It's unlikely we'll be able to move them off to `spin` until sometime next year.

feat(pipeline_templates): Add stage looping support

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy
orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandler.groovy
orca-retrofit/src/test/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandlerSpec.groovy

While fumbling around in our logs, I noticed a bunch of logs like this:
`retrofit.RetrofitError: Path parameter "imageId" value must not be null.`
Added a condition in the Retrofit ExceptionHandler to never retry these sort of requests since they'll never succeed anyway.
While digging, I also noticed the `GetCommitsTask` makes a call to front50 that is never used, so I tore that out.

fix(retrofit): Do not retry requests that cannot succeed

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardException.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy

Also added some markers for things to do to Traffic Guards to improve reliability of the feature itself.
My current plan to improve Traffic Guards is to add a new purpose-specific endpoint clouddriver for the data that guards need:
1. `GET /trafficGuards/{application}/clusters/{account}/{name}` - Get a cluster.
2. `GET /trafficGuards/{application}/instanceServerGroups?instanceIds=[]` - Get a `Map<InstanceId, ServerGroup>` response.
These two endpoints will allow us to cut down the number of network calls `orca -> clouddriver` in a traffic guarded codepath by quite a lot and also allow us to get the freshest data. Within clouddriver we'll end up going direct to the cloud provider for data if we don't detect a traffic guard condition. Using this PR to collect opinions (although will …

chore(trafficguard): Add metrics to traffic guards

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/InstantiationTypeRestrictor.java

From jasonfillo on slack
> jasonfillo [3:25 PM]
> LocalDate is just for Date operations. Instant will do Date and Time and is tied directly to UTC which all your backend, database, business logic, whatever should probably be using

feat(spel): add support for Instant.java in spel

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy

Currently the SpEL evaluator returns an error if the result contains any SpEL; this means that it's impossible to escape expressions of the form "${VARIABLE:default}" (which are common in Helm templates) so that they are left verbatim by the SpEL evaluator. Change the way that the evaluator detects partial evaluation so that the result is allowed to contain strings that look like SpEL.

fix(spel): Fix escaping of SpEL expressions

---

orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java

When the `RedisExecutionRepository` is used with keiko's redis queue implementation, the buffered execution redis index keys are now prefixed with the queue name. This allows qos to be used with partitioned orca workers sharing an execution repository, without risk of actuation violating partition boundaries.
Note: if currently using `orca-qos`, execution buffering should be disabled before deploying this change and reenabled after deployment, once validating there are no buffered executions.

feat(qos): namespace redis buffered execution index

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueShovelConfiguration.kt
orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java

Fix 2 issues when Orca is configured with redis.connectionPrevious
- Fix expression syntax
- Change argument names to resolve the correct beans

fix(redis): fix multi-redis configuration

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/OortHelper.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/OortHelperSpec.groovy

This PR addresses a couple of situations where we were not handling a
non-existent server group.
We encountered some odd edge cases where `WaitForAllInstancesNotUpTask`
would end up getting stuck waiting on a server group that had previously
been destroyed. Easily reproduced by submitting slightly offset destroy
server group operations.
Should a server group with the same name happen to be created again, the
task would detect that and succeed (since a new server group has no UP
instances when first created!).
These tasks will now short-circuit if they're unable to find a server
group _AND_ they were expecting one to exist.

fix(clouddriver): Handle missing server groups when checking instances

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityStage.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityStageSpec.groovy

Only check for entity tags if the current stage context contains
sufficient coordinates to identify the target server group.
```
@GET('/tags')
List<Map> getEntityTags(@QueryMap Map parameters)
```
If `parameters` contains a null value (say for an account or server group
name), it will be stripped out and not sent across the wire.
This effectively changes a query for a very specific server group and
account into a wildcard.
The best way to ensure that server groups are correctly being unpinned
is to enable the `RestorePinnedServerGroupsPoller` is enabled.
`pollers.restorePinnedServerGroups.enabled: true`

fix(clouddriver): Handle situations where the wrong `pinned_capacity` tags were deleted

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/EphemeralServerGroupsPoller.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPoller.java
orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/AbstractPollingNotificationAgent.java

I missed the fact that some of our pollers are configured using seconds, and others milliseconds in https://github.com/spinnaker/orca/pull/2366, which fundamentally broke some stuff. This restores correct scheduling.

fix(core): Make polling interval time unit configurable

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/artifacts/FindArtifactsFromResourceTask.java

Include the manifest found in addition to the artifacts. Rename the stage to `FindManifest`, similar to find image stages.
This makes it possible to, for example, retrieve the current number of replicas for a deployment and use this when updating that deployment, or to use that number when creating a new deployment (for example, when doing blue-green deployments).

feat(provider/kubernetes): v2 Include manifest when finding resource

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy

Daniel told me not to be so clever and just use `null`.
Also fixing orca startup when optional beans aren't actually present.

fix(metrics): null value is string null, optional values actually optional

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt

prevent `stageTimeoutMs` propagating to execution window stages

fix(timeouts): don't time out execution windows

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandlerTest.kt

The change in ccbaf76bf48089c71e5a3ed83d4676b4cb6fb2d4 resulted in a
cancelled execution with many leaf nodes each publishing an ExecutionComplete
and causing dependant pipelines to run.

fix(executions): revert ExecutionComplete event publishing change

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTaskSpec.groovy

It's possible that a server group will not be fully indexed (missing
image information) when it's selected for rollback.
An edge case but this PR guards against the resulting NPE.

fix(clouddriver): Guard against an NPE when determining rollback target

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPoller.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPollerSpec.groovy

This allows for a service account to be used that would grant access to
privileged accounts and applications.

feat(clouddriver): Allow username to be overridden in `RestorePinnedServerGroupsPoller`

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTask.groovy

It's far too verbose and just clutters the logs in our environment.
If in the future there is interest in improving this, I would suggest
filtering the response down to the cluster being operated on and logging
that.

fix(clouddriver): stop logging the force cache contents

---

gradle.properties

Fixes an efficiency regression for low- to medium-volumed orca deployments.

chore(*): Bump keiko to 2.9.5

---

orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionStatus.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandlerTest.kt
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Routes cancelation into the CompleteExecutionHandler, allowing it to
determine the final pipeline status, and not updating the pipeline status
until other branches with running stages have been marked as canceled.

fix(cancel): consistent CANCELED event

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/RollbackClusterStage.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/RollbackClusterStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStageSpec.groovy
orca-dry-run/src/main/kotlin/com/netflix/spinnaker/orca/dryrun/DryRunStageDefinitionBuilderFactory.kt

The stage runs a task that identifies the cluster to roll back. That info is useful and it's just a read operation. Also, if that has not happened construction of the after stages that actually perform the rollback operations fails.

fix(dryrun): Rollback cluster stages can run for real

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/oracle/OracleImageFinder.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/oracle/OracleImageFinderSpec.groovy

Added an OracleImageFinder implementation which is needed for the Oracle cloud's find image pipeline stage to work correctly.
Related PRs:
https://github.com/spinnaker/deck/pull/5605
https://github.com/spinnaker/clouddriver/pull/2874
@markxnelson

fix(provider/oracle): Add OracleImageFinder for findImageByTags to work

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy

Right now `getClass().getSimpleName()` == `_trigger_closure3`. Using a string instead.

fix(metrics): use string instead of class name

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStageSpec.groovy
orca-kotlin/src/main/kotlin/com/netflix/spinnaker/orca/ext/Stage.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/admin/HydrateQueueCommand.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandlerTest.kt

This addresses a scenario where an execution would never complete if
the set of after stage statuses contained a mix of SUCCEEDED and
TERMINAL.
See `onFailureStages()` on `CreateServerGroupStage`.

fix(queue): `ContinueParentStageHandler` should complete if all after stages are complete

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java

Sometimes the "Force Cache Refresh" task of deploying a v2 manifest would take
up to 12 minutes to complete. This would occur as result of a timing issue
between when Orca submits the refresh requests to the cloud driver and when the
cloud driver processes the requests.
The fix is to handle the scenario where Orca "forgets" pending requests that
have been previously completed if not all the pending requests are completed
when it queries the cloud driver.
This is to fix issue spinnaker/spinnaker#3366

fix(orca) fix force cache refresh sometimes taking 12 minutes (#3366)

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/MetricsTagHelper.kt

At long last, we know exactly where we had that bad metric.
An example of the invalid measurements (there's a ton of these):
```
invalid measurement: Measurement(task.invocations.duration.withType:account=:atlas.dstype=rate:cloudProvider=aws:executionType=PIPELINE:isComplete=true:region=n_a:statistic=totalOfSquares:status=SUCCEEDED:taskType=com.netflix.spinnaker.orca.igor.tasks.StartScriptTask,1537820460000,0.0)
```

fix(metrics): Correctly handle potentially empty account tag

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy

(kind of similar to this one https://github.com/spinnaker/orca/pull/2406 )
When a templated pipeline has `expectedArtifacts`, and said pipeline is triggered by another pipeline (parent), the expectedartifacts value is not kept after the the process done by `PipelineProcessors`

fix(pipeline_templates): Fix expected artifacts when templated pipeline is triggered by a parent pipeline

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/CustomStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelDeployStage.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelDeployStageSpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/locks/LockContext.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/locks/LockContextSpec.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTask.groovy

fix for a couple items broken by #2420 :
* locking in strategies and child pipelines will now use the parent pipeline id 
* traffic guard getting a 403 on an application lookup is non fatal (treated as application not existing)
* also increases the poll interval for monitoring child pipelines from 1s -> 15s

fix(locking): fixes locking in strategies / child pipelines

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/AbstractClusterWideClouddriverOperationStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/JobUtils.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractBulkServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/ClusterLockHelper.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/MonikerHelper.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTaskSpec.groovy

Cluster is not a required field on Moniker, and in a number of cases where we are working with a Moniker from pipeline configuration or a submitted execution the cluster can be absent. For TrafficGuard, locking, and cluster status checking purposes we want to programmatically rely on the Moniker object holding the cluster to check. This adds a few more checks and fallbacks to the serverGroupName to build the Moniker object if there is no cluster available

fix(moniker): handle Monikers without cluster

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/DetermineLockTask.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/DetermineLockTaskSpec.groovy

Rolling in the locking code to an existing system running pipelines can cause a new node to plan a disable lock stage when the corresponding acquire lock stage was not planned. If locking is not enabled, the determine lock failure becomes non fatal and just generates a stubbed out lock context.

fix(locking): determine lock should not fail when locking is disabled

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy

Before: An empty `expectedArtifacts` array in a webhook stage definition results in a failed pipeline with no explanation provided, and an error in Orca related to missing artifacts.
After: The pipeline is allowed to continue when the webhook response doesn't contain any artifacts.
Closes https://github.com/spinnaker/spinnaker/issues/3354

fix(webhook): ignore empty expectedArtifacts list in webhook stage response

---

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTask.groovy

The current try/catch suppresses any validation failures that were
raised by `front50`.
Regressed in spinnaker/orca#2387

fix(front50): Default handling for any retrofit exceptions

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.kt

Noticed we've got some zombos, but the logs that we emit aren't very friendly to machine parsing.

chore(queue): Add kv logs for zombie executions

---

orca-clouddriver/orca-clouddriver.gradle
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/AbstractClusterWideClouddriverOperationStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/DisableClusterStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/RollbackClusterStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ScaleDownClusterStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupLinearStageSupport.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/AbstractClusterWideClouddriverOperationStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/RollbackClusterStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/HighlanderStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupLinearStageSupportSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/DetermineLockTaskSpec.groovy

Originally the locking.enabled flag would cause the locking tasks to
no-op. This change guards the wiring of locking synthetic stages
as well, as a means of ensuring there are no extra unexpected stages
present when locking is disabled, and to better allow vetting the
feature

fix(locking): more guards around locking

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollback.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollback.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/ExplicitRollbackSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollbackSpec.groovy

A new `delayBeforeDisableSeconds` property has been added to both the
`ExplicitRollback` and `PreviousImageRollback` strategies.

feat(rollback): Support wait before disable during an orchestrated rollback

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy

RPM versions cannot be extracted in the same way as deb versions.

fix(artifacts/trigger/buildInfo): This makes rpms supported

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/CheckForRemainingTerminationsTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/tasks/image/RollingPushTaskSpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/WaitTask.java

We've seen that with rolling push + a specified wait time, this stage is only waiting after the first termination. It _seems_ like start time is never getting reset, and therefore all following wait stages immediately complete because they think they started at the same time as the first wait stage.
This PR resets start time to the lowest time possible. If it sees that time in the running stage, it resets the time to the current time.
@robfletcher - does this seem like a reasonable fix? I'd like to remove the variable from the context entirely (that seems preferable to `Instant.MIN`), but I'm not sure if that's possible.

fix(rollingPush): reset start time

---

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupSpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/StageSpec.groovy

This is a port of https://github.com/spinnaker/orca/pull/2349 to 1.9.x

fix(core): Avoid revisiting stages when traversing ancestors (#2349)

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/Manifest.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DisableManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/EnableManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DynamicResolveManifestTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/GenericUpdateManifestTask.java

https://github.com/spinnaker/spinnaker/issues/3470

feat(provider/kubernetes): dynamic enable/disable

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt

No longer setting MaxAttemptsAttribute on CompleteExecution messages due to a potential race condition when a pipeline has many parallel end branches completing within a close window.

fix(queue): remove max attempts from CompleteExecution

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/OrcaMessageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

Addresses[1] a race condition triggered by the final two or more synthetic BEFORE stages completing close together in time, where duplicate ContinueParentStageMessage B is queued while ContinueParentStageMessage A is being executed (and in the unack'd queue), potentially resulting in duplicate execution of downstream tasks and pipeline failure.
[1] Keiko's ensure method isn't currently atomic; until that changes this only makes the race condition less likely.

fix(queue): only push ContinueParentStage message if not in unacked

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/gce/ModifyGceAutoscalingPolicyStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/gce/WaitForGceAutoscalingPolicyTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/gce/autoscaling/UpsertGceAutoscalingPolicyTask.java

There's no UI for this stage yet, but you can still configure it as a custom stage. The config is as follows:
```
{
"accountName": "spin-jtk54", # gce account name
"cloudProvider": "gce",
"cluster": "app-cluster-name",
"credentials": "spin-jtk54", # gce account name for synthesized stages
"mode": "OFF", # autoscaling mode
"moniker": {
"app": "app",
"cluster": "app-cluster-name",
"detail": "name",
"stack": "cluster"
},
"regions": [
"us-central1",
"us-east1"
],
"serverGroupName": "app-cluster-name-v000", # specify one of serverGroupName or target
"target": "current_asg_dynamic", # specify one of serverGroupName or target
"type": "modifyGceAutoscalingPolicy"
}
```
[Target enum is defined here.](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnake …

feat(gce): Adds stage for modifying autoscaling policies.

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt

Ensures that a top level stage's context has expressions processed during planning.
(not necessary for synthietic stages as they are explicitly added to the graph withMergedContext())

fix(expressions): expressions in top level stage planning.

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTaskSpec.groovy

This was causing service accounts to be overwritten when two pipelines in different applications had the same name in https://github.com/spinnaker/spinnaker/issues/3562

fix(authz): Use pipeline ids for managed service account names.

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SaveServiceAccountTaskSpec.groovy

fix(authz): Use pipeline ids for managed service account names. (#2501)

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy

Instead of just enforcing capacity > 0, we want to compare the current
capacity and the future capacity. This is meant to prevent incidents where
a production cluster could accidentally go from 200 to 3 instances for
example.

 feat(traffic-guards): consider capacity ratio

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/FindImageFromTagsTask.java

The current timeouts are just fine most of the time, but we've been accumulating a lot of images and temporarily have very elevated image lookup times. We'd like to be lenient with those lookups until the times come back down.

fix(findImage): make both find image task timeouts overridable

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/TerminateInstanceAndDecrementServerGroupTask.groovy

`stage.context` contained a `null` value that was subsequently failing
with:
```
java.lang.NullPointerException: null value in entry: scmInfo=null
...
at com.netflix.spinnaker.orca.clouddriver.tasks.instance.TerminateInstanceAndDecrementServerGroupTask.execute(TerminateInstanceAndDecrementServerGroupTask.groovy:80)
```

fix(clouddriver): Avoid NPE in terminate and decrement server group task

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTaskSpec.groovy

This adds the spectator registry to ManifestForceCacheRefreshTask as an initial start to getting more detailed metrics from the Kubernetes manifest tasks. In particular this will give us detailed timing emitted directly from this task on completion and, more importantly, a specific metric when the Force Cache Refresh has been "autoSucceeded" based on the 12 minute timeout. I followed the pattern [here](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy#L52-L60) to make testing a bit easier.
Fixes https://github.com/spinnaker/spinnaker/issues/3605

feat(kubernetes): ManifestForceCacheRefreshTask Metrics

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/image/DeleteImageStage.java

Removing the monitor task from delete image. 
If the image does not actually get deleted due to a transient error, Swabbie will try again in the future.

feat(swabbie): do not monitor delete image

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java

When a pipeline is missing artifacts on startup, we currently throw an IllegalStateException, which eventually returns a 500 code to the client.  As this is a problem with the request, and it should not be retried, let's be more clear by making it an IllegalArgumentException, which returns a 400 code.

fix(artifacts): Use client error return code for missing artifacts

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Just filter out executions if they can't be found.

fix(tasks): do not fail if execution not found in /pipelines call

---

orca-bakery/orca-bakery.gradle
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy

We use the owner field in the bake stage to tag images with their owner.
Right now, we just pull this from the stage.
This PR adds a lookup to front50 to find the application, and if that application exists and the owner exists it updates the owner to be that value.

feat(bake): pass owner as application owner

---

orca-webhook/orca-webhook.gradle
orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfiguration.java
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/service/WebhookServiceSpec.groovy

The webhook okhttp wasn't using the defaults we have in the config. We were seeing requests time out after 10 seconds (which is not consistent with previous behavior). This PR updates okhttp to use the config values for read and connect timeout.
@ajordens let me know if you'd do this a different way, happy to make changes.

fix(webhook): using okhttp configs instead of defaults

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java

This should slow down how often a failed refresh attempt is made by forcing orca to listen to the backoff period for the ManifestForeCacheRefresh task

fix(provider/kubernetes): manifest refresh is retryable

---

orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookConfiguration.java
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/config/WebhookConfigurationSpec.groovy

Supports converting a `payload` represented as a map to suitable
url encoded form values in the event that the content type of the
webhook request is `application/x-www-form-urlencoded`.
```
{
"customHeaders": {
"Content-Type": "application/x-www-form-urlencoded"
},
"method": "POST",
"name": "Webhook",
"type": "webhook",
"payload": {
"home": "Cosby",
"favorite flavor": "flies"
},
"url": "https://webhook.site/92081a97-2044-4fc1-9b66-a126f3baa082"
}
```
Should not apply to any other content types or payload types.

feat(webhook): Support for `application/x-www-form-urlencoded`

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

This PR adds the ability to allow orchestrating a pipeline given its config ID and a trigger body. The intention of this endpoint is to be used by `echo-pipelinetriggers` module, allowing the use of the GraphQL endpoint in Front50 to reduce network overhead on cron triggers (and probably also other triggers?)
I also renamed a couple methods in the OperationsController that didn't make any sense.

feat(web): Allow orchestrating pipeline configs by id

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/model/V2PipelineTemplate.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/V2PipelineTemplateController.java

Also fixes SpEL rendering for /orchestrate - was broken due to model changes in a previous PR. Maintains backwards compatibility for v1 plan. @jervi @gardleopard may be interested in this as well.

feat(MPTv2): Adds separate v2 plan endpoint.

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/TriggerSpec.groovy

Upgrading from 1.8 to 1.10, I noticed that our webhook triggers were no longer working. Digging into the orca logs, there was an exception being thrown
```
c.n.s.k.w.e.GenericExceptionHandlers     : Internal Server Error
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.List<E>
```
originating at [this line](https://github.com/spinnaker/orca/blob/release-1.10.x/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt#L134), as a result of trying to deserialize the `notifications` field [here](https://github.com/spinnaker/orca/blob/release-1.10.x/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt#L107).
The line of code responsible for deserializing that field …

fix(triggers): Handle explicitly null container fields in triggers

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/AbstractClusterWideClouddriverOperationStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/DisableClusterStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ScaleDownClusterStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/BulkDestroyServerGroupStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CloneServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/AbstractClusterWideClouddriverOperationStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/HighlanderStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategySpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilderSpec.groovy

```
stages.cloneServerGroupStage.forceCacheRefresh.enabled: false
```
Current belief is that `ServerGroupCacheForceRefreshTask` is being used
in a few spots unnecessarily and causing pipelines/stages to run longer
than needed.
We will test in our environment, if the belief holds true we'll either:
(a) remove the `ServerGroupCacheForceRefreshTask` or
(b) make it easier to disable `ServerGroupCacheForceRefreshTask` across the board

feat(pipeline): Support conditional disabling of `ServerGroupCacheForceRefreshTask`

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/WaitUntilStage.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/WaitUntilTask.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/WaitUntilTaskSpec.groovy

This adds a `waitUntil` stage which will be used in the kayenta pipeline to accurately schedule when to run canary reports in a sequence on a pre-computed schedule.  `waitUntil` waits for an absolute time in milliseconds.
Kayenta sets up a schedule, which is visible in the UI, of when it will run analysis stages.  It spaces these apart by a fixed amount, and it is nice to see the times they are scheduled to run.  The current Kayenta stage uses `wait` stages with a fixed amount to do this, but if the report takes seconds to run, it will drift and end up running the canary longer than it should.  `waitUntil` removes this drift.

feat(waitUntil): add waitUntil stage for internal use

---

orca-sql/orca-sql.gradle

Orca tests are not compiling because gradle is pulling the latest version of minutest, which removed some classes we depend on. Pin the version to the latest version before this breaking change.

fix(sql): Pin minutest dependency

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequest.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java

Expected artifacts are not being returned from template plan requests as they are not in the spec; this is breaking display of templated pipelines with expected artifacts.

fix(pipelines): Add expected artifacts to pipeline template spec

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

Create a new '/plan' endpoint that allows callers to request a plan for a pipeline template. Any calls to '/orchestrate' with pipeline.plan set to true can be migrated to this endpoint, but the '/orchestrate' endpoint will continue to work.
This new endpoint has a new feature, the flag 'resolveArtifacts' that allows the caller to toggle whether to resolve artifacts when making the plan.

 fix(pipelines): Allow caller to specify whether to resolve artifacts

---

orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepositorySpec.groovy

The tests assume ordering of executions fetched from the database, but our ULID implementation only guarantees monotonically increasing ids to millisecond precision, so we get occasional failing tests when two executions are created in the same millisecond.

fix(sql): Fix intermittently failing tests

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy

This logs the exception when a pipeline started/finish event to echo
fails.

refactor(echo/notifications): Log exceptions

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

When a templated pipeline is first configured, we call the plan endpoint to generate the pipeline for display in the UI. This rendered pipeline doesn't have the inherited fields included; these are only inherited on a save operation. In order to properly show the rendered pipeline after a plan request, also process any inherited fields when requesting a plan.
As this code is run on any save operation, it is already required to be idempotent (so subsequent saves without a change in the UI are no-ops); it is thus safe to run it after configuring the pipeline as well.

fix(pipelines): Fix rendering of templated pipelines

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTaskSpec.groovy

The capacity check in TrafficGuard assumes entire server groups are going
away, which is not necessarily true in the case of rolling red/blacks.
In the RRB case, AbstractClusterWideClouddriverTask generates katoOps
for operations like disableServerGroup with a desiredPercentage property
and clouddriver is responsible for selecting which instances to disable.

fix(traffic-guards): bypass the traffic guard capacity check during RRB

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java

ExpressionTransform.transformString and .transformList are useful, not just transformMap.
Check out this construction of a Map, and the need to ensure a consistent key between controller and the processor just to evaluate a String.
https://github.com/spinnaker/orca/blob/1931bd1a43c978f945866587f68897082409577c/orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy#L490
https://github.com/spinnaker/orca/blob/d7c223a14a44af61d827c680203b45aebc825b4e/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java#L64
Things like this could be simpler without the need to artificially construct a Map.

fix(pipelines): make String and List expression transforms public

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionEvaluationSummary.java

ExpressionEvaluationSummary.Result attributes have some useful information like description and exceptionType. It would be nice to be able to access these from other packages or other projects. ExpressionEvaluationSummary is public and it publicly exposes Result through getExpressionResult so it makes sense to have access all the way down.

fix(pipelines): allow access to evaluation result attributes

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy

We access autoscaling policy fields when synthesizing
dynamic stages if the server group is autoscaled.
We have to explicitly add the getter for java-groovy interop.
This is a port of the relevant parts of https://github.com/spinnaker/orca/pull/2488.

fix(targeting): Adds autoscaling policy getter.

---

orca-core-tck/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationExecutionCleanupPollingNotificationAgent.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionComparatorSpec.groovy
orca-migration/src/main/kotlin/com/netflix/spinnaker/orca/pipeline/persistence/migration/OrchestrationMigrationAgent.kt
orca-migration/src/main/kotlin/com/netflix/spinnaker/orca/pipeline/persistence/migration/PipelineMigrationAgent.kt
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplateService.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/OrcaMessageHandler.kt
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/telemetry/RedisInstrumentedExecutionRepository.kt
orca-redis/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepositorySpec.groovy
orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt
orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/telemetry/SqlInstrumentedExecutionRepository.kt
orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepositorySpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/ProjectController.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

A user discovered a situation where SQL behaves differently than Redis:
```
$ SIZE=100
$ curl -s "https://spinnaker/applications/my_app/executions/search?application=my_app&pipelineName=DEPLOY&triggerTimeStartBoundary=1539846060000&triggerTimeEndBoundary=1539964800000&reverse=true&size=$SIZE" | jq '. | length'
27
$ SIZE=1000
$ curl -s "https://spinnaker/applications/my_app/executions/search?application=my_app&pipelineName=DEPLOY&triggerTimeStartBoundary=1539846060000&triggerTimeEndBoundary=1539964800000&reverse=true&size=$SIZE" | jq '. | length'
98
```
This happens because with redis, we'd get all the executions and then filter down to the matching ones. In sql, we are only getting `limit` number of executions and then filtering them down to the matching ones. This is unexpected.
This PR …

fix(search): execution results < limit == no more matches

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStage.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStageSpec.groovy

Manual judgement notifications are weirdly different from all other notifications, so this extra bit of change is needed on top of the stuff from yesterday.
tag: https://github.com/spinnaker/spinnaker/issues/2784

fix(pubsub): Make manual judgement notifications work with pubsub

---

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/VerifyApplicationHasNoDependenciesTask.groovy

See https://github.com/spinnaker/spinnaker/issues/3857 for context, we NPEd in the error handling so we couldn't even see the proper exception from Retrofit.

fix(appDelete): Handle retrofit exceptions with no response object.

---

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/ExecutionMapper.kt

Not sure why we're sometimes getting duplicate executions back. This is an attempt to not have duplicates.

fix(sql): trying not to return duplicate results in get executions

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy

Adds `failFastStatusCodes` property to the webhook stage. This is an array of status
codes that will short circuit the retry logic and instead fail the stage

feat(webhooks): Ability to specify HTTP status codes that cause the stage to fail fast

---

orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy
orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitInterceptorProvider.java

The `RetrofitInterceptorProvider` interface provides an extension point
through which additional okhttp/okhttp3 interceptors can be registered.

feat(retrofit): Support registering custom interceptors

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy

Always set the webhook response body (for success, failures, etc)
This is helpful for debugging webhooks

fix(webhooks): Propogate webhook response reliably

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy

Always use `error` (never `errorMessage`) to report errors from webhooks stage
This is what UI looks for (improvements in that area will be PR'd shortly)

fix(webhooks): use error field consistently

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

Opted to set it during `withLoggingContext()` rather than introduce
another `ThreadLocal` or mess with `ExecutionContext`.

feat(queue): Make `taskStartTime` available on MDC context

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableTask.java

In the event that `status.getStable() == null` then `status.getStable().getMessage()` will throw an NPE
We ran into this in a production setting. Happy to discuss other alternatives.

(fix): Possible NPE with `WaitForManifestStableTask`

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy

We have a user who is using SpEL to conditionally set the `baseName` in the bake. If the parameter of the pipeline has a value for baseName, it's set in the stage. If the parameter is empty, they send us empty string because there is no way to conditionally set a field in the UI. 
`"baseName": "${ parameters['customBaseName'] ?: '' }",`
It feels like the right behavior to remove this parameter from what gets turned into the BakeRequest. This shouldn't break anything because right now if you send an empty string for baseName our bakery errors out.

feat(bake): if base name is empty string, remove from bake request

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTaskSpec.groovy

Instead of bubbling semi-useless error message verbatim from JsonPath
Make it relevant and clear to the end user why monitoring for webhook failed
if the specified json path is not valid

fix(webhooks): give better error message for monitored webhooks

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/DualExecutionRepository.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/telemetry/RedisInstrumentedExecutionRepository.kt
orca-redis/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepositorySpec.groovy
orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt
orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/telemetry/SqlInstrumentedExecutionRepository.kt

This is to support de-duplicating pipelines from an internal tool (Gutenberg) which sends a ton of pipeline requests to us with a low timeout/retry cycle.

feat(core): Support pipeline correlation ids

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy

The find image stage can generate a variety of exceptions that would
escape from findBaselineAmis.

fix(canary): capture exceptions from findImage in DeployCanaryStage

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStageSpec.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/RegionCollector.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/StageSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/RegionCollectorSpec.groovy

FindImageFromClusterTask now looks ahead to find all regions from subsequent deploy stages
This moves the failure point of a pipeline up when an image isn't found.
E.g. FindImage specifies to look for images in `us-east`, but a deploy right after was modified to
deploy to `us-east` AND `us-west`. Thus FindImage will locate the `us-east` image,
the deploy for that image will start but the deploy for `us-west` will fail.
This failure can cause regions to have different versions deployed.
To prevent this, we now will fail in the FindImage task before any deploy starts

fix(FindImageFromCluster): infer regions from deploy stages

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java

This was left off from the previous PR (https://github.com/spinnaker/orca/pull/2640)

fix(stage): removing immutable empty list from allDownstreamStages

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/WaitForUpInstancesTaskSpec.groovy

AWS deployments are somewhat special in that they create an initial
asg of size 0/0/0 and then subsequently resize it to the target
capacity.
This PR protects against premature success by favoring the
clouddriver-supplied capacity if we see a 0/0/0 asg but expect a
non-0/0/0 asg.
The edge case only appears when the `ForceCacheRefresh` task is dropped
from the deploy stages in `orca`.
relates to spinnaker/clouddriver#3356

feat(clouddriver): Consider target capacity if supplied from `clouddriver`

---

orca-sql/orca-sql.gradle
orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/PagedIterator.kt
orca-sql/src/test/kotlin/com/netflix/spinnaker/orca/sql/SqlHealthcheckQueueActivatorTest.kt
orca-sql/src/test/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/PagedIteratorTest.kt

This kept Orca from building. I’m guessing that it wasn’t caught because everyone else (including travis) have a com.oneeyedmen:minutest:0.34.0 sitting in their .m2 cache.
It is described here (https://github.com/dmcg/minutest) that the group for the minutest project changed from ‘com.oneeyedmen’ to ‘dev.minutest’ and com.oneeyedmen:minutest:0.34.0 can no longer be referenced. The minor code changes are just what was needed when updating the dep.

fix(dependencies): update minutest dependency in orca-sql to fix build

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionEvaluationSummary.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt

* Improve error messages in FindImage stage when images are inferred from subsequent deploys
* Don't surface intermediate errors during SpEL evaluation

fix(errors): Better error messages

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

Include application name from the execution to MDC during task execution
This way it's always there which is convenient for log analysis

fix(logging context): add application name to the MDC

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/ReorderPipelinesStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/ReorderPipelinesTask.java

Adds a reordering task for pipelines and pipeline strategies so that we don't need to kick of a save task for each pipeline in an application after they are reordered or one is removed.
Corresponding PRs:
Deck: https://github.com/spinnaker/deck/pull/6519
Gate: https://github.com/spinnaker/gate/pull/723
Front50: https://github.com/spinnaker/front50/pull/448

feat(core): add support for reordering pipelines

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategySpec.groovy

Fixes an issue where a single instance starting to fail in one of the
RRB `Grow to X%` tasks would fail the whole deployment.

fix(rrb): pass targetHealthyDeployPercentage to resize tasks

---

orca-core-tck/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy

Another test fails occasionally due to non-monotonic ULIDs over short timescales.

fix(redis): Fix intermittently failing test

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequest.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandler.kt

One can specify notification on the pipeline in deck (even if pipeline is templated)
However, those notifications are not respected because they don't end up in the
pipeline config. Copy them there so notifications work as expected.

fix(MPT): Propagate notifications from pipeline config
