orca-web/orca-web.gradle

reference /opt in startScripts

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy

make it work against new format of deploymentDetails

fix context parameters for deployServerGroup

---

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTask.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/model/Application.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/model/ApplicationSpec.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy

Updates Application class to align with Front50's Application class (https://github.com/spinnaker/front50/blob/master/front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy) so that we can persist dynamic properties.

convert application to use dynamic properties

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

@ajordens how much are you in love with this?

optionally record user canceling tasks and pipelines

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/WaitForDestroyedServerGroupTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/WaitForDestroyedAsgTaskSpec.groovy

Adding a little visibility into why a destroy task has not yet completed - something we see periodically
@claymccoy please review

log instances when destroy server group has not yet completed

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/StageBuilder.groovy

Working on a test for this at the moment, but this should get people unblocked

reset any cancelled stages before restarting

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DetachInstancesTask.groovy

Also makes DetachInstancesTask retryable to account for Retrofit NetworkErrors with katoService

add terminate.account.name and terminate.region to DetachInstances stageOutputs

---

build.gradle
orca-core/orca-core.gradle
orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/notifications/AbstractPollingNotificationAgent.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/notifications/JesqueActivator.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationExecutionCleanupPollingNotificationAgent.groovy
orca-core/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaConfiguration.java
orca-core/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaStatusChangedEvent.java
orca-core/src/main/java/com/netflix/spinnaker/kork/eureka/internal/EurekaEventBridge.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/notifications/JesqueActivatorSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/notifications/JesqueControlSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/restart/PipelineRestartAgentSpec.groovy
orca-eureka/src/main/java/com/netflix/spinnaker/orca/eureka/DiscoveryStatusPoller.java
orca-eureka/src/main/java/com/netflix/spinnaker/orca/eureka/NoDiscoveryApplicationStatusPublisher.java
orca-eureka/src/test/groovy/com/netflix/spinnaker/orca/eureka/DiscoveryStatusPollerSpec.groovy
orca-eureka/src/test/groovy/com/netflix/spinnaker/orca/eureka/NoDiscoveryApplicationStatusPublisherSpec.groovy

Revert "update dependencies"

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/kubernetes/KubernetesServerGroupCreator.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/kubernetes/README.md

Add kubernetes server group creator

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy

- requires a configuration change in deck

BakeStage is now restartable

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy

- Insert a DisableClusterStage prior to any ShrinkClusterStage
- WaitForClusterDisableTask will wait a particular amount of time to allow for any connection draining / discovery out_of_service to complete

Server groups should be disabled prior to being destroyed

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/azure/AzureSecurityGroupUpserter.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/azure/AzureServerGroupCreator.groovy

Add Azure server group and security group related provider classes

Add implementation classes for Azure specific providers

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy

- Specifically pipelines with multiple deploy stages and DestroyServerGroup stages with multiple target regions

Handle more complex scenarios for disable-before-destroy

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/RollbackServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ResizeStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToServerGroupResizeStrategy.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/RollbackServerGroupStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToServerGroupResizeStrategySpec.groovy

- Will resize the currently disabled ASG such that it matches the active ASG

Add an implicit resize to a rollback operation

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy

Add ErrorConfiguration to sanitize response messages

---

orca-web/orca-web.gradle

a la:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-web/clouddriver-web.gradle#L34-L35
https://github.com/spinnaker/gate/blob/master/gate-web/gate-web.gradle#L28-L29
@ajordens or @robfletcher please review - did a quick smoke test locally and it works as expected

gzip responses

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy

Makes use of new endpoint written here: https://github.com/spinnaker/clouddriver/pull/349
Don't merge until that above PR is in.
@ttomsu, @cfieber PTAL.

core: Make use of ImagesSummary endpoint

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesServerGroupCreator.groovy

Needs #741 to be useful.
@duftler

provider/kubernetes: Populate find image results from context

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionStarter.groovy

dedups stage ids for restarts to resolve issue where restarting a pipeline will create multiple synthetic stages with the same exact id

deduplicate stage ids for restarts

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/Location.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolver.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/OortHelper.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/StageData.groovy

This is needed to correctly do dynamic lookups of kubernetes server groups for use by pipeline stages.
@duftler

provider/kubernetes: Add `NAMESPACE` to Location types.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy

fix bug in location zone checking

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesSecurityGroupUpserter.groovy

@duftler 
Appears to be required by each cloud provider.

provider/kubernetes: Security group upserter

---

.travis.yml

use trusty gcp build worker

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/loadbalancer/UpsertLoadBalancersStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/UpsertLoadBalancersTask.groovy

orca changes for issue https://github.com/spinnaker/spinnaker/issues/760
unit tests to follow

New pipeline stage for creating multiple load balancers

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineStarter.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineStarterListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Pipeline.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/pipeline/PipelineStarterListenerSpec.groovy

Fixing the issue https://github.com/spinnaker/spinnaker/issues/805
Allowing queuing pipelines to stay in queue.

Customize queue behavior for pipeline waiting

---

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/UpsertLoadBalancersTaskSpec.groovy

unit test for UpsertLoadBalancersTask -  issue spinnaker/spinnaker#760

unit test - new stage for creating multiple loadbalancers

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/UpsertServerGroupTagsTask.groovy

Fix UpsertServerGroupTagsTask to correctly determine the server group to issue forceCacheRefresh against

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStage.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/MonitorAcaTaskTask.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/RegisterAcaTaskTask.groovy

Add Stage for Generic ACA Task.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/JobForceCacheRefreshTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy

Fixup missing imports & clarify logic w/ comment

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/ExecutionStatus.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/BatchStepStatus.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/StageStatusPropagationListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTasklet.groovy

Link to issue -- https://github.com/spinnaker/spinnaker/issues/685

allow pipeline to continue even when Jenkins stage fails

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/ExecutionListener.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/StageListener.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/StageTaskPropagationListener.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/config/EchoConfiguration.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoEventSpec.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListenerSpec.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50Configuration.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListenerSpec.groovy
orca-spring-batch/src/main/java/com/netflix/spinnaker/config/SpringBatchConfiguration.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/SpringBatchExecutionRunner.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/listeners/SpringBatchExecutionListenerProvider.java
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/orca/batch/SpringBatchExecutionRunnerSpec.groovy

- DependentPipelineExecutionListener is no longer a JobExecutionListener (rather it's an ExecutionListener)

Listeners are now Comparable<>

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/DestroyJobStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/DestroyJobForceCacheRefreshTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/DestroyJobTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/RunJobForceCacheRefreshTask.groovy

core: Destroy job stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolver.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractWaitForClusterWideClouddriverTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/OortHelper.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToClusterResizeStrategy.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ModifyAwsScalingProcessStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupLinearStageSupportSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolverSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TerminatingInstanceSupportSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ScaleDownClusterTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ShrinkClusterTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/scalingprocess/AbstractAwsScalingProcessTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractServerGroupTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ApplySourceServerGroupSnapshotTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CaptureSourceServerGroupCapacityTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/DestroyServerGroupTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForAllInstancesDownTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleExactResizeStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleRelativeResizeStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScaleToServerGroupResizeStrategySpec.groovy

Recent problems with WaitForShrinkClusterTask seem to be down to this delegate field getting nulled out at some point.
PTAL @cfieber

encapsulate the map delegate in TargetServerGroup 

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTaskSpec.groovy

corresponding Deck changes to follow

allow users to specify that UNSTABLE jobs be treated as SUCCEEDED

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/InstanceService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTaskSpec.groovy

New OkHttp rejects empty PATCH requests and the task is silently retrying any RetrofitError so the task just always times out.
SPIN-1746

delivery empty body with Quip patch request

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelRunStage.groovy

core: Run jobs in parallel

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelRunJobsStage.groovy

core: s/run/runJobs

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy

The quip stage needs to get the package name to patch the instacne.  When using a Jenkins Job it is able pull this off the pipelines trigger object.
However Quip is often used with a Jenkins stage instead of a trigger resulting in an empty version resolving.
This fix also looks at both the buildInfo on the context and trigger to get the target deb version and then build the version name.
@dzapata @ajordens @robfletcher @cfieber PTAL

fixes SPIN-1749: get package name when no jenkins trigger present.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/AbstractDiscoveryTask.groovy

change instance discovery calls to not append Description 

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/CompleteCanaryTask.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/tasks/CompleteCanaryTaskSpec.groovy

@robfletcher @cfieber @ajordens PTAL

Allows a ACATack stage to continue on an unhealthy canary.

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/parallel/WaitForRequisiteCompletionTask.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/parallel/WaitForRequisiteCompletionTaskSpec.groovy

SPIN-1767: Handle FAILD_CONTINUE status for stage join points.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ModifyAwsScalingProcessStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DisableServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/EnableServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/ResizeServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/RollbackServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupLinearStageSupport.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/RollbackServerGroupStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupLinearStageSupportSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSupport.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoEventSpec.groovy
orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/pipeline/UpdatePersistedPropertyStage.groovy
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/stages/LinearStageDefinitionBuilder.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/stages/SpringBatchStageBuilderProvider.java
orca-test/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSpec.groovy

- First real usages of synthetic stages

Migrated TargetServerGroupLinearStage (and children)

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/HighlanderStrategySpec.groovy

Favor namespace, then region, then zone when resolving location. @duftler PTAL. @ajordens FYI.

Favor namespace, then region, then zone when resolving location.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy

At some point I switched back from region -> namespace, breaking cluster wide ops

provider/kubernetes: Cluster wide operations fix

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/AbstractCloudProviderAwareStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CloneServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/CreateServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/CustomStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/HighlanderStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/NoStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingPushStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/Strategy.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/DeployStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelDeployStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelRunJobsStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/RollingPushStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/DeployStrategyStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/Strategy.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/StrategyFlowComposer.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/AbstractDeployStrategyStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/HighlanderStrategySpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategySpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/StageBuilder.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/lifecycle/LinearStageSpec.groovy

- Fixed circular dependecy issue w/ StageBuilder
- As of this change set, I was able to run a Bake/Deploy w/ Custom pipeline

Deploy Stage and Strategy migrations

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/ExecutionStatus.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/BatchStepStatus.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/ExecutionContextManager.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/ExecutionPropagationListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTasklet.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupport.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/parallel/WaitForRequisiteCompletionTask.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/ExpressionPreconditionTask.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/ExecutionPropagationListenerSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/OptionalStageSupportSpec.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageExecutionListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStepExecutionListenerSpec.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

- Parameter or Expression based

Optional stage support

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy

Add Azure support for baking

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/azure/AzureServerGroupCreator.groovy

@duftler @spinnaker/netflix-reviewers PTAL

Add bake data to deploy operation information

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonSecurityGroupUpserter.groovy

defaulting to `false` to preserve current functionality

(aws) pass ingressAppendOnly flag to clouddriver on sec grp upsert

---

build.gradle
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/QuickPatchStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/JarDiffsTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/AbstractQuipTask.groovy

The tasks that use these services do their own timeout management.

stop instance service using fully configured Retrofit client

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy

(netflix) fail canary deployment if no baseline image found

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/openstack/OpenstackSecurityGroupUpserter.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/openstack/README.md
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/openstack/OpenstackSecurityGroupUpserterSpec.groovy

Added OpenstackSecurityGroupUpserter.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/UpdateInstancesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/UpdateLaunchConfigTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/UpdateSecurityGroupsForServerGroupStage.groovy

This might be a little provider-specific, but there are worse stages in Orca.
@cfieber or @ajordens PTAL

update security groups stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesContainerFinder.groovy

See https://github.com/spinnaker/deck/pull/2361

provider/kubernetes: Trigger based on docker account

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/cluster/ShrinkClusterStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/DestroyServerGroupStage.groovy

It now disables before destroy

(titus) Remove special cases when destroying server group

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DeploymentDetailsAware.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreatorSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/CreateDeployTaskSpec.groovy

- Also `amiDetails` is a List<Map> (not sure how this ever worked previously)

Handle region/regions when looking upstream for amiDetails

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/loadbalancer/MigrateLoadBalancerStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/loadbalancer/MigrateLoadBalancerTask.java

It's essentially a pass-through to Clouddriver.
@cfieber PTAL

provide a stage for migrating load balancers

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/securitygroup/MigrateSecurityGroupStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/MigrateServerGroupStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MigrateTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/securitygroup/MigrateSecurityGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/MigrateServerGroupTask.java

Extracting the task into an abstract one, since I am literally changing one line each time.
@cfieber PTAL

implement migrate load balancer, security group stages

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/serialize/SerializeApplicationTask.groovy

Made changes to output, let me how it looks @duftler @lwander

provider/google: Fixed outputs in serialize application task

---

orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

It could break due to a millisecond boundary happening between invocations of `new Date`. Also mocking a `Clock` is kind of pointless.

Fix flaky test

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/InstanceHealthCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/MonitorQuipTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/MonitorQuipTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTaskSpec.groovy

Skipping all quip executions and leaving an empty instance collection was blowing up

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/BuildArtifactFilter.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildArtifactFilterSpec.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTaskSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

- This filtering was previously only applied to incoming trigger artifacts

Apply artifact filtering to the archived artifacts of a Jenkins stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/securitygroup/MigrateSecurityGroupStage.java

provider/amazon: fix stage type on migrateSecurityGroup

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy

Reverts spinnaker/orca#917
Sorry, hit Merge in the wrong tab.

Revert "core/bake: Don't strip extraneous attributes from bake requests sent to Netflix's internal bakery."

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/ImageTagger.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/UpsertImageTagsTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTagger.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSupport.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSupportSpec.groovy

- Accounts for any delays between an image being baked and indexed

Retry if an upstream image cannot be found

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/OperatingSystem.groovy

I don't always edit `@Deprecated` classes, but when I do it's to hard-code more things that should be configuration driven.
@spinnaker/netflix-reviewers FYI

Add xenial OperatingSystem

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/ImageTagger.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/WaitForUpsertedImageTagsTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTagger.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSupport.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSupportSpec.groovy

- Will tag all upstream images that are found in a pipeline

Support tagging multiple images

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy

@spinnaker/netflix-reviewers FYI

allow longer for a cluster wide task to begin

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

throw exception when trying to orchestrate disabled pipeline

---

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/WaitTaskSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/WaitTask.groovy

A number of users have asked about this functionality.
Next step is to add the ability to skip the remaining wait via the UI.

allow remaining wait time to be skipped

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/RedisConfiguration.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy

Supports a migration scenario from one redis instance to another
- Still need to sort out how best to handle `PipelineStartTracker`
- Tools (likely a background agent) to support moving of completed pipelines/orchestrations from old -> new redis will be forthcoming

`JedisExecutionRespository` support for multiple redis backends

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/notifications/AbstractPollingNotificationAgent.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/migrations/MultiRedisOrchestrationMigrationNotificationAgent.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/migrations/MultiRedisPipelineMigrationNotificationAgent.groovy

These migrators support a migration from <old> redis to <new> redis.

Orchestration and Pipeline migration (multi-redis)

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindow.groovy

Same functionality added last week to the wait stage.

allow overriding of execution window

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/snapshot/RestoreSnapshotStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/snapshot/SaveSnapshotStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/snapshot/RestoreSnapshotTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/snapshot/SaveSnapshotTask.groovy

Changed the name of the stage and task from serializeApplication to saveSnapshot. PTAL @lwander

provider/core: changed name from serialize application to save snapshot

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindow.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindowSpec.groovy

We've heard this from a few folks - they want to specify days of the week in addition to time windows, e.g. Monday through Friday.

allow days of week to be specified in execution windows

---

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/DeleteApplicationTask.groovy
orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTask.groovy
orca-applications/src/test/groovy/com/netflix/spinnaker/orca/applications/tasks/DeleteApplicationTaskSpec.groovy
orca-applications/src/test/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTaskSpec.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/model/Application.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/AbstractFront50Task.groovy

@jtk54 @duftler PTAL
@ajordens, @cfieber - this PR relies on https://github.com/spinnaker/front50/pull/129, so Front50 will need to go out before Orca in your next release.
Closes https://github.com/spinnaker/fiat/issues/43

Adds permission calls during create/update/delete of application config

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryStage.groovy

relates to spinnaker/deck#2668

failPipeline/continuePipeline should be propagated to monitorCanaryStage

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStage.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStageSpec.groovy

Make ACATask Stage Restartable

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/CompositeStageListener.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/StageStatusPropagationListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Task.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/listeners/CompositeStageListenerSpec.groovy
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/listeners/SpringBatchStageListener.java
orca-test/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSpec.groovy

listeners promote stage and task status correctly in v1 and v2

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy

Persist job status on each poll cycle so this is available to the UI

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStage.groovy
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/SpringBatchExecutionRunner.java
orca-test/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSpec.groovy

Rolling push resets correctly

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ParallelDeployStage.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/StageBuilder.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/StageStatusPropagationListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/StageTaskPropagationListener.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/BranchingStageDefinitionBuilder.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/LinearStage.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ParallelStage.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/lifecycle/LinearStageSpec.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/stages/LinearStageDefinitionBuilder.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/stages/ParallelDeployStageDefinitionBuilder.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/stages/ParallelStageDefinitionBuilder.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/stages/SpringBatchStageBuilderProvider.java
orca-test/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSpec.groovy

- Parallel stages are wrapped in a ParallelStageDefinitionBuilder
- StageStatusPropagationListener will mark SUCCEEDED a synthetic stage if the last task has run

Fixes for various issues uncovered during v1/v2 testing of Bake + Deploy

---

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/DeleteApplicationTask.groovy
orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTask.groovy
orca-applications/src/test/groovy/com/netflix/spinnaker/orca/applications/tasks/DeleteApplicationTaskSpec.groovy
orca-applications/src/test/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTaskSpec.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTaskSpec.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/tasks/PageApplicationOwnerTask.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/AbstractFront50Task.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy

- Refactoring to use front50 V2 application API

front50 Application V2 API

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSupport.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageTaggerSupportSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ApplySourceServerGroupSnapshotTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/pipeline/DeploymentStrategiesExecutionSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTasklet.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/AbstractStage.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/StageNavigator.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/adapters/TaskTaskletSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/lifecycle/LinearStageSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/StageNavigatorSpec.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/MonitorCanaryStage.groovy

Made cancel callback work with v2 engine (and v1)

---

orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy
orca-web/orca-web.gradle
orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/model/OrchestrationViewModel.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/web/config/WebConfiguration.groovy

I haven't tested all of these endpoints yet, but Orca/Fiat integration went much smoother than I thought it would.
@jtk54 @duftler @ajordens @cfieber PTAL
Closes https://github.com/spinnaker/fiat/issues/37

Adds Fiat integration annotations.

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/parallel/WaitForRequisiteCompletionTask.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/parallel/WaitForRequisiteCompletionTaskSpec.groovy

handles the case of a join point waiting on a STOPPED requisite stage

---

orca-web/config/orca.yml
orca-web/orca-web.gradle

Closes https://github.com/spinnaker/spinnaker/issues/1166
@duftler @jtk54 PTAL

Fixes ./gradlew startup issue with proper fix. 

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DestroyAwsServerGroupTask.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.groovy

provider/amazon: use HashMap for context in DestroyAsgTask

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/StageBuilder.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/StageBuilderSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStage.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStage.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/JenkinsStage.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/ScriptStage.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStage.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/AcaTaskStageSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

- start/end times are nullified for restarted stages

Restarting a stage should also restart any "completed" children stages

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy

supersedes https://github.com/spinnaker/orca/pull/996
(sorry, we need to get this out ASAP)

(core) move serverGroupReported missing logic out of global scope

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/DeployStrategyStage.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionJobBuilder.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionStarter.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/LinearStage.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/AbstractStage.groovy

and some thrashing on CompileStatic

dependency update

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

Given a list of pipeline config ids, the `/pipelines` endpoint will return the latest executions that have a start time or have not yet started. This new endpoint will be used in echo to offer a viable deployment & restart story using an in-memory scheduler.
Also open to a different endpoint; perhaps `/latestPipelines` or something, so `/pipelines` can stay open for something a little more generic?
@cfieber @ajordens PTAL

Adding latest pipeline executions endpoint

---

build.gradle
orca-web/orca-web.gradle
orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy

Updated to dependences 0.63.0 and added Stackdriver

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/MonitorQuipTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/TriggerQuipTask.groovy

Increase quip monitor timeout

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStage.java
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/JenkinsStage.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/ScriptStage.groovy

sometimes you just want to send a request and not care if the downstream pipeline / stage / job / etc completes

(core) add waitForCompletion field to fire and forget

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/FindImageFromTagsTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/FindImageFromTagTaskSpec.groovy

Presently we SUCCEED the task/stage and the downstream stage will bomb out.

FindImageFromTagsTask fails task if no tagged images are found.

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/listeners/StageStatusPropagationListener.groovy

In v1 there is a special task to add these details to the context but it seems way more reliable to do it in a listener. 
This is what was missing for SPIN-2129.

supply stage details for v2 executions

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTaskSpec.groovy

Fail Jenkins Stage when properties file expected, but not provided

---

orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/SpringBatchExecutionRunner.java
orca-test/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSpec.groovy

handle multiple root stages in v2 engine

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy

@ttomsu PTAL
https://github.com/spinnaker/fiat/issues/116

Remove wildstar in call to cached jobs

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

- Added an endpoint for canceling tasks by passing a list of task ids

Handy batch task cancelling

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy

If an image is baked in multiple regions, but only deployed into one of them, a later findImageFromCluster operation will fail to find the image in both regions if the source account is not the same as the bake account.
Before giving up, check the default bake account for the image. The deploy operation itself performs the `allowLaunchOperation`, which shares the image across to the deployment target.
@cfieber or @ajordens PTAL

fallback to find image from default bake account before failing

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSupport.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-test/src/main/groovy/com/netflix/spinnaker/orca/pipeline/ExecutionRunnerSpec.groovy

Fix issue where multiple execution window pre-stages are added to parallel stages

Only attach execution window to non-synthetic stage

---

build.gradle
orca-web/orca-web.gradle

update to latest build, update ospackaging to project conventions

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/batch/ExecutionContextManager.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/batch/ExecutionContextManagerSpec.groovy

expressions in stage context should be parsed before first task runs

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/appengine/StartAppEngineServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/appengine/StopAppEngineServerGroupStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AbstractWaitForAppEngineServerGroupStopStartTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/StartAppEngineServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/StopAppEngineServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/WaitForAppEngineServerGroupStartTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/WaitForAppEngineServerGroupStopTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/WaitForAppEngineServerGroupStartTaskSpec.groovy

@duftler or @lwander please review

provider/appengine start / stop tasks and stages

---

orca-core/orca-core.gradle
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
orca-web/config/orca.yml
orca-web/src/main/resources/logback-defaults.xml

PTAL @ajordens @jtk54 @cfieber @tomaslin 
Fixes https://github.com/spinnaker/fiat/issues/114

Propagates security context when a pipeline triggers another pipeline

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

@tomaslin as you suggested in https://github.com/spinnaker/orca/pull/1105

Add isPipeline = true if a parentPipeline is found.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreator.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/CreateDeployTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreatorSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/CreateDeployTaskSpec.groovy

Removes the `-vpc` security group case.

Removing vpc0 security group special case

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplateObjectMapper.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/IllegalTemplateConfigurationException.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/TemplateRenderException.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/MapMerge.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/PipelineTemplateVisitor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplateMerge.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/GraphMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConditionalStanzaTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigModuleReplacementTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ModuleInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/PipelineConfigInheritanceTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/Conditional.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/NamedContent.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/NamedHashMap.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateModule.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderContext.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderEngine.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/Renderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/IfEqHelper.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/ModuleHelper.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/MapMergeSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplateMergeSpec.groovy

Still a way, way early start into the implementation of the [proposed dcd-spec](https://github.com/robzienert/dcd-spec), but this is the general direction I'm headed down. Looking for initial feedback before I start dumping a bunch of time into it next week. Stole a bit of code from Cam's spike.

pipeline templates config wip

---

halconfig/orca.yml

@duftler PTAL (also, what's the status of that TODO in there)?

Base orca halconfig

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/FileTemplateSchemeLoader.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/TemplateLoader.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/loader/TemplateLoaderSpec.groovy

- raises an exception if a cycle is detected (A -> B -> A)

Support for loading more than one level of template source

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConditionalStanzaTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/Conditional.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/ConditionHelper.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConditionalStanzaTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/PipelineConfigInheritanceTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/ConditionHelperSpec.groovy

More tests, wow. Almost like a real developer.
@ajordens @cfieber PTAL

Adding handlebars condition; tests for pipeline transforms

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/InterestingHealthProviderNamesSupplier.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/TitusInterestingHealthProviderNamesSupplier.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/TitusInterestingHealthProviderNamesSupplierSpec.groovy

- Added an interface that allows processing and augmentation of the context. For titus we are adding a label and use it in checking whether or not to set the interestingProviderNames for discovery purposes

Handling interesting  health provider for titus

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Pipeline.groovy
orca-spring-batch/src/main/java/com/netflix/spinnaker/zombie/Lock.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/zombie/SimpleRedisLock.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/zombie/ZombiePipelineCleanupAgent.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/zombie/ZombiePipelineCleanupConfig.java
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/zombie/SimpleRedisLockSpec.groovy
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/zombie/ZombiePipelineCleanupAgentSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy

poller to clean up pipelines that died if an orca instance goes out

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/generator/ExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/PipelineConfigInheritanceTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGeneratorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/PipelineConfigInheritanceTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy
orca-pipelinetemplate/src/test/resources/templates/simple-001.yml

Pretty naive implementation at this point, but it does work.
PTAL @cfieber @ajordens

First pass at pipeline executions

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java

un-deprecate initializationStage flag

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupMetadataTagTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupMetadataTagTaskSpec.groovy

Might as well include the name of the pipeline, right?

include pipeline name in server group metadata tag

---

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageType.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/BuildArtifactFilter.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/BuildArtifactFilterSpec.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTaskSpec.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

PR's will be opened against Rosco and Spinnaker repos that require this change

Add NUPKG as a supported PackageType (Windows support)

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/cleanup/FastPropertyCleanupListener.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/PropertyChangeCleanupSpec.groovy

This should fix the fast property rollback on pipeline TERMINAL and CANCEL status

Fix Fast Property Rollback

---

Dockerfile
Dockerfile.slim
build.gradle
cloudbuild.yaml

Same process as https://github.com/spinnaker/fiat/pull/146
@cfieber @duftler FYI

Slims container & bumps spinnaker gradle project version

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/TitusInterestingHealthProviderNamesSupplier.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/TitusInterestingHealthProviderNamesSupplierSpec.groovy

- interestingHealthProviderNames resolved from job label will have priority
- Added rollingPush to the list of supported stages

Adding support for interestingHealthProviderNames resolution when stage is of type rollingPush

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/cleanup/FastPropertyCleanupListener.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/PropertyChangeCleanupSpec.groovy

In order to rollback a deleted fast property we have to remove the original propertyId
before we upsert it.  Otherwise the backend service will try to update a property that
does not exist.

Fix Fast Property Rollback for Deleting

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/ActiveExecutionTracker.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/zombie/ZombiePipelineCleanupAgent.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/config/SpringBatchConfiguration.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/SpringBatchActiveExecutionTracker.java
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/orca/batch/SpringBatchActiveExecutionTrackerSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

endpoint to return active executions underway on each Orca instance

---

Dockerfile.slim
cloudbuild.yaml

GCB tag latest build

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/GraphMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConditionalStanzaTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderContext.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/ModuleHelper.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConditionalStanzaTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRendererSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

- Parsing pipeline trigger info prior to preprocessors
- Ensuring trigger info is set in pipeline after preprocessors

Injecting trigger infor into pipeline prior to preprocessors

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy

Allows templates and configuration to inject stages at the beginning / end of pipelines, as well as before and after other stages.

Stage DAG injection

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/entitytags/BulkUpsertEntityTagsStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/entitytags/BulkUpsertEntityTagsTask.java

Depends on https://github.com/spinnaker/clouddriver/pull/1426

add bulkUpsertEntityTags stage

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy

- Updated injectFirst to add directly to the beginning of the list since graph is topologically sorted
- Updated injectLast. Now finding leaf nodes through dfs as well
- Ensuring no cycle is introduced during injection

Refactoring & adding cycle detection in DAG

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/ActiveExecutionTracker.java
orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/SpringBatchActiveExecutionTracker.java
orca-spring-batch/src/test/groovy/com/netflix/spinnaker/orca/batch/SpringBatchActiveExecutionTrackerSpec.groovy

also, expire details of zombie executions after a week

fix(netflix): ensure older instances report counts

---

orca-spring-batch/src/main/java/com/netflix/spinnaker/orca/batch/SpringBatchActiveExecutionTracker.java

The use of `Sets.union` was causing such a deeply nested data structure with large amounts of running executions that we get StackOverflowError trying to iterate over it. Changed the implementation to much simpler and RxJava-y form.

fix(executions): avoid intermittent StackOverflowError

---

orca-pipelinetemplate/README.md

Updating the README for `orca-pipelinetemplate` to outline bare-minimum getting started docs.

docs(pipelinetemplate): Quick start guide to pipeline templates

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy

helper method to retrieve a property file from a URL and return the result into a map. ( This is useful for Jenkins integrations where the lingua franca seems to be a properties file across jobs )

feat(spel): #propertiesFromUrl helper method

---

halconfig/orca-bootstrap.yml

chore(halyard): Add bootstrapping profile to orca

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateConfiguration.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy

fix(pipelinetemplate): Ensure pipelines are executed on v2

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1SchemaValidationHelper.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidator.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGeneratorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1SchemaValidationHelperSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidatorSpec.groovy

fix(pipelinetemplate): Fix configuration stage injection & requisiteStageRefId rendering

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/IllegalTemplateConfigurationException.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/TemplateRenderException.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConditionalStanzaTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/DefaultRenderContext.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderContext.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderUtil.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/helper/ModuleHelper.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1SchemaValidationHelper.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateSchemaValidator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/validator/Errors.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/HandlebarsRendererSpec.groovy

No functionality change here, just working on providing better context when errors occur in the handlebars templates.

refactor(pipelinetemplate): Improving error output of handlebars rendering

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java

fix(pipelinetemplate): Default spring condition if prop is unset

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/RollingPushStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/CleanUpTagsTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/RollingPushStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/CleanUpTagsTaskSpec.groovy

- Deleting tags using the imageId to filter tags containing a non matching imageId

fix(tagging): Cleaning up tags on Rolling Push

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java

Undefined "strategy" can't be cast to `boolean`.

fix(core): Remove unsafe bool cast

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonServerGroupCreator.groovy

if propertyfiles have a imageName, this will also be used to resolve titus image names

feat(titus): resolve imageName from property files

---

orca-web/orca-web.gradle

chore(fiat): Bump Fiat API to start using UserPermission cache

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/JenkinsStage.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/TravisStage.groovy

Adds support for a new Travis stage. It reuses the Jenkins api towards Igor.

feat(travis stage): Add explicit Travis stage

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java

Adding a group & example property for template variables, which will be used for UI organizational purposes only.
Also an unrelated comment marking a potential debug quality of life update discovered today.

feat(pipelinetemplate): Adding group to template variables

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy

Started creating some templates where stage names and comments needed rendering.

fix(pipelinetemplate): Render stage name and comments

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStageData.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/AbstractClusterWideClouddriverTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DisableClusterTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ScaleDownClusterTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy

This only supports an incremental rollout without any attention paid to autoscaling or calling out to custom strategies.

feat(rrb) Bare bones RRB support

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/CaptureSourceServerGroupCapacityTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroup.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/OortHelper.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/SourceResolver.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/TargetReferenceConfiguration.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/TargetReferenceSupport.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/CaptureSourceServerGroupCapacityTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/TargetReferenceConfigurationSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/DetermineTerminationCandidatesTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/WaitForNewInstanceLaunchTaskSpec.groovy
orca-smoke-test/src/integrationTest/groovy/com/netflix/spinnaker/orca/smoke/gce/OrcaSmokeGoogleSpec.groovy

depends on https://github.com/spinnaker/clouddriver/pull/1268

send cloudProvider to Clouddriver instead of providerType

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy

The whitelist used to allow subtypes of the specified types this changes to an
explicit list of allowed types.

fix(expressions) - fix allowed class whitelisting.

---

orca-pipelinetemplate/README.md
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java

fix(dcd): fixes NPE if template does not have variables

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle

I missed these while removing the handlebars functionality.

chore(pipelinetemplate): Removing unused handlebar gradle deps

---

build.gradle
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy

picks up latest frigga with updated naming support incluing ~ in details

chore(dependencies): update to latest spinnaker-dependencies

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy

The apparently innocuous change to eliminate starting a separate thread just to immediately join it was actually not so innocuous.
This reverts to the previous state (aside from the Runnable -> Callable change requred from updated kork)

fix(pipelines) - revert change that removed dependent pipelines from a dedicated thread

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Orchestration.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Pipeline.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/restart/PipelineRecoveryListener.groovy

implement equals and hashCode on Execution and Stage to avoid circularity, add v1 execution engine enum for compatibility with historical executions

fix a couple of issues spotted in initial testing of nü orca

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateConfiguration.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy

fix(pipelinetemplate): Do not default execution engine of templated pipelines

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueProcessor.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueProcessorSpec.kt

there's a common handler for error messages and `QueueProcessor` was failing to find handlers for sub-types.

fix(queue): handle sub-classes of message types

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/zombie/ZombiePipelineCleanupAgent.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/QueueConfiguration.kt
orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandler.groovy
orca-retrofit/src/test/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/RetrofitExceptionHandlerSpec.groovy
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/config/SpringBatchConfiguration.java

1. Prevent the zombie pipeline agent from killing v3 pipelines
2. Fix intermittent connectivity issue with Bakery
3. Prevent v2 pipelines queuing because there's only one thread available to run them.

ongoing nü orca fixes

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisExecutionLogRepository.kt

It turns out that `use` is more than just a scope function.

fix(queue): stop leaking all the redis connections

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy

In nü-orca when a synthetic stage is added it writes the stage id to an index, then writes the stage's fields to the execution hash. Unfortunately it's possible for another thread / orca instance to try to read the pipeline at the same time and it might get the new stage id from the index but then find nothing in the execution hash causing NPE when deserializing the stage status. 
This appears to be the cause of some parallel stages failing to start.
This PR adds some transactions to the operations in `JedisExecutionRepository`. It should mean that at least any modifications to the stage index and the pipeline data are treated atomically.

enhancement(core): add some transactional behavior to ExecutionRepository

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy

This avoids a potential dirty read when concurrently adding stages to the pipeline. It was possible previously to get a stage id from the stage index key without having read the stage data in the pipeline hash, deserialization would then fail.

fix(queue): transactionally read pipeline data

---

gradle/spek.gradle
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisExecutionLogConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisExecutionLogRepository.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueSpec.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/QueueConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/log/ExecutionLogListener.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/log/ExecutionLogRepository.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/discovery/DiscoveryActivatedSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/MessageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueProcessorSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ConfigurationErrorHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/PauseStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/PauseTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeExecutionHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/memory/InMemoryQueueSpec.kt
orca-test/src/main/groovy/com/netflix/spinnaker/orca/test/redis/EmbeddedRedisConfiguration.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](http://www.spinnaker.io/docs/contributing-to-spinnaker).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a …

some tidy up including preventing spring tests leaking redis connections

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/SpringIntegrationTest.kt

fix(queue): don't recursively add infinite execution windows

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

feat(pipeline): endpoint for evaluating pipeline expressions

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy

feat(SPEL): new base64 encode and decode methods

New base64 encode and decode methods

---

gradle/spek.gradle
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/MessageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueProcessorSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/SpringIntegrationTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ConfigurationErrorHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/DeadMessageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/PauseStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/PauseTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeExecutionHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ResumeTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandlerSpec.kt

@duftler this will fix the problem you reported with `SpringIntegrationTest` not running with Gradle.

A couple of test run fixes

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGeneratorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransformSpec.groovy

- Before and After injections now support a list of target stage Ids

feat(pipelinetemplate): Add support for list injection for Before and After stanzas

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy

We're seeing periodic 504s from some endpoints when making a webhook call. This naively retries on any exception.
@jervi or @spinnaker/reviewers any concerns with this?

fix(webhook): retry webhook creation on exception

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateConfiguration.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy

fix(pipelinetemplate): Remove unused ID property from config schema

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy

Kind of a major oversight until now, the plan functionality required template owners to publish their changes before actually performing plans on them. This will allow us to pass templates in the plan request.
@ajordens @jeyrschabu PTAL

feat(pipelinetemplate): Support inline templates during plan ops

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/memory/InMemoryQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/MonitorableQueue.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/ExecutionLatch.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/SpringIntegrationTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/metrics/MonitorableQueueSpec.kt

Gauge metrics for orphaned messages and ready messages

Additional queue metrics

---

AUTHORS
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/dcos/DcosContainerFinder.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/dcos/DcosJobRunner.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/dcos/DcosServerGroupCreator.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/dcos/README.md
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTaskSpec.groovy

Adds support for DC/OS pipeline stages to create server groups, run jobs, and find containers.

feat(provider/dcos): Add support for DC/OS pipelines

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplateMerge.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java

Also making unquestionably the most helpful error even more helpful.

fix(pipelinetemplate): Include partials in template merge ops

---

orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/config/PreconfiguredWebhookProperties.groovy
orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStage.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/config/PreconfiguredWebhookSpec.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/pipeline/PreconfiguredWebhookStageSpec.groovy

bug fix for https://github.com/spinnaker/spinnaker/issues/1738

fix(preconfigured webhooks):  support headers and statusURLResolution 

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java

- Added a fixed retry logic in fromUrl

fix(expressions): retry within fromUrl expression helper

---

orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/DeleteApplicationTask.groovy
orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/VerifyApplicationHasNoDependenciesTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AbstractWaitForAppEngineServerGroupStopStartTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/BulkWaitForDestroyedServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForDestroyedServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java

If a RetrofitError is a network problem rather than an HTTP condition the response is null.

fix(clouddriver): NPE safe some HTTP error condition checks

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java

- Added a handler for IOException
- throwing an exception when a request isn't retryable

chore(expressions): retry within fromUrl expression helper on network errors as well

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java

- Handling 200 - 299 response code in fromUrl

fix(expressions): should not throw an exception if request was successful

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisRateLimitBackend.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/TrafficShapingQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/interceptor/ApplicationRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/interceptor/GlobalRateLimitQueueInterceptor.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/interceptor/ApplicationRateLimitQueueInterceptorSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/interceptor/GlobalRateLimitQueueInterceptorSpec.kt

chore(queue): Normalizing traffic shaping metrics

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessor.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/generator/ExecutionGenerator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGeneratorSpec.groovy

Works with this config
```
{
"appConfig": {},
"config": {
"pipeline": {
"application": "gardtesting",
"name": "Pipeline as code to dev deploy",
"template": {
"source": "http://{{trigger.properties.pipeline_template}}"
},
"variables": {}
},
"schema": "1"
},
"executionEngine": "v2",
"isNew": true,
"keepWaitingPipelines": false,
"lastModifiedBy": "gard.rimestad@schibsted.com",
"limitConcurrent": true,
"parallel": true,
"stages": [],
"triggers": [
{
"enabled": true,
"job": "gard-rimestad/pac-testing/master",
"master": "travis-schibsted",
"propertyFile": "dummy",
"type": "travis"
}
],
"type": "templatedPipeline",
"updateTs": "1497954271000"
}
```
execution data:
```
{
"appConfig": {},
"application": "gardtesting",
"authentication": {
"allowedAccounts": [
"infra-dev"
],
"user": …
```

feat(pipelinetemplate) make pipelineConfigId optional

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/JesqueConfiguration.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaPersistenceConfiguration.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/RedisConfiguration.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/migrations/MultiRedisOrchestrationMigrationNotificationAgent.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/migrations/MultiRedisPipelineMigrationNotificationAgent.groovy
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueConfiguration.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueIntegrationTest.kt
orca-spring-batch/src/main/groovy/com/netflix/spinnaker/orca/batch/SpringBatchActiveExecutionTracker.java

adds a dedicated pool for v3 queue processing to differentiate pool usage between queue and execution repository

feat(redis/metrics): adds metrics for redis connection pools.

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisTrafficShapingConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisPriorityCapacityRepository.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/TrafficShapingConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/capacity/PriorityCapacityListener.kt

(facepalm). Also optimization on the listener itself.

fix(queue): Correctly wire up priority capacity listener

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/GlobalRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/PriorityCapacityQueueInterceptor.kt

chore(queue): Adding application tag to time all interceptor metrics where possible

---

.gitignore
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy

* add build info to pipeline execution.
* currently only adds prior/current build if there are commit diffs

feat(aws/commits): add build info to execution

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTag.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/filters/FriggaFilterSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTagSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTagSpec.groovy

- Added support for resolving a pipeline by name and application

feat(pipelinetemplate): Adds ability to resolve a pipeline id by application and pipeline name

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/tasks/CreatePipelineTemplateTask.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/tasks/SavePipelineTemplateTask.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/tasks/UpdatePipelineTemplateTask.java

fix(pipelinetemplate): Require name and description metadata

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/ApplicationRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/GlobalRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/PriorityCapacityQueueInterceptor.kt

FYI @spinnaker/netflix-reviewers I went a little overboard. We really only need the metrics, not logs in learning mode.

chore(queue): Removing some noisy log messages

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java

fix(pipeline_templates): don't fail if config variables are null

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/config/QueueConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueExecutor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueProcessor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/ThreadPoolQueueExecutor.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/QueueProcessorSpec.kt

do not merge: I've not actually tried this out other than the QueueIntegrationTest

fix(queue): don't pull messages from the queue when no threads available

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/filters/FriggaFilterSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTagSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTagSpec.groovy

- renderer takes a list of tags that it registers

chore(pipelinetemplate): Refactor renderer to take a list of tags

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgent.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgentSpec.groovy

fix(core): Old pipeline cleanup correctly handling null startTime

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/pipeline/DeletePipelineTemplateStage.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/tasks/DeletePipelineTemplateTask.java

feat(pipeline_templates): delete template operation

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerSpec.kt

Some tasks (e.g. monitor Jenkins) may return CANCELED if the external process was canceled. This was not catered for in RunTaskHandler.

fix(queue) handle tasks that return CANCELED

---

build.gradle
orca-core/orca-core.gradle
orca-front50/orca-front50.gradle
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueSpec.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/memory/InMemoryQueueSpec.kt
orca-web/orca-web.gradle
orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/web/config/WebConfiguration.groovy

Merging into `boot-upgrade` branch

chore(springBoot): Upgrade to Spring Boot 1.5.4

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

We had an exception class for this that was not being used for some reason.

attach error to stage context if it times out

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/OrchestrationLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy

This no longer gets used anywhere (that I can see).

chore(queue) remove appConfig field from executions

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy

fix inverted logic for rolling push check by percentage

fix(core) - fix condition in rolling push check

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/WaitForClusterDisableTask.groovy

seeing some issues wrt rolling red back, reverting

fix(core) - reverting rolling push condition

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

* update task timeout message to include metrics used for timeout
calculation.

chore(queue): update timeout message

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/filters/Base64Filter.java

```yaml
myEncodedbase64Value: "{{ myPlaintextVar|base64 }}"
```

feat(pipeline_template): Add base64 jinja filter

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingPushStrategy.groovy

fix(rollingpush): provide better error message when source not found

---

build.gradle
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/OrchestrationLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/PipelineLauncher.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Execution.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

Depends on https://github.com/spinnaker/kork/pull/90, https://github.com/spinnaker/gate/pull/439

feat(execution): Add origin field to executions

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueue.kt

I'll followup in a separate PR with some better error condition logging / handling, I'd like to grab the message by the hash and log that out as well so we can have better insight / capability to recover from actual collisions. I'd really like to find a strategy to just handle it and not require manual intervention.
@spinnaker/netflix-reviewers FYI

fix(queue): Increase hashing bits to decrease message collisions

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

fix(queue): Inherit timeout value from top-level stage

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy

- Added a new field root_volume_size to the bake request

chore(bake): Add root volume size to the request body

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy

- root_volume_size should be ignored if null

fix(bake): root_volume_size should be ignored if null

---

gradle.properties
gradle/kotlin.gradle
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/MonitorableQueue.kt

Compilation workaround https://youtrack.jetbrains.com/issue/KT-19723

chore(orca) bump kotlin to 1.1.4

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolver.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolverSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt

Will now retry for 10 minutes with a 15s delay between attempts.
Improved logging in `TargetServerGroupResolver` in the event that retries
are exhausted. The exception will be included which should better allow
for the caller to be identified.

tweak(queue): Add a few more attempts when a stage fails to plan

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionEvaluationSummary.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionEvaluator.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupport.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/SpelHelperFunctionException.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/FilteredMethodResolver.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/FilteredPropertyAccessor.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/InstantiationTypeRestrictor.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/MapPropertyAccessor.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/ReturnTypeRestrictor.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/WhitelistTypeLocator.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/ExpressionPreconditionTask.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/HttpClientUtils.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/v2/ContextParameterProcessorSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt

- Extracted expressions evaluation to new package
- Exposing expression failures via a detailed summary
- Added support for flagging a pipeline to be processed with v2

feat(pipelineexpressions): Adding a v2 expressions evaluator

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGeneratorSpec.groovy

fix(pipeline_templates): notification inheritance

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/YamlRenderedValueConverter.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

fix(pipeline_template): Plan serialization & empty string rendering

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/DeployCanaryStage.groovy

Fixes a regression introduced in https://github.com/spinnaker/orca/commit/5555874a51540854749bc5d74f7ec14f219b7a69

fix(canary): fix Orchestration constructor in DeployCanary stage

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/tasks/MonitorCanaryTask.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/tasks/MonitorCanaryTaskSpec.groovy

If a canary is configured to run for 48 hours or more, it won't without a manually-configured timeout. 
Addressing this by setting the timeout for the monitor stage in its context, adding a 15-minute buffer to deal with extra time spent sleeping and waiting.
@robfletcher or @cfieber PTAL

fix(canary): add timeout buffer for canaries > 48 hours

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/FilteredMethodResolver.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/whitelisting/FilteredPropertyAccessor.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy

- Adding an option to configure the SPEL evaluator version
- Added missing copyright header to some classes

feat(expressions): Allowing to globally configure SPEL evaluator version

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupEntityTagGenerator.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupMetadataTagTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/SpinnakerMetadataServerGroupTagGenerator.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupMetadataTagTaskSpec.groovy

Minor refactor of the server group tagging task, making it pluggable.
@ajordens or other @spinnaker/reviewers PTAL

refactor(tagging): make server group tagging task pluggable

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/exceptions/ExceptionHandler.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionEvaluationSummary.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupport.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/v2/ContextParameterProcessorSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

- Merging general exception errors with expression errors when stage completes
- This allows to automatically show all expressions failures in UI
- Including field containing failed expression in error description
- Updated error messaging verbiage

feat(expressions): Including expressions errors to show in UI

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutator.java

Rather than failing hard on a template that cannot be resolved, log an error and proceed as if the template is dynamic.

fix(pipeline_template): Catch template load errors on pipeline save

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/ResourceSchemeLoader.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaIntegrationSpec.groovy
orca-pipelinetemplate/src/test/resources/integration/v1schema/inheritance-child.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/inheritance-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/inheritance-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/inheritance-root.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/simple-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/simple-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/simple-template.yml

I've wanted an integration test suite for pipeline templates for awhile now. Just getting around to it. As far as actual tests go, there's not a whole lot here, but I plan to make subsequent PRs filling in additional bits. My intention here is to eventually cover the entirety of the spec.
@emjburns @danielpeach FYI

test(pipeline_template): Adding integration test suite

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluatorSpec.groovy

- Refactored to allow version override at pipeline level

chore(expressions): Allow to override global spel version at pipeline level

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/ConfigStageInjectionTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/TemplateModule.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRenderer.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTag.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaIntegrationSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTagSpec.groovy
orca-pipelinetemplate/src/test/resources/integration/v1schema/conditionalStage-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/conditionalStage-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/conditionalStage-template.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/modules-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/modules-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/modules-template.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/partials-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/partials-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/partials-template.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/partialsAndModules-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/partialsAndModules-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/partialsAndModules-template.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/stageInjection-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/stageInjection-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/stageInjection-template.yml

fix(pipeline_template): Multiple fixes from integration suite

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/migrations/MultiRedisOrchestrationMigrationNotificationAgent.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/migrations/MultiRedisPipelineMigrationNotificationAgent.groovy

Log if there are still incomplete orchestrations or pipelines while running a MultiRedisMigration

feat(redis_migration): log pending tasks

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStage.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeStageSpec.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/CheckPreconditionsStage.groovy

The `deploymentDetails` field in the stage output was not created properly because #1597 changed the stage types for the parallel stages.  This reverts the names of the parallel stages to the basic name (without `.parallel`)
The `Parallel` static Stage Def classes are removed in favor of inline conditionals

fix(stages/bakery): Fix bake stage, ensure deploymentDetails is added to context

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransform.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/resources/templates/conditional-partials.yml

Renders the partials' stage config before rendering partials, to allow for more advanced jinja expressions in the partials.

feat(pipeline_template): Jinja rendering in partials

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequest.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequestSpec.groovy

fix(pipeline_template): Regression in deserializing tempalted pipeline requests

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePreprocessor.kt
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/handler/PipelineTemplateContext.kt
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/handler/PipelineTemplateErrorHandler.kt

fix(pipeline_template): Do not store state in error handler lol

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/RollbackServerGroupStage.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/RollbackServerGroupStageSpec.groovy

Allow rollbacks to proceed when < 100% of instances in the rollback asg report healthy.

fix(rollbacks): support for tolerating some instance failures

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

fix(web): Return correct num executions with dual redis

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java

spinnaker/spinnaker#1902
spinnaker/spinnaker#1996

feat(core): Deploy manifest stage & task

---

build.gradle
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AppEngineServerGroupCreator.groovy
orca-core/orca-core.gradle
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

In addition, adds artifact resolution to the GAE server group creator. This change should be backwards-compatible.
@ rz and fletch: I couldn't figure out the StageContext issues, so we went with reading the trigger for a first rough cut of this feature.

feat(pipeline): Resolve received and expected artifacts in trigger.

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/ExpressionPreconditionTask.groovy

- ensure evaluation errors are included in precondition

fix(expressions): Include evaluation summary in precondition in v2

---

orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePreprocessor.kt
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequest.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandler.kt
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandlerSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/validator/V1TemplateConfigurationSchemaValidatorSpec.groovy

As part of the kotlin refactor, Spek introduced junit5, which disables the test task. This happily allowed some tests to regress. ಠ_ಠ (╯°□°）╯︵ ┻┻

fix(pipeline_template): Fixing regression in test harness

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/AbstractBulkServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/BulkWaitForDestroyedServerGroupTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForDestroyedServerGroupTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/MonikerHelper.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/BulkDestroyServerGroupTaskSpec.groovy

Use monikers in server group tasks if available. If not available, fall back on frigga.

feat(moniker): Use monikers within server-group tasks

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeleteManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeleteManifestTask.java

core(manifest): Delete manifest op

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RedBlackStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/StageData.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupport.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupportSpec.groovy

Coordinates for both the new and old server groups are passed along as
pipeline parameters.

feat(rrb): Support for running a pipeline between scale up and disable

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy

First try to use a moniker, then fallback on the application name, then fallback on frigga.
There will be a Deck change to add the moniker to the stage JSON.

feat(moniker): Use moniker for Job stages.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/MonikerHelper.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTaskSpec.groovy

fix(moniker): Properly cast Moniker from stage context

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/SpinnakerMetadataServerGroupTagGenerator.java

Subsequent PR will make this work properly for Titus.

fix(entitytags): Do not fetch previous server group for Titus

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/RestrictExecutionDuringTimeWindow.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/tasks/WaitTask.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/ManualJudgmentStage.groovy

Account for pausing in time calculation.
@robfletcher @robzienert PTAL

fix(polling): update time left calculation

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/cleanup/FastPropertyCleanupListener.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/PropertyChangeCleanupSpec.groovy

Instead of relying on the global context, we should look at the stages themselves to see if they're marked for rollback - and also only roll back property stages that are marked for rollback.
I have a mental todo to move the fast property stages into our internal repository, just... not tonight.

fix(fastproperties): always clean up properties marked for rollback

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy

We occasionally see the `getFileContents` call return nothing when a file should be there. We believe there's a race condition, where the file is being queried before the job runner has uploaded it.
@tomaslin PTAL

fix(runJob): retry fetching property files if not found

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/cleanup/FastPropertyCleanupListener.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/PropertyChangeCleanupSpec.groovy

* better logging when properties are not cleaned up
* fix timestamp comparison

fix(mahe): fix property extraction on cleanup

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/AlertOnAccessMap.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/StageContext.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/v2/ContextParameterProcessorSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt
orca-test/src/main/groovy/com/netflix/spinnaker/orca/test/model/ExecutionBuilder.groovy

Ensure a deploy stage is getting deployment details from its ancestor and not from global context.

fix(deploy): avoid crossing the streams in parallelized deploys

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy

(internal Netflix only code path)

fix(mahe): send correct query to determine if fast property exists

---

orca-mahe/src/main/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTask.groovy
orca-mahe/src/test/groovy/com/netflix/spinnaker/orca/mahe/tasks/CreatePropertiesTaskSpec.groovy

- Explicitly processing expressions in property stage override

fix(fastproperties): Processing expressions in property override

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/Manifest.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableTask.java

spinnaker/spinnaker#1902
spinnaker/spinnaker#2018

feat(core): Wait for manifest stable task

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/AlertOnAccessMap.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/StageContext.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/v2/ContextParameterProcessorSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt
orca-test/src/main/groovy/com/netflix/spinnaker/orca/test/model/ExecutionBuilder.groovy

This reverts commit f49653055f614cb38110e4e7924cedf923f0fdb5.

Revert "fix(deploy): avoid crossing the streams in parallelized deploys"

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/pipeline/UpdatePipelineTemplateStage.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/pipeline/UpdatePipelineTemplateStageSpec.groovy

Derp. If someone removes inheritance from a pipeline, it won't be re-saved.
@emjburns

fix(pipeline_template): Resave all pipelines on template update

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeleteManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeleteManifestForceCacheRefreshTask.java

We were using 1. the wrong cache refresh type, and 2. waiting on task results that would never appear

fix(manifest): Fix delete behavior

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

fix(web): Make trigger map mutable

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

gradle 3.5
spinnaker-gradle-plugin 3.17.0
spinnaker-dependencies 0.122.0

chore(dependencies): dependency updates

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy

Adding a retry to prevent failure on network error between services.

fix(job): retry on call to clouddriver for job status

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupport.java
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy

- added helper function for deployedServerGroups
- allows specifying an optional name/id for the stage to filter on
- added alias to deployedServerGroups

feat(expressions): deployed server groups helper functions & misc fixes

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupport.java

- make deployedServerGroups null safe

fix(expressions): Fixing NPE on deployedServerGroups

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy

- explicitly processing expressions in notification content

fix(expressions): process notification content

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy

- processing the notification content

fix(expressions): Fixing spel in notifications

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeleteManifestTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/GenericUpdateManifestTask.java

https://github.com/spinnaker/clouddriver/pull/2222

fix(manifests): s/name/manifestName

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/handler/V1TemplateLoaderHandler.kt

These changes were lost somehow: https://github.com/spinnaker/orca/pull/1596

fix(mpt): allow default values to be templated from other variables

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTaskSpec.groovy

We have seen a few cases where no properties were returned by
igor even the CI tool (Travis in our case) printed the magic json
search string in logs.
Somehow related to https://github.com/spinnaker/orca/pull/1721

fix(runJob): retry fetching property files from CI if not found

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java

https://github.com/spinnaker/deck/pull/4627
https://github.com/spinnaker/spinnaker/issues/2225

feat(provider/kubernetes): deploy both optional & required artifacts

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PromoteManifestKatoOutputsTask.java

https://github.com/spinnaker/spinnaker/issues/2225

fix(provider/kubernetes): promote context as well as output

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.groovy
orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupport.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionsSupportSpec.groovy

Small helper function for possible non-existent stages -- helps out use cases with parametric/optional stages.

feat(spel): Add stageExists helper function.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsServerGroupCreator.groovy

feat(provider/ecs): Added EcsServerGroupCreator
@cfieber @ajordens @robzienert @dkirillov

feat(provider/ecs): Added EcsServerGroupCreator

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsImageFinder.java

feat(provider/ecs): Added EcsImageFinder
@cfieber @ajordens @robzienert @dkirillov

feat(provider/ecs): Added EcsImageFinder

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java

https://github.com/spinnaker/spinnaker/issues/2235

feat(kubernetes): Evaluate spel in remote manifests

---

gradle.properties
orca-core/src/main/groovy/com/netflix/spinnaker/orca/telemetry/ThreadPoolMetricsPostProcessor.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/QueueConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/stages.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt

See individual commits for details

Fixes for Orca stability

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisActiveExecutionsMonitor.kt

This PR also fixes the guage creation such that metrics on total number
of active pipelines and orchestrations are correctly reported.

fix(queue): Move `RedisActiveExecutionsMonitor` off @Scheduler thread

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisActiveExecutionsMonitor.kt

Minor log message tweak to reflect what is actually being happening.

fix(queue): s/Registering/Refreshing

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/appengine/AppEngineServerGroupCreator.groovy

Move logic surrounding resolution of artifacts in appengine deploys into clouddriver.

refactor(appengine): Reduce artifact resolve code

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTaskSpec.groovy

Pipelines that had been manually sorted in deck would become out of order when roer was used to save over them.  This happened because any existing index property on the saved pipeline was wiped out by the incoming roer pipeline.
This PR checks whether a new pipeline matches application and ID with an existing pipeline and then, if so, copies the existing pipeline's index into the new pipeline so that ordering is maintained.

fix(front50): save with existing pipeline index

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingRedBlackStrategy.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/StageData.groovy

Previously predefined pipeline parameters were not passed down to the
validation pipeline.

fix(rrb): Include pipeline parameters when invoking validation pipeline

---

orca-loadtest/src/main/resources/request-bodies/wait.json
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/TemplatedPipelineRequestSpec.groovy
orca-pipelinetemplate/src/test/resources/convertedPipelineTemplateSource.json
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

In the spirit of crufty crusties...

chore(*): Cleanup appConfig cruft

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/spek/should.kt

If RestartStage is called on a synthetic stage, actually restart its parent.

fix(queue): synthetic stages aren't restartable

---

orca-core/src/main/groovy/com/netflix/spinnaker/orca/pipeline/model/Stage.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/StageSpec.groovy

This addresses an issue where a resize operation does not correctly
restore the aws scaling processes that were manipulated by a sibling
`STAGE_BEFORE` stage.
This was previously not an issue due to the global context.

fix(core): ancestors() of a synthetic stage should include `STAGE_BEFORE` siblings

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/exceptions/TemplateRenderException.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/loader/HttpTemplateSchemeLoader.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/NamedHashMap.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/PipelineTemplate.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/model/StageDefinition.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/RenderUtil.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/filters/Base64Filter.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTag.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/PipelineIdTag.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/StrategyIdTag.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/validator/Errors.java

Fix compilation warnings reported by the Error Prone static analysis tool.

Fix warnings

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/QueueProcessor.kt

Orca doesn't do nearly enough work to warrant such a low default, even at high load.

chore(queue): Increase work queue poll interval

---

orca-core/orca-core.gradle
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PubSubTrigger.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/StageContext.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Trigger.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy
orca-test/src/main/groovy/com/netflix/spinnaker/orca/test/model/ExecutionBuilder.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

Also added some tests to protect against future refactors

fix(artifacts): fix bind behavior

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java

chore(expressions): fix javadoc

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

fix(pipeline/validate): throw pipeline error _after_ recording failure

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java

Fix assumptions made that were broke by #1892.

fix(spel): Fix assumptions made that were broke by #1892.

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy

We've been storing this `stageDetails` object in the context of every stage for a long time but we don't actually need it for anything. We don't send that data to Echo and it's all completely redundant.

chore(echo): Stop storing redundant information with each stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java

https://github.com/spinnaker/spinnaker/issues/2304

feat(provider/kubernetes): support multiple docs in one artifact

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/AbstractRedisExecutionRepository.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepository.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy

- fix bugs that could break pipelines running via previousRedis during a migration
- add related test coverage, fix test issues if running with compile time @Nonnull checks (intellij)

fix(persistence): fix bugs when running w/previousRedis

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

When a pipeline is triggered by another pipeline, allow the
second pipeline to see any artifacts that were emitted by
the first pipeline.

feat(artifacts) Artifact passing in pipelines

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueue.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/migration/KeikoMessageDeserializer.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/migration/KeikoMessageDeserializerTest.kt

This is how I should've written the migrators for 6.x 🤦‍♂️

feat(queue): Keiko to 5.x message migrators

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy

Pipelines that don't declare "expected artifacts" still need to be able to pass artifacts into their triggers
@ezimanyi PTAL

fix(artifacts): fix passing of pipeline artifacts

---

orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/JenkinsTrigger.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy

closes: https://github.com/spinnaker/spinnaker/issues/2321

fix(trigger/jenkins): add support for display path

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/JenkinsTrigger.java

fix(jenkins): ignore full display name in trigger

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/MortService.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/MortServiceSpec.groovy

 fix(clouddriver/kubernetes) - Handle complex security group descriptions

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesContainerFinder.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/DockerTrigger.java

fix(trigger/docker) - Fixes class based triggers from maps for Docker

fix(trigger/docker) - Fixes class based triggers from maps for Docker

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/RunJobStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/artifacts/BindProducedArtifactsTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/artifacts/FindArtifactFromExecutionTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PromoteManifestKatoOutputsTask.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy

https://github.com/spinnaker/spinnaker/issues/2339
@ezimanyi PTAL

feat(artifacts): allow stages to 'produce artifacts'

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.java

only remove 'name' if it exists

fix(stage): npe no longer thrown when stage name is not present

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.java

fix(stage): npe no longer thrown when stage name is not present (#1999)

---

build.gradle
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/artifacts/FindArtifactFromExecutionTask.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java

fix(artifacts): fix unconverted artifacts on triggers (#2001)

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy

fix(notifications): sending required fields to echo (#2007)

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/dynomite/DynomiteExecutionRepository.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/AbstractRedisExecutionRepository.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisPipelineStack.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy

- this PR excludes dynomite configurate classes (to use classes recently added to kork after RedisClientDelegate use is refactored)
- DynomiteExecutionRepositorySpec is pending an upcoming DynomiteClient release that is compatible with EmbeddedRedis.

feat(persistence): Dynomite ExecutionRepository

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForRequiredInstancesDownTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForRequiredInstancesDownTaskSpec.groovy

If `clouddriver` returns a specific set of instance ids that have been
disabled as part of a percentage-based disable (it will for aws!),
`orca` only needs to wait until these instances have been disabled.
This short circuits a recalculation that may be out of date if
autoscaling has occurred in the background.

feat(clouddriver): Improved support for partially disabling a server group

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy

This appears to have been broken when the global context was removed.

fix(core): Correctly handle artifact matching with multiple packages

---

gradle.properties
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/ThreadPoolQueueExecutor.kt
orca-web/config/orca.yml

Depends on https://github.com/spinnaker/keiko/pull/22

feat(queue): Fill executor every poll cycle

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/instance/AbstractInstancesCheckTask.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/RetryableTask.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/WaitTask.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/WaitTaskSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt

- refactor WaitTask to no longer busy poll during the wait period

feat(core) expose stage to getDynamicBackoffPeriod

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Forgot to make the same change for orchestrations on last PR.

fix(API): don't allow running tasks to be deleted

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Run Jobs that generate a large amount of log output can dramatically slow down loading of the pipeline executions screen in deck.
This PR introduces an `expand` query param to the execution history API endpoint.  When `false` the log output under jobStatus in both the context and outputs will be stripped.  The param defaults to true to maintain backwards compatibility.

feat(core): strip logs from runjob executions and add expand param to executions history

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt

This is the same PR as https://github.com/spinnaker/orca/pull/2019 but for the branch `release-1.6.x`.

fix(spel): Revert "fix(spel): Operate on evaluated stage in handlers. (#1972)"

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy

This counter metric will be incremented whenever a stored execution
cannot be deserialized. This is an indicator of backwards incompatible
execution schema changes.

feat(metric): execution deserialization errors

---

orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisOrcaQueueConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueShovelConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisTrafficShapingConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisPriorityCapacityRepository.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/RedisRateLimitBackend.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/OrcaQueueConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/TrafficShapingConfiguration.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/config/TrafficShapingProperties.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/TrafficShapingQueue.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/capacity/PrioritizationStrategy.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/capacity/PriorityCapacityListener.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/capacity/PriorityCapacityRepository.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/ApplicationRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/GlobalRateLimitQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/PriorityCapacityQueueInterceptor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/ratelimit/RateLimitBackend.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/TrafficShapingQueueTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/ApplicationRateLimitQueueInterceptorTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/GlobalRateLimitQueueInterceptorTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/trafficshaping/interceptor/PriorityCapacityQueueInterceptorTest.kt

Reverts spinnaker/orca#2098
Nothing wrong with the PR as such, just hit merge on the wrong tab!

Revert "chore(*): Remove queue traffic shaping codebase"

---

orca-core/orca-core.gradle
orca-core/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisPipelineStack.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepositoryTck.groovy

```
MORE RED. MORE RED. MORE RED. MORE RED. MORE RED.
MORE RED. MORE RED. MORE RED. MORE RED. MORE RED.
MORE RED. MORE RED. MORE RED. MORE RED. MORE RED.
MORE RED. MORE RED. MORE RED. MORE RED. MORE RED.
MORE RED. MORE RED. MORE RED. MORE RED. MORE RED.
MORE RED. MORE RED. MORE RED. MORE RED. MORE RED.
MORE RED. MORE RED. MORE RED. MORE RED. MORE RED.
MORE RED. MORE RED. MORE RED. MORE RED. RED RUM.
RED RUM.  RED RUM.  RED RUM.  RED RUM.  RED RUM.
```

chore(*): Removing Dynomite

---

gradle.properties

DLQs messages with no matching handler

chore(keiko): Upgrade Keiko

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/Manifest.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableTask.java

@wjoel PTAL
https://github.com/spinnaker/clouddriver/pull/2469

feat(provider/kubernetes): allow jobs/pods to fail

---

gradle.properties
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/messages.kt

Depends on https://github.com/spinnaker/keiko/pull/31

fix(queue): Override RunTask message ack timeout

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java

- removed unused spelEvaluator version code
- small cosmetic changes

refactor(expressions): Remove deprecated versioning code

---

build.gradle
orca-bakery/orca-bakery.gradle
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeryService.groovy
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/manifests/BakeManifestRequest.java
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/pipeline/BakeManifestStage.java
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java

feat(bake/manifest): bake manfest stage

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java

Since people write numbres as strings.

fix(stage): Allow startTimeExpiry to be a string

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/manifests/BakeManifestRequest.java
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java

https://github.com/spinnaker/rosco/pull/247

feat(bake/manifest): propagate "overrides" value

---

orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/DelegatingApplicationEventMulticaster.kt
orca-core/src/test/groovy/com/netflix/spinnaker/orca/listeners/DelegatingApplicationEventMulticasterSpec.groovy

Internal dialogue while initially writing this, "Man, it'd be bad if someone made a typo on this." 🤦‍♂️

fix(core): Fixing a typo in event listener multicaster

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/manifests/BakeManifestRequest.java
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java

https://github.com/spinnaker/spinnaker/issues/2636

feat(bake/manifest): allow multiple input artifacts

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy

Changed to OverridableTimeoutRetryableTask to allow overriding the timeout and setting a dynamic backoff period.
Retrying each second for the first minute, then every 15 seconds for the next hour. We have some users that have webhooks that take 30+ minutes to finish, and it's excessive to poll every second for that whole duration.

fix(webhook): after one minute monitor every 15s

---

orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java

fix(redis): Add JedisConfiguration to import

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/KubernetesInterestingHealthProviderNamesSupplier.java

fix(kubernetes) - fixes WaitForClusterDisable timeout for kubernetes during redblack (#2176)

---

orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java

We'll want this guy for Project SuperQualifiedLobotomy. No one will ever figure out that code name.

feat(redis): Conditional prop for RedisExecutionRepository

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java

Was sloppy in updating the UI's artifact fields, "inputArtifacts" needs to be read in orca.

fix(bake/manifest): propagate field change to orca

---

build.gradle

Necessary for integrating FPs.

chore(*): Upgrade to Boot 1.5.10

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/config/PipelineTemplateConfiguration.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/YamlRenderedValueConverter.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaIntegrationSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/JinjaRendererSpec.groovy

cherry-pick https://github.com/spinnaker/orca/pull/2193

fix(pipeline_template): Don't share snakeyaml instance across threads

---

orca-kotlin/src/main/kotlin/com/netflix/spinnaker/orca/ext/Stage.kt
orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/Stages.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/OrcaMessageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/messages.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/MessageCompatibilityTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandlerTest.kt

We don't need this feature to support any current stages and it's currently causing issues. We'll revisit as and when we have a use-case for it.

feat(core): revert support for parallel after stages

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/EchoService.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/pipeline/JiraStage.java
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/tasks/CreateJiraIssueTask.java

- simple jira stage supporting creating a jira issue

feat(jira): Adding a jira stage support

---

build.gradle
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionBufferActuator.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionPromoter.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/PromotionPolicy.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/bufferpolicy/EnqueueDeckOrchestrationsBufferPolicy.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/bufferpolicy/NaiveBufferPolicy.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/bufferstate/ActiveExecutionsBufferStateSupplier.kt
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/promotionpolicy/NaivePromotionPolicy.kt
orca-qos/src/test/kotlin/com/netflix/spinnaker/orca/qos/DefaultExecutionPromoterTest.kt
orca-qos/src/test/kotlin/com/netflix/spinnaker/orca/qos/ExecutionBufferActuatorTest.kt

A couple handfuls of refactors & fixes from post-merge conversations with various people. They're all pretty small, probably best reviewed commit-by-commit.

refactor(qos): Operational changes

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/JiraService.java
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/tasks/CreateJiraIssueTask.java

- created jiraService class containing jira creation bits

refactor(jira): Extracted jira creation into a service class

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/Manifest.java

feat(manifest): add manifest to manifest model

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTask.groovy

It's possible that a force cache refresh has not propated to a replica.
Previously, `orca` would have re-force cache refreshed the entry.
This PR will simply retry (default 10s backoff) until such time that
there is at least one recent pending force cache update available to
check against.

fix(clouddriver): Automatically retry if replica lag detected when force cache refreshing

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java

Fixes https://github.com/spinnaker/spinnaker/issues/2550

fix(provider/kubernetes): support both list formats for remote artifacts

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/JiraService.java

- making fields public
- fixed response type fields

chore(jira): Adding method to easily create request

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java

fix(provider/kubernetes): use thread local yaml parser (#2198)

---

build.gradle
orca-retrofit/orca-retrofit.gradle
orca-retrofit/src/main/groovy/com/netflix/spinnaker/orca/retrofit/RetrofitConfiguration.groovy

This reverts commit 26b508d77b1e3c8124191a2c456255e4b0cbd025.

Revert "config(okhttp3): pick up okhttp3 as retrofit client (#2218)"

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableTask.java

feat(provider/kubernetes): propagate manifest failures to UI

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

* include error details on failure
* enable helper functions (allowUnknownKeys=true)

fix(expressions): improved evaluateExpression api

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/MonitorWebhookTask.groovy

@ajordens is this formatted ok?

chore(log): adding execution id

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/RestorePinnedServerGroupsPoller.java

This mimics what the `EphemeralServerGroupsPoller` is doing.

fix(clouddriver): Support restoring pinned server groups in privileged accounts

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy

fixes https://github.com/spinnaker/spinnaker/issues/2796

fix(provider/kubernetes): fix lookup of non-namespaced manis

---

orca-redis/orca-redis.gradle

Ha-ha. Turns out code won't compile if you don't compile it.

fix(redis): Add kotlin to module

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/OrcaMessageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartExecutionHandlerTest.kt

fix(queue): Allow restart of a failed branch while pipeline is running

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessor.java

fix(pipeline/expressions): reference trigger as map, not object (#2253)

---

orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionBufferActuator.kt

This cuts the amount of logs in half on starting executions when QOS is enabled.

refactor(qos): Reduce logging noise during actuation

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.kt

I'm dumb. Should have done this already.

fix(zombies): log zombie executions

---

orca-core-tck/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/PollingAgentExecutionRepositoryTck.groovy
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java

fix(redis): Fix polling agent redis implementation

---

orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java

perf(redis): Pipeline cardinality commands in polling agents

---

orca-core-tck/src/main/groovy/com/netflix/spinnaker/orca/pipeline/persistence/PollingAgentExecutionRepositoryTck.groovy
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java

I don't know how this managed to pass the PR build, but it's definitely wrong.
Old behavior didn't accumulate cardinality counts when `type == null`.

fix(redis): Broken test with perf refactor

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsImageFinder.java

feat(provider/ecs): added support for non-ecr docker repositories
@robzienert @ajordens

feat(provider/ecs): added support for non-ecr docker repositories

---

orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java

I am not a smart man. This fixes the transient test errors that have been happening in PRs.

fix(redis): Incorrect pipelined results handling

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/artifacts/CleanupArtifactsTask.java

https://github.com/spinnaker/clouddriver/pull/2688

feat(provider/kubernetes): cleanup artifacts task

---

gradle.properties
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitorTest.kt

Necessary for continued SQL work.

feat(queue): Upgrade keiko to 2.9.0

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/PatchManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PatchManifestTask.java

Closes spinnaker/spinnaker#2786
@lwander

feat(provider/kubernetes): Add a new patch manifest stage for V2 provider

---

orca-kotlin/src/main/kotlin/com/netflix/spinnaker/orca/ext/Stage.kt
orca-queue-tck/src/main/kotlin/com/netflix/spinnaker/orca/q/Stages.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/OrcaMessageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/messages.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/MessageCompatibilityTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandlerTest.kt

Do not merge.
This reverts commit f99de659b08ae9afe3b0e0b66c88a2d578e075e8.
Was reverted because the parent stage never completed, but I haven't been able to reproduce this. Would appreciate a look over to see if there is an obvious situation that I'm not thinking of that would produce the bug.

Revert "feat(core): revert support for parallel after stages (#2194)"

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/EchoService.groovy

Add a new notification type bearychat. 
This PR is related to [spinnaker/spinnaker#2874](https://github.com/spinnaker/spinnaker/issues/2874)

feat(notification): add bearychat support

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestTask.java

fix(provider/kubernetes): fix NPE when no artifact given (#2289)

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/ExecutionRepository.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-redis/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepositorySpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

Also related:
https://github.com/spinnaker/echo/pull/277
https://github.com/spinnaker/gate/pull/560

feat(pipelines): Add endpoint to search for pipeline executions.

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/EchoService.groovy

Add a new notification type Google Chat.
This is part of the issue spinnaker/spinnaker#2936

feat(notification): Add support for Google Chat.

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/CustomTriggerDeserializerSupplier.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/support/TriggerDeserializer.kt

feat(core): Adding custom trigger deserializer capability

---

.gitignore
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/TriggerSpec.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/JenkinsStage.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/WerckerStage.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorWerckerJobStartedTask.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/pipeline/WerckerStageSpec.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorWerckerJobStartedTaskSpec.groovy

- Wercker CI as a pipeline Stage in Spinnaker
Related PRs (Wercker CI build trigger):
https://github.com/spinnaker/halyard/pull/960
https://github.com/spinnaker/igor/pull/297
https://github.com/spinnaker/deck/pull/5519
https://github.com/spinnaker/echo/pull/295
https://github.com/spinnaker/gate/pull/574
@markxnelson

feat(stage/wercker): Implemented a Wercker Pipeline Stage for triggering Wercker Builds

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/model/Manifest.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableTask.java

Corresponds to https://github.com/spinnaker/clouddriver/pull/2810

feat(kubernetes): add manifest warnings to context

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DisableInstancesInDiscoveryTask.groovy

Perform the same check as DisableInstancesTask and TerminateInstancesTask

feat(traffic guards): perform check on disableInstancesInDiscovery

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/V1SchemaExecutionGenerator.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-pipelinetemplate/src/test/resources/integration/v1schema/dependsOn-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/example-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/exampleCombined-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/inheritance-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/loops-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/modularStageConfig-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/modules-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/nestedConditionalStage-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/parameterInheritance-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/partials-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/partialsAndModules-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/simple-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/stageInjection-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/stageReplacement-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/triggerInheritance-config.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/triggerInheritance-expected.json
orca-pipelinetemplate/src/test/resources/integration/v1schema/triggerInheritance-template.yml
orca-pipelinetemplate/src/test/resources/integration/v1schema/variableParameters-expected.json

I never implemented trigger inheritance. *facepalm*

fix(pipeline_templates): Fix trigger inheritance

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTaskSpec.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/PackageInfo.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/PackageInfoSpec.groovy

If there are `artifacts` present in the trigger, and those are the requested artifacts, parse the version out of them and then submit that to the bakery. Added some tests around this.
Refactor pass #1 at `PackageInfo` to make variable names make sense. My desire is to do a refactor #2 to make this class easier to reason about and modify. Added some comments to aid others in understanding this class.

feat(bake): parse version from kork Artifacts

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/ServerGroupCacheForceRefreshTask.groovy

Partially addresses spinnaker/spinnaker#3030 and treats symptoms when clouddriver doesn't return servergroups from ondemand cache refresh which orca expects. Previously, the logic was a bit broken and orca wouldn't issue a new request in a timely manner if clouddriver lost it.
replaces spinnaker/orca#2316

fix(cache/ondemand): re-request missed server group cache refreshes

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/image/DeleteImageStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/DeleteImageTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/MonitorDeleteImageTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/DeleteImageTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/tasks/image/MonitorDeleteImageTaskSpec.groovy

feat(image): Adding a delete image stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/DeleteImageTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/MonitorDeleteImageTask.java

- do not include stage context in the task result
- adding stage context somehow causing an NPE when evaluating result

fix(deleteImage): Fixing delete image stage

---

orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionStatus.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CancelExecutionHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteExecutionHandlerTest.kt
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

This reverts commit 8a814a1d2e505a3bbe8a051667157ea2c157ab9b.

Revert "fix(cancel): consistent CANCELED event (#2398)"

---

orca-core/src/main/java/com/netflix/spinnaker/orca/locks/ExecutionCompleteLockReleasingListener.java
orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/AbstractPollingNotificationAgent.java
orca-qos/src/main/kotlin/com/netflix/spinnaker/orca/qos/ExecutionPromoter.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/metrics/AtlasQueueMonitor.kt

This change supplies scheduled agent class names to a jooq `renderEnd` execution listener so that resulting `SqlExecutionRepository` statements are annotated with the agent class, such as:
```select e.id, e.body, s.execution_id, s.body, e.status from (select `id`, `body`, `status` from orchestrations where (status IN ('BUFFERED')) order by id desc) as `e` left outer join (select `execution_id`, `body` from orchestration_stages) as `s` on (s.execution_id = e.id) -- agentClass: DefaultExecutionPromoter```

feat(agents): store class names on MDC for sql query annotation

---

orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgent.java
orca-core/src/main/java/com/netflix/spinnaker/orca/notifications/scheduling/TopApplicationExecutionCleanupPollingNotificationAgent.java

Optimized variants for sql will be forthcoming.

feat(core): Pipeline/Orchestration cleanup should only run for redis

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy

Adding bakery capability to the oracle provider.
See also https://github.com/spinnaker/halyard/pull/1011 and https://github.com/spinnaker/rosco/pull/273.

feat(bake/oracle): Added oracle OCI bakery.

---

orca-test-redis/src/main/java/com/netflix/spinnaker/orca/test/redis/EmbeddedRedisConfiguration.java

* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Stop leaking Redis processes

---

build.gradle
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueShovelConfiguration.kt
orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConfiguration.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/locks/RedisLockManager.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/notifications/RedisNotificationClusterLock.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/telemetry/RedisActiveExecutionsMonitor.kt
orca-redis/src/test/groovy/com/netflix/spinnaker/orca/locks/RedisLockManagerSpec.groovy

Depends on https://github.com/spinnaker/kork/pull/188.
Opening early to give some additional context to above PR.

fix(redis): Cleaning up kork redis client configuration

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreatorSpec.groovy

This is part of a series of commits to introduce the new CloudFoundry implementation. The existing provider code was unused.

refactor(provider/cf): initial commit for cloud foundry implementation

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/3342
Totally forgot about this; had a todo in our config and everything, my bad!

fix(spring): Disable JDBC autoconfigure

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/manifests/helm/HelmBakeManifestRequest.java
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java

issue: spinnaker/spinnaker#3108

feat(bake/manifests): use custom output artifact name in helm bakery

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servicebroker/DeleteServiceStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servicebroker/DeployServiceStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servicebroker/DeleteServiceTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servicebroker/DeployServiceTask.java

See https://github.com/spinnaker/clouddriver/pull/2965.

feat(provider/cf): pipeline stages to delete and deploy service broker services

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ManifestForceCacheRefreshTask.java

https://github.com/spinnaker/clouddriver/pull/2985

fix(provider/kubernetes): fix FCR for cluster-scoped resources w/ namespace

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/StageDefinitionBuilder.java
orca-kotlin/src/main/kotlin/com/netflix/spinnaker/orca/ext/Stage.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/SkipStageHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/SkipStageHandlerTest.kt
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

feat(core): manually skip a stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/rollingpush/CheckForRemainingTerminationsTask.groovy

fix(task): remove unused import

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DisableManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/EnableManifestStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DisableManifestTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/EnableManifestTask.java

https://github.com/spinnaker/spinnaker/issues/3470

feat(provider/kubernetes): enable/disable manifest

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

* changes log message when orchestration fails
* changes log severity to warn when orchestration fails

fix(orchestrate/failure): Log a warning message when failing orchestration

---

orca-core/src/main/java/com/netflix/spinnaker/orca/commands/ForceExecutionCancellationCommand.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/commands/ForceExecutionCancellationCommandSpec.groovy

fix(spring): Wire up force cancel command manually

---

gradle/installViaTravis.sh

Forgot this one in https://github.com/spinnaker/orca/pull/2485
@stewchen FYI
Ref: spinnaker/spinnaker#2844

chore(builds): Forgot installViaTravis script

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/v2/transform/V2ConfigStageInjectionTransform.java

fix(MPTv2): Remove unused static logger.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/service/JobService.java

so it is the same as webhook stage

refactor(jobs): clean up configuration for preconfigured run job 

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreatorSpec.groovy

Co-Authored-By: Jammy Louie <jlouie@pivotal.io>
Co-Authored-By: Stu Pollock <spollock@pivotal.io>
spinnaker/spinnaker#3656

feat(provider/cf): add clone SG action

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForRequiredInstancesDownTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/HealthHelper.groovy

fix(instrumentation): Remove temporary instrumentation.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuard.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/utils/TrafficGuardSpec.groovy

Would be helpful to know what _has_ been found when the error is "could
not find x".

chore(traffic-guards): more details in error message and log

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/DetermineSourceServerGroupTask.groovy

This should present the user with a more appropriate error message
if an authorization check fails.
Only propagates the `RetrofitError` on an HTTP 403.

fix(clouddriver): Propagate `RetrofitError` from `DetermineSourceServerGroupTask`

---

gradle.properties

Pull in https://github.com/spinnaker/keiko/pull/51

chore(dependencies): bump keiko version

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

Create a new '/plan' endpoint that allows callers to request a plan for a pipeline template. Any calls to '/orchestrate' with pipeline.plan set to true can be migrated to this endpoint, but the '/orchestrate' endpoint will continue to work.
This new endpoint has a new feature, the flag 'resolveArtifacts' that allows the caller to toggle whether to resolve artifacts when making the plan.

fix(pipelines): Allow caller to specify whether to resolve artifacts

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorJenkinsJobTask.groovy

Recently, we made igor return 404 if the properties file was not found (https://github.com/spinnaker/igor/pull/341/files). This PR updates the monitor jenkins stage to correctly error if the properties file isn't found (instead of retrying forever and ever).

fix(jenkins): handle property file not found better

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

Recently we had igor return a 404 if the properties file was not found (https://github.com/spinnaker/igor/pull/341/files). This was causing pipelines that had jenkins triggers with property files on them to fail when the properties file didn't exist. The error message for the pipeline was just `Status: TERMINAL by system — -` with a reason of "404". 
This PR fixes the error message so that it's obvious what caused the failure.

fix(pipelines): detailed error when jenkins trigger prop file not found

---

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/ExecutionMapper.kt

maybe this will catch duplicates...

fix(sql): compare executions by id not object

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListenerSpec.groovy

Application and pipeline level notifications fails for protected apps, because orca is not propagating authentication to front50. That's sad if you want both security _and_ notifications. But I'm pleased to announce that with this PR, you can have your cake AND eat it too.
Root cause is https://github.com/spinnaker/front50/pull/408 (@ajordens FYI)

fix(notifications): Propagate auth for application notifications

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/MapLoadBalancersStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/UnmapLoadBalancersStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/AbstractLoadBalancerRegistrationTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/MapLoadBalancersTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/UnmapLoadBalancersTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/AbstractLoadBalancerRegistrationTaskSpec.groovy

This change contains preparation for adding pipeline stages to Deck for mapping load balancers to  server groups, and also for unmapping load balancers from server groups.

feat(core): Map/Unmap SGs and Load Balancers

---

orca-webhook/src/main/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTask.groovy
orca-webhook/src/test/groovy/com/netflix/spinnaker/orca/webhook/tasks/CreateWebhookTaskSpec.groovy

Instead of throwing an exception, make sure to propagate task results on failed webhook calls.
Also, best effort JSON parse of the body (since it comes in as a string) for any SPeL
expressions to still work.

fix(webhooks): propogate body on failed calls

---

orca-sql-mysql/mysql-setup.sql

adding database creation to the setup script

chore(mysql): Adding database creation to the setup script

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.groovy

feat(cf): add clone SG pipeline stage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/OortService.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/CloudFoundryDeployServiceStagePreprocessor.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/CloudFoundryDestroyServiceStagePreprocessor.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servicebroker/DeployServiceStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servicebroker/DeployServiceStagePreprocessor.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servicebroker/DestroyServiceStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servicebroker/DestroyServiceStagePreprocessor.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryDeployServiceTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryDestroyServiceTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryMonitorKatoServicesTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryWaitForDeployServiceTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryWaitForDestroyServiceTask.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servicebroker/AbstractWaitForServiceTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/CloudFoundryDeployServiceStagePreprocessorTest.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/CloudFoundryDestroyServiceStagePreprocessorTest.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryDeployServiceTaskTest.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryDestroyServiceTaskTest.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryMonitorKatoServicesTaskTest.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryWaitForDeployServiceTaskTest.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryWaitForDestroyServiceTaskTest.groovy

feat(cf): Move service polling into orca

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/PatchManifestStage.java

Corresponding Deck PR: https://github.com/spinnaker/deck/pull/6632

feat(kubernetes): add dynamic target selection to Patch Manifest Stage

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt

Fixes error introduced by me in https://github.com/spinnaker/orca/pull/2653

fix(expressions): Fix ConcurrentModificationException

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java

Making way for further changes, cleaning up warnings that come from treatment of generics.

chore(artifacts): Clean up generics in ArtifactResolver

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/V2SchemaExecutionGenerator.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

This reverts commit 2f766c870a2268d8e7561cdcf62156f7d95d7d83.

fix(artifacts): Revert double artifact resolution

---

orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionContext.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/StageExpressionFunctionProvider.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/StageExpressionFunctionProviderSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/AuthenticationAware.kt

This fn provides a direct reference to the currently executing `Stage`.

feat(spel): New `currentStage()` function

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy

Artifact resolution is not currently idempotent; this causes occasional bugs where trying to resolve again causes errors due to duplicate artifacts. In order to be truly idempotent, also changed the Set instances in the resolution to LinkedHashSet so that the order of operations (and resulting artifact lists in the pipeline) are stable and deterministic.

fix(artifacts): Make artifact resolution idempotent

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/config/IgorConfiguration.groovy

Depends on https://github.com/spinnaker/igor/pull/374, please see that PR for a description.

feat(buildmasters): Permission support for build masters (CI's)

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/CIStage.java

WaitForCompletion is a Boolean, but given that the prior groovy code accepted either a String or a Boolean, being defensive and handling both.

fix(ci): Fix cast error in CIStage

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/ScriptStage.groovy

The script stage also needs to fetch properties

fix(scriptStage): add get properties task

---

orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java

The previous implementation was expensive in terms of redis memory usage and eventually would cause slowdowns of redis command processing.

fix(executions): Break up execution lookup script.

---

orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/render/tags/ModuleTagSpec.groovy

I was trying to reproduce the particular case that broke on the Jinjava upgrade.  So far I've been unsuccessful, as these tests all pass both before and after the upgrade. But it's probably worth committing the tests anyway, just to prevent other issues in the future.

test(pipelinetemplates): Add tests to ModuleTag

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ResizeStrategySupport.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ResizeStrategySupportSpec.groovy

0 was being used in the Elvis operator but it is not Groovy-truthy.
Fix that to an actual null check.

fix(unpin): bug caused us to not be able to unpin to 0

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/ConcourseTrigger.kt

The type needs to be concrete in order to be deserializable.

fix(concourse): Fix concourse build info type

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsServerGroupCreator.groovy

Enables deploying a specific Docker image, or a trigger or baked image
Fixes https://github.com/spinnaker/spinnaker/issues/3455

feat(ecs): Grab container image from trigger or context

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/ConditionAwareDeployStagePreprocessor.java
orca-core/src/main/java/com/netflix/spinnaker/orca/conditions/Condition.java
orca-core/src/main/java/com/netflix/spinnaker/orca/conditions/ConditionConfigurationProperties.java
orca-core/src/main/java/com/netflix/spinnaker/orca/conditions/ConditionSupplier.java
orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/WaitForConditionStage.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateConditionTask.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateConditionTaskSpec.groovy

- adds ability to add a synthetic wait before a deploy stage
- pauses a deployment if certain conditions are not met
- provides visibility into currently unmet conditions

feat(core): Add support for a condition aware deploy preprocessor

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/ConditionAwareDeployStagePreprocessor.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateConditionTask.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateConditionTaskSpec.groovy

- s/@ConditionalOnBean/@ConditionalOnExpression

fix(conditions): Make task conditional per config

---

orca-clouddriver/orca-clouddriver.gradle
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/KubernetesPreconfiguredJobProperties.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/PreconfiguredJobStageProperties.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/TitusPreconfiguredJobProperties.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/service/JobService.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/kubernetes/KubernetesContainerFinder.groovy

supports preconfigured run job stages for the kubernetes v2 provider. i
had to break the config into provider specific configuration to work
around serialization issues.

feat(runJob): support kubernetes jobs

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/KubernetesPreconfiguredJobProperties.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/TitusPreconfiguredJobProperties.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/service/JobService.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy

adds tests for the preconfigured job stage for upcoming groovy -> java
refactor.

fix(preconfiguredJob): add tests preconfig job

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/image/ImageTagger.java

Revert "fix(imagetagging): assert foundImage count >= upstreamImageIds count"

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/V2Util.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50Configuration.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListener.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/spring/DependentPipelineExecutionListenerSpec.groovy
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/V2PipelineTemplateController.java

The listener for pipeline triggers was not planning templated pipelines and hence not triggering on pipeline completion.

fix(MPTv2): Fix pipeline triggers for v2 templated pipelines.

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/CreateServiceKeyStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryCreateServiceKeyTask.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryCreateServiceKeyTaskTest.java

feat(cf): Create Service Key Stage

---

orca-core/src/main/java/com/netflix/spinnaker/orca/conditions/Condition.java
orca-core/src/main/java/com/netflix/spinnaker/orca/conditions/ConditionConfigurationProperties.java
orca-core/src/main/java/com/netflix/spinnaker/orca/conditions/ConfigurationBackedConditionSupplier.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/conditions/ConfigurationBackedConditionSupplierSpec.groovy

- support for config based conditions
- support for config based whitelisted clusters

feat(conditions): Adding support for config based conditions

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/EvaluateVariablesTask.java
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/ExpressionAware.kt

This is from additional PR comments on #2817

chore(expressions): Don't create new objectmapper all the time

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
orca-applications/orca-applications.gradle
orca-bakery/orca-bakery.gradle
orca-clouddriver/orca-clouddriver.gradle
orca-core/orca-core.gradle
orca-front50/orca-front50.gradle
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java
orca-igor/orca-igor.gradle
orca-pipelinetemplate/orca-pipelinetemplate.gradle
orca-queue/orca-queue.gradle
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-webhook/orca-webhook.gradle

As a prelude to consuming the BOM from Kork, I need to upgrade the Gradle version.

Upgrade to Gradle 5.0

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/JenkinsTrigger.kt

(Travis is piggybacking on the Jenkins trigger implementation in Orca)

fix(travis): Support timestamp in JenkinsBuildInfo (provided by Travis)

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/audit/ExecutionTrackingMessageHandlerPostProcessor.kt

Currently, the stageID isn't sent over when we make e.g. clouddriver calls.
This makes tracing the operation of a given stage VERY difficult.
Add stageIDs to the MDC context for propagation with HTTP headers

fix(logging): Correctly propagate stage IDs for logging

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/v2/transform/V2DefaultVariableAssignmentTransform.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/V2SchemaExecutionGenerator.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/v2/transform/V2DefaultVariableAssignmentTransformTest.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/4158.

fix(MPTv2): Restricts config var scope based on declared template vars.

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/ServiceKeyExpressionFunctionProvider.java
orca-core/src/test/java/com/netflix/spinnaker/orca/pipeline/expressions/functions/ServiceKeyExpressionFunctionProviderTest.java

feat(cf): Fetch created service key via SpEL

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

This PR offers protection if `fiat` were unavailable when attempting
to fetch preconfigured webhooks.
The current behavior results in an HTTP 500 even if there were no
restricted preconfigured webhooks.
The proposed behavior would result in the unrestricted subset being
returned with an error logged.

fix(webhooks): Avoid a nasty HTTP 500 fetching preconfigured webhooks

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/conditions/EvaluateConditionTask.java

- added more logging around pausing deploys

chore(conditions): Adding logging

---

orca-web/orca-web.gradle

Prereq for spinnaker/kork#273 merge

chore(dependencies): ensure direct dependency on kork-secrets-aws

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/conditions/EvaluateConditionTask.java

chore(conditions): Adding better log messages

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/ApplySourceServerGroupCapacityTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/CloudFoundryDeployStagePreProcessor.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/CFRollingRedBlackStrategy.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/strategy/Strategy.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/CFRollingRedBlackStrategyTest.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/CloudFoundryDeployStagePreProcessorTest.java

feat(cf): Added support for rolling red black deployments

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/conditions/EvaluateConditionTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/conditions/EvaluateConditionTaskSpec.groovy

- added a metric around deploy pauses

chore(conditions): Adding metrics around deploy pauses

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/OperationsController.groovy

fix(web): s/pipeline/config

---

build.gradle
orca-core/src/main/java/com/netflix/spinnaker/orca/events/ExecutionListenerAdapter.java
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/ExecutionLauncher.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/model/ExecutionSpec.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListener.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingExecutionListenerSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/audit/ExecutionTrackingMessageHandlerPostProcessor.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/OperationsControllerSpec.groovy

Update the headers to match https://github.com/spinnaker/kork/pull/270

refactor(headers): Update spinnaker headers

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/clone/CloudFoundryManifestArtifactDecorator.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/SourceResolver.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/StageData.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/SourceResolverSpec.groovy

feat(core): ability to resolve targeted SG on different accounts and regions

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/UpsertDisruptionBudgetStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/UpsertDisruptionBudgetTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/UpsertDisruptionBudgetTaskSpec.groovy

- Adding a stage to update `disruptionBudget` details for a `titus` jobs

feat(titus) : Adding stage to update disruption budget details

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/ConcourseService.java
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/ConcourseStageDefinition.java
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/model/ConcourseStageExecution.java
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/pipeline/ConcourseStage.java
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/WaitForConcourseJobCompletionTask.java
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/WaitForConcourseJobStartTask.java
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/ConcourseController.java

The stage flow is documented [here](https://docs.google.com/presentation/d/1bPDrPhiLnu7GX_hn5vClgLrArOijkvJibK1Kyrb5GIE/edit?usp=sharing).

feat(stages): Add Concourse stage

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy
orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/config/BakeryConfiguration.groovy
orca-bakery/src/test/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequestSpec.groovy

cherry-pick of #2926 with merge conflicts fixed

fix(bake/rosco): fix regression in snake casing of rosco specific bake properties

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/DeploymentDetailsAware.groovy

- fix bug introduced in #2960  , add the `clouddriver` check after synthetic stages are computed

fix(findImage) : Fix findImage bug introduced in #2960

---

build.gradle
orca-bom/orca-bom.gradle
settings.gradle

This simplifies dependency resolution downstream

feat(orca-bom): publish orca-bom

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryJobRunner.java

feat(cf): "Run Job" stage support for CloudFoundry

feat(cf): "Run Job" stage support for CloudFoundry

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy

With a titus preconfigured job you can override the cluster definition. If you override the cluster definition, you have to provide an application to run in. This means that all usages of the preconfigured job are in that application.
That's not ideal when you're using application based permissions. This PR allows you to optionally leave out `application` from a provided cluster override. If `application` is missing, we fill it in with the application the stage is running in.

fix(preconfiguredJob): make cluster.application optional

---

orca-web/orca-web.gradle
orca-web/src/main/groovy/com/netflix/spinnaker/orca/Main.groovy

This PR enables orca to use plugins. See https://docs.google.com/document/d/1KFDCIIC_abJMVczmcTqeb3XenNibFet5acN4bq9KD3k/edit?usp=sharing

Feat(plugins): adding ability to use plugins

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageFinder.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageFinderSpec.groovy

The image query will return a substring match on package name, which can result in an incorrect match if there are multiple packages with the same prefix (e.g. myapp and myappserver).
If there are appversion tags on the image (added by baking) then prefer using those as an indicator of the package name, and do an exact match on the appversion's package name as a filter of the image find results.
If no results pass the appversion filtering, fall back to existing behaviour

feat(aws/findImage): if present use appversion to filter results

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt

- Revert changes made in commit 465a7a43ffa439e1e3c3945e4222dd59a643e516

Revert changes made to add pipeline name header

---

orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/api/BakeRequest.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/alicloud/AliCloudSecurityGroupUpserter.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/alicloud/AliCloudServerGroupCreator.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ModifyScalingGroupStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ScalingGroupDescriptionSupport.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/ModifyScalingGroupTask.java

This PR adds a new provider "Alibaba Cloud" to supports new spinnaker/clouddriver#3852 and creating new bakery on Alibaba Cloud: spinnaker/rosco#396
In addition, I have submitted a new cloud provider proposal: spinnaker/community#15 and please check it.

feat(alibabacloud): add a new provider of alicloud

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoService.groovy

While working on idempotent cloud operations, we ran into an odd bug where the same operation was being processed twice but not being correlated to each other. It came down to the fact that each `requestOperation` creates its own UUID, rather than something more deterministic.
We want deterministic clientRequestIds for cloud operations because tasks & stages can be re-driven. Rather than restarting an operation from the beginning (which could be undesirable, like creating multiple server groups), we want to consistently signal that a particular operation is the same.

fix(clouddriver): Deterministic request IDs for cloud operations

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/KatoService.groovy
orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionContext.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/functions/StageExpressionFunctionProviderSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/AuthenticationAware.kt

Finishing what I started here: https://github.com/spinnaker/orca/pull/3077
Oopsies.

fix(clouddriver): Add stage information to KatoService request id

---

orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/model/V2PipelineTemplate.java

https://github.com/spinnaker/spinnaker/issues/4755

fix(core): Handle validation of templates with no defined stages

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/TaskControllerSpec.groovy

Currently when we fetch a task we pull all the stage context keys into a flatmap called `variables` so that the UI can look at them easily ([here](https://github.com/spinnaker/orca/blob/c11ba0c26e57b81db80e3ef738d914c843368981/orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy#L715)). A key that has a null or empty value overwrites a previously set key with a good value. This is a problem in some deploy tasks because the UI uses the `deploy.server.groups` key to show the spiny wheel indicating that a task is working on a server group, and that value gets unset because the last task has the key `deploy.server.groups` with an empty value (default behavior of `ApplySourceServerGroupCapacityTask` I think). 
I discovered this while wondering why the `keel` …

fix(tasks): duplicate empty keys ignored

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/gce/GceDeployStagePreProcessor.groovy

fix(gce): revert a conditional that was accidentally flipped in #3128

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluator.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/expressions/PipelineExpressionEvaluatorSpec.groovy

-- Fixed issue with expressions that need Execution context to be available to evaluate.
-- Inspects the function definition and injects the execution context Function param dynamically.
@marchello2000

fix(SpEL): Execution context injected into expressions dynamically

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy

@robzienert i think this is a typo, although im not an expert in this library so might just be how it is

fix(clouddriver): small typo fix

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java

- added a toString method with the stage id & execution id

chore(core): Adding stage.toString()

---

orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/ResolveKayentaConfigIdTask.kt
orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/tasks/RunKayentaCanaryTask.kt

Based on post-merge feedback from https://github.com/spinnaker/orca/pull/3215 
- Change exception types to `kork.exceptions.UserException`

fix(Kayenta): Change exception type to kork.UserException

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTask.java
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/StartGoogleCloudBuildTaskSpec.groovy

Closes https://github.com/spinnaker/spinnaker/issues/5051

fix(gcb): process spel in gcb build definition artifact

---

orca-kayenta/orca-kayenta.gradle
orca-mine/orca-mine.gradle

I don't know what changed such that these two modules no longer compile on master, but uhh... this fixes it.

fix(gradle): Add spring-boot-autoconfigure to kayenta and mine

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/AdminController.groovy
orca-web/src/main/java/com/netflix/spinnaker/orca/controllers/ExecutionsImportController.java
orca-web/src/main/java/com/netflix/spinnaker/orca/model/ExecutionImportResponse.java
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/AdminControllerSpec.groovy
orca-web/src/test/groovy/com/netflix/spinnaker/orca/controllers/ExecutionsImportControllerSpec.groovy

- Log stmts clean up
- Only import execution if app can be retrieved from front50.

fix(executions): Only import executions if application exists in Front50

---

gradle.properties
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Trigger.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolver.java
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactResolverSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarterSpec.groovy
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutator.java
orca-pipelinetemplate/src/main/java/com/netflix/spinnaker/orca/pipelinetemplate/v2schema/model/V2PipelineTemplate.java
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/TemplatedPipelineModelMutatorSpec.groovy
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisOrcaQueueConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisQueueShovelConfiguration.kt
orca-queue-redis/src/main/kotlin/com/netflix/spinnaker/orca/q/redis/pending/RedisPendingExecutionService.kt
orca-queue-redis/src/test/kotlin/com/netflix/spinnaker/orca/q/redis/RedisQueueIntegrationTest.kt
orca-redis/orca-redis.gradle
orca-redis/src/main/java/com/netflix/spinnaker/orca/config/RedisConnectionInfo.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/notifications/RedisClusterNotificationClusterLock.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/notifications/RedisNotificationClusterLock.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/pipeline/persistence/jedis/RedisExecutionRepository.java
orca-redis/src/main/java/com/netflix/spinnaker/orca/telemetry/RedisPoolMetricsPostProcessor.java
orca-redis/src/test/groovy/com/netflix/spinnaker/orca/pipeline/persistence/jedis/JedisExecutionRepositorySpec.groovy
orca-test-redis/src/main/java/com/netflix/spinnaker/orca/test/redis/EmbeddedRedisConfiguration.java

This reverts commit df71ed993f77b06b029f5e129256f1972d1d0d3b.
https://github.com/spinnaker/spinnaker/issues/5257

Revert "chore(dependencies): Upgrade Spring Boot to 2.2.1 (#3333)"

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/model/PluginInfo.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/DeletePluginInfoStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/UpsertPluginInfoStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/DeletePluginInfoTask.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/UpsertPluginInfoTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/DeletePluginInfoTaskSpec.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/UpsertPluginInfoTaskSpec.groovy

Continuing rename started here -- https://github.com/spinnaker/front50/pull/679

refactor(plugins): Rename from PluginArtifact to PluginInfo

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/model/PluginInfo.java

- Adding required constructors for plugin info object serialization/deserialization.

feat(plugins):  Add required constructors for Jackson serialization

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/OrcaMessageHandler.kt

We're seeing this error case but it's not clear why this is happening or what message we're failing on. Adding a log to hopefully help find the cause.

chore(InvalidTaskId): adding logs for when we can't find a task

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/OrcaMessageHandler.kt

this class has a great to string. best ever. let's use it.

chore(logs): update InvalidTaskId log msg

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/SimpleTask.java

fix(plugins): Get SimpleStage extension class from ExtensionClassProvider

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/DependentPipelineStarter.groovy

This was originally required for Spring Batch (back in the day). I saw an issue while on call that I suspect may have been called by the callables in this not working correctly. Specifically assigning the `pipeline` variable _inside_ the callable rather than returning it seems weird.

removed sketchy thread stuff from DependentPipelineStarter

---

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgent.kt

Today, the query `OldPipelineCleanupAgent` performs is quite expensive:
```sql
select application, config_id, count(id) as `count` from pipelines where (build_time <= ? and (status IN ('CANCELED','SUCCEEDED','STOPPED','SKIPPED','TERMINAL','FAILED_CONTINUE'))) group by application, config_id having count(id) > ?;
```
Most of the time this query times out on our installation.
This change breaks it up into two queries:
1. first, get apps that have at least the min number of executions required
2. then, use that list, chunk it up and perform a query as above with additional restriction where `application in (.. chunk ..)`
This makes a lot more queries but each query is quicker

fix(old pipe cleanup): chunk up results of old pipeline cleanup agent

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/launchconfigurations/DeleteLaunchConfigurationStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/launchconfigurations/DeleteLaunchConfigurationTask.java

- added deleteLaunchConfigurationStage to support launch config deletion

fix(clouddriver): Adding deleteLaunchConfigurationStage

---

orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/ExecutionCopier.kt

It's important that we capture the executions BEFORE we capture their stages because we use the execution's `updated_at` for our diff calculation.
Before this change, it was possible to see a peered execution that was `SUCCEEDED` but a stage within that execution still showing as `RUNNING`.
This happens because we would grab the stages from the source DB, persist them to the dest DB (this can take some time) and only then we would
grab the executions and persist those. But in this flow our peer could have updated the stage in the time between we capture stages and capture
the execution and we would forever miss that update (if the execution was completed now)
It's totally fine for the stages to be "newer" than their execution since that will be fixed up in the next agent run

fix(peering): Capture the source execution BEFORE the source stage during peering

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/Stage.java

This reverts commit 90c113b85c46409c5e6b4c0add42c27359cc925b.

Revert "fix(perf): Make `getAncestors` call faster (#3306)"

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/tasks/WaitTask.java

fix(wait): Some people want to wait more than 24days

---

orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/PeeringAgent.kt
orca-peering/src/test/groovy/com/netflix/spinnaker/orca/peering/PeeringAgentSpec.groovy

We want to make sure that when we validate that a mock has been called 0 times, we validate that against any args passed into the mock (vs. specific args)

fix(peering): Fix the tests to check for call counts better

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryServerGroupCreator.java

Fixes spinnaker/spinnaker#5519

fix(cf): Load manifest artifact before evaluating manifest

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollback.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/rollback/PreviousImageRollbackSpec.groovy

- include request target groups and security groups

fix(rollback): Should be passing target groups and security groups in request

---

gradle.properties

Previous build failures have been fixed https://github.com/spinnaker/orca/pull/3559

chore(dependencies): Bump kork version to 7.30.1

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PatchManifestTask.java

Prior to [this refactor](https://github.com/spinnaker/orca/pull/3402), PatchManifestTask read `patchBody` directly from the `ManifestEvaluator`'s result. Now, we are attempting to read it off the stage's context, but we deserialized the context with the same model, `PatchManifestContext`, that we used to deserialize the initial stage inputs, which [tries to read `manifests` from `patchBody`](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/PatchManifestContext.java#L74) (at this point, we should be reading `manifests` from the `manifests` key instead). This is intended to be a cherry-pickable fix, but a better, more invasive fix would define different models for the inputs and outputs of each task and …

fix(kubernetes): correctly write Patch Manifest patchBody

---

orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/keel/task/ImportDeliveryConfigTask.kt
orca-keel/src/test/kotlin/com/netflix/spinnaker/orca/keel/ImportDeliveryConfigTaskTests.kt

To go along with https://github.com/spinnaker/keel/pull/1027, this PR improves on existing error handling for keel responses by standardizing on the Spring-like response format, which allows us to relay more types of error messages/details to the UI.

fix(errors): Improve handling of keel errors in ImportDeliveryConfigTask

---

orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/v1schema/graph/transform/RenderTransformSpec.groovy

Various Jinjava issues have been problematic for us in the past in how they affect MPTv1.
As we are in the process of upgrading to latest Jinjava we discovered this issue: https://github.com/HubSpot/jinjava/issues/429
This test is reasonably representative of various issues we've seen including the issue above. Adding it so we have some sense of validation
when we bump Jinjava version

chore(jinjava): add test for jinjava breaks

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/release_info.sh
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
orca-bom/orca-bom.gradle
orca-plugins-test/orca-plugins-test.gradle
orca-web/orca-web.gradle

Also enables the orca-plugins-test module.

chore(build): update to newer spinnaker project plugin

---

gradle.properties

Noticed this while I was doing some Orca testing, looks like I botched a conflict resolution.

chore(dependencies): Remove duplicate keikoVersion

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/SetPreferredPluginReleaseTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/SetPreferredPluginReleaseTaskSpec.groovy

I don't understand why a flag exists for this, but I'm going to set it to always true.

fix(plugins): Add preferred query param flag

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletion.groovy
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/job/WaitOnJobCompletionTest.java

re-add back changes from https://github.com/spinnaker/orca/pull/3624/files
which were accidentally reverted as part of https://github.com/spinnaker/orca/pull/3644/files

fix(titus): custom job timeout should match task timeout

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/Front50Service.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/LoadPluginReleaseStage.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/ExtractRequiredPluginDependenciesTask.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/tasks/LoadPluginReleaseTask.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/ExtractRequiredPluginDependenciesTaskSpec.groovy

Helpful stage for administering preferred plugin versions in pipelines.

feat(plugins): Load plugin release stage

---

orca-api-tck/src/test/resources/orca-test-app.yml
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/config/CloudDriverConfiguration.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/KatoRestServiceSpec.groovy
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/config/EchoConfiguration.groovy
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/config/Front50Configuration.groovy
orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/config/IgorConfiguration.groovy
orca-keel/src/main/kotlin/com/netflix/spinnaker/orca/config/KeelConfiguration.kt
orca-plugins-test/src/test/resources/orca-plugins-test.yml
orca-retrofit/orca-retrofit.gradle
orca-web/src/test/resources/orca-test.yml

fix(misc): Move to client provider impl for spinnaker internal services

---

orca-clouddriver-provider-titus/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/TitusAmazonServerGroupCreatorDecorator.java
orca-clouddriver-provider-titus/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/TitusAmazonServerGroupCreatorDecoratorSpec.groovy

restorting back some logic that was missed in refactor here (https://github.com/spinnaker/orca/pull/3688/files#diff-f4fd7e2fcf07f509c4f3be8808c5e76cL111-L113)

fix(titus): Lookup image form jenkins properties file

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageFinder.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/AmazonImageFinderSpec.groovy

if present in the stage json
See https://spinnakerteam.slack.com/archives/CB78MFQPP/p1591123948104700 for background.
If there are some docs to update, I could use a pointer to them.

feat(aws/findimage): pass account to clouddriver when retrieving images

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineExpressionFunctionProvider.java

This function is useful when we are running a dependent pipeline that falls in a different application

feature(Pipeline Expressions): Add function pipelineIdInApplication hich allows to fetch the ID of a pipeline given its name and its application name

---

orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryDisableClusterStage.groovy
orca-mine/src/main/groovy/com/netflix/spinnaker/orca/mine/pipeline/MonitorCanaryStage.groovy
orca-mine/src/test/groovy/com/netflix/spinnaker/orca/mine/pipeline/CanaryDisableClusterStageSpec.groovy

Accidentally left an incorrect namespace when I created one of the stages. This was causing an issue for the OSS build which excludes mine. 
@kevinawoo are you able to verify this fixes your issue?
@marchello2000

fix(mine): Correcting class namespace

---

orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/ApplicationExpressionFunctionProvider.java

Function to retrieve application metadata (from `front50`) via SpEL

feat(SpEL): Add applicationMetadata SpEL helper function

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/pipeline/ResizeAsgStage.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/PreconfigureDestroyAsgTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/ResizeAsgTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/servergroup/WaitForCapacityMatchTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/ResizeAsgStageSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/pipeline/support/ResizeSupportSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/kato/tasks/ResizeAsgTaskSpec.groovy

This reverts commit 8587846bb4226c58f5398fc12786e23492dbc04e.

Revert "chore(deprecate): Remove `resizeAsg` stage/task (#3786)"

---

orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/JiraService.java

fix(jira): allow anon, toString()

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/UpdateLaunchTemplateStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/strategies/RollingPushStrategy.groovy

- launch template support in rolling push strategy.

feat(rollingPush): Adding support for launch template

---

.detekt.yml
build.gradle
gradle/kotlin.gradle

Not fixing any warnings yet... just getting it in place.

chore(build): Add detekt to project

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/launchtemplates/DeleteLaunchTemplateStage.java
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/launchtemplates/DeleteLaunchTemplateTask.java

- added support for launch template delete

feat(clouddriver): Adding DeleteLaunchTemplateStage

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/scalingprocess/AbstractAwsScalingProcessTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/scalingprocess/ResumeAwsScalingProcessTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/scalingprocess/SuspendAwsScalingProcessTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/scalingprocess/AbstractAwsScalingProcessTaskSpec.groovy

This reverts commit b146bf638d3090b1542f860ec39b1cefac564f63 (#3910)

fix(aws): *do* filter scaling processes to resume/suspend

---

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/graph/StageDefinitionBuilder.java
orca-front50/src/main/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStage.java
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/pipeline/PipelineStageSpec.groovy
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt
orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/TaskController.groovy

Update canManuallySkip to look at stage context and override it on the PipelineStage to enable pipeline stages to be skippable.

feat(stages): Make pipeline stage skippable.

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartScriptTask.groovy

Supports `defaultJob` being changed on-the-fly without a service restart.

feat(igor): Back the default script stage job by a dynamic/fast property

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy

This should, hopefully, resolve https://github.com/spinnaker/spinnaker/issues/6052 which was a likely a regression of https://github.com/spinnaker/orca/pull/3760
If the mapping is empty, skip it.

fix(preconfigured job): Fix for https://github.com/spinnaker/spinnaker/issues/6052

---

orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/FindImageFromClusterTaskSpec.groovy

Unintentionally commented this out earlier.

fix(clouddriver): Re-enable the unit test `@Unroll`

---

build.gradle
gradle.properties
gradle/kotlin.gradle

chore(kotlin): move to new kotlin version and upgrade kork

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartWaitingExecutionsHandler.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/messages.kt

Small quality of life improvement here, ensure we're providing a reason for the cancelation during a purge.

chore(queue): Clarify cancelation reason when purging waiting pipelines

---

orca-api/src/main/java/com/netflix/spinnaker/orca/api/pipeline/persistence/ExecutionRepositoryListener.java
orca-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt
orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/OldPipelineCleanupPollingNotificationAgentSpec.groovy
orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/cleanup/TopApplicationExecutionCleanupPollingNotificationAgentSpec.groovy
orca-sql/src/test/groovy/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlPipelineExecutionRepositorySpec.groovy

Little persist listener, needed for some skunkworks observability stuff I'm working on.

feat(sql): Add ExecutionRepositoryListener

---

gradle.properties
orca-peering/src/main/kotlin/com/netflix/spinnaker/orca/peering/MySqlRawAccess.kt
orca-queue-sql/src/main/kotlin/com/netflix/spinnaker/orca/q/sql/pending/SqlPendingExecutionService.kt
orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/pipeline/persistence/SqlExecutionRepository.kt

JOOQ added `@Nullable` and `@Nonnull` annotations so a couple of minor fixes were required

Fixed JOOQ bump from Kork

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/StartScriptTask.groovy

Same fix as https://github.com/spinnaker/orca/pull/4045 but for the script stage.

fix(script): Add startTime to call to Igor when starting Jenkins script stage

---

orca-igor/src/main/groovy/com/netflix/spinnaker/orca/igor/tasks/MonitorQueuedJenkinsJobTask.groovy

```
spinnaker:
baseUrl:
www: https://www.spinnaker.net
```

fix(jenkins): Minor tweak to backlink config value per PR feedback

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeployCloudFormationTask.java

The `templateBody` field has a size limit of 51200 bytes; larger CFN templates need to be hosted in S3. This PR updates the CloudFormation deploy task to send `templateURL` instead of `templateBody` if the specified template artifact's reference is an s3:// url.
Corresponding PR: https://github.com/spinnaker/clouddriver/pull/5279

feat(cfn): send templateURL instead of templateBody if template artifact reference is an s3 url

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pollers/EphemeralServerGroupsPoller.java

Investingating an issue around TTL'd server groups.

fix(clouddriver): Removing the additional ephemeral server group logging

---

orca-core/src/main/java/com/netflix/spinnaker/orca/DynamicTaskImplementationResolver.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/NoOpTaskImplementationResolver.kt
orca-core/src/main/java/com/netflix/spinnaker/orca/TaskImplementationResolver.java
orca-core/src/main/java/com/netflix/spinnaker/orca/config/OrcaConfiguration.java
orca-core/src/main/java/com/netflix/spinnaker/orca/config/TaskOverrideConfigurationProperties.kt
orca-dry-run/src/test/kotlin/com/netflix/spinnaker/orca/dryrun/DryRunStageTest.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/StageDefinitionBuilders.kt
orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteStageHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/CompleteTaskHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/ContinueParentStageHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/PauseTaskHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RestartStageHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartStageHandlerTest.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/StartTaskHandlerTest.kt

-- New TaskImplementationResolver  which resolves a task node to a  task definition

feat(taskdefresolver): Dynamic task definition resolver

---

orca-core/src/main/java/com/netflix/spinnaker/orca/events/StageListenerAdapter.java
orca-core/src/main/java/com/netflix/spinnaker/orca/listeners/StageListener.java
orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListener.groovy
orca-echo/src/test/groovy/com/netflix/spinnaker/orca/echo/spring/EchoNotifyingStageListenerSpec.groovy

...not the stage status
fixes a regression introduced in https://github.com/spinnaker/orca/pull/4076/files#r597099896

fix(events): publish TaskComplete events with the task status

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/DeleteCloudFormationStage.java
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeleteCloudFormationTask.java
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/WaitForCloudFormationCompletionTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/DeleteCloudFormationTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/aws/cloudformation/WaitForCloudFormationCompletionTaskSpec.groovy

Depends on spinnaker/clouddriver#5344 to implement the delete stack
operation in the AWS provider.
Implements spinnaker/spinnaker#5764

feat(aws/cloudformation): add delete stack stage

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryWaitForDeployServiceTask.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/AbstractCloudFoundryWaitForServiceOperationTaskTest.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryWaitForDeployServiceTaskTest.java

feat(cloudfoundry): Uses last operation state & description to surface that something went wrong.
Related PR: https://github.com/spinnaker/clouddriver/pull/5396

feat(cloudfoundry): Uses last operation state & description

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/cf/CloudFoundryDeleteServiceBindingsStage.java
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryDeleteServiceBindingTask.java
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cf/CloudFoundryDeleteServiceBindingsTask.java

This work is to create a new stage in spinnaker for cloudfoundry. 
This stage specifically handles Unbinding services from applications.

feat(cloudfoundry/unbind): delete service binding stage

---

keiko-redis/keiko-redis.gradle
keiko-sql/keiko-sql.gradle
orca-queue/orca-queue.gradle
orca-test-kotlin/orca-test-kotlin.gradle

instead of hard-coding it here

chore(build): get the version of arrow from spinnaker-dependencies

---

orca-clouddriver/orca-clouddriver.gradle
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/DelegatingOortService.java
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/config/KubernetesPreconfiguredJobProperties.java
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/ResolveTargetManifestTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy

chore(dependencies): Upgrade io-kubernetes java client to resolve CVEs

---

orca-web/src/main/groovy/com/netflix/spinnaker/orca/controllers/AdminController.groovy
orca-web/src/test/kotlin/com/netflix/spinnaker/orca/controllers/AdminControllerTest.kt

Depends on https://github.com/spinnaker/kork/pull/874 (tests won't pass without it).

fix(discovery): fixes admin controller disable behavior

---

orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/model/PipelineBuilder.java

NullPointerException was thrown when triggering pipeline with no stage and can't find any pipeline execution records.

fix(core): NPE when triggering pipeline with no stage configured

---

orca-sql/src/main/kotlin/com/netflix/spinnaker/orca/sql/SqlHealthIndicator.kt

Just a small typo I thought I would fix.
@asher

fix(docs): Fix minor typo in SqlHealthIndicator

---

.mergify.yml

chore(build): update Mergify config

---

.github/workflows/build.yml
.github/workflows/docs_master.yml
.github/workflows/pr.yml
.github/workflows/release.yml

closes: https://github.com/spinnaker/spinnaker/issues/6611

chore(ci): update setup-java GHA to v2

---

.github/workflows/bump_dependencies.yml
.github/workflows/release.yml

Cherry-pick of https://github.com/spinnaker/orca/pull/4247 to release-1.27.x

feat(build): bump dependencies for the given branch (#4247)

---

orca-bakery/src/main/java/com/netflix/spinnaker/orca/bakery/tasks/manifests/CreateBakeManifestTask.java

Add Kustomize 4 support, the backward compatibility with Kustomize 3 is saved.

feat(orca): add Kustomize 4 support

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStage.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/job/PreconfiguredJobStageSpec.groovy

`manifest` field defined in `KubernetesPreconfiguredJobProperties` class has `io.kubernetes.client.openapi.models.V1Job` type. This type is defined in Kubernetes Open API models package. This package contains special JSON serializers e.g `io.kubernetes.client.custom.Quantity.QuantityAdapter`. They must be used to get correct JSON format.

fix: Resource requests on custom stage | Error: got "map", expected "string…"

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/providers/cloudrun/CloudrunServerGroupCreator.java

This is part of https://github.com/spinnaker/governance/issues/302
Adding cloudrun provider functionality in orca.

feat(cloudrun): Adding cloudrun provider functionality in orca.

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/model/Manifest.java
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableContext.java
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/WaitForManifestStableTask.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/model/ManifestTest.java
orca-clouddriver/src/test/resources/com/netflix/spinnaker/orca/clouddriver/model/manifests/stable.json

- Exposes kubernetes events in orca that could be used for:
- Providing more context in case of failures
- Easier debugging of the issues

feat(kubernetes events in orca): Exposes kubernetes events in orca for enhanced logging

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/manifest/DeployManifestContext.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStageTest.java

Introduce blue/green strategy as this is a terminology used more often in the industry compared to the Neflix specific phrasing
Relates to:
https://github.com/spinnaker/clouddriver/pull/5811
https://github.com/spinnaker/deck/pull/9911
https://github.com/spinnaker/front50/pull/1176

feat(kubernetes): Introduce blue/green traffic management strategy

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStageTest.java

Expand support for rollout strategies with more K8s types beyond ReplicaSet.

feat(k8s): Add support of Deployment kind for Blue/Green deployments.

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTask.java
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/DetermineRollbackCandidatesTaskSpec.groovy

Feature was tested in previous pr. Adding feature flag.

fix(timeout): Added feature flag for rollback timeout ui input.

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStageTest.java

Reverts spinnaker/orca#4355
reverting this due to reverting the feature, see https://github.com/spinnaker/clouddriver/pull/5865#issuecomment-1426315921

Revert "feat(k8s): Add support of Deployment kind for Blue/Green deployments."

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStageTest.java

Resolved conflicts that occurred while backporting changes to previous versions

Chore(conflicts): Resolved conflicted code in release-1.27.x from PR-4144

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStageTest.java

Resolved conflicts that occurred while backporting changes to previous versions

Chore(conflicts): Resolved conflicted code in release-1.29.x from PR-4144

---

orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStage.java
orca-clouddriver/src/test/java/com/netflix/spinnaker/orca/clouddriver/pipeline/manifest/DeployManifestStageTest.java

Resolved conflicts that occurred while backporting changes to previous versions

Chore(conflicts): Resolved conflicted code in release-1.28.x from PR-4144

---

gradle.properties

https://github.com/spinnaker/fiat/actions/runs/4634491904/jobs/8200743791 failed to create this autobump

chore(dependencies): Autobump korkVersion (#4444)

---

orca-queue/src/main/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandler.kt
orca-queue/src/test/kotlin/com/netflix/spinnaker/orca/q/handler/RunTaskHandlerTest.kt

To address this issue:
https://github.com/spinnaker/spinnaker/issues/6867

fix(orca): tying exceptions to tasks

---

orca-qos/src/test/kotlin/com/netflix/spinnaker/orca/qos/DefaultExecutionPromoterTest.kt

fix(qos/test): fix syntax in DefaultExecutionPromoterTest

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.java11.slim
Dockerfile.java11.ubuntu
Dockerfile.ubuntu
build.gradle
gradle.properties
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/JarDiffsTask.groovy
orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/kato/tasks/quip/AbstractQuipTask.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/providers/aws/DeployCloudFormationStageTest.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TargetServerGroupResolverSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/pipeline/servergroup/support/TerminatingInstanceSupportSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/DetermineHealthProvidersTaskSpec.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/cluster/ShrinkClusterTaskSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ArtifactUtilsSpec.groovy
orca-core/src/test/groovy/com/netflix/spinnaker/orca/pipeline/util/ContextParameterProcessorSpec.groovy
orca-front50/src/test/groovy/com/netflix/spinnaker/orca/front50/tasks/MonitorPipelineTaskSpec.groovy
orca-igor/src/test/groovy/com/netflix/spinnaker/orca/igor/tasks/GetCommitsTaskSpec.groovy
orca-pipelinetemplate/src/test/groovy/com/netflix/spinnaker/orca/pipelinetemplate/PipelineTemplatePipelinePreprocessorSpec.groovy
orca-retrofit/src/test/groovy/com/netflix/spinnaker/orca/retrofit/exceptions/BaseRetrofitExceptionHandlerSpec.groovy
orca-retrofit/src/test/java/com/netflix/spinnaker/orca/retrofit/exceptions/SpinnakerServerExceptionHandlerTest.java

Number 5 on our Java 17 adventure.
See also https://github.com/spinnaker/front50/pull/1274, https://github.com/spinnaker/igor/pull/1143 etc

feat(java17): use JRE17, run tests on JRE17, compile with JDK11

---

orca-integration/orca-integration.gradle
orca-integration/src/test/java/com/netflix/spinnaker/orca/BaseContainerTest.java
orca-integration/src/test/java/com/netflix/spinnaker/orca/MySqlContainerTest.java
orca-integration/src/test/java/com/netflix/spinnaker/orca/PostgresContainerTest.java
orca-integration/src/test/java/com/netflix/spinnaker/orca/RedisContainerTest.java
orca-integration/src/test/resources/mysql_init.sql
orca-integration/src/test/resources/postgres_init.sql

- Refactored existing StandaloneContainerTest to abstract reusable code into BaseContainerTest
- Added new tests to start Orca with 1) postgres 15 and 2) mysql 8

fix(tests): add new containerized integration tests for mysql and postgres

---

orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsServerGroupCreator.groovy
orca-clouddriver/src/test/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/providers/ecs/EcsServerGroupCreatorSpec.groovy

Fixes issue https://github.com/spinnaker/spinnaker/issues/6926

fix(ecs): Docker image extraction from context
